const carddata7 = [
    { desc : "	Tous les joueurs doivent se lever et danser pendant 30 secondes. Le premier qui s'arrête prend une pénalité.	" , type: 7},
	{ desc : "	Tous les joueurs doivent échanger de place dans le sens des aiguilles d'une montre pour le prochain tour.	" , type: 7},
	{ desc : "	Tous les joueurs mettent un objet personnel au centre. [playerCurr] ferme les yeux, en choisit un et doit deviner à qui il appartient.	" , type: 7},
	{ desc : "	Tout le monde doit changer de place et s'asseoir sur les genoux de quelqu'un	" , type: 7},
	{ desc : "	Tous les joueurs forment un cercle et doivent se tenir la main pendant un tour complet	" , type: 7},
	{ desc : "	Tous les joueurs doivent faire une photo de groupe avec une pose ridicule	" , type: 7},
	{ desc : "	Chaque joueur doit faire un compliment à la personne à sa droite	" , type: 7},
	{ desc : "	Tout le monde doit échanger de chaussures avec quelqu'un d'autre	" , type: 7},
	{ desc : "	Tous les joueurs doivent faire un toast avec leurs verres et partager une chose positive de leur semaine	" , type: 7},
	{ desc : "	Chaque joueur doit montrer son talent caché pendant 15 secondes	" , type: 7},
	{ desc : "	Tous les joueurs doivent se mettre debout et jouer à \"pierre, feuille, ciseaux\" avec la personne à leur gauche	" , type: 7},
	{ desc : "	Tout le monde doit parler à l'envers pendant 2 minutes	" , type: 7},
	{ desc : "	Chaque joueur doit donner son téléphone à la personne à sa droite pendant 3 minutes	" , type: 7},
	{ desc : "	Tous les joueurs doivent faire une chaîne humaine et traverser la pièce ensemble	" , type: 7},
	{ desc : "	Chaque joueur doit dessiner le portrait de la personne en face de lui en 1 minute	" , type: 7},
	{ desc : "	Tous les joueurs doivent faire un \"freeze challenge\" pendant 1 minute	" , type: 7},
	{ desc : "	Chaque joueur doit raconter un bon souvenir qu'il a avec une personne présente	" , type: 7},
	{ desc : "	Tous les joueurs doivent se tenir en équilibre sur une jambe, le dernier à tenir gagne	" , type: 7},
	{ desc : "	Tous les joueurs écrivent un secret anonyme sur un papier, mélangez-les et devinez à qui appartient chaque secret	" , type: 7},
	{ desc : "	Chaque joueur doit prendre une photo de groupe en utilisant un filtre ridicule	" , type: 7},
	{ desc : "	Tout le monde doit ajouter un ingrédient dans un verre et le dernier joueur doit boire le mélange	" , type: 7},
	{ desc : "	Tous les joueurs changent de place dans le sens inverse des aiguilles d'une montre	" , type: 7},
	{ desc : "	Chaque joueur doit enlever une chaussette et les mélanger au centre, puis retrouver la sienne les yeux bandés	" , type: 7},
	{ desc : "	Tous les joueurs se mettent en ligne par ordre de taille sans parler	" , type: 7},
	{ desc : "	Chaque joueur doit faire une imitation d'un autre joueur, les autres doivent deviner qui est imité	" , type: 7},
	{ desc : "	Tous les joueurs jouent à \"pierre, feuille, ciseaux\" en même temps, les perdants boivent	" , type: 7},
	{ desc : "	Chaque joueur doit donner son téléphone à son voisin de gauche qui envoie un message au contact de son choix	" , type: 7},
	{ desc : "	Tous les joueurs doivent faire un câlin collectif pendant 10 secondes	" , type: 7},
	{ desc : "	Chaque joueur doit partager un fait surprenant sur lui-même que personne ne connaît	" , type: 7},
	{ desc : "	Tous les joueurs doivent se tenir en équilibre sur une jambe, le premier à tomber prend une pénalité	" , type: 7},
	{ desc : "	Chaque joueur doit compléter la phrase \"Je n'ai jamais...\" et ceux qui l'ont fait boivent	" , type: 7},
	{ desc : "	Tous les joueurs doivent danser la macarena ensemble	" , type: 7},
	{ desc : "	Chaque joueur ajoute un mouvement à une chorégraphie que tous répètent à la fin	" , type: 7},
	{ desc : "	Tous les joueurs changent de place avec la personne la plus éloignée d'eux	" , type: 7},
	{ desc : "	Chaque joueur doit faire une grimace, le plus drôle selon le vote gagne un privilège	" , type: 7},
	{ desc : "	Tous les joueurs doivent faire semblant d'être des zombies pendant 30 secondes	" , type: 7},
	{ desc : "	Chaque joueur doit faire un compliment à chaque personne présente	" , type: 7},
	{ desc : "	Tous les joueurs doivent faire un \"freeze challenge\" pendant 1 minute, celui qui bouge boit	" , type: 7},
	{ desc : "	Chaque joueur doit raconter une anecdote embarrassante en 30 secondes	" , type: 7},
	{ desc : "	Tous les joueurs doivent faire la pose la plus ridicule possible pour une photo de groupe	" , type: 7},
	{ desc : "	Chaque joueur doit chuchoter un défi à l'oreille de son voisin qui doit l'exécuter	" , type: 7},
	{ desc : "	Tous les joueurs doivent échanger leurs boissons avec leur voisin de droite	" , type: 7},
	{ desc : "	Chaque joueur doit montrer sa pire photo sur son téléphone	" , type: 7},
	{ desc : "	Tous les joueurs doivent faire un toast au joueur le plus âgé	" , type: 7},
	{ desc : "	Chaque joueur doit imiter le cri d'un animal choisi par le groupe	" , type: 7},
	{ desc : "	Tous les joueurs doivent faire une chaîne de massage pendant 30 secondes	" , type: 7},
	{ desc : "	Chaque joueur doit faire un pas de danse qui sera copié par tout le groupe	" , type: 7},
	{ desc : "	Tous les joueurs doivent se tenir la main et former un nœud humain que les autres doivent démêler	" , type: 7},
	{ desc : "	Chaque joueur doit faire une imitation d'une célébrité choisie par le groupe	" , type: 7},
	{ desc : "	Tous les joueurs doivent jouer à \"Ni oui ni non\" pendant 2 minutes	" , type: 7},
	{ desc : "	Chaque joueur doit montrer le contenu de son sac/portefeuille	" , type: 7},
	{ desc : "	Tous les joueurs se mettent en cercle et chacun doit faire un compliment à la personne à sa droite	" , type: 7},
	{ desc : "	Chaque joueur doit raconter une blague, celui qui fait le moins rire prend une pénalité	" , type: 7},
	{ desc : "	Tous les joueurs doivent jouer à \"Jacques a dit\" pendant 2 minutes	" , type: 7},
	{ desc : "	Chaque joueur doit remercier son voisin de gauche pour quelque chose d'imaginaire et ridicule	" , type: 7},
	{ desc : "	Tous les joueurs doivent se mettre en ordre alphabétique par prénom sans parler	" , type: 7},
	{ desc : "	Chaque joueur invente un geste ridicule que tout le groupe doit reproduire	" , type: 7},
	{ desc : "	Tous les joueurs doivent échanger leurs chaussures pendant un tour	" , type: 7},
	{ desc : "	Chaque joueur doit raconter la journée du joueur à sa droite comme s'il était lui	" , type: 7},
	{ desc : "	Tous les joueurs doivent se tenir en équilibre sur une jambe et se pousser doucement	" , type: 7},
	{ desc : "	Chaque joueur doit mimer une profession pendant que les autres devinent	" , type: 7},
	{ desc : "	Tous les joueurs doivent chanter le refrain d'une chanson populaire à l'unisson	" , type: 7},
	{ desc : "	Chaque joueur doit faire un selfie avec une expression différente	" , type: 7},
	{ desc : "	Tous les joueurs doivent faire un concours de grimaces	" , type: 7},
	{ desc : "	Chaque joueur doit dessiner le portrait de son voisin sans regarder sa feuille	" , type: 7},
	{ desc : "	Tous les joueurs doivent échanger de place pendant que la musique joue, quand elle s'arrête, ils figent	" , type: 7},
	{ desc : "	Chaque joueur doit imiter la façon de marcher de quelqu'un dans le groupe	" , type: 7},
	{ desc : "	Tous les joueurs doivent faire une pyramide humaine ou essayer	" , type: 7},
	{ desc : "	Tous les joueurs doivent échanger leurs chaussures pendant [1-3] tours.	" , type: 7},
	{ desc : "	Tout le monde doit parler avec l'accent québécois jusqu'au prochain tour.	" , type: 7},
	{ desc : "	Faites tous un selfie avec la pire grimace possible et postez-le simultanément sur vos réseaux.	" , type: 7},
	{ desc : "	Formez une pyramide humaine et maintenez-la pendant 30 secondes.	" , type: 7},
	{ desc : "	Chacun doit imiter le rire d'un autre joueur jusqu'à la fin du tour.	" , type: 7},
	{ desc : "	Tous les joueurs doivent échanger leurs chaussures pendant [1-3] tours.	" , type: 7},
	{ desc : "	Tout le monde doit parler avec l'accent québécois jusqu'au prochain tour.	" , type: 7},
	{ desc : "	Faites tous un selfie avec la pire grimace possible et postez-le simultanément sur vos réseaux.	" , type: 7},
	{ desc : "	Formez une pyramide humaine et maintenez-la pendant 30 secondes.	" , type: 7},
	{ desc : "	Chacun doit imiter le rire d'un autre joueur jusqu'à la fin du tour.	" , type: 7},
	{ desc : "	Tous les joueurs doivent faire un \"freeze challenge\" pendant 1 minute.	" , type: 7},
	{ desc : "	Tout le monde doit échanger son téléphone avec la personne à sa droite pour les 2 prochains tours.	" , type: 7},
	{ desc : "	Chaque joueur doit boire une gorgée à chaque fois que quelqu'un dit \"euh\" pendant 5 minutes.	" , type: 7},
	{ desc : "	Tous les joueurs doivent chanter le refrain des \"Champs-Élysées\" de Joe Dassin ensemble.	" , type: 7},
	{ desc : "	À tour de rôle, chaque joueur doit ajouter un mouvement à une chorégraphie collective.	" , type: 7},
	{ desc : "	Pendant [1-3] tours, tout le monde doit s'adresser aux autres en les appelant \"Votre Majesté\".	" , type: 7},
	{ desc : "	Formez un train et faites le tour de la pièce en chantant \"Le Petit Train\" de André Claveau.	" , type: 7},
	{ desc : "	Tous les joueurs doivent faire un toast en imitant Emmanuel Macron.	" , type: 7},
	{ desc : "	Tout le monde doit faire une photo de groupe où chacun imite son emoji préféré.	" , type: 7},
	{ desc : "	Chaque joueur doit raconter une partie d'une histoire absurde, en ajoutant une phrase à tour de rôle.	" , type: 7},
	{ desc : "	Tout le monde doit envoyer le même message étrange (choisi par le groupe) à un contact de son choix.	" , type: 7},
	{ desc : "	Tous les joueurs doivent mettre leur téléphone au centre. Premier à craquer et à le consulter a un gage.	" , type: 7},
	{ desc : "	Chaque joueur doit imiter un autre joueur jusqu'à être deviné.	" , type: 7},
	{ desc : "	Tous les joueurs doivent dessiner le portrait d'un autre joueur en 30 secondes. Le pire dessin désigne celui qui boit.	" , type: 7},
	{ desc : "	Tout le monde doit danser la Macarena sans se tromper ou boire un shot.	" , type: 7},
	{ desc : "	Chaque joueur doit tenir un verre d'eau sur sa tête pendant 1 minute sans le faire tomber.	" , type: 7},
	{ desc : "	Tous les joueurs doivent échanger leurs verres et continuer à boire dedans.	" , type: 7},
	{ desc : "	Chaque joueur doit mimer un animal, et tous doivent faire le cri de cet animal ensemble.	" , type: 7},
	{ desc : "	Tout le monde doit faire un \"chifoumi\" en même temps. Les perdants boivent.	" , type: 7},
	{ desc : "	Chaque joueur doit partager son pire souvenir d'école en moins de 30 secondes.	" , type: 7},
	{ desc : "	Tous les joueurs doivent fermer les yeux. Au signal, pointez la personne que vous trouvez la plus drôle.	" , type: 7},
	{ desc : "	Chacun doit boire une gorgée à chaque fois que quelqu'un touche ses cheveux pendant 5 minutes.	" , type: 7},
	{ desc : "	Tous les joueurs doivent parler à l'envers (inverser l'ordre des mots) pendant [1-2] tours.	" , type: 7},
	{ desc : "	Tout le monde doit tenir en équilibre sur un pied pendant 30 secondes. Les premiers à tomber boivent.	" , type: 7},
	{ desc : "	Chaque joueur doit raconter un mensonge et une vérité sur lui. Les autres doivent deviner.	" , type: 7},
	{ desc : "	Tous les joueurs doivent échanger de place dans le sens des aiguilles d'une montre à chaque nouveau tour.	" , type: 7},
	{ desc : "	Tout le monde doit faire une grimace et garder cette expression pendant 1 minute sans rire.	" , type: 7},
	{ desc : "	Chaque joueur doit faire un compliment sincère à la personne à sa gauche.	" , type: 7},
	{ desc : "	Tous les joueurs doivent terminer leurs phrases par \"comme dirait ma grand-mère\" pendant [1-3] tours.	" , type: 7},
	{ desc : "	Chacun doit chanter une partie de \"La Marseillaise\" solo à tour de rôle.	" , type: 7},
	{ desc : "	Tout le monde doit dessiner un objet sur le front d'un autre joueur avec un marqueur effaçable.	" , type: 7},
	{ desc : "	Chaque joueur doit mettre son t-shirt à l'envers pendant [1-3] tours.	" , type: 7},
	{ desc : "	Tous les joueurs doivent faire le tour de la table en marchant comme un canard.	" , type: 7},
	{ desc : "	Chacun doit donner son téléphone à un autre joueur qui pourra envoyer UN message de son choix.	" , type: 7},
	{ desc : "	Tout le monde doit jouer à \"pierre-feuille-ciseaux\" en même temps. Le perdant majoritaire boit.	" , type: 7},
	{ desc : "	Chaque joueur doit partager son premier surnom et pourquoi il l'a reçu.	" , type: 7},
	{ desc : "	Tous les joueurs doivent faire un câlin collectif pendant 10 secondes.	" , type: 7},
	{ desc : "	Chacun doit faire un discours de 20 secondes sur le sujet donné par le joueur précédent.	" , type: 7},
	{ desc : "	Tout le monde doit jouer un tour en gardant un crayon entre le nez et la lèvre supérieure.	" , type: 7},
	{ desc : "	Chaque joueur doit boire quand son mois de naissance est cité (de janvier à décembre).	" , type: 7},
	{ desc : "	incarne la Mort en visite surprise et annonce à [playerX] que son temps est compté… avec un clin d’œil macabre.	" , type: 7},
	{ desc : "	joue un faux exorciste qui « chasse » les mauvais esprits de [playerX] avec des prières décalées.	" , type: 7},
	{ desc : "	fais semblant d’être un serial killer en plein confessionnal et interroge [playerX] sur ses pires secrets.	" , type: 7},
	{ desc : "	deviens un fantôme vengeur et murmure à [playerX] des menaces pleines d’ironie.	" , type: 7},
	{ desc : "	incarne un psychanalyste macabre qui analyse les cauchemars de [playerX].	" , type: 7},
	{ desc : "	fais le rôle d’un clochard enragé du cimetière et raconte à [playerX] des histoires morbides.	" , type: 7},
	{ desc : "	interprète un pompier du désespoir qui sauve [playerX] d’un incendie imaginaire tragique.	" , type: 7},
	{ desc : "	incarne un docteur fou qui confesse à [playerX] que ses « patients » refusent de mourir.	" , type: 7},
	{ desc : "	joue un sosie de Frankenstein qui tente de recréer [playerX] à partir de pièces détachées imaginaires.	" , type: 7},
	{ desc : "	fais semblant d’être un agent des funérailles pour organiser un enterrement absurde de [playerX].	" , type: 7},
	{ desc : "	deviens un détective du surnaturel enquêtant sur la disparition fictive d’âmes, avec [playerX] comme témoin.	" , type: 7},
	{ desc : "	incarne un guide spirituel en mission « dernier voyage » pour [playerX].	" , type: 7},
	{ desc : "	fais le rôle d’un boucher d’humour noir qui présente à [playerX] sa « spécialité » macabre.	" , type: 7},
	{ desc : "	interprète un médiateur entre le vivant et le mort, avec [playerX] comme arbitre de l’au-delà.	" , type: 7},
	{ desc : "	joue un psychopathe charmant qui raconte à [playerX] son CV de « tueur en série » fictif.	" , type: 7},
	{ desc : "	deviens un comédien obsédé par l’apocalypse et invite [playerX] à assister à son « dernier spectacle ».	" , type: 7},
	{ desc : "	incarne un vampire moderne qui doit convaincre [playerX] de lui offrir son « nectar » (avec humour noir).	" , type: 7},
	{ desc : "	fais semblant d’être un conseiller funéraire qui organise un enterrement improvisé pour [playerX].	" , type: 7},
	{ desc : "	joue le rôle d’un nécromancien qui tente de ressusciter le moral de [playerX].	" , type: 7},
	{ desc : "	incarne un chef de gang de zombies qui recrute [playerX] dans son « équipe de mort-vivant ».	" , type: 7},
	{ desc : "	fais semblant d’être un « speed dating macabre » où [playerX] doit trouver l’âme sœur parmi les fantômes.	" , type: 7},
	{ desc : "	deviens un psychologue de l’enfer et demande à [playerX] d’expliquer ses cauchemars les plus sombres.	" , type: 7},
	{ desc : "	incarne un clown sinistre dont le sourire terrifiant hante [playerX].	" , type: 7},
	{ desc : "	joue un faucheur malicieux qui propose à [playerX] un pacte pour échapper à l’ennui mortel.	" , type: 7},
	{ desc : "	fais semblant d’être un présentateur d’un talk-show post-mortem avec [playerX] en invité « décédé ».	" , type: 7},
	{ desc : "	incarne un escroc du surnaturel qui vend à [playerX] des billets pour le « dernier train » imaginaire.	" , type: 7},
	{ desc : "	joue un « expert en rites funéraires » qui explique à [playerX] comment bien préparer son départ.	" , type: 7},
	{ desc : "	deviens un vendeur de cercueils fantaisistes et essaie de convaincre [playerX] d’investir dans le « luxe éternel ».	" , type: 7},
	{ desc : "	incarne un personnage inspiré de Tim Burton qui fait partager à [playerX] ses histoires tordues de l’ombre.	" , type: 7},
	{ desc : "	fais le rôle d’un « dernier avocat » pour défendre [playerX] dans une audience fictive de l’au-delà.	" , type: 7},
	{ desc : "	joue un concierge d’un asile imaginaire et demande à [playerX] de lui confier ses secrets les plus noirs.	" , type: 7},
	{ desc : "	incarne un porteur de croix sarcastique qui décerne à [playerX] son « destin funeste ».	" , type: 7},
	{ desc : "	fais semblant d’être un écrivain de tragédies macabres qui improvise une histoire sur [playerX].	" , type: 7},
	{ desc : "	deviens un organisateur de funérailles déjanté qui propose à [playerX] un enterrement « sur mesure ».	" , type: 7},
	{ desc : "	incarne un conseiller conjugal de l’au-delà et aide [playerX] à résoudre ses conflits « mortels ».	" , type: 7},
	{ desc : "	joue un imitateur de cimetière qui récite des épitaphes humoristiques à [playerX].	" , type: 7},
	{ desc : "	fais le rôle d’un barman de l’enfer qui sert à [playerX] un cocktail « à mourir de rire ».	" , type: 7},
	{ desc : "	incarne un commandant de la brigade des ombres et fait passer à [playerX] un « examen d’âme ».	" , type: 7},
	{ desc : "	joue un imitateur de faucheuse qui échange avec [playerX] sur le thème de la « mortalité chic ».	" , type: 7},
	{ desc : "	deviens un critique de films d’horreur en direct et demande à [playerX] d’incarner le personnage tragique.	" , type: 7},
	{ desc : "	incarne un exorciste sarcastique qui tente d’expulser les « démons » de [playerX].	" , type: 7},
	{ desc : "	fais semblant d’être un parolier désabusé qui réécrit en mode dark les classiques de la chanson d’amour pour [playerX].	" , type: 7},
	{ desc : "	joue un imitateur de tueur en série qui propose à [playerX] un faux test de personnalité « macabre ».	" , type: 7},
	{ desc : "	incarne un gardien de cimetière excentrique qui fait visiter à [playerX] ses tombes imaginaires.	" , type: 7},
	{ desc : "	deviens un humoriste de stand-up version « apocalyptique » qui raconte à [playerX] ses pires scénarios.	" , type: 7},
	{ desc : "	fais le rôle d’un oracle du malheur et prédis à [playerX] une fin pleine d’ironie noire.	" , type: 7},
	{ desc : "	incarne un arbitre de duel mortel qui organise un face-à-face surréaliste avec [playerX].	" , type: 7},
	{ desc : "	joue un psychologue macabre qui tente d’expliquer à [playerX] pourquoi tout est voué à l’échec.	" , type: 7},
	{ desc : "	deviens un imitateur de mort subite et raconte à [playerX] comment « mourir de rire » est le meilleur remède.	" , type: 7},
	{ desc : "	incarne un personnage sorti d’un conte gothique, et demande à [playerX] de lui raconter son histoire la plus tragique… avec humour.	" , type: 7}

];