const carddata6 = [
   { desc : "Énoncer à tour de rôle un pays commençant par la lettre \"B\". Le joueur qui n'a plus d'idée prend une pénalité." , type: 6},
	{ desc : "Énoncer à tour de rôle un titre de chanson contenant un prénom. Le joueur qui n'a plus d'idée prend une pénalité." , type: 6},
	{ desc : "Énoncer à tour de rôle une marque de voiture. Le joueur qui n'a plus d'idée prend une pénalité." , type: 6},
	{ desc : "Citer à tour de rôle un super-héros. Le joueur qui n'a plus d'idée prend une pénalité." , type: 6},
	{ desc : "Citez à tour de rôle un pays commençant par la lettre \"M\"" , type: 6},
	{ desc : "Nommez à tour de rôle un animal qui vit dans l'eau" , type: 6},
	{ desc : "Citez à tour de rôle un acteur ou une actrice qui a joué dans un film Marvel" , type: 6},
	{ desc : "Nommez à tour de rôle une marque de bière" , type: 6},
	{ desc : "Citez à tour de rôle un chanteur ou une chanteuse des années 80" , type: 6},
	{ desc : "Nommez à tour de rôle une capitale européenne" , type: 6},
	{ desc : "Citez à tour de rôle un personnage de Disney" , type: 6},
	{ desc : "Nommez à tour de rôle un sport olympique" , type: 6},
	{ desc : "Citez à tour de rôle un fruit exotique" , type: 6},
	{ desc : "Nommez à tour de rôle une série Netflix" , type: 6},
	{ desc : "Citez à tour de rôle un instrument de musique" , type: 6},
	{ desc : "Nommez à tour de rôle un personnage de jeu vidéo" , type: 6},
	{ desc : "Citez à tour de rôle un plat traditionnel français" , type: 6},
	{ desc : "Nommez à tour de rôle une marque de vêtements" , type: 6},
	{ desc : "Citez à tour de rôle un film d'animation" , type: 6},
	{ desc : "Nommez à tour de rôle une invention du 20ème siècle" , type: 6},
	{ desc : "Citez à tour de rôle un artiste peintre célèbre" , type: 6},
	{ desc : "Nommez à tour de rôle un cocktail" , type: 6},
	{ desc : "Citez à tour de rôle un légume" , type: 6},
	{ desc : "Nommez à tour de rôle un personnage historique" , type: 6},
	{ desc : "Citez à tour de rôle une marque de téléphone" , type: 6},
	{ desc : "Nommez à tour de rôle un monument célèbre" , type: 6},
	{ desc : "Citez à tour de rôle un dinosaure" , type: 6},
	{ desc : "Nommez à tour de rôle une planète ou une étoile" , type: 6},
	{ desc : "Citez à tour de rôle un métier insolite" , type: 6},
	{ desc : "Nommez à tour de rôle une chanson française populaire" , type: 6},
	{ desc : "Citez à tour de rôle un livre classique" , type: 6},
	{ desc : "Nommez à tour de rôle un site web populaire" , type: 6},
	{ desc : "Citez à tour de rôle un super-pouvoir" , type: 6},
	{ desc : "Nommez à tour de rôle un joueur de football actuel" , type: 6},
	{ desc : "Citez à tour de rôle une marque de voiture allemande" , type: 6},
	{ desc : "Nommez à tour de rôle un personnage de Game of Thrones" , type: 6},
	{ desc : "Citez à tour de rôle un groupe de musique des années 90" , type: 6},
	{ desc : "Nommez à tour de rôle un champion olympique français" , type: 6},
	{ desc : "Citez à tour de rôle un personnage des Simpson" , type: 6},
	{ desc : "Nommez à tour de rôle un pays d'Afrique" , type: 6},
	{ desc : "Citez à tour de rôle un célèbre criminel de l'histoire" , type: 6},
	{ desc : "Nommez à tour de rôle un type de fromage" , type: 6},
	{ desc : "Citez à tour de rôle un personnage de Star Wars" , type: 6},
	{ desc : "Nommez à tour de rôle une race de chien" , type: 6},
	{ desc : "Citez à tour de rôle un joueur de basket NBA" , type: 6},
	{ desc : "Nommez à tour de rôle une marque de luxe" , type: 6},
	{ desc : "Citez à tour de rôle un organe du corps humain" , type: 6},
	{ desc : "Nommez à tour de rôle un film de science-fiction" , type: 6},
	{ desc : "Citez à tour de rôle un terme médical" , type: 6},
	{ desc : "Nommez à tour de rôle une chaîne YouTube populaire" , type: 6},
	{ desc : "Citez à tour de rôle une pièce de Shakespeare" , type: 6},
	{ desc : "Nommez à tour de rôle un type de pâtes italiennes" , type: 6},
	{ desc : "Citez à tour de rôle un personnage de bande dessinée" , type: 6},
	{ desc : "Nommez à tour de rôle une application mobile populaire" , type: 6},
	{ desc : "Citez à tour de rôle un sport extrême" , type: 6},
	{ desc : "Nommez à tour de rôle un ancien métier qui n'existe plus ou presque" , type: 6},
	{ desc : "Citez à tour de rôle une danse traditionnelle" , type: 6},
	{ desc : "Nommez à tour de rôle un film d'animation Pixar" , type: 6},
	{ desc : "Citez à tour de rôle un type d'arbre" , type: 6},
	{ desc : "Nommez à tour de rôle un personnage de Friends" , type: 6},
	{ desc : "Citez à tour de rôle un phénomène météorologique" , type: 6},
	{ desc : "Nommez à tour de rôle un acteur qui a joué James Bond" , type: 6},
	{ desc : "Citez à tour de rôle un jeu de société" , type: 6},
	{ desc : "Nommez à tour de rôle un élément chimique" , type: 6},
	{ desc : "Citez à tour de rôle une chanson Disney" , type: 6},
	{ desc : "Nommez à tour de rôle un type de phobic" , type: 6},
	{ desc : "Citez à tour de rôle un festival de musique français" , type: 6},
	{ desc : "Nommez à tour de rôle un personnage de roman classique" , type: 6},
	{ desc : "Citez à tour de rôle un animal en voie de disparition" , type: 6},
	{ desc : "Nommez à tour de rôle un type de pierre précieuse" , type: 6},
	{ desc : "Citez à tour de rôle un plat asiatique" , type: 6},
	{ desc : "Nommez à tour de rôle un supermarché ou magasin français" , type: 6},
	{ desc : "Citez à tour de rôle un type de danse latine" , type: 6},
	{ desc : "Nommez à tour de rôle un champion/une championne de tennis" , type: 6},
	{ desc : "Citez à tour de rôle un personnage de contes de fées" , type: 6},
	{ desc : "Nommez à tour de rôle un type de fleur" , type: 6},
	{ desc : "Citez à tour de rôle un film oscarisé" , type: 6},
	{ desc : "Nommez à tour de rôle un instrument de musique à vent" , type: 6},
	{ desc : "Citez à tour de rôle un grand philosophe" , type: 6},
	{ desc : "Nommez à tour de rôle un type de vin" , type: 6},
	{ desc : "Citez à tour de rôle un roi ou une reine de l'histoire" , type: 6},
	{ desc : "Nommez à tour de rôle un type de thé" , type: 6},
	{ desc : "Citez à tour de rôle un mème internet populaire" , type: 6},
	{ desc : "Nommez à tour de rôle un personnage de Harry Potter" , type: 6},
	{ desc : "Chacun à tour de rôle doit nommer un animateur du \"Club Dorothée\". Le premier qui sèche boit." , type: 6},
	{ desc : "Citez à tour de rôle un titre de chanson de Johnny Hallyday. Premier qui ne trouve plus perd." , type: 6},
	{ desc : "Nommez à tour de rôle un personnage des \"Bronzés\". Celui qui répète ou ne trouve pas prend un gage." , type: 6},
	{ desc : "Citez une réplique culte du cinéma français. Premier à sécher perd." , type: 6},
	{ desc : "Nommez un Premier ministre français depuis 1990. Premier qui ne trouve plus boit un shot." , type: 6},
	{ desc : "Chacun à tour de rôle doit nommer un animateur du \"Club Dorothée\". Le premier qui sèche boit." , type: 6},
	{ desc : "Citez à tour de rôle un titre de chanson de Johnny Hallyday. Premier qui ne trouve plus perd." , type: 6},
	{ desc : "Nommez à tour de rôle un personnage des \"Bronzés\". Celui qui répète ou ne trouve pas prend un gage." , type: 6},
	{ desc : "Citez une réplique culte du cinéma français. Premier à sécher perd." , type: 6},
	{ desc : "Nommez un Premier ministre français depuis 1990. Premier qui ne trouve plus boit un shot." , type: 6},
	{ desc : "Énoncer à tour de rôle un slogan de publicité. Le joueur qui n'a plus d'idée prend une pénalité." , type: 6},
	{ desc : "Chacun doit citer une marque de voiture française. Premier qui sèche boit." , type: 6},
	{ desc : "Nommez à tour de rôle un présentateur du JT français (passé ou présent). Premier qui répète ou ne trouve pas perd." , type: 6},
	{ desc : "Citez des marques de fromage français. Premier qui ne trouve plus a un gage." , type: 6},
	{ desc : "Chacun doit nommer un stade de football français. Premier qui sèche perd." , type: 6},
	{ desc : "Nommez à tour de rôle un personnage de la série \"Kaamelott\". Premier qui répète ou ne trouve pas boit." , type: 6},
	{ desc : "Citez des chaînes de la TNT française. Premier qui sèche a un gage." , type: 6},
	{ desc : "Chacun doit nommer un département français avec son numéro. Premier qui se trompe ou ne trouve pas boit." , type: 6},
	{ desc : "Citez à tour de rôle un animateur ou une animatrice de M6. Premier qui répète ou sèche perd." , type: 6},
	{ desc : "Nommez des personnages des \"Guignols de l'info\". Premier qui ne trouve plus a un gage." , type: 6},
	{ desc : "Citez à tour de rôle un groupe ou chanteur des années 80. Premier qui répète ou ne trouve pas boit." , type: 6},
	{ desc : "Nommez une émission de télé-réalité française. Premier qui sèche perd." , type: 6},
	{ desc : "Chacun doit citer un joueur de l'équipe de France championne du monde 1998. Premier qui ne trouve plus a un gage." , type: 6},
	{ desc : "Citez à tour de rôle un humoriste français. Premier qui répète ou sèche perd." , type: 6},
	{ desc : "Nommez un alcool typiquement français. Premier qui ne trouve plus boit (ironiquement)." , type: 6},
	{ desc : "Citez une chanson avec un prénom dans le titre. Premier qui sèche perd." , type: 6},
	{ desc : "Chacun doit nommer un personnage de Disney. Premier qui répète ou ne trouve pas a un gage." , type: 6},
	{ desc : "Nommez à tour de rôle un chanteur ou groupe des années 2000. Premier qui sèche perd." , type: 6},
	{ desc : "Citez des marques de cosmétiques françaises. Premier qui ne trouve plus a un gage." , type: 6},
	{ desc : "Chacun doit nommer un champion olympique français. Premier qui répète ou ne trouve pas boit." , type: 6},
	{ desc : "Citez à tour de rôle un plat traditionnel français. Premier qui sèche perd." , type: 6},
	{ desc : "Nommez un film avec Gérard Depardieu. Premier qui ne trouve plus a un gage." , type: 6},
	{ desc : "Chacun doit citer une émission de France Télévisions. Premier qui répète ou sèche perd." , type: 6},
	{ desc : "Nommez à tour de rôle un monument parisien. Premier qui ne trouve plus boit." , type: 6},
	{ desc : "Citez des prénoms commençant par la lettre M. Premier qui sèche a un gage." , type: 6},
	{ desc : "Chacun doit nommer une station de métro parisien. Premier qui répète ou ne trouve pas perd." , type: 6},
	{ desc : "Citez à tour de rôle un acteur qui a joué James Bond. Premier qui sèche boit." , type: 6},
	{ desc : "Nommez un film avec Louis de Funès. Premier qui ne trouve plus a un gage." , type: 6},
	{ desc : "Chacun doit citer une équipe de Ligue 1. Premier qui répète ou sèche perd." , type: 6},
	{ desc : "Nommez à tour de rôle un ancien candidat de \"Star Academy\". Premier qui ne trouve plus boit." , type: 6},
	{ desc : "Citez des présentateurs de météo français. Premier qui sèche a un gage." , type: 6},
	{ desc : "Chacun doit nommer une marque de bière. Premier qui répète ou ne trouve pas perd." , type: 6},
	{ desc : "Citez à tour de rôle un personnage de la série \"Plus Belle La Vie\". Premier qui sèche boit." , type: 6},
	{ desc : "Nommez un rappeur français. Premier qui ne trouve plus a un gage." , type: 6},
	{ desc : "Chacun doit citer une marque française de luxe. Premier qui répète ou sèche perd." , type: 6},
	{ desc : "Nommez à tour de rôle un festival français. Premier qui ne trouve plus boit." , type: 6},
	{ desc : "Citez des personnages de bande dessinée franco-belge. Premier qui sèche a un gage." , type: 6},
	{ desc : "Chacun doit nommer un roi de France. Premier qui répète ou ne trouve pas perd." , type: 6},
	{ desc : "Citez à tour de rôle une série française. Premier qui sèche boit." , type: 6},
	{ desc : "Nommez un homme politique de la 5ème République. Premier qui ne trouve plus a un gage." , type: 6},
	{ desc : "Chacun doit citer un acteur/actrice français(e) qui a joué à Hollywood. Premier qui répète ou sèche perd." , type: 6},
	{ desc : "Nommez à tour de rôle une chaîne de fast-food présente en France. Premier qui ne trouve plus boit." , type: 6},
	{ desc : "Citez des membres du groupe \"Les Enfoirés\". Premier qui sèche a un gage." , type: 6},
	{ desc : "Chacun doit nommer un designer ou créateur de mode français. Premier qui répète ou ne trouve pas perd." , type: 6},
	{ desc : "Citez à tour de rôle une marque de spiritueux français. Premier qui sèche boit (logiquement)." , type: 6},

];