const carddata4 = [
    { desc : "Fais semblant d'être bourré pendant [1-2] tours" , type: 4},
{ desc : "Parle comme un robot jusqu'à ton prochain tour" , type: 4},
{ desc : "Fais semblant d'être une star de la téléréalité pendant 1 minute" , type: 4},
{ desc : "Parle avec un accent étranger jusqu'à la fin du jeu" , type: 4},
{ desc : "Fais semblant d'être possédé pendant 30 secondes" , type: 4},
{ desc : "Raconte une blague, si personne ne rit, bois un verre" , type: 4},
{ desc : "Envoie un message gênant au dernier contact de ton téléphone" , type: 4},
{ desc : "Fais semblant d'être un commentateur sportif pendant 1 minute" , type: 4},
{ desc : "Parle en chuchotant jusqu'à ton prochain tour" , type: 4},
{ desc : "Imite le rire du joueur à ta gauche" , type: 4},
{ desc : "Fais un compliment à chaque joueur, mais commence par \"Sans mentir...\"" , type: 4},
{ desc : "Montre ton historique de recherche des 24 dernières heures" , type: 4},
{ desc : "Fais semblant d'être un présentateur météo pendant 1 minute" , type: 4},
{ desc : "Parle en rimant pendant [1-3] tours" , type: 4},
{ desc : "Imite un personnage de Disney au choix des autres joueurs" , type: 4},
{ desc : "Fais semblant d'être un politicien en campagne pendant 1 minute" , type: 4},
{ desc : "Récite l'alphabet à l'envers en moins de 30 secondes" , type: 4},
{ desc : "Fais semblant d'être un prof de fitness pendant 1 minute" , type: 4},
{ desc : "Garde le doigt dans ton nez jusqu'à ton prochain tour" , type: 4},
{ desc : "Imite la démarche du joueur à ta droite" , type: 4},
{ desc : "Fais semblant d'être un vendeur de téléshopping pendant 1 minute" , type: 4},
{ desc : "Chante le refrain de la dernière chanson que tu as écoutée" , type: 4},
{ desc : "Fais semblant d'être un guide touristique pendant 1 minute" , type: 4},
{ desc : "Parle à la troisième personne jusqu'à la fin de la partie" , type: 4},
{ desc : "Imite un animal au choix des autres joueurs" , type: 4},
{ desc : "Fais semblant d'être un médium pendant 1 minute" , type: 4},
{ desc : "Envoie un selfie au groupe avec une expression ridicule" , type: 4},
{ desc : "Fais semblant d'être ivre pendant [1-2] tours" , type: 4},
{ desc : "Parle avec un objet imaginaire jusqu'à ton prochain tour" , type: 4},
{ desc : "Imite la voix d'un personnage de dessin animé" , type: 4},
{ desc : "Fais semblant d'être un mannequin sur un podium pendant 1 minute" , type: 4},
{ desc : "Montre la photo la plus embarrassante de toi sur ton téléphone" , type: 4},
{ desc : "Fais semblant d'être un chanteur d'opéra pendant 1 minute" , type: 4},
{ desc : "Envoie un message vocal ridicule au groupe" , type: 4},
{ desc : "Imite l'accent du joueur à ta gauche" , type: 4},
{ desc : "Fais semblant d'être un dictateur pendant 1 minute" , type: 4},
{ desc : "Récite une comptine en remplaçant certains mots par des gros mots" , type: 4},
{ desc : "Fais semblant d'être un reporter de guerre pendant 1 minute" , type: 4},
{ desc : "Parle avec une voix très aiguë pendant [1-2] tours" , type: 4},
{ desc : "Imite un accent régional au choix des autres joueurs" , type: 4},
{ desc : "Fais semblant d'être un personnage de télé-réalité pendant 1 minute" , type: 4},
{ desc : "Bois un verre d'eau en gardant la tête en bas" , type: 4},
{ desc : "Fais semblant d'être un agent secret pendant 1 minute" , type: 4},
{ desc : "Parle avec un accent britannique jusqu'à ton prochain tour" , type: 4},
{ desc : "Imite la façon de parler du joueur à ta droite" , type: 4},
{ desc : "Fais semblant d'être un présentateur de journal télévisé pendant 1 minute" , type: 4},
{ desc : "Fais 10 pompes ou bois un verre" , type: 4},
{ desc : "Fais semblant d'être une star de cinéma pendant 1 minute" , type: 4},
{ desc : "Parle en bégayant pendant [1-2] tours" , type: 4},
{ desc : "Imite un animal de la ferme au choix des autres joueurs" , type: 4},
{ desc : "imite un autre joueur pendant 30 secondes et les autres doivent deviner qui tu imites." , type: 4},
{ desc : "appelle le 5ème contact de ton téléphone et fais-lui croire que tu as gagné à la loterie." , type: 4},
{ desc : "montre la dernière photo que tu as prise avec ton téléphone." , type: 4},
{ desc : "[playerCurr] et [playerX], faites un concours de grimaces, les autres votent pour le vainqueur." , type: 4},
{ desc : "raconte une histoire en commençant chaque phrase par la dernière lettre du mot qui termine la phrase précédente." , type: 4},
{ desc : "envoie un message à ton crush ou ex sans contexte : \"Je pense encore à toi\" (tu as le droit de préciser que c'est un jeu après)" , type: 4},
{ desc : "fais 15 pompes maintenant ou bois un shot" , type: 4},
{ desc : "appelle tes parents et dis-leur que tu as adopté un animal exotique" , type: 4},
{ desc : "échange de vêtements avec [playerX] pendant [1-2] tours" , type: 4},
{ desc : "montre les [1-3] dernières personnes que tu as appelées" , type: 4},
{ desc : "publie une story Instagram choisie par [playerX]" , type: 4},
{ desc : "laisse [playerX] envoyer un message à n'importe qui dans tes contacts" , type: 4},
{ desc : "fais un discours de 1 minute sur pourquoi les licornes devraient gouverner le monde" , type: 4},
{ desc : "fais 10 squats tout en récitant l'alphabet à l'envers" , type: 4},
{ desc : "bois un verre d'eau avec une cuillère à soupe de sauce soja" , type: 4},
{ desc : "tiens en équilibre sur une jambe pendant tout le tour suivant" , type: 4},
{ desc : "danse sur la chanson choisie par [playerX]" , type: 4},
{ desc : "fais une vidéo TikTok sur place avec [playerX]" , type: 4},
{ desc : "chante le refrain de ta chanson préférée devant tout le monde" , type: 4},
{ desc : "garde un glaçon dans ta main jusqu'à ce qu'il fonde complètement" , type: 4},
{ desc : "montre ta plus récente conversation avec quelqu'un qui n'est pas dans cette pièce" , type: 4},
{ desc : "porte tes chaussures aux mains pendant [1-2] tours" , type: 4},
{ desc : "laisse [playerX] dessiner quelque chose sur ton visage" , type: 4},
{ desc : "fais [1-3] tours sur toi-même puis essaie de marcher droit sur 5 mètres" , type: 4},
{ desc : "trouve 5 objets rouges dans la pièce en moins de 30 secondes" , type: 4},
{ desc : "raconte une blague, si personne ne rit, bois un shot" , type: 4},
{ desc : "imite un youtubeur connu en train de faire une intro" , type: 4},
{ desc : "fais semblant d'être un guide touristique qui présente la pièce où vous êtes" , type: 4},
{ desc : "récite l'alphabet en rotant (ou en faisant semblant)" , type: 4},
{ desc : "mange une combinaison de nourriture choisie par le groupe" , type: 4},
{ desc : "appelle un restaurant et demande s'ils livrent sur la lune" , type: 4},
{ desc : "parle avec un accent étranger jusqu'à ton prochain tour" , type: 4},
{ desc : "fais la planche pendant 30 secondes" , type: 4},
{ desc : "fais un compliment à chaque personne dans la pièce" , type: 4},
{ desc : "montre la photo la plus embarrassante de toi sur ton téléphone" , type: 4},
{ desc : "fais-toi une coiffure créée par [playerX] et garde-la jusqu'à la fin du jeu" , type: 4},
{ desc : "mets ton t-shirt à l'envers pendant [1-3] tours" , type: 4},
{ desc : "raconte une histoire dramatique en n'utilisant que 10 mots" , type: 4},
{ desc : "laisse [playerX] te maquiller les yeux bandés" , type: 4},
{ desc : "envoie un selfie à ton patron/professeur avec un message bizarre" , type: 4},
{ desc : "bois un shot de sauce soja ou de vinaigre" , type: 4},
{ desc : "fais un poirier contre le mur ou bois un shot" , type: 4},
{ desc : "imite la voix de Siri/Alexa pendant [1-3] tours" , type: 4},
{ desc : "laisse [playerX] te dessiner une moustache au marqueur" , type: 4},
{ desc : "appelle un ami au hasard et parle-lui uniquement en chantant" , type: 4},
{ desc : "enfile tes chaussettes sur tes mains pendant [1-2] tours" , type: 4},
{ desc : "sors dehors et hurle le premier mot qui te vient à l'esprit" , type: 4},
{ desc : "ajoute \"dans mon lit\" à la fin de chaque phrase que tu dis pendant [1-3] tours" , type: 4},
{ desc : "mange une cuillère de cannelle ou prends une pénalité" , type: 4},
{ desc : "bois un verre d'eau à l'envers (penché en avant)" , type: 4},
{ desc : "laisse [playerX] te faire une coupe de cheveux imaginaire" , type: 4},
{ desc : "récite l'alphabet en faisant un bruit d'animal différent pour chaque lettre" , type: 4},
{ desc : "appelle un restaurant et demande si tu peux réserver une table pour toi et tes 15 hamsters" , type: 4},
{ desc : "envoie un message à tes parents disant que tu envisages de rejoindre un cirque" , type: 4},
{ desc : "imite une publicité de téléshopping pour un objet banal dans la pièce" , type: 4},
{ desc : "fais un rap de 30 secondes sur la personne à ta droite" , type: 4},
{ desc : "sors dehors et danse la macarena" , type: 4},
{ desc : "mets autant de vêtements que possible en 30 secondes" , type: 4},
{ desc : "mange un morceau de nourriture sans utiliser tes mains" , type: 4},
{ desc : "fais 10 sauts en étoile tout en récitant les tables de multiplication" , type: 4},
{ desc : "fais une vidéo de présentation pour une application de rencontre imaginaire" , type: 4},
{ desc : "envoie \"Je pense à toi\" à un contact aléatoire" , type: 4},
{ desc : "essaie de vendre tes chaussures à [playerX] de façon convaincante" , type: 4},
{ desc : "imite une célébrité pendant que les autres devinent" , type: 4},
{ desc : "échange de t-shirt avec la personne à ta gauche" , type: 4},
{ desc : "fais le tour de la pièce en marchant comme un crabe" , type: 4},
{ desc : "fais un discours de remerciement comme si tu venais de gagner un Oscar pour \"Meilleur dormeur\"" , type: 4},
{ desc : "montre la photo la plus ancienne dans ton téléphone" , type: 4},
{ desc : "mets un glaçon dans ton pantalon/t-shirt et garde-le jusqu'à ce qu'il fonde" , type: 4},
{ desc : "laisse [playerX] te bander les yeux et devine ce que tu manges" , type: 4},
{ desc : "fais une déclaration d'amour passionnée à un objet dans la pièce" , type: 4},
{ desc : "envoie un message à ta mère/père lui demandant s'ils ont vu ton dinosaure de compagnie" , type: 4},
{ desc : "fais 10 tours sur toi-même puis essaie de marcher droit" , type: 4},
{ desc : "parle en imitant un accent étranger pendant [1-3] tours" , type: 4},
{ desc : "avale une cuillère de moutarde ou prends une pénalité" , type: 4},
{ desc : "fais semblant d'être possédé(e) pendant 30 secondes" , type: 4},
{ desc : "appelle le dernier numéro que tu as composé et dis \"Mission accomplie\"" , type: 4},
{ desc : "fais une demande en mariage à [playerX] de façon théâtrale" , type: 4},
{ desc : "invente une chorégraphie sur place pour une chanson choisie par [playerX]" , type: 4},
{ desc : "balance ton sac/portefeuille au milieu et laisse [playerX] fouiller et montrer un objet au hasard" , type: 4},
{ desc : "porte tes vêtements à l'envers pendant [1-3] tours" , type: 4},
{ desc : "laisse chaque joueur écrire un mot sur une partie visible de ton corps" , type: 4},
{ desc : "bois un mélange créé par [playerX] (rien de dangereux)" , type: 4},
{ desc : "imite l'animal choisi par [playerX] pendant 1 minute" , type: 4},
{ desc : "fais une chorégraphie TikTok enseignée par [playerX]" , type: 4},
{ desc : "montre les [1-3] dernières photos que tu as prises avec ton téléphone." , type: 4},
{ desc : "envoie un message vocal en imitant la voix de Jean-Marie Le Pen à la dernière personne que tu as appelée." , type: 4},
{ desc : "Fais 10 pompes ou bois un shot." , type: 4},
{ desc : "Raconte une histoire dramatique en utilisant uniquement des titres de films français." , type: 4},
{ desc : "Appelle un ami qui n'est pas présent et convaincs-le que tu viens de gagner au loto." , type: 4},
{ desc : "imite la voix d'un GPS qui guide [playerX] vers la cuisine." , type: 4},
{ desc : "parle comme un commentateur sportif en décrivant [playerX] qui boit son verre." , type: 4},
{ desc : "imite l'accent du sud pendant [1-2] tours complets." , type: 4},
{ desc : "récite les paroles d'une chanson de Mylène Farmer avec la voix de Dark Vador." , type: 4},
{ desc : "raconte ton dernier week-end comme si tu étais Jean-Pierre Pernaut aux infos régionales." , type: 4},
{ desc : "montre les [1-3] dernières photos que tu as prises avec ton téléphone." , type: 4},
{ desc : "envoie un message vocal en imitant la voix de Jean-Marie Le Pen à la dernière personne que tu as appelée." , type: 4},
{ desc : "Fais 10 pompes ou bois un shot." , type: 4},
{ desc : "Raconte une histoire dramatique en utilisant uniquement des titres de films français." , type: 4},
{ desc : "Appelle un ami qui n'est pas présent et convaincs-le que tu viens de gagner au loto." , type: 4},
{ desc : "laisse [playerX] publier un statut de son choix sur ton compte Facebook." , type: 4},
{ desc : "Montre à tous les joueurs ton historique de recherche Google des dernières 24h." , type: 4},
{ desc : "imite une pub pour un produit ridicule que [playerX] invente sur le moment." , type: 4},
{ desc : "Appelle le 5ème contact de ton téléphone et parle-lui avec l'accent belge." , type: 4},
{ desc : "Récite l'alphabet à l'envers en moins de 30 secondes ou bois." , type: 4},
{ desc : "fais un discours de 1 minute sur pourquoi tu ferais un meilleur Premier ministre que l'actuel." , type: 4},
{ desc : "dessine le portrait de [playerX] les yeux fermés. Si personne ne le reconnaît, tu bois." , type: 4},
{ desc : "Laisse un joueur écrire un mot sur ton front au marqueur qui restera jusqu'à la fin de la soirée." , type: 4},
{ desc : "Envoie un selfie ridicule au contact professionnel le plus récent dans ton téléphone." , type: 4},
{ desc : "mange une cuillère de moutarde ou de sauce piquante." , type: 4},
{ desc : "Fais 5 tours sur toi-même puis essaie de marcher droit jusqu'à la porte." , type: 4},
{ desc : "mets tes chaussettes sur tes mains pour les 3 prochains tours." , type: 4},
{ desc : "chante le générique d'un dessin animé de ton enfance." , type: 4},
{ desc : "Reste debout sur une jambe pendant tout ton prochain tour." , type: 4},
{ desc : "Fais semblant de présenter la météo en utilisant les joueurs comme éléments géographiques." , type: 4},
{ desc : "Fais un appel visio à un membre de ta famille et explique-lui que tu es en pleine séance spirite." , type: 4},
{ desc : "échange ton haut avec [playerX] jusqu'à la fin de la partie." , type: 4},
{ desc : "Fais un discours de remerciement comme si tu venais de recevoir un César du cinéma." , type: 4},
{ desc : "Laisse le groupe choisir ta photo de profil sur une appli de ton choix pour les prochaines 24h." , type: 4},
{ desc : "Termine chacune de tes phrases par \"comme dirait Jean Castex\" pendant [1-3] tours." , type: 4},
{ desc : "Bois un verre d'eau avec une cuillère à soupe de sel ou de sucre." , type: 4},
{ desc : "fais un slow avec [playerX] sur la chanson de son choix." , type: 4},
{ desc : "Enlève tes chaussures et joue avec les pieds exposés jusqu'à ton prochain tour." , type: 4},
{ desc : "fais semblant d'être en plein orgasme pendant 10 secondes." , type: 4},
{ desc : "Laisse [playerX] te coiffer comme il veut avec ce qu'il a sous la main." , type: 4},
{ desc : "Envoie \"Je pense à toi...\" à un ex ou à un contact aléatoire." , type: 4},
{ desc : "fais un défilé de mode en utilisant des objets trouvés dans la pièce comme accessoires." , type: 4},
{ desc : "fais le poirier contre un mur ou bois deux shots." , type: 4},
{ desc : "Imite le cri d'un animal choisi par le groupe pendant 10 secondes." , type: 4},
{ desc : "récite la table de multiplication de 7 en moins de 20 secondes." , type: 4},
{ desc : "Parle à la troisième personne en te désignant par ton prénom pendant [1-3] tours." , type: 4},
{ desc : "fais un massage des épaules à [playerX] pendant 1 minute." , type: 4},
{ desc : "Bois un mélange créé par les autres joueurs (rien de dangereux)." , type: 4},
{ desc : "fais semblant d'être bourré(e) jusqu'à ton prochain tour." , type: 4},
{ desc : "Fais une déclaration d'amour à un objet dans la pièce pendant 30 secondes." , type: 4},
{ desc : "fais-toi porter comme une mariée par [playerX]." , type: 4},
{ desc : "Change de place avec le joueur à ta gauche à chaque fois que quelqu'un dit \"et\"." , type: 4},
{ desc : "récite une comptine en faisant des pompes." , type: 4},
{ desc : "Garde un glaçon dans ta main jusqu'à ce qu'il fonde complètement." , type: 4},
{ desc : "imite le rire de [playerX] à chaque fois que quelqu'un parle pendant [1-2] tours." , type: 4},
{ desc : "Fais 10 squats tout en récitant les paroles d'une chanson choisie par le groupe." , type: 4},
{ desc : "bois dans le verre de [playerX] jusqu'à la fin de la partie." , type: 4},
{ desc : "fais une vidéo TikTok avec [playerX] et publie-la." , type: 4},
{ desc : "Porte tes vêtements à l'envers pour les 3 prochains tours." , type: 4},
{ desc : "envoie un message à tes parents disant que tu envisages de t'inscrire à une télé-réalité." , type: 4},
{ desc : "Chante l’hymne national en remplaçant les paroles par des mots absurdes." , type: 4},
{ desc : "Fais 10 pompes pendant que [playerX] te compte à haute voix." , type: 4},
{ desc : "Imite un animal choisi par le groupe pendant 30 secondes." , type: 4},
{ desc : "Danse sans musique pendant 1 minute en faisant des gestes exagérés." , type: 4},
{ desc : "Récite l’alphabet à l’envers en essayant de ne pas rire." , type: 4},
{ desc : "Fais une déclaration d’amour passionnée à un objet du quotidien." , type: 4},
{ desc : "Tiens une position de yoga ridicule pendant 30 secondes." , type: 4},
{ desc : "Fais une imitation de ton personnage de film préféré." , type: 4},
{ desc : "Fais une blague avec une voix de dessin animé pendant 1 minute." , type: 4},
{ desc : "Réalise une petite chorégraphie improvisée, accompagné(e) d’un solo de claquettes." , type: 4},
{ desc : "Fais semblant de te battre contre un adversaire invisible pendant 30 secondes." , type: 4},
{ desc : "Mime une scène culte d’un film d’action en impliquant un autre joueur." , type: 4},
{ desc : "Fais une déclaration enflammée à la personne assise à ta droite." , type: 4},
{ desc : "Raconte une histoire complètement inventée en intégrant trois mots choisis par le groupe." , type: 4},
{ desc : "Prends un accessoire dans la pièce et fais-en ton “micro” pour un solo de rap de 30 secondes." , type: 4},
{ desc : "Fais le tour de la pièce en marchant en arrière et en imitant une star de cinéma." , type: 4},
{ desc : "Tiens un discours de remerciement comme si tu venais de remporter un prix prestigieux." , type: 4},
{ desc : "Fais une démonstration de ton “meilleur” pas de danse en solo." , type: 4},
{ desc : "Chante une comptine pour enfants avec une intonation dramatique." , type: 4},
{ desc : "Fais une imitation d’un animateur de téléréalité en encourageant le public." , type: 4},
{ desc : "Réalise un défi de mime : fais deviner une émotion sans parler pendant 20 secondes." , type: 4},
{ desc : "Fais un compliment exagéré à chaque joueur en 10 secondes chrono." , type: 4},
{ desc : "Raconte une blague « vaseuse » mais avec assurance." , type: 4},
{ desc : "Donne ton meilleur discours de motivation pour lancer une “mission impossible”." , type: 4},
{ desc : "Fais le tour de la pièce en criant « Je suis le roi/la reine de la soirée ! »" , type: 4},
{ desc : "Fais un strip-tease (d’un geste comique et suggestif) sans te déshabiller complètement." , type: 4},
{ desc : "Réalise une mini-séance de stand-up en 1 minute." , type: 4},
{ desc : "Fais le cri de guerre d’une équipe imaginaire." , type: 4},
{ desc : "Imite une publicité télévisée pour un produit absurde." , type: 4},
{ desc : "Raconte une histoire d’amour impossible en moins de 1 minute." , type: 4},
{ desc : "Fais une démonstration de “moonwalk” ou un pas de danse connu." , type: 4},
{ desc : "Improvise un discours en remerciant des “fans imaginaires”." , type: 4},
{ desc : "Fais semblant d’être dans un clip musical et improvise la chorégraphie." , type: 4},
{ desc : "Réalise un défi de rapidité en donnant 10 synonymes d’un mot choisi par le groupe." , type: 4},
{ desc : "Fais une imitation sonore d’un animal pendant 20 secondes." , type: 4},
{ desc : "Récite un poème inventé sur le thème de la soirée." , type: 4},
{ desc : "Lance un toast original à la santé de tous les joueurs." , type: 4},
{ desc : "Fais semblant de te faire interviewer par un journaliste imaginaire." , type: 4},
{ desc : "Réalise une performance de claquettes improvisée." , type: 4},
{ desc : "Fais le tour de la pièce en criant le prénom de chaque joueur d’une voix exagérée." , type: 4},
{ desc : "Imite un personnage de dessin animé en pleine crise existentielle." , type: 4},
{ desc : "Réalise une courte parodie d’une émission de télé-réalité." , type: 4},
{ desc : "Fais une danse de “la victoire” sur un air imaginaire." , type: 4},
{ desc : "Lance un défi de mimer un métier au choix pour que les autres devinent." , type: 4},
{ desc : "Fais une dédicace humoristique à la personne assise en face de toi." , type: 4},
{ desc : "Improvise une courte scène de film d’action en duo avec un autre joueur." , type: 4},
{ desc : "Fais un discours de remerciement en remerciant “l’univers” pour ta chance." , type: 4},
{ desc : "Raconte une anecdote totalement inventée sur ta dernière aventure." , type: 4},
{ desc : "Fais un tour sur toi-même en criant des mots d’encouragement." , type: 4},
{ desc : "Invente un nouveau slogan publicitaire pour la soirée et le crie fièrement." , type: 4},
{ desc : "Lance un discours dramatique en remerciant ton ombre pour son soutien." , type: 4},
{ desc : "Imité un mime pendant 1 minute sans prononcer un mot." , type: 4},
{ desc : "Effectue 20 sauts sur place tout en récitant l'alphabet." , type: 4},
{ desc : "Chante ta chanson préférée en mode opéra." , type: 4},
{ desc : "Fais le tour de la pièce en marchant en arrière et en imitant des bruits d'animaux." , type: 4},
{ desc : "Donne-toi 30 secondes pour créer une sculpture humaine en utilisant uniquement ton corps." , type: 4},
{ desc : "Réalise une démonstration de claquettes sur une table imaginaire." , type: 4},
{ desc : "Imite le cri d’un fauve et laisse le groupe deviner de quel animal il s’agit." , type: 4},
{ desc : "Déclare ton amour de façon exagérée pour ton snack préféré." , type: 4},
{ desc : "Interprète un mini sketch en jouant le rôle d’un super-héros sauvant la soirée." , type: 4},
{ desc : "Fais une imitation de robot pendant 30 secondes." , type: 4},
{ desc : "Réalise 10 squats en hurlant un cri de guerre." , type: 4},
{ desc : "Lance un défi de jonglage imaginaire avec un objet choisi par le groupe." , type: 4},
{ desc : "Frappe sur la table en imitant le battement d’un tambour." , type: 4},
{ desc : "Exécute un pas de danse inspiré du moonwalk en tournant en rond." , type: 4},
{ desc : "Simule un concert rock en jouant de la guitare électrique imaginaire." , type: 4},
{ desc : "Invente une chorégraphie improvisée sur le thème d’un amour perdu." , type: 4},
{ desc : "Imite un animateur de télé-réalité qui lance un challenge improbable." , type: 4},
{ desc : "Réalise un sketch en incarnant deux personnages opposés (change de voix à mi-parcours)." , type: 4},
{ desc : "Lance un compliment exagéré à [playerX] en 10 secondes chrono." , type: 4},
{ desc : "Exécute une danse de la pluie en te déplaçant de manière rythmée." , type: 4},
{ desc : "Effectue 15 sauts en imitant un kangourou." , type: 4},
{ desc : "Prononce un discours d’adieu pour un objet du quotidien que tu chéris." , type: 4},
{ desc : "Imité un présentateur de jeux télé et invite [playerX] à participer." , type: 4},
{ desc : "Passe 30 secondes en slow motion, en exagérant chacun de tes mouvements." , type: 4},
{ desc : "Traverse la pièce en chantant une chanson d’action digne d’un film d’aventure." , type: 4},
{ desc : "Réalise une mini séance de yoga avec des poses inventées et farfelues." , type: 4},
{ desc : "Imite l’introduction d’une pub absurde pour un produit totalement inventé." , type: 4},
{ desc : "Lance un défi de rapidité en touchant 5 objets choisis par le groupe le plus vite possible." , type: 4},
{ desc : "Fais semblant d’appeler la police pour signaler un drame imaginaire hilarant." , type: 4},
{ desc : "Organise une course en marche arrière jusqu’à la porte." , type: 4},
{ desc : "Imité un animal marin pendant 20 secondes." , type: 4},
{ desc : "Exécute une performance de danse contemporaine avec des mouvements exagérés." , type: 4},
{ desc : "Imite ton personnage de dessin animé préféré pendant 30 secondes." , type: 4},
{ desc : "Propose un défi de mime pour faire deviner un métier sans parler." , type: 4},
{ desc : "Réalise un strip-tease humoristique (sans te déshabiller) sur un air de samba." , type: 4},
{ desc : "Imite une célébrité racontant une blague en 15 secondes." , type: 4},
{ desc : "Déclame ta victoire avec un cri de triomphe et des gestes exagérés." , type: 4},
{ desc : "Lance un toast exagéré à la santé d’un objet anodin de la pièce." , type: 4},
{ desc : "Mets en scène une courte scène d’action en duel imaginaire avec [playerX]." , type: 4},
{ desc : "Effectue 10 flexions en imitant un public de stade en délire." , type: 4},
{ desc : "Fais semblant de courir un marathon dans le salon." , type: 4},
{ desc : "Imite un vent violent en te déplaçant de manière chaotique." , type: 4},
{ desc : "Reconstitue une scène policière en interrogeant un suspect fictif." , type: 4},
{ desc : "Exécute une courte danse hip-hop avec des mouvements improvisés." , type: 4},
{ desc : "Imité une publicité pour un produit de beauté totalement absurde." , type: 4},
{ desc : "Lance un défi de rap improvisé autour d’un mot choisi par le groupe." , type: 4},
{ desc : "Montre tes talents d’acrobate en imitant un gymnaste pendant 30 secondes." , type: 4},
{ desc : "Imite le bruit d’un engin de chantier en action en te déplaçant sur place." , type: 4},
{ desc : "Réalise une performance de claquettes rythmée en restant sur place." , type: 4},
{ desc : "Invente une scène où tu annonces à [playerX] que son personnage vient de trépasser de façon absurde." , type: 4},
{ desc : "Fais une imitation de mourant en exagérant chaque geste pour déclencher le fou rire général." , type: 4},
{ desc : "Raconte un « discours funèbre » improvisé pour un objet de la pièce (avec ironie)." , type: 4},
{ desc : "Marche comme un zombie pendant 1 minute en criant des slogans macabres." , type: 4},
{ desc : "Imite un médecin un peu fou qui explique à [playerX] comment éviter l’inévitable." , type: 4},
{ desc : "Fais une déclaration d’amour morbide à un objet symbolique (ex. ta vieille horloge)." , type: 4},
{ desc : "Imite la voix d’un tueur en série fictif qui avoue ses « crimes » hilarants à [playerX]." , type: 4},
{ desc : "Réalise un mini-spectacle en incarnant un fantôme en quête de vengeance, avec [playerX] comme victime complice." , type: 4},
{ desc : "Lance un toast ironique à la « santé éternelle » de tous les joueurs." , type: 4},
{ desc : "Imite une scène de confession où tu admets que tu es prêt(e) à « mourir de rire »." , type: 4},
{ desc : "Fais semblant de lire ton épitaphe en te moquant de ta vie, avec un ton désabusé." , type: 4},
{ desc : "Reconstitue une scène d’enterrement en exagérant les lamentations et les adieux absurdes." , type: 4},
{ desc : "Imité un présentateur de talk-show funèbre qui interroge [playerX] sur sa « dernière volonté »." , type: 4},
{ desc : "Fais un discours apocalyptique en annonçant que « la fin du monde » est proche, mais avec humour noir." , type: 4},
{ desc : "Imite un personnage de film d’horreur qui se moque de sa propre tragédie." , type: 4},
{ desc : "Réalise un défi de grimaces morbides en imitant des statues funéraires." , type: 4},
{ desc : "Marche en slow motion en imitant le dernier souffle d’un personnage fictif." , type: 4},
{ desc : "Imite le cri d’un mourant dans une scène dramatique, puis éclate de rire." , type: 4},
{ desc : "Fais une chorégraphie macabre en imitant une danse de zombies." , type: 4},
{ desc : "Lance un défi à [playerX] de mimer une scène d’horreur avec un twist humoristique." , type: 4},
{ desc : "Fais un strip-tease (comique et suggestif) en simulant que tu es « en train de te faire enterrer »." , type: 4},
{ desc : "Réalise 10 squats en criant des slogans ironiques sur la mort." , type: 4},
{ desc : "Imite un fantôme qui hante la pièce en récitant des poèmes morbides." , type: 4},
{ desc : "Lance un défi de rapidité pour faire deviner le « dernier mot » macabre à l’aveugle." , type: 4},
{ desc : "Imité un acteur de film d’horreur dans une scène où il se moque de sa propre fin." , type: 4},
{ desc : "Fais semblant d’être le DJ d’un bal funèbre en diffusant des sons lugubres de façon décalée." , type: 4},
{ desc : "Réalise un « karaoke funèbre » en chantant une chanson connue avec des paroles réécrites de façon sombre." , type: 4},
{ desc : "Imité un inspecteur des morts qui enquête sur l’absurdité d’un crime fictif." , type: 4},
{ desc : "Organise une mini-séance de yoga « pour l’âme » en mimant une méditation funèbre." , type: 4},
{ desc : "Imite le discours d’un politicien annonçant des mesures pour « éviter l’apocalypse » avec dérision." , type: 4},
{ desc : "Fais le tour de la pièce en imitant le bruit d’un cercueil qui claque, le tout de façon exagérée." , type: 4},
{ desc : "Imite un sosie de Frankenstein qui « répare » des membres imaginaires sur scène." , type: 4},
{ desc : "Réalise une scène d’horreur parodique où tu annonces que « l’enfer a ouvert ses portes » pour [playerX]." , type: 4},
{ desc : "Imité un imitateur de mort subite et demande à [playerX] de deviner la cause fictive." , type: 4},
{ desc : "Lance un défi de mime sur le thème « dernier souffle » avec des gestes dramatiques." , type: 4},
{ desc : "Fais semblant d’organiser une cérémonie de remise de prix pour le « meilleur décès » de la soirée." , type: 4},
{ desc : "Imité un humoriste macabre qui transforme chaque échec en un « adieu glorieux »." , type: 4},
{ desc : "Réalise un défi de jonglage imaginaire avec des « cercueils volants »." , type: 4},
{ desc : "Fais un cri de guerre funèbre en t’inspirant des discours apocalyptiques." , type: 4},
{ desc : "Imite un détective des ombres qui interroge [playerX] sur une disparition fictive." , type: 4},
{ desc : "Réalise une performance de danse « du dernier battement » en slow motion." , type: 4},
{ desc : "Fais le tour de la pièce en simulant une « marche funèbre » avec des pas exagérés." , type: 4},
{ desc : "Imité un présentateur de quiz sur la mort qui pose des questions absurdes sur l’après-vie." , type: 4},
{ desc : "Réalise un discours dramatique où tu annonces que « le rideau tombe » sur ta performance." , type: 4},
{ desc : "Lance un défi d’improvisation où tu inventes l’ultime excuse pour éviter un enterrement." , type: 4},
{ desc : "Fais semblant d’être un expert en rites occultes et décris en détails un rituel absurde." , type: 4},
{ desc : "Imité un personnage qui annonce sa propre fin en mode « stand-up » et laisse le public deviner la chute." , type: 4},
{ desc : "Réalise une parodie de sermon funèbre en exagérant la gravité de chaque mot." , type: 4},
{ desc : "Lance un défi à [playerX] de recréer la scène d’un film d’horreur culte en y ajoutant un twist ironique." , type: 4},
{ desc : "Imite un personnage de roman gothique qui déclare que « mourir n’a jamais été aussi divertissant »." , type: 4},
{ desc : "Réalise un strip-tease comique pendant 30 secondes, en gardant une touche de provocation." , type: 4},
{ desc : "Fais une déclaration d’amour improvisée à un objet de la pièce (avec des sous-entendus coquins)." , type: 4},
{ desc : "Imite une scène de séduction de film en exagérant les gestes et répliques pour faire rire tout le monde." , type: 4},
{ desc : "Réalise un mini-karaoké d’une chanson d’amour en modifiant les paroles pour qu’elles soient hilarantes." , type: 4},
{ desc : "Fais une démonstration de massage « sensuel » sur un coussin, avec des explications farfelues." , type: 4},
{ desc : "Imite un publicitaire pour un produit aphrodisiaque imaginaire et vends-le à [playerX]." , type: 4},
{ desc : "Exécute une danse sexy et décalée, en invitant [playerX] à te rejoindre sur scène." , type: 4},
{ desc : "Organise une séance de « speed flirting » en donnant 3 compliments extravagants à [playerX] en 15 secondes." , type: 4},
{ desc : "Réalise une improvisation de séduction en mimant une scène de rencontre dans un ascenseur bondé." , type: 4},
{ desc : "Fais une déclaration d’amour hyperbolique à ton plat préféré, en le personnifiant." , type: 4},
{ desc : "Réalise un défi de mime où tu dois faire deviner une position de danse sensuelle sans parler." , type: 4},
{ desc : "Imite un coach en séduction qui donne des conseils absurdes à [playerX] sur comment faire un « clin d’œil mortel »." , type: 4},
{ desc : "Effectue 10 squats en récitant des compliments coquins à haute voix." , type: 4},
{ desc : "Fais le tour de la pièce en distribuant des « baisers imaginaires » à tous les joueurs." , type: 4},
{ desc : "Invente une chorégraphie « sexy » sur un air de publicité rétro et exécute-la en duo avec [playerX]." , type: 4},
{ desc : "Imite une publicité pour des sous-vêtements révolutionnaires, en décrivant leur « pouvoir aphrodisiaque »." , type: 4},
{ desc : "Lance un défi de rapidité en donnant 5 synonymes de « sexy » dans un style comique." , type: 4},
{ desc : "Fais semblant d’être un influenceur en direct qui présente son « outfit du soir » ultra sexy." , type: 4},
{ desc : "Réalise une scène où tu es un coach de love hacking et enseigne à [playerX] une technique de flirt improbable." , type: 4},
{ desc : "Organise un mini-concours de compliments osés en invitant deux joueurs à s’affronter verbalement." , type: 4},
{ desc : "Imité un narrateur de téléréalité décrivant en détail la rencontre la plus torride… et ridicule." , type: 4},
{ desc : "Fais une démonstration de « regard de braise » en fixant [playerX] pendant 10 secondes de manière exagérée." , type: 4},
{ desc : "Réalise une parodie de film romantique en improvisant une scène où le destin de [playerX] est scellé par un regard." , type: 4},
{ desc : "Lance un toast à la « passion décalée » en criant un slogan inventé sur l’amour." , type: 4},
{ desc : "Imité un séducteur des temps modernes qui doit convaincre [playerX] de rejoindre son « club des cœurs audacieux »." , type: 4},
{ desc : "Fais une déclaration d’amour en rimes absurdes en t’adressant à [playerX]." , type: 4},
{ desc : "Réalise une imitation d’un vendeur de parfums aphrodisiaques et propose un « échantillon gratuit » à [playerX]." , type: 4},
{ desc : "Organise une mini-séance de conseils de drague express en 30 secondes avec des répliques à double sens." , type: 4},
{ desc : "Imite un personnage de film érotique en reconstituant une scène mythique… version parodique." , type: 4},
{ desc : "Fais le tour de la pièce en distribuant des « devis de séduction » humoristiques à chacun." , type: 4},
{ desc : "Lance un défi de danse sensuelle en duo avec [playerX], en exagérant chaque mouvement." , type: 4},
{ desc : "Réalise un strip-tease de 10 secondes avec un accessoire insolite (comme un foulard) pour amuser le groupe." , type: 4},
{ desc : "Imité un expert en « positions improbables » et explique à [playerX] comment « réinventer l’étreinte »." , type: 4},
{ desc : "Fais une démonstration de « clin d’œil professionnel » en le combinant avec une réplique osée." , type: 4},
{ desc : "Organise une improvisation où tu dois séduire [playerX] en ne parlant que par des expressions faciales." , type: 4},
{ desc : "Réalise une mini scène de séduction en utilisant des accessoires de la pièce comme éléments de drague." , type: 4},
{ desc : "Imite un coach de « love talk » qui enseigne à [playerX] comment transformer un compliment banal en explosion de charme." , type: 4},
{ desc : "Fais une déclaration en cascade, en répétant une phrase coquine avec des variations de ton exagérées." , type: 4},
{ desc : "Lance un défi où tu dois faire rire [playerX] avec un compliment qui se transforme en jeu de mots sexy." , type: 4},
{ desc : "Organise un duel de regards « enflammés » avec [playerX], ponctué de gestes théâtraux." , type: 4},
{ desc : "Réalise une performance de « danse des séducteurs » en invitant tout le groupe à imiter tes mouvements." , type: 4},
{ desc : "Fais un discours humoristique sur l’amour moderne, en y incluant des conseils absurdes pour flirter en 2025." , type: 4},
{ desc : "Imité un animateur de talk-show érotique qui pose des questions décalées sur la vie amoureuse de [playerX]." , type: 4},
{ desc : "Lance un défi de mime où tu dois faire deviner à [playerX] un geste de flirt sans utiliser de mots." , type: 4},
{ desc : "Réalise une scène où tu annonces en grande pompe l’arrivée d’un « expert en baisers légendaires » (toi-même) à [playerX]." , type: 4},
{ desc : "Imite un narrateur de roman érotique qui décrit avec humour la rencontre improbable entre deux âmes en peine." , type: 4},
{ desc : "Fais une démonstration de « danse du désir » avec des mouvements exagérés et comiques pour séduire [playerX]." , type: 4},
{ desc : "Lance un défi où tu dois improviser un slogan publicitaire pour un accessoire de séduction farfelu." , type: 4},
{ desc : "Réalise une scène où tu joues le rôle d’un « Cupidon moderne » qui tente maladroitement d’unir [playerX] avec un autre joueur." , type: 4},
{ desc : "Imite un personnage de série romantique en délivrant à [playerX] une déclaration d’amour pleine de sous-entendus et de rires." , type: 4}


];