const carddata16 = [
{ "desc" : "Les gens qui pètent dans l'ascenseur et sortent au prochain étage", "type":16},
{ "desc" : "Les gens qui se grattent les couilles puis te serrent la main", "type":16},
{ "desc" : "Les gens qui disent \"j'ai une grosse bite\" mais qui ont un compte OnlyFans avec 3 abonnés", "type":16},
{ "desc" : "Les gens qui mettent des strings quand ils ont une mycose", "type":16},
{ "desc" : "Les gens qui font semblant d'avoir joui pour que ça se termine plus vite", "type":16},
{ "desc" : "Les gens qui kiffent l'odeur de leurs propres pets", "type":16},
{ "desc" : "Les gens qui s'endorment après t'avoir fait une fellation à moitié", "type":16},
{ "desc" : "Les gens qui se vantent de leurs conquêtes mais sont puceau à 30 ans", "type":16},
{ "desc" : "Les gens qui se touchent les parties en public puis reniflent leurs doigts", "type":16},
{ "desc" : "Les gens qui boivent ton reste de bière avec le mégot dedans", "type":16},
{ "desc" : "Les gens qui roulent des pelles à leur chien", "type":16},
{ "desc" : "Les gens qui trompent leur partenaire et s'en vantent", "type":16},
{ "desc" : "Les gens qui pissent à côté de la cuvette et ne nettoient pas", "type":16},
{ "desc" : "Les gens qui vomissent dans ton évier lors d'une soirée", "type":16},
{ "desc" : "Les gens qui disent \"j'ai un pote black\" pour justifier leur racisme", "type":16},
{ "desc" : "Les gens qui te demandent \"t'as déjà essayé avec quelqu'un du même sexe?\"", "type":16},
{ "desc" : "Les gens qui se mouchent dans leur serviette au restaurant", "type":16},
{ "desc" : "Les gens qui font caca et ne se lavent pas les mains", "type":16},
{ "desc" : "Les gens qui te racontent qu'ils ont chié liquide pendant 3 jours", "type":16},
{ "desc" : "Les gens qui se grattent le cul puis sentent leurs doigts", "type":16},
{ "desc" : "Les gens qui font l'amour très fort quand tu dors sur leur canapé", "type":16},
{ "desc" : "Les gens qui disent \"t'es bonne\" dans la rue puis s'énervent quand t'ignores", "type":16},
{ "desc" : "Les gens qui matent tes seins au lieu de te regarder dans les yeux", "type":16},
{ "desc" : "Les gens qui se vantent de leur cunnilingus mais ne savent même pas où est le clitoris", "type":16},
{ "desc" : "Les gens qui portent le même slip toute la semaine", "type":16},
{ "desc" : "Les gens qui prennent des laxatifs avant un rencard \"pour être sûr\"", "type":16},
{ "desc" : "Les gens qui exhibent leurs piercings génitaux à la première rencontre", "type":16},
{ "desc" : "Les gens qui te proposent une partouze dès le premier rendez-vous", "type":16},
{ "desc" : "Les gens qui pensent qu'un doigt dans le cul sans prévenir c'est excitant", "type":16},
{ "desc" : "Les gens qui disent \"je ne suis pas homophobe mais...\" puis sortent un truc homophobe", "type":16},
{ "desc" : "Les gens qui essuient leur morve sous la table", "type":16},
{ "desc" : "Les gens qui se masturbent en pensant à ta mère", "type":16},
{ "desc" : "Les gens qui se curent les dents avec la carte de crédit", "type":16},
{ "desc" : "Les gens qui te parlent de leur infection vaginale pendant le dîner", "type":16},
{ "desc" : "Les gens qui rotent à table et disent \"pardon\" comme si ça réglait tout", "type":16},
{ "desc" : "Les gens qui pètent sous la couette et te mettent la tête dessous", "type":16},
{ "desc" : "Les gens qui te disent \"j'ai pas utilisé de capote\" après l'acte", "type":16},
{ "desc" : "Les gens qui t'appellent par le prénom de leur ex pendant l'orgasme", "type":16},
{ "desc" : "Les gens qui t'envoient des dick pics sans consentement", "type":16},
{ "desc" : "Les gens qui se vantent du nombre de MST qu'ils ont eues", "type":16},
{ "desc" : "Les gens qui raclent leur gorge et avalent publiquement", "type":16},
{ "desc" : "Les gens qui viennent chez toi et chient si longtemps que tu dois aérer tout l'appart", "type":16},
{ "desc" : "Les gens qui te montrent leurs hémorroïdes", "type":16},
{ "desc" : "Les gens qui draguent ton père/ta mère devant toi", "type":16},
{ "desc" : "Les gens qui font semblant d'être ivre pour pouvoir te peloter", "type":16},
{ "desc" : "Les gens qui te détaillent leur diarrhée façon commentateur sportif", "type":16},
{ "desc" : "Les gens qui pètent pendant la levrette et rigolent", "type":16},
{ "desc" : "Les gens qui se vantent de ne jamais se laver les parties intimes", "type":16},
{ "desc" : "Les gens qui prennent des laxatifs pour perdre du poids avant la plage", "type":16},
{ "desc" : "Les gens qui rotent l'alphabet complet pour impressionner", "type":16},
{ "desc" : "Les gens qui te racontent leur accouchement avec détails sanglants pendant un repas", "type":16},
{ "desc" : "Les gens qui se grattent les aisselles puis te font sentir leurs doigts", "type":16},
{ "desc" : "Les gens qui t'envoient des photos d'eux sur les toilettes", "type":16},
{ "desc" : "Les gens qui matent du porno et se masturbent quand tu dors à côté", "type":16},
{ "desc" : "Les gens qui ne changent leur sous-vêtement qu'une fois par semaine", "type":16},
{ "desc" : "Les gens qui sifflent les serveuses en leur mettant une main aux fesses", "type":16},
{ "desc" : "Les gens qui te font l'amour en faisant des bruits d'animaux", "type":16},
{ "desc" : "Les gens qui te montrent leurs crottes dans les toilettes \"pour avis médical\"", "type":16},
{ "desc" : "Les gens qui se mettent un doigt dans l'oreille puis le reniflent", "type":16},
{ "desc" : "Les gens qui se lavent les dents une fois par semaine mais t'embrassent avec la langue", "type":16},
{ "desc" : "Les gens qui te demandent \"elle suce bien?\" en parlant de ta copine", "type":16},
{ "desc" : "Les gens qui racontent leurs ébats sexuels en détail au travail", "type":16},
{ "desc" : "Les gens qui remettent leur slip sale après la douche", "type":16},
{ "desc" : "Les gens qui t'envoient leur test de grossesse positif par WhatsApp", "type":16},
{ "desc" : "Les gens qui font des bruits de succion avec leur langue pendant les repas", "type":16},
{ "desc" : "Les gens qui enlèvent leurs chaussures puantes en public", "type":16},
{ "desc" : "Les gens qui se vantent d'avoir baisé dans ton lit pendant ta soirée", "type":16},
{ "desc" : "Les gens qui suçotent bruyamment leurs doigts après avoir mangé des chips", "type":16},
{ "desc" : "Les gens qui font caca dans la douche et l'écrasent pour l'évacuer", "type":16},
{ "desc" : "Les gens qui se curent le nez et collent les crottes sous ton canapé", "type":16},
{ "desc" : "Les gens qui t'expliquent à quel point ils sont \"juteux\" pendant l'orgasme", "type":16},
{ "desc" : "Les gens qui reniflent le siège après que quelqu'un se soit levé", "type":16},
{ "desc" : "Les gens qui crachent par terre puis marchent dedans", "type":16},
{ "desc" : "Les gens qui te racontent leurs infections urinaires en détail", "type":16},
{ "desc" : "Les gens qui pètent dans ton oreiller avant de partir le matin", "type":16},
{ "desc" : "Les gens qui draguent lourdement ta soeur à ton mariage", "type":16},
{ "desc" : "Les gens qui se lavent les cheveux mais pas le cul", "type":16},
{ "desc" : "Les gens qui t'appellent pour te raconter qu'ils sont constipés depuis 3 jours", "type":16},
{ "desc" : "Les gens qui te montrent les photos de leur ex à poil", "type":16},
{ "desc" : "Les gens qui disent \"je n'ai pas mes règles\" mais en ont plein la culotte", "type":16},
{ "desc" : "Les gens qui se raclent la gorge et crachent dans l'évier de la cuisine", "type":16},
{ "desc" : "Les gens qui essaient d'embrasser ton partenaire quand ils sont bourrés", "type":16},
{ "desc" : "Les gens qui te demandent \"t'avales ou tu recraches?\"", "type":16},
{ "desc" : "Les gens qui te racontent leurs hémorroïdes pendant que tu manges", "type":16},
{ "desc" : "Les gens qui se grattent l'entrejambe puis sentent leurs mains", "type":16},
{ "desc" : "Les gens qui crachent dans ton verre quand tu as le dos tourné", "type":16},
{ "desc" : "Les gens qui pètent en faisant du squat en salle de sport", "type":16},
{ "desc" : "Les gens qui essuient leur sueur sur toi à la salle de sport", "type":16},
{ "desc" : "Les gens qui ramassent et remangent la nourriture tombée par terre", "type":16},
{ "desc" : "Les gens qui se lavent les aisselles avec ton gant de toilette", "type":16},
{ "desc" : "Les gens qui shootent dans les pigeons pour rigoler", "type":16},
{ "desc" : "Les gens qui tchattent aux toilettes et ne se lavent pas les mains", "type":16},
{ "desc" : "Les gens qui t'écrivent \"j'ai trop envie de toi\" puis s'endorment en 3 minutes", "type":16},
{ "desc" : "Les gens qui pissent dans ta douche quand ils sont invités chez toi", "type":16},
{ "desc" : "Les gens qui te disent \"j'adore ton style\" puis se moquent de ta tenue avec leurs potes", "type":16},
{ "desc" : "Les gens qui se curent l'oreille avec leur clé de voiture", "type":16},
{ "desc" : "Les gens qui s'essuient le cul puis sentent le papier", "type":16},
{ "desc" : "Les gens qui vomissent dans leur bouche puis avalent devant toi", "type":16},
{ "desc" : "Les gens qui disent \"j'ai un humour trop noir\" mais font juste des blagues racistes", "type":16},
{ "desc" : "Les gens qui pètent quand ils jouissent", "type":16},
{ "desc" : "Les gens qui lèchent leur doigt pour tourner les pages d'un livre", "type":16},
{ "desc" : "Les gens qui se rincent juste la bouche au lieu de se brosser les dents", "type":16},
{ "desc" : "Les gens qui te racontent qu'ils se sont masturbés en pensant à toi", "type":16},
{ "desc" : "Les gens qui utilisent ton rasoir pour se raser les parties intimes", "type":16},
{ "desc" : "Les gens qui te montrent des photos de leurs selles anormales", "type":16},
{ "desc" : "Les gens qui se lavent les dents puis t'embrassent avec la bouche pleine de dentifrice", "type":16},
{ "desc" : "Les gens qui te demandent si t'as déjà trompé ton/ta partenaire dès le premier rendez-vous", "type":16},
{ "desc" : "Les gens qui se grattent le paquet puis te serrent la main", "type":16},
{ "desc" : "Les gens qui t'envoient des vidéos d'eux en train de se branler", "type":16},
{ "desc" : "Les gens qui crachent dans la piscine publique", "type":16},
{ "desc" : "Les gens qui t'empruntent un string et te le rendent sans l'avoir lavé", "type":16},
{ "desc" : "Les gens qui pissent sous la douche commune à la salle de sport", "type":16},
{ "desc" : "Les gens qui font un rot puis disent \"mmm, ça sent le kebab d'hier\"", "type":16},
{ "desc" : "Les gens qui te racontent qu'ils ont chié dans leur lit à 28 ans", "type":16},
{ "desc" : "Les gens qui font semblant de ne pas bander pour ne pas mettre de capote", "type":16},
{ "desc" : "Les gens qui te racontent leurs fantasmes sur ta mère", "type":16},
{ "desc" : "Les gens qui pètent dans la voiture et verrouillent les fenêtres", "type":16},
{ "desc" : "Les gens qui te demandent de sentir leur haleine", "type":16},
{ "desc" : "Les gens qui se curent le nez et te serrent la main juste après", "type":16},
{ "desc" : "Les gens qui t'envoient une photo de leur mycose génitale pour te demander si c'est grave", "type":16},
{ "desc" : "Les gens qui te racontent qu'ils ont chié dans la cabine d'essayage", "type":16},
{ "desc" : "Les gens qui te disent qu'ils t'aiment juste pour baiser", "type":16},
{ "desc" : "Les gens qui te demandent des photos de tes pieds dès le premier message", "type":16},
{ "desc" : "Les gens qui parlent de leur chiasse aiguë pendant un dîner romantique", "type":16},
{ "desc" : "Les gens qui reniflent tes sous-vêtements quand tu prends une douche", "type":16},
{ "desc" : "Les gens qui te demandent si tes seins sont vrais à la première rencontre", "type":16},
{ "desc" : "Les gens qui pètent dans ton lit puis s'en vont", "type":16},
{ "desc" : "Les gens qui se grattent les fesses puis sentent leurs doigts", "type":16},
{ "desc" : "Les gens qui te racontent leur vie sexuelle avec ton pote/ta pote", "type":16},
{ "desc" : "Les gens qui t'envoient des messages de drague alors qu'ils sont mariés", "type":16},
{ "desc" : "Les gens qui urinent dans la douche commune et font semblant de rien", "type":16},
{ "desc" : "Les gens qui te disent \"t'es la première personne à qui je fais ça\" pour la 50ème fois", "type":16},
{ "desc" : "Les gens qui crachent dans ton verre quand tu ne regardes pas", "type":16},
{ "desc" : "Les gens qui reniflent ta culotte discrètement dans ton panier à linge", "type":16},
{ "desc" : "Les gens qui parlent de leurs précédents partenaires sexuels pendant l'acte", "type":16},
{ "desc" : "Les gens qui disent \"c'est la première fois que je fais ça\" en pratiquant parfaitement", "type":16},
{ "desc" : "Les gens qui vident leur nez dans leur main puis l'essuient sous ton canapé", "type":16},
{ "desc" : "Les gens qui prennent des photos de toi aux toilettes", "type":16},
{ "desc" : "Les gens qui posent un étron et ne tirent pas la chasse d'eau", "type":16},
{ "desc" : "Les gens qui passent la nuit chez toi et laissent des poils pubiens partout", "type":16},
{ "desc" : "Les gens qui rotent à table puis disent \"ça passe mieux maintenant\"", "type":16},
{ "desc" : "Les gens qui se vantent de ne jamais utiliser de préservatif", "type":16},
{ "desc" : "Les gens qui essaient de t'embrasser alors qu'ils ont un herpès visible", "type":16},
{ "desc" : "Les gens qui pissent dans ta bouteille d'eau quand tu as le dos tourné", "type":16},
{ "desc" : "Les gens qui te racontent leurs fantasmes sur les animaux", "type":16},
{ "desc" : "Les gens qui te demandent combien de partenaires sexuels tu as eus devant tes parents", "type":16},
{ "desc" : "Les gens qui sentent leurs aisselles puis font \"hmm, pas mal\"", "type":16},
{ "desc" : "Les gens qui t'interrogent sur tes pratiques sexuelles dès la première rencontre", "type":16},
{ "desc" : "Les gens qui chient et te demandent de venir voir pour des raisons médicales", "type":16},
{ "desc" : "Les gens qui se curent les dents en public avec leur carte bancaire", "type":16},
{ "desc" : "Les gens qui t'envoient des vidéos d'eux en train de vomir", "type":16},
{ "desc" : "Les gens qui se grattent les parties puis préparent à manger sans se laver les mains", "type":16},
{ "desc" : "Les gens qui ramassent les restes dans les assiettes des autres au restaurant", "type":16},
{ "desc" : "Les gens qui te disent \"j'ai eu des jumeaux\" alors qu'ils ont abandonné l'un d'eux", "type":16},
{ "desc" : "Les gens qui te racontent qu'ils sont allés aux putes avec ton père", "type":16},
{ "desc" : "Les gens qui font caca et laissent la porte ouverte", "type":16},
{ "desc" : "Les gens qui se font un lavement devant toi sans prévenir", "type":16},
{ "desc" : "Les gens qui te montrent leurs verrues génitales pendant un repas", "type":16},
{ "desc" : "Les gens qui pètent en faisant l'amour et disent \"désolé, c'est l'excitation\"", "type":16},
{ "desc" : "Les gens qui essaient de t'embrasser avec la bouche pleine de nourriture", "type":16},
{ "desc" : "Les gens qui se grattent le cul puis sentent leurs doigts devant tout le monde", "type":16},
{ "desc" : "Les gens qui t'assurent qu'ils n'ont pas d'MST mais t'en refilent une", "type":16},
{ "desc" : "Les gens qui urinent dans les piscines et te le disent après", "type":16},
{ "desc" : "Les gens qui disent \"j'aime ton parfum\" en reniflant tes cheveux comme un pervers", "type":16},
{ "desc" : "Les gens qui se curent le nez et mangent leurs crottes discrètement", "type":16},
{ "desc" : "Les gens qui te demandent si tu veux voir leur \"gros zizi\"", "type":16},
{ "desc" : "Les gens qui crachent dans ton café quand tu as le dos tourné", "type":16},
{ "desc" : "Les gens qui te racontent qu'ils ont fait caca dans la mer juste à côté de toi", "type":16},
{ "desc" : "Les gens qui te vomissent dessus en boîte de nuit", "type":16},
{ "desc" : "Les gens qui te demandent de leur prêter de l'argent pendant qu'ils te font l'amour", "type":16},
{ "desc" : "Les gens qui reniflent le siège des toilettes après quelqu'un", "type":16},
{ "desc" : "Les gens qui te disent \"je suis trop sensible\" mais jouissent en 30 secondes", "type":16},
{ "desc" : "Les gens qui pètent dans l'eau du bain et font des bulles", "type":16},
{ "desc" : "Les gens qui te montrent des photos de leurs pets sur coussin qui ont laissé une trace", "type":16},
{ "desc" : "Les gens qui se masturbent sous la table pendant un dîner de famille", "type":16},
{ "desc" : "Les gens qui n'hésitent pas à t'envoyer une photo de leur prolapsus anal", "type":16},
{ "desc" : "Les gens qui prennent leur téléphone pendant que tu leur fais une fellation", "type":16},
{ "desc" : "Les gens qui jugent ton corps après avoir couché avec toi", "type":16},
{ "desc" : "Les gens qui te racontent leurs exploits sexuels avec ta soeur", "type":16},
{ "desc" : "Les gens qui te demandent si tu veux sentir leurs pieds", "type":16},
{ "desc" : "Les gens qui font des gargarismes bruyants dans les toilettes publiques", "type":16},
{ "desc" : "Les gens qui urinent dans les plantes en soirée", "type":16},
{ "desc" : "Les gens qui te draguent puis draguent ta mère devant toi", "type":16},
{ "desc" : "Les gens qui pètent juste avant de sortir de l'ascenseur", "type":16},
{ "desc" : "Les gens qui utilisent ta brosse à dents pour se gratter le dos", "type":16},
{ "desc" : "Les gens qui se masturbent en regardant la photo de famille sur ta commode", "type":16},
{ "desc" : "Les gens qui crachent dans les plats en cuisine quand ils sont énervés", "type":16},
{ "desc" : "Les gens qui jouissent en criant \"MAMAAAAAN!\"", "type":16},
{ "desc" : "Les gens qui pètent pendant un massage et font comme si c'était normal", "type":16},
{ "desc" : "Les gens qui te racontent leurs problèmes de constipation pendant ton repas", "type":16},
{ "desc" : "Les gens qui te montrent la mycose entre leurs orteils pendant que tu manges", "type":16},
{ "desc" : "Les gens qui gémissent trop fort au cinéma sans raison", "type":16},
{ "desc" : "Les gens qui t'envoient des photos de leur \"collection\" de préservatifs usagés", "type":16},
{ "desc" : "Les gens qui pissent dans ton lavabo quand les toilettes sont occupées", "type":16},
{ "desc" : "Les gens qui léchent leurs doigts pour essuyer la saleté sur ton visage", "type":16},
{ "desc" : "Les gens qui te racontent qu'ils couchent avec ton ex juste pour te faire mal", "type":16},
{ "desc" : "Les gens qui se curent l'oreille avec leur clé et te la font sentir ensuite", "type":16},
{ "desc" : "Les gens qui te demandent s'ils peuvent boire ton pipi", "type":16},
{ "desc" : "Les gens qui te montrent leur culotte sale pour te demander si c'est normal", "type":16},
{ "desc" : "Les gens qui pètent puis agitent la main pour t'en faire profiter", "type":16},
{ "desc" : "Les gens qui se curent les dents à table avec leur ongle", "type":16},
{ "desc" : "Les gens qui comparent la taille de leur pénis avec celui de ton ex", "type":16},
{ "desc" : "Les gens qui utilisent ton gant de toilette pour s'essuyer les fesses", "type":16},
{ "desc" : "Les gens qui te racontent qu'ils se sont déjà masturbés dans ton lit", "type":16},
{ "desc" : "Les gens qui se mouchent dans leur main puis l'essuient sous la table", "type":16},
{ "desc" : "Les gens qui crachent le long des escaliers mécaniques dans les centres commerciaux", "type":16},
{ "desc" : "Les gens qui te draguent puis draguent ta soeur, puis ta mère à la même soirée", "type":16},
{ "desc" : "Les gens qui te montrent leurs dents pourries en gros plan", "type":16},
{ "desc" : "Les gens qui te demandent si tu veux goûter leur morve", "type":16},
{ "desc" : "Les gens qui se grattent les testicules et te demandent si tu sens la même odeur qu'eux", "type":16},
{ "desc" : "Les gens qui t'envoient des photos de leurs toilettes bouchées", "type":16},
{ "desc" : "Les gens qui se mettent à poil \"pour être plus à l'aise\" dès qu'ils sont chez toi", "type":16},
{ "desc" : "Les gens qui te demandent si tu les trouves sexy juste après avoir vomi", "type":16},
{ "desc" : "Les gens qui te racontent qu'ils ont couché avec ta mère dans le passé", "type":16},
{ "desc" : "Les gens qui pissent dans la douche pendant que tu te douches aussi", "type":16},
{ "desc" : "Les gens qui disent \"je peux te montrer ma collection de photos coquines?\"", "type":16},
{ "desc" : "Les gens qui rotent l'alphabet à table pour impressionner", "type":16},
{ "desc" : "Les gens qui te demandent de leur gratter le dos et te montrent ensuite les peaux mortes", "type":16},
{ "desc" : "Les gens qui te racontent leurs fantasmes sur les personnes âgées", "type":16},
{ "desc" : "Les gens qui reniflent ta chaise après que tu te sois levé", "type":16},
{ "desc" : "Les gens qui pètent pendant un entretien d'embauche et accusent le recruteur", "type":16},
{ "desc" : "Les gens qui te montrent les poils qu'ils viennent de s'arracher", "type":16},
{ "desc" : "Les gens qui se curent les oreilles avec les clés puis les remettent dans ton sac", "type":16},
{ "desc" : "Les gens qui disent \"je vais jouir\" puis s'endorment", "type":16},
{ "desc" : "Les gens qui te parlent des problèmes intestinaux de leur enfant pendant un dîner", "type":16},
{ "desc" : "Les gens qui se vantent d'avoir couché avec ton frère/soeur sans que tu demandes", "type":16},
{ "desc" : "Les gens qui rotent dans ta bouche pendant un baiser", "type":16},
{ "desc" : "Les gens qui te demandent ton avis sur la couleur de leurs selles", "type":16},
{ "desc" : "Les gens qui se grattent l'entrejambe puis te servent à manger avec la même main", "type":16},
{ "desc" : "Les gens qui t'envoient une photo de leur testicule enflé en demandant \"c'est grave?\"", "type":16},
{ "desc" : "Les gens qui te proposent de sentir leurs pieds moites après le sport", "type":16},
{ "desc" : "Les gens qui font semblant de ne pas savoir utiliser un préservatif pour ne pas en mettre", "type":16},
{ "desc" : "Les gens qui se curent le nez avec ta fourchette quand tu as le dos tourné", "type":16},
{ "desc" : "Les gens qui partagent les détails de leur vie sexuelle sur les réseaux sociaux", "type":16},
{ "desc" : "Les gens qui te racontent leurs fantasmes zoophiles sans que tu demandes", "type":16},
{ "desc" : "Les gens qui font caca et ne se lavent jamais les mains", "type":16},
{ "desc" : "Les gens qui te montrent les photos de leur dernier prolapsus rectal", "type":16},
{ "desc" : "Les gens qui urinent dans ton lit \"par accident\" après une soirée", "type":16},
{ "desc" : "Les gens qui se mettent à poil dès qu'ils boivent deux verres", "type":16},
{ "desc" : "Les gens qui sortent un étron, le prennent en photo puis ne tirent pas la chasse", "type":16},
{ "desc" : "Les gens qui te racontent qu'ils ont une MST après avoir couché avec toi", "type":16},
{ "desc" : "Les gens qui te demandent de leur prêter ton vibromasseur", "type":16},
{ "desc" : "Les gens qui jugent ta vie sexuelle mais sont accros au porno", "type":16},
{ "desc" : "Les gens qui te racontent comment ils ont perdu leur virginité avec ton parent", "type":16},
{ "desc" : "Les gens qui te proposent de visionner leur sextape amateur", "type":16},
{ "desc" : "Les gens qui te disent \"j'ai pas mes règles\" après l'acte et rigolent de ta panique", "type":16},
{ "desc" : "Les gens qui te demandent quel goût a leur sperme après une fellation", "type":16},
{ "desc" : "Les gens qui s'assoient sur ton visage pour péter", "type":16},
{ "desc" : "Les gens qui violent les règles d'hygiène en cuisine et s'en vantent", "type":16},
{ "desc" : "Les gens qui se brossent les dents aux toilettes en crachant dans l'urinoir", "type":16},
{ "desc" : "Les gens qui te demandent ton avis sur une grosseur sur leur scrotum", "type":16},
{ "desc" : "Les gens qui te montrent les photos de leur circoncision", "type":16},
{ "desc" : "Les gens qui prétendent être vierges mais ont eu 50 partenaires", "type":16},
{ "desc" : "Les gens qui te racontent les détails de leur dernier examen gynécologique", "type":16},
{ "desc" : "Les gens qui mentent sur leur taille de pénis puis se vexent quand tu rigoles", "type":16},
{ "desc" : "Les gens qui utilisent ton déodorant pour leurs aisselles puis pour leur entrejambe", "type":16},
{ "desc" : "Les gens qui t'embrassent avec un mal de gorge purulent", "type":16},
{ "desc" : "Les gens qui te font l'amour puis demandent \"c'est qui déjà ton prénom?\"", "type":16},
{ "desc" : "Les gens qui pissent dans ton shampoing pour rigoler", "type":16},
{ "desc" : "Les gens qui te parlent de leur vie sexuelle alors que tu manges", "type":16},
{ "desc" : "Les gens qui utilisent ta serviette de bain pour s'essuyer les fesses", "type":16},
{ "desc" : "Les gens qui crient \"surpriiise\" quand ils te montrent leur pénis", "type":16},
{ "desc" : "Les gens qui te font croire qu'ils ont joui mais ont juste sué beaucoup", "type":16},
{ "desc" : "Les gens qui te posent des questions intimes devant tes parents", "type":16},
{ "desc" : "Les gens qui te racontent leurs expériences sexuelles avec leur cousin/cousine", "type":16},
{ "desc" : "Les gens qui t'envoient des photos de leurs analyses d'urine", "type":16},
{ "desc" : "Les gens qui se curent le nez pendant un entretien d'embauche", "type":16},
{ "desc" : "Les gens qui oublient volontairement de dire qu'ils ont une MST", "type":16},
{ "desc" : "Les gens qui t'expliquent comment lécher un clitoris pendant un repas de famille", "type":16},
{ "desc" : "Les gens qui se grattent les aisselles puis te servent à boire", "type":16},
{ "desc" : "Les gens qui crachent dans ta bière quand tu as le dos tourné", "type":16},
{ "desc" : "Les gens qui disent avoir une grosse bite et sortent un concombre miniature", "type":16},
{ "desc" : "Les gens qui laissent des poils pubiens dans ta baignoire", "type":16},
{ "desc" : "Les gens qui te racontent leur fantasme sexuel sur ta grand-mère", "type":16},
{ "desc" : "Les gens qui se masturbent en public sous une couverture", "type":16},
{ "desc" : "Les gens qui te proposent de te montrer leurs hémorroïdes", "type":16},
{ "desc" : "Les gens qui te demandent si tu veux goûter leur lait maternel", "type":16},
{ "desc" : "Les gens qui te parlent de leurs problèmes de libido devant ton enfant", "type":16},
{ "desc" : "Les gens qui reniflent tes vêtements quand tu n'es pas là", "type":16},
{ "desc" : "Les gens qui te draguent puis se vantent de t'avoir mis un doigt dans le cul", "type":16},
{ "desc" : "Les gens qui te demandent si tu veux voir leur collection de crottes", "type":16},
{ "desc" : "Les gens qui urinent dans le lit et disent \"c'est pas grave, ça sèchera\"", "type":16},
{ "desc" : "Les gens qui crachent sur la nourriture des autres pour la \"réserver\"", "type":16},
{ "desc" : "Les gens qui lèchent leurs doigts après s'être gratté l'entrejambe", "type":16},
{ "desc" : "Les gens qui te piquent ton déodorant pour se l'appliquer sur les parties intimes", "type":16},
{ "desc" : "Les gens qui te disent \"t'as déjà essayé la sodomie?\" dès le premier rendez-vous", "type":16},
{ "desc" : "Les gens qui rotent et disent \"mmm, goût d'oeuf pourri\"", "type":16},
{ "desc" : "Les gens qui te demandent de sentir leur caleçon pour vérifier s'il est propre", "type":16},
{ "desc" : "Les gens qui t'expliquent en détail comment ils chient mou depuis trois jours", "type":16},
{ "desc" : "Les gens qui te montrent leur collection de préservatifs usagés", "type":16},
{ "desc" : "Les gens qui pètent puis agitent la couette pour te le faire sentir", "type":16},
{ "desc" : "Les gens qui te demandent ton avis sur la couleur de leurs sécrétions", "type":16},
{ "desc" : "Les gens qui jouent avec leur morve en public", "type":16},
{ "desc" : "Les gens qui t'appellent le prénom de leur ex pendant l'orgasme puis disent \"c'est pareil\"", "type":16},
{ "desc" : "Les gens qui te racontent qu'ils ont couché avec ton ex juste pour te mettre mal à l'aise", "type":16},
{ "desc" : "Les gens qui se vantent de ne jamais se brosser les dents et t'embrassent", "type":16},
{ "desc" : "Les gens qui te demandent de vérifier si leur anus saigne", "type":16},
{ "desc" : "Les gens qui jouissent et disent \"désolé, c'est la première fois\" pour la 50ème fois", "type":16},
{ "desc" : "Les gens qui t'envoient des photos de leur pus d'infection", "type":16},
{ "desc" : "Les gens qui te disent \"je t'aime\" juste pour coucher avec toi", "type":16},
{ "desc" : "Les gens qui te racontent comment ils se sont masturbés avec tes sous-vêtements", "type":16},
{ "desc" : "Les gens qui s'essuient la morve sur ta manche", "type":16},
{ "desc" : "Les gens qui pètent dans ta voiture puis verrouillent les fenêtres", "type":16},
{ "desc" : "Les gens qui comparent la taille de leur pénis avec celui de ton frère", "type":16},
{ "desc" : "Les gens qui utilisent ton rasoir pour se raser les aisselles puis les parties intimes", "type":16},
{ "desc" : "Les gens qui te montrent leur infection génitale pendant un repas", "type":16},
{ "desc" : "Les gens qui t'envoient des photos de leurs selles pour avoir ton avis médical", "type":16},
{ "desc" : "Les gens qui te demandent de leur prêter un sous-vêtement propre et te le rendent sale", "type":16},
{ "desc" : "Les gens qui te parlent de leurs anciennes MST pendant un dîner romantique", "type":16},
{ "desc" : "Les gens qui attendent que tu regardes pour se gratter les fesses puis sentir leurs doigts", "type":16},
{ "desc" : "Les gens qui font semblant de ne pas savoir qu'ils puent des aisselles", "type":16},
{ "desc" : "Les gens qui te décrivent leur diarrhée en termes culinaires", "type":16},
{ "desc" : "Les gens qui prétendent être experts en sexe mais ne trouvent pas le clitoris", "type":16},
{ "desc" : "Les gens qui te demandent de sentir l'odeur sous leurs seins", "type":16},
{ "desc" : "Les gens qui sentent leurs pieds puis essaient de te faire sentir leurs doigts", "type":16},
{ "desc" : "Les gens qui se masturbent avec ton oreiller quand tu n'es pas là", "type":16},
{ "desc" : "Les gens qui urinent dans ta douche et ne rincent pas", "type":16},
{ "desc" : "Les gens qui te montrent les poils qu'ils viennent de s'épiler des parties intimes", "type":16},
{ "desc" : "Les gens qui te racontent leur fantasme de coucher avec ton père/ta mère", "type":16},
{ "desc" : "Les gens qui te lèchent le visage sans raison", "type":16},
{ "desc" : "Les gens qui pètent et disent \"ah, c'est pas moi, c'est toi\"", "type":16},
{ "desc" : "Les gens qui partagent leurs expériences d'échangisme avec tes parents", "type":16},
{ "desc" : "Les gens qui te disent \"j'ai pas d'MST\" mais te refilent une chaude-pisse", "type":16},
{ "desc" : "Les gens qui t'envoient des photos de leurs pieds infectés", "type":16},
{ "desc" : "Les gens qui te demandent de vérifier s'ils ont une mauvaise haleine en te soufflant dessus", "type":16},
{ "desc" : "Les gens qui se curent le nez et essuient sur ton canapé", "type":16},
{ "desc" : "Les gens qui te racontent leur expérience sexuelle avec ton parent", "type":16},
{ "desc" : "Les gens qui gémissent de façon exagérée au restaurant", "type":16},
{ "desc" : "Les gens qui te montrent les cicatrices de leur circoncision pendant un repas", "type":16},
{ "desc" : "Les gens qui demandent \"tu me trouves gros?\" en étant à poil devant toi", "type":16},
{ "desc" : "Les gens qui pètent à la salle de sport en faisant du squat", "type":16},
{ "desc" : "Les gens qui t'expliquent l'odeur de leurs parties génitales sans que tu demandes", "type":16},
{ "desc" : "Les gens qui sentent leur doigt après se l'être mis dans le nombril", "type":16},
{ "desc" : "Les gens qui te racontent leurs diarrhées explosives de la veille", "type":16},
{ "desc" : "Les gens qui prétendent être des dieux du sexe mais transpirent après 2 minutes", "type":16},
{ "desc" : "Les gens qui t'envoient des photos d'eux aux toilettes en train de chier", "type":16},
{ "desc" : "Les gens qui utilisent ta brosse à dents et ne te le disent pas", "type":16},
{ "desc" : "Les gens qui mettent leur doigt dans ton verre pour goûter ta boisson", "type":16},
{ "desc" : "Les gens qui se grattent les testicules puis cuisinent sans se laver les mains", "type":16},
{ "desc" : "Les gens qui te montrent leur furoncle sur la fesse pendant que tu manges", "type":16},
{ "desc" : "Les gens qui pètent silencieusement puis quittent la pièce", "type":16},
{ "desc" : "Les gens qui crient \"surprise!\" et te montrent leur pénis en érection", "type":16},
{ "desc" : "Les gens qui disent \"je me suis permis de\" avant de faire quelque chose sans permission", "type":16},
{ "desc" : "Les gens qui te demandent \"ça va?\" mais continuent de marcher sans attendre ta réponse", "type":16},
{ "desc" : "Les gens qui mangent bruyamment la bouche ouverte", "type":16},
{ "desc" : "Les gens qui parlent au cinéma pendant le film", "type":16},
{ "desc" : "Les gens qui te coupent systématiquement la parole", "type":16},
{ "desc" : "Les gens qui envoient des messages vocaux de 5 minutes", "type":16},
{ "desc" : "Les gens qui marchent lentement en groupe sur tout le trottoir", "type":16},
{ "desc" : "Les gens qui postent chaque repas sur Instagram", "type":16},
{ "desc" : "Les gens qui klaxonnent dès que le feu passe au vert", "type":16},
{ "desc" : "Les gens qui laissent leur téléphone sonner sans décrocher", "type":16},
{ "desc" : "Les gens qui font semblant de ne pas voir la file d'attente et passent devant tout le monde", "type":16},
{ "desc" : "Les gens qui écoutent leurs messages vocaux en haut-parleur dans les lieux publics", "type":16},
{ "desc" : "Les gens qui te racontent en détail le film que tu vas voir", "type":16},
{ "desc" : "Les gens qui se garent sur deux places de parking", "type":16},
{ "desc" : "Les gens qui ramènent tout à eux dans une conversation", "type":16},
{ "desc" : "Les gens qui te coupent la parole pour finir ta phrase et se trompent", "type":16},
{ "desc" : "Les gens qui te demandent pourquoi tu ne bois pas d'alcool", "type":16},
{ "desc" : "Les gens qui prétendent connaître une célébrité sans jamais l'avoir rencontrée", "type":16},
{ "desc" : "Les gens qui se lèchent les doigts avant de tourner les pages d'un livre", "type":16},
{ "desc" : "Les gens qui te demandent d'être leur photographe personnel pendant toute une soirée", "type":16},
{ "desc" : "Les gens qui t'appelle pour te dire \"je t'envoie un message\"", "type":16},
{ "desc" : "Les gens qui regardent par-dessus ton épaule ce que tu lis", "type":16},
{ "desc" : "Les gens qui te racontent leurs rêves en détail", "type":16},
{ "desc" : "Les gens qui posent des questions pendant un film qu'ils comprennent s'ils se taisaient", "type":16},
{ "desc" : "Les gens qui te font la bise alors qu'ils sont malades", "type":16},
{ "desc" : "Les gens qui tchattent pendant l'acte sexuel", "type":16},
{ "desc" : "Les gens qui te parlent quand tu as tes écouteurs", "type":16},
{ "desc" : "Les gens qui te disent \"t'as maigri\" quand tu as grossi", "type":16},
{ "desc" : "Les gens qui te disent \"t'as grossi\" quand tu as maigri", "type":16},
{ "desc" : "Les gens qui te font remarquer ton acné comme si tu ne l'avais pas vu", "type":16},
{ "desc" : "Les gens qui parlent à leur chien comme à un bébé en public", "type":16},
{ "desc" : "Les gens qui te réveillent pour te demander si tu dors", "type":16},
{ "desc" : "Les gens qui te posent une question et répondent à ta place", "type":16},
{ "desc" : "Les gens qui t'appellent juste pour dire qu'ils n'ont pas le temps de te parler", "type":16},
{ "desc" : "Les gens qui disent \"c'est comme dans Game of Thrones\" à propos de tout", "type":16},
{ "desc" : "Les gens qui te demandent \"tu te souviens de moi?\" sans se présenter", "type":16},
{ "desc" : "Les gens qui s'assoient à côté de toi dans un bus vide", "type":16},
{ "desc" : "Les gens qui créent un groupe WhatsApp et envoient 15 messages par jour", "type":16},
{ "desc" : "Les gens qui prennent des photos au flash dans les musées", "type":16},
{ "desc" : "Les gens qui répondent \"comme tu veux\" quand tu leur demandes ce qu'ils veulent manger", "type":16},
{ "desc" : "Les gens qui te montrent des vidéos TikTok en te tenant le téléphone sous le nez", "type":16},
{ "desc" : "Les gens qui te disent \"faut pas stresser\" quand tu stresses", "type":16},
{ "desc" : "Les gens qui mettent leur musique à fond sur la plage", "type":16},
{ "desc" : "Les gens qui font du bruit en mangeant une pomme", "type":16},
{ "desc" : "Les gens qui mettent des hashtags pour chaque mot de leur publication", "type":16},
{ "desc" : "Les gens qui gardent leur sac à dos dans le métro bondé", "type":16},
{ "desc" : "Les gens qui disent \"j'ai une question\" au lieu de poser directement leur question", "type":16},
{ "desc" : "Les gens qui t'envoient \"on peut parler?\" sans contexte et répondent 3h plus tard", "type":16},
{ "desc" : "Les gens qui t'expliquent le fonctionnement d'un truc que tu utilises depuis 10 ans", "type":16},
{ "desc" : "Les gens qui s'installent à la table juste à côté de la tienne dans un restaurant vide", "type":16},
{ "desc" : "Les gens qui te demandent pourquoi tu n'as pas encore d'enfant", "type":16},
{ "desc" : "Les gens qui te font répéter mais ne t'écoutent toujours pas la deuxième fois", "type":16},
{ "desc" : "Les gens qui parlent fort au téléphone dans les transports en commun", "type":16},
{ "desc" : "Les gens qui t'envoient plusieurs messages au lieu d'un seul", "type":16},
{ "desc" : "Les gens qui te demandent de travailler gratuitement parce que \"c'est pour l'exposition\"", "type":16},
{ "desc" : "Les gens qui donnent leur avis sur un sujet qu'ils ne connaissent pas", "type":16},
{ "desc" : "Les gens qui te disent \"tu devrais sourire plus\"", "type":16},
{ "desc" : "Les gens qui te touchent les cheveux sans permission", "type":16},
{ "desc" : "Les gens qui se pointent chez toi sans prévenir", "type":16},
{ "desc" : "Les gens qui mettent les pieds sur la table basse", "type":16},
{ "desc" : "Les gens qui te répondent par un emoji", "type":16},
{ "desc" : "Les gens qui se sentent obligés de commenter tes choix alimentaires", "type":16},
{ "desc" : "Les gens qui utilisent \"littéralement\" pour tout sauf son sens littéral", "type":16},
{ "desc" : "Les gens qui font du sport dans le métro", "type":16},
{ "desc" : "Les gens qui te demandent \"alors, toujours célibataire?\" à chaque repas de famille", "type":16},
{ "desc" : "Les gens qui laissent leurs enfants hurler au restaurant sans rien dire", "type":16},
{ "desc" : "Les gens qui te montrent des photos de leurs enfants pendant 45 minutes", "type":16},
{ "desc" : "Les gens qui prennent leur temps à la caisse alors qu'il y a une longue file", "type":16},
{ "desc" : "Les gens qui te corrigent sur tout, y compris la prononciation de \"gif\"", "type":16},
{ "desc" : "Les gens qui te spoilent une série sans te demander où tu en es", "type":16},
{ "desc" : "Les gens qui arrosent leur Facebook de photos de leurs vacances", "type":16},
{ "desc" : "Les gens qui te demandent ton métier et te répondent \"ah, c'est intéressant...\" sans conviction", "type":16},
{ "desc" : "Les gens qui regardent leurs notifications pendant que tu parles", "type":16},
{ "desc" : "Les gens qui disent \"je te dérange?\" mais continuent de te déranger quand même", "type":16},
{ "desc" : "Les gens qui te font écouter une chanson en te fixant pour voir ta réaction", "type":16},
{ "desc" : "Les gens qui prennent la dernière part de pizza sans demander", "type":16},
{ "desc" : "Les gens qui te demandent des conseils et font exactement l'inverse", "type":16},
{ "desc" : "Les gens qui viennent aux soirées avec leur guitare non sollicitée", "type":16},
{ "desc" : "Les gens qui te montrent des vidéos drôles mais rient avant la chute", "type":16},
{ "desc" : "Les gens qui laissent des miettes de pain dans le beurre", "type":16},
{ "desc" : "Les gens qui gâchent la surprise d'un cadeau", "type":16},
{ "desc" : "Les gens qui veulent toujours splitté l'addition au centime près", "type":16},
{ "desc" : "Les gens qui partagent ton secret à d'autres personnes", "type":16},
{ "desc" : "Les gens qui te disent \"t'as pas changé\" alors que t'as pris 15 kilos", "type":16},
{ "desc" : "Les gens qui te demandent un service et s'énervent quand tu refuses", "type":16},
{ "desc" : "Les gens qui se vantent du prix de tout ce qu'ils possèdent", "type":16},
{ "desc" : "Les gens qui sortent les \"ah mais avant la Covid\" à toutes les sauces", "type":16},
{ "desc" : "Les gens qui te disent \"t'es plus belle/beau sans maquillage/barbe\"", "type":16},
{ "desc" : "Les gens qui te font remarquer tes fautes d'orthographe dans une conversation informelle", "type":16},
{ "desc" : "Les gens qui te demandent pourquoi tu es fatigué quand tu as des cernes", "type":16},
{ "desc" : "Les gens qui mettent leur musique sans écouteurs dans les transports", "type":16},
{ "desc" : "Les gens qui font des stories Instagram de chaque minute de leur concert", "type":16},
{ "desc" : "Les gens qui te proposent de te mettre en relation avec leur cousin au chômage quand tu mentions ton travail", "type":16},
{ "desc" : "Les gens qui te touchent le ventre quand tu es enceinte", "type":16},
{ "desc" : "Les gens qui te font la morale sur tes habitudes alimentaires", "type":16},
{ "desc" : "Les gens qui disent \"je t'avais dit\" après chaque problème", "type":16},
{ "desc" : "Les gens qui ne respectent jamais les horaires et arrivent toujours en retard", "type":16},
{ "desc" : "Les gens qui ramènent leur nouveau partenaire à chaque soirée après 3 jours de relation", "type":16},
{ "desc" : "Les gens qui te demandent ton signe astrologique pour expliquer ta personnalité", "type":16},
{ "desc" : "Les gens qui ne rangent pas leur caddie sur le parking", "type":16},
{ "desc" : "Les gens qui ne remettent pas les haltères à leur place à la salle de sport", "type":16},
{ "desc" : "Les gens qui te racontent des anecdotes où ils sont toujours les héros", "type":16},
{ "desc" : "Les gens qui ne se lavent pas les mains après être allés aux toilettes", "type":16},
{ "desc" : "Les gens qui récitent les dialogues d'un film que vous regardez ensemble", "type":16},
{ "desc" : "Les gens qui te demandent ton âge puis disent \"ah, je te donnais moins/plus\"", "type":16},
{ "desc" : "Les gens qui mettent les doigts sur ton écran pour montrer quelque chose", "type":16},
{ "desc" : "Les gens qui te racontent la fin d'un livre que tu es en train de lire", "type":16},
{ "desc" : "Les gens qui font du bruit avec leur paille quand leur verre est vide", "type":16},
{ "desc" : "Les gens qui jouent avec leur nourriture au restaurant", "type":16},
{ "desc" : "Les gens qui t'appellent juste pour te dire qu'ils vont t'envoyer un email", "type":16},
{ "desc" : "Les gens qui te demandent \"ça a coûté combien?\" pour tout ce que tu achètes", "type":16},
{ "desc" : "Les gens qui te disent \"t'as l'air fatigué\" quand tu vas bien", "type":16},
{ "desc" : "Les gens qui parlent avec la bouche pleine", "type":16},
{ "desc" : "Les gens qui se curent les dents en public", "type":16},
{ "desc" : "Les gens qui font des selfies avec flash dans les endroits sombres", "type":16},
{ "desc" : "Les gens qui t'envoient des chaînes de messages \"sinon tu auras 10 ans de malheur\"", "type":16},
{ "desc" : "Les gens qui te racontrent leur vie sur les réseaux alors qu'ils ne t'ont pas parlé depuis 10 ans", "type":16},
{ "desc" : "Les gens qui te demandent \"quoi de neuf?\" mais coupent la parole pour parler d'eux", "type":16},
{ "desc" : "Les gens qui t'envoient \"tu fais quoi?\" toutes les 30 minutes", "type":16},
{ "desc" : "Les gens qui mâchent leur chewing-gum la bouche ouverte", "type":16},
{ "desc" : "Les gens qui laissent les toilettes sales après leur passage", "type":16},
{ "desc" : "Les gens qui squattent les machines à la salle de sport en regardant leur téléphone", "type":16},
{ "desc" : "Les gens qui te parlent comme si tu avais 5 ans quand tu es malade", "type":16},
{ "desc" : "Les gens qui te posent toujours les mêmes questions à chaque fois qu'ils te voient", "type":16},
{ "desc" : "Les gens qui te répondent \"bientôt\" quand tu demandes l'heure d'arrivée", "type":16},
{ "desc" : "Les gens qui te demandent \"comment ça va?\" et s'énervent si tu réponds autre chose que \"bien\"", "type":16},
{ "desc" : "Les gens qui te parlent de \"leur projet de roman\" depuis 15 ans", "type":16},
{ "desc" : "Les gens qui te disent \"j'ai pensé à toi\" sans explication", "type":16},
{ "desc" : "Les gens qui te textent \"on s'appelle?\" mais sont jamais disponibles pour le faire", "type":16},
{ "desc" : "Les gens qui parlent de leurs problèmes de digestion pendant le repas", "type":16},
{ "desc" : "Les gens qui te montrent des vidéos d'accident horribles sans prévenir", "type":16},
{ "desc" : "Les gens qui commentent toutes tes photos avec \"trop belle/beau\"", "type":16},
{ "desc" : "Les gens qui prennent trois places avec leurs bagages dans le train", "type":16},
{ "desc" : "Les gens qui ne mettent pas leur clignotant en voiture", "type":16},
{ "desc" : "Les gens qui te tapent sur l'épaule pour attirer ton attention", "type":16},
{ "desc" : "Les gens qui répondent à tes messages après 3 semaines comme si de rien n'était", "type":16},
{ "desc" : "Les gens qui racontent leurs exploits sexuels sans qu'on leur demande", "type":16},
{ "desc" : "Les gens qui sonnent à la porte un dimanche matin", "type":16},
{ "desc" : "Les gens qui t'envoient des messages à 3h du matin", "type":16},
{ "desc" : "Les gens qui te demandent \"tu te souviens de moi?\" dans la rue", "type":16},
{ "desc" : "Les gens qui ne répondent jamais clairement par oui ou par non", "type":16},
{ "desc" : "Les gens qui regardent leur téléphone pendant un film au cinéma", "type":16},
{ "desc" : "Les gens qui disent \"je ne suis pas raciste, mais...\"", "type":16},
{ "desc" : "Les gens qui touchent sans cesse leur barbe en te parlant", "type":16},
{ "desc" : "Les gens qui refusent de partager la recette d'un plat qu'ils ont cuisiné", "type":16},
{ "desc" : "Les gens qui t'appellent uniquement quand ils ont besoin de quelque chose", "type":16},
{ "desc" : "Les gens qui laissent 1% de jus dans la bouteille et la remettent au frigo", "type":16},
{ "desc" : "Les gens qui te demandent de les prendre en photo 20 fois de suite", "type":16},
{ "desc" : "Les gens qui prennent des selfies avec leur plat au restaurant", "type":16},
{ "desc" : "Les gens qui font des \"challenges\" dangereux sur TikTok", "type":16},
{ "desc" : "Les gens qui te parlent pendant que tu regardes une série", "type":16},
{ "desc" : "Les gens qui te posent des questions personnelles dès la première rencontre", "type":16},
{ "desc" : "Les gens qui empestent le parfum dans l'ascenseur", "type":16},
{ "desc" : "Les gens qui te disent \"tu devrais vraiment essayer le yoga\"", "type":16},
{ "desc" : "Les gens qui se vantent d'être \"brutalement honnêtes\" pour justifier leur méchanceté", "type":16},
{ "desc" : "Les gens qui crient \"SPOILER ALERT\" après avoir déjà spoilé", "type":16},
{ "desc" : "Les gens qui tournent leur cuillère bruyamment dans leur tasse", "type":16},
{ "desc" : "Les gens qui tapent du pied sous la table en permanence", "type":16},
{ "desc" : "Les gens qui te font des \"jump scares\" pour rigoler", "type":16},
{ "desc" : "Les gens qui te racontent leurs problèmes de couple dans les moindres détails", "type":16},
{ "desc" : "Les gens qui finissent ta phrase et se trompent complètement", "type":16},
{ "desc" : "Les gens qui mettent des stories de leurs pieds à la plage", "type":16},
{ "desc" : "Les gens qui font semblant de ne pas te voir quand tu les croises", "type":16},
{ "desc" : "Les gens qui te disent \"ah, je connais quelqu'un qui fait ton métier et gagne 3 fois plus\"", "type":16},
{ "desc" : "Les gens qui te montrent les messages privés d'autres personnes", "type":16},
{ "desc" : "Les gens qui te demandent un avis et s'énervent quand tu leur donnes", "type":16},
{ "desc" : "Les gens qui portent le même parfum que leur ex", "type":16},
{ "desc" : "Les gens qui critiquent la série que tu adores sans l'avoir vue", "type":16},
{ "desc" : "Les gens qui te demandent de répéter et te coupent à la deuxième syllabe", "type":16},
{ "desc" : "Les gens qui t'envoient des messages avec juste des points d'exclamation", "type":16},
{ "desc" : "Les gens qui crient \"PAS ENCORE!\" quand tu mets ta chanson préférée", "type":16},
{ "desc" : "Les gens qui ouvrent la porte des toilettes sans frapper", "type":16},
{ "desc" : "Les gens qui te demandent ton code WiFi dès qu'ils arrivent chez toi", "type":16},
{ "desc" : "Les gens qui jettent leurs mégots de cigarette par terre", "type":16},
{ "desc" : "Les gens qui te disent \"relaxe-toi\" quand tu es stressé", "type":16},
{ "desc" : "Les gens qui t'envoient des photos d'eux à la salle de sport tous les jours", "type":16},
{ "desc" : "Les gens qui te touchent pour te montrer leur nouveau tatouage", "type":16},
{ "desc" : "Les gens qui finissent la dernière bière sans en racheter", "type":16},
{ "desc" : "Les gens qui te racontent en détail leurs opérations chirurgicales", "type":16},
{ "desc" : "Les gens qui empruntent tes affaires sans te demander", "type":16},
{ "desc" : "Les gens qui te répondent \"c'est compliqué\" à une question simple", "type":16},
{ "desc" : "Les gens qui te demandent \"pourquoi t'es encore célibataire?\"", "type":16},
{ "desc" : "Les gens qui te touchent les cheveux et disent \"ils sont tellement doux\"", "type":16},
{ "desc" : "Les gens qui ne te présentent jamais à leurs amis", "type":16},
{ "desc" : "Les gens qui vérifient tes factures au restaurant", "type":16},
{ "desc" : "Les gens qui te donnent des conseils sur comment élever tes enfants", "type":16},
{ "desc" : "Les gens qui font des Facebook Live de concerts entiers", "type":16},
{ "desc" : "Les gens qui te demandent de les aider à déménager un canapé le samedi matin", "type":16},
{ "desc" : "Les gens qui t'envoient des messages cryptiques comme \"on doit parler...\"", "type":16},
{ "desc" : "Les gens qui te font sursauter et disent \"t'es trop sur les nerfs\"", "type":16},
{ "desc" : "Les gens qui se mouchent bruyamment au restaurant", "type":16},
{ "desc" : "Les gens qui te disent \"c'est tellement toi\" pour un truc bizarre", "type":16},
{ "desc" : "Les gens qui t'envoient des vidéos de 10 minutes sans contexte", "type":16},
{ "desc" : "Les gens qui marchent pieds nus dans les lieux publics", "type":16},
{ "desc" : "Les gens qui te font des remarques sur ton poids pendant que tu manges", "type":16},
{ "desc" : "Les gens qui te disent \"tu verras quand tu auras des enfants\"", "type":16},
{ "desc" : "Les gens qui amènent leur ordinateur portable au lit", "type":16},
{ "desc" : "Les gens qui te demandent \"t'as fini?\" quand tu as encore de la nourriture dans ton assiette", "type":16},
{ "desc" : "Les gens qui font semblant de ne pas avoir d'argent quand c'est leur tour de payer", "type":16},
{ "desc" : "Les gens qui te demandent ton salaire dès la première rencontre", "type":16},
{ "desc" : "Les gens qui font des duckfaces sur toutes les photos", "type":16},
{ "desc" : "Les gens qui ne rincent pas la baignoire après s'être lavés", "type":16},
{ "desc" : "Les gens qui n'aiment pas les animaux et te le font savoir", "type":16},
{ "desc" : "Les gens qui postent des photos de leurs enfants sur tous les réseaux sociaux", "type":16},
{ "desc" : "Les gens qui utilisent le haut-parleur pour téléphoner en public", "type":16},
{ "desc" : "Les gens qui disent \"je t'ai envoyé un email\" puis t'expliquent tout l'email", "type":16},
{ "desc" : "Les gens qui te demandent si tu as tes règles quand tu es énervée", "type":16},
{ "desc" : "Les gens qui remettent leur masque sous le nez en permanence", "type":16},
{ "desc" : "Les gens qui te sifflent pour attirer ton attention", "type":16},
{ "desc" : "Les gens qui postent des photos de leurs pieds bandés après une entorse", "type":16},
{ "desc" : "Les gens qui boivent directement à la bouteille dans le frigo", "type":16},
{ "desc" : "Les gens qui mangent tes frites sans demander", "type":16},
{ "desc" : "Les gens qui te disent \"t'es trop susceptible\" quand tu réagis à leurs remarques blessantes", "type":16},
{ "desc" : "Les gens qui te demandent \"tu me trouves grossi?\"", "type":16},
{ "desc" : "Les gens qui te parlent comme si tu étais débile quand tu es étranger", "type":16},
{ "desc" : "Les gens qui disent \"c'est mon opinion\" pour justifier des propos inacceptables", "type":16},
{ "desc" : "Les gens qui bâillent sans mettre la main devant la bouche", "type":16},
{ "desc" : "Les gens qui te disent \"il faut vivre avec son temps\" quand tu n'aimes pas un truc à la mode", "type":16},
{ "desc" : "Les gens qui te racontent un film en entier alors que tu veux le voir", "type":16},
{ "desc" : "Les gens qui parlent d'eux à la troisième personne", "type":16},
{ "desc" : "Les gens qui te touchent l'écran du téléphone avec leurs doigts sales", "type":16},
{ "desc" : "Les gens qui te disent \"on est vendredi 13\" comme si tu ne savais pas lire un calendrier", "type":16},
{ "desc" : "Les gens qui font des blagues sur ton prénom que tu entends depuis 30 ans", "type":16},
{ "desc" : "Les gens qui prennent des selfies pendant les enterrements", "type":16},
{ "desc" : "Les gens qui te montrent des photos de leur ex sans raison", "type":16},
{ "desc" : "Les gens qui t'invitent à des \"dîners\" qui sont en fait des réunions Tupperware", "type":16},
{ "desc" : "Les gens qui commencent leur phrase par \"sans vouloir te vexer, mais...\"", "type":16},
{ "desc" : "Les gens qui comparent leurs enfants aux tiens", "type":16},
{ "desc" : "Les gens qui te demandent \"t'étais où? Je t'ai appelé\" sans laisser de message", "type":16},
{ "desc" : "Les gens qui te parlent de CrossFit à la première occasion", "type":16},
{ "desc" : "Les gens qui te font croire qu'ils ne sont pas beaux sur les photos où ils sont magnifiques", "type":16},
{ "desc" : "Les gens qui s'asseyent sur ton lit avec leurs vêtements de ville", "type":16},
{ "desc" : "Les gens qui te disent \"c'est trop court\" quand tu te coupes les cheveux", "type":16},
{ "desc" : "Les gens qui font du jogging sur place au feu rouge", "type":16},
{ "desc" : "Les gens qui te racontent leur régime alimentaire en détail pendant que tu manges un dessert", "type":16},
{ "desc" : "Les gens qui ne ferment jamais les placards de la cuisine", "type":16},
{ "desc" : "Les gens qui te réveillent tôt le week-end pour \"profiter de la journée\"", "type":16},
{ "desc" : "Les gens qui font une danse de la victoire quand ils gagnent au Monopoly", "type":16},
{ "desc" : "Les gens qui te chuchotent des blagues pendant un enterrement", "type":16},
{ "desc" : "Les gens qui répondent \"je ne sais pas, à toi de voir\" quand tu demandes leur avis", "type":16},
{ "desc" : "Les gens qui viennent à une soirée déguisée sans se déguiser", "type":16},
{ "desc" : "Les gens qui te demandent \"ça va?\" 15 fois dans la même conversation", "type":16},
{ "desc" : "Les gens qui regardent par-dessus ton épaule quand tu tapes ton code bancaire", "type":16},
{ "desc" : "Les gens qui conduisent à 10 km/h en dessous de la limitation", "type":16},
{ "desc" : "Les gens qui te demandent \"tu t'es fait quoi aux cheveux?\" quand tu n'as rien changé", "type":16},
{ "desc" : "Les gens qui se vantent d'avoir couché avec leur prof", "type":16},
{ "desc" : "Les gens qui rentrent dans ton bureau sans frapper", "type":16},
{ "desc" : "Les gens qui te demandent \"tu peux me dépanner?\" mais ne te remboursent jamais", "type":16},
{ "desc" : "Les gens qui sortent leur pénis en boîte de nuit pour rigoler", "type":16},
{ "desc" : "Les gens qui te proposent de goûter leur plat après avoir mis leur fourchette dans leur bouche", "type":16},
{ "desc" : "Les gens qui te racontent leur vie sur Tinder mais ne répondent jamais à tes messages", "type":16},
{ "desc" : "Les gens qui te demandent \"pourquoi t'es habillé comme ça?\"", "type":16},
{ "desc" : "Les gens qui ont toujours une meilleure anecdote que la tienne", "type":16},
{ "desc" : "Les gens qui disent \"je suis un peu psychopathe\" comme si c'était cool", "type":16},
{ "desc" : "Les gens qui te montrent des photos d'eux quand ils étaient plus minces", "type":16},
{ "desc" : "Les gens qui postent des photos de leur hospitalisation", "type":16},
{ "desc" : "Les gens qui commencent tous leurs messages par \"coucou c'est moi\"", "type":16},
{ "desc" : "Les gens qui prétendent qu'ils ont inventé une expression connue", "type":16},
{ "desc" : "Les gens qui te reprennent sur la prononciation d'un mot étranger", "type":16},
{ "desc" : "Les gens qui utilisent les toilettes sans tirer la chasse", "type":16},
{ "desc" : "Les gens qui te proposent d'aller \"boire un café\" mais commandent un thé", "type":16},
{ "desc" : "Les gens qui te serrent dans leurs bras trop longtemps", "type":16},
{ "desc" : "Les gens qui te disent \"tu devrais sortir plus souvent\"", "type":16},
{ "desc" : "Les gens qui te touchent le ventre en disant \"t'as mangé quoi?\"", "type":16},
{ "desc" : "Les gens qui prennent des photos de ton repas pour leur Instagram", "type":16},
{ "desc" : "Les gens qui te parlent comme si tu étais sourd quand tu es étranger", "type":16},
{ "desc" : "Les gens qui te demandent comment marche ton appareil puis appuient sur tous les boutons", "type":16},
{ "desc" : "Les gens qui prétendent qu'ils ne regardent pas la télé mais connaissent toutes les émissions", "type":16},
{ "desc" : "Les gens qui te touchent les cheveux en disant \"ils sont gras\"", "type":16},
{ "desc" : "Les gens qui placent subtilement leur diplôme dans toutes les conversations", "type":16},
{ "desc" : "Les gens qui disent \"je connais mes limites\" avant de vomir sur tes chaussures", "type":16},
{ "desc" : "Les gens qui crient \"SURPRISE\" quand tu sors des toilettes", "type":16},
{ "desc" : "Les gens qui te demandent tes projets pour l'année alors qu'on est le 1er janvier", "type":16},
{ "desc" : "Les gens qui touchent ton ventre de femme enceinte sans demander", "type":16},
{ "desc" : "Les gens qui sont trop émotifs devant un film que tu regardes pour la première fois", "type":16},
{ "desc" : "Les gens qui remâchent leur chewing-gum après l'avoir retiré de leur bouche", "type":16},
{ "desc" : "Les gens qui te montrent leurs cicatrices sans prévenir", "type":16},
{ "desc" : "Les gens qui te forcent à sentir leur haleine pour savoir si ça sent mauvais", "type":16},
{ "desc" : "Les gens qui mettent des stories Instagram à leur entraînement quotidien", "type":16},
{ "desc" : "Les gens qui te demandent si tu es fatigué quand tu ne portes pas de maquillage", "type":16},
{ "desc" : "Les gens qui te parlent de leur vie sexuelle pendant un dîner de famille", "type":16},
{ "desc" : "Les gens qui critiquent ton métier sans savoir ce que tu fais vraiment", "type":16},
{ "desc" : "Les gens qui font semblant de connaître une chanson en marmonnant les paroles", "type":16},
{ "desc" : "Les gens qui te racontent leurs problèmes puis te disent \"mais t'inquiète, ça va\"", "type":16},
{ "desc" : "Les gens qui disent \"j'ai trop mangé\" après chaque repas", "type":16},
{ "desc" : "Les gens qui reniflent constamment au lieu de se moucher", "type":16},
{ "desc" : "Les gens qui te tutoient alors que tu les vouvoies", "type":16},
{ "desc" : "Les gens qui insistent pour partager leur dessert avec toi", "type":16},
{ "desc" : "Les gens qui te parlent pendant que tu lis", "type":16},
{ "desc" : "Les gens qui te disent \"tu ne devrais pas porter du noir\"", "type":16},
{ "desc" : "Les gens qui portent des tongs en ville", "type":16},
{ "desc" : "Les gens qui te montrent des vidéos de leurs enfants qui font des trucs banals", "type":16},
{ "desc" : "Les gens qui te racontent leurs rêves érotiques avec toi dedans", "type":16},
{ "desc" : "Les gens qui se servent dans ton assiette sans demander", "type":16},
{ "desc" : "Les gens qui t'envoient des messages à 7h du matin le week-end", "type":16},
{ "desc" : "Les gens qui te demandent \"t'as pris un coup de soleil?\" quand tu rougis", "type":16},
{ "desc" : "Les gens qui te font des câlins quand ils transpirent", "type":16},
{ "desc" : "Les gens qui jouent avec leur téléphone pendant un rendez-vous", "type":16},
{ "desc" : "Les gens qui te disent \"t'as de la chance\" quand tu travailles dur", "type":16},
{ "desc" : "Les gens qui te demandent \"t'as un chewing-gum?\" tous les jours", "type":16},
{ "desc" : "Les gens qui se curent le nez en conduisant", "type":16},
{ "desc" : "Les gens qui tiennent absolument à te montrer leurs photos de vacances", "type":16},
{ "desc" : "Les gens qui posent la même question à 5 personnes différentes jusqu'à avoir la réponse qu'ils veulent", "type":16},
{ "desc" : "Les gens qui font des commentaires sur la nourriture dans ton caddie", "type":16},
{ "desc" : "Les gens qui te disent \"tu verras quand tu seras grand\" à 30 ans", "type":16},
{ "desc" : "Les gens qui t'envoient \"t'es là?\" puis disparaissent quand tu réponds", "type":16},
{ "desc" : "Les gens qui te font des remarques sur tes choix alimentaires pendant un repas", "type":16},
{ "desc" : "Les gens qui te racontent le film pendant que tu le regardes", "type":16},
{ "desc" : "Les gens qui font semblant de ne pas avoir reçu ta demande de remboursement", "type":16},
{ "desc" : "Les gens qui te répondent \"c'est la vie\" quand tu leur parles d'un problème sérieux", "type":16},
{ "desc" : "Les gens qui te demandent des conseils puis font l'inverse", "type":16},
{ "desc" : "Les gens qui disent \"je n'ai pas le temps de lire\" mais passent 5h sur TikTok", "type":16},
{ "desc" : "Les gens qui prennent le dernier bonbon sans proposer", "type":16},
{ "desc" : "Les gens qui laissent les tiroirs et placards ouverts après utilisation", "type":16},
{ "desc" : "Les gens qui laissent leurs cheveux dans le siphon de la douche", "type":16},
{ "desc" : "Les gens qui comparent la taille de leur pénis avec leurs potes", "type":16},
{ "desc" : "Les gens qui t'appellent pour te parler d'un mail qu'ils viennent de t'envoyer", "type":16},
{ "desc" : "Les gens qui te montrent des photos de leur ex pour te demander qui est plus beau", "type":16},
{ "desc" : "Les gens qui mettent leurs pieds sur ton tableau de bord en voiture", "type":16},
{ "desc" : "Les gens qui t'écrivent \"on s'appelle quand?\" mais ne décrochent jamais", "type":16},
{ "desc" : "Les gens qui t'expliquent des trucs que tu fais depuis 10 ans", "type":16},
{ "desc" : "Les gens qui posent des questions pendant les présentations", "type":16},
{ "desc" : "Les gens qui te demandent de surveiller leurs affaires aux toilettes", "type":16},
{ "desc" : "Les gens qui se plaignent de leur conjoint lors d'un dîner où il/elle est présent", "type":16},
{ "desc" : "Les gens qui te disent \"t'es pas drôle\" quand tu ne ris pas à leur blague", "type":16},
{ "desc" : "Les gens qui racontent leur vie intégrale au caissier du supermarché", "type":16},
{ "desc" : "Les gens qui mettent trop de parfum dans les transports", "type":16},
{ "desc" : "Les gens qui ouvrent des chips bruyamment au cinéma", "type":16},
{ "desc" : "Les gens qui gardent leur veste à l'intérieur toute la journée", "type":16},
{ "desc" : "Les gens qui te montrent des photos de leur montre connectée qui a enregistré leur sommeil", "type":16},
{ "desc" : "Les gens qui t'envoient un \"tu dors?\" à 3h du matin", "type":16},
{ "desc" : "Les gens qui te montrent une vidéo YouTube avec 15 pubs", "type":16},
{ "desc" : "Les gens qui te font sentir leur aisselle", "type":16},
{ "desc" : "Les gens qui te demandent \"tu sors ce soir?\" et s'offusquent quand tu dis non", "type":16},
{ "desc" : "Les gens qui se moquent de ton accent régional", "type":16},
{ "desc" : "Les gens qui te demandent \"pourquoi t'as pas de bonnes notes, t'es intelligent pourtant\"", "type":16},
{ "desc" : "Les gens qui te disent \"tu devrais essayer la méditation\" quand tu es stressé", "type":16},
{ "desc" : "Les gens qui te parlent de leur régime en mangeant une salade triste", "type":16},
{ "desc" : "Les gens qui ouvrent un paquet de gâteaux mais n'en mangent qu'un", "type":16},
{ "desc" : "Les gens qui te demandent \"t'as pas un euro?\" tous les jours", "type":16},
{ "desc" : "Les gens qui veulent te montrer des vidéos de leurs exploits sportifs", "type":16},
{ "desc" : "Les gens qui insistent pour prendre une photo de groupe à chaque sortie", "type":16},
{ "desc" : "Les gens qui publient des posts cryptiques pour attirer l'attention", "type":16},
{ "desc" : "Les gens qui parlent sans arrêt de leurs allergies alimentaires", "type":16},
{ "desc" : "Les gens qui te disent \"tu devrais porter des couleurs\" quand tu es en noir", "type":16},
{ "desc" : "Les gens qui demandent \"tu me trouves changé?\" après s'être coupé les cheveux d'un centimètre", "type":16},
{ "desc" : "Les gens qui mettent la musique à fond à 8h du matin le dimanche", "type":16},
{ "desc" : "Les gens qui te disent \"t'es vraiment bizarre\" quand tu ne suis pas le mouvement", "type":16},
{ "desc" : "Les gens qui te demandent de les aider à déménager mais n'ont rien préparé", "type":16},
{ "desc" : "Les gens qui flirtent avec ton partenaire devant toi", "type":16},
{ "desc" : "Les gens qui te demandent \"t'as une bonne mutuelle?\" quand tu te blesses", "type":16},
{ "desc" : "Les gens qui parlent au téléphone dans les salles de cinéma", "type":16},
{ "desc" : "Les gens qui ne rangent pas leur caddie au supermarché", "type":16},
{ "desc" : "Les gens qui conduisent en gardant leur clignotant allumé pendant des kilomètres", "type":16},
{ "desc" : "Les gens qui mangent la bouche ouverte", "type":16},
{ "desc" : "Les gens qui se coupent les ongles dans les transports en commun", "type":16},
{ "desc" : "Les gens qui disent \"c'est pas pour dire, mais...\" et qui le disent quand même", "type":16},
{ "desc" : "Les gens qui te spoilent la fin d'une série que tu viens de commencer", "type":16},
{ "desc" : "Les gens qui t'envoient un message \"Il faut qu'on parle\" sans préciser le sujet", "type":16},
{ "desc" : "Les gens qui conduisent à 80 km/h sur la voie de gauche de l'autoroute", "type":16},
{ "desc" : "Les gens qui te demandent \"alors, toujours célibataire?\" à chaque repas de famille", "type":16},
{ "desc" : "Les gens qui font \"chhht\" pour te faire taire alors qu'ils parlent depuis une heure", "type":16},
{ "desc" : "Les gens qui te montrent des vidéos YouTube en te fixant pour voir ta réaction", "type":16},
{ "desc" : "Les gens qui envoient des messages vocaux de 5 minutes pour dire trois phrases", "type":16},
{ "desc" : "Les gens qui répondent \"comme tu veux\" quand tu leur demandes où manger", "type":16},
{ "desc" : "Les gens qui te posent une question et qui te coupent au milieu de ta réponse", "type":16},
{ "desc" : "Les gens qui te racontent leurs rêves en détail pendant 20 minutes", "type":16},
{ "desc" : "Les gens qui collent leur front contre le tien pour te dire un secret en soirée", "type":16},
{ "desc" : "Les gens qui se garent sur deux places de parking", "type":16},
{ "desc" : "Les gens qui jettent leurs mégots par terre à deux mètres d'une poubelle", "type":16},
{ "desc" : "Les gens qui te \"corrigent\" en disant chocolatine au lieu de pain au chocolat", "type":16},
{ "desc" : "Les gens qui se lavent les dents au bureau dans les toilettes communes", "type":16},
{ "desc" : "Les gens qui te font remarquer que tu as pris un peu de poids", "type":16},
{ "desc" : "Les gens qui disent \"bonne journée également\" quand tu leur dis \"bonne journée\"", "type":16},
{ "desc" : "Les gens qui te regardent manger en commentant ton repas", "type":16},
{ "desc" : "Les gens qui écrivent \"sa va\" au lieu de \"ça va\"", "type":16},
{ "desc" : "Les gens qui font leurs courses à 6 personnes côte à côte en bloquant tout le rayon", "type":16},
{ "desc" : "Les gens qui sortent en jogging mais ne font jamais de sport", "type":16},
{ "desc" : "Les gens qui te fixent dans l'ascenseur sans rien dire", "type":16},
{ "desc" : "Les gens qui te racontent toute leur vie alors que tu les as juste croisés pour acheter du pain", "type":16},
{ "desc" : "Les gens qui essaient de te vendre leur produit MLM à chaque fois qu'ils te voient", "type":16},
{ "desc" : "Les gens qui disent \"on peut se tutoyer\" alors qu'ils t'ont déjà tutoyé", "type":16},
{ "desc" : "Les gens qui te tapent sur l'épaule pour dire bonjour mais qui t'ont foutu une claque en fait", "type":16},
{ "desc" : "Les gens qui te donnent des conseils médicaux alors qu'ils ont arrêté l'école en 4ème", "type":16},
{ "desc" : "Les gens qui te demandent de répéter 3 fois puis te disent \"c'est pas grave laisse tomber\"", "type":16},
{ "desc" : "Les gens qui marchent lentement côte à côte en prenant tout le trottoir", "type":16},
{ "desc" : "Les gens qui se parfument comme s'ils se douchaient avec", "type":16},
{ "desc" : "Les gens qui lisent par-dessus ton épaule dans le métro", "type":16},
{ "desc" : "Les gens qui t'envoient 10 messages d'affilée au lieu d'en faire un seul", "type":16},
{ "desc" : "Les gens qui postent chaque jour leur séance de sport sur les réseaux sociaux", "type":16},
{ "desc" : "Les gens qui disent \"j'ai fait une intolérance alimentaire\" au lieu de \"j'ai trop mangé et j'ai chié partout\"", "type":16},
{ "desc" : "Les gens qui commencent toutes leurs phrases par \"franchement\"", "type":16},
{ "desc" : "Les gens qui s'entraînent à rapper dans les transports en commun avec leurs écouteurs", "type":16},
{ "desc" : "Les gens qui te plantent un doigt dans les côtes quand ils te disent bonjour", "type":16},
{ "desc" : "Les gens qui t'ignorent quand tu les salues dans la rue", "type":16},
{ "desc" : "Les gens qui remettent leurs chaussettes sales de la veille", "type":16},
{ "desc" : "Les gens qui disent \"tu dors?\" à 3h du matin quand tu dormais justement", "type":16},
{ "desc" : "Les gens qui te répondent \"mdr\" quand tu leur as écrit un pavé", "type":16},
{ "desc" : "Les gens qui te parlent de cryptomonnaie alors que tu n'as rien demandé", "type":16},
{ "desc" : "Les gens qui te racontent le film en même temps que tu le regardes", "type":16},
{ "desc" : "Les gens qui prennent 20 minutes pour commander au restaurant", "type":16},
{ "desc" : "Les gens qui te disent \"t'as l'air fatigué\" alors que tu vas très bien", "type":16},
{ "desc" : "Les gens qui font des réunions qui auraient pu être des emails", "type":16},
{ "desc" : "Les gens qui disent \"je ne suis pas raciste, mais...\"", "type":16},
{ "desc" : "Les gens qui te demandent \"ça fait combien de temps qu'on se connaît?\" pour te taper de l'argent", "type":16},
{ "desc" : "Les gens qui mettent la musique à fond sur leur enceinte portable à la plage", "type":16},
{ "desc" : "Les gens qui te réveillent pour te dire qu'ils vont se coucher", "type":16},
{ "desc" : "Les gens qui ne se lavent pas les mains après être allés aux toilettes", "type":16},
{ "desc" : "Les gens qui disent \"je t'appelle dans 5 minutes\" et qui t'appellent 3 jours plus tard", "type":16},
{ "desc" : "Les gens qui lèchent leurs doigts pour tourner les pages", "type":16},
{ "desc" : "Les gens qui te demandent \"tu me reconnais?\" alors que tu ne les as jamais vus", "type":16},
{ "desc" : "Les gens qui grattent bruyamment leurs parties intimes en public", "type":16},
{ "desc" : "Les gens qui ne savent pas faire la différence entre \"c'est\" et \"s'est\"", "type":16},
{ "desc" : "Les gens qui te racontent l'épisode de leur série préférée alors que tu n'en as rien à foutre", "type":16},
{ "desc" : "Les gens qui te parlent pendant que tu as tes écouteurs", "type":16},
{ "desc" : "Les gens qui laissent leurs enfants hurler dans les restaurants", "type":16},
{ "desc" : "Les gens qui te disent \"détends-toi\" quand tu es énervé", "type":16},
{ "desc" : "Les gens qui s'assoient à côté de toi dans un bus vide", "type":16},
{ "desc" : "Les gens qui te demandent \"tu peux me dépanner de 5 euros?\" tous les jours depuis 10 ans", "type":16},
{ "desc" : "Les gens qui te font la bise avec leur rhume carabiné", "type":16},
{ "desc" : "Les gens qui te disent \"tu devrais sourire plus\" alors que tu n'en as pas envie", "type":16},
{ "desc" : "Les gens qui ne rincent pas leur verre après avoir bu du lait", "type":16},
{ "desc" : "Les gens qui te montrent des photos de leurs enfants pendant 45 minutes", "type":16},
{ "desc" : "Les gens qui font sonner leur téléphone en mode vibreur sur une table en métal", "type":16},
{ "desc" : "Les gens qui te font des blagues sur ton prénom comme si tu ne les avais jamais entendues", "type":16},
{ "desc" : "Les gens qui te demandent un service et qui te disent \"quand tu auras le temps\" alors que c'est urgent", "type":16},
{ "desc" : "Les gens qui partagent des fake news sans vérifier", "type":16},
{ "desc" : "Les gens qui te demandent de les aider à déménager sans prévoir à manger", "type":16},
{ "desc" : "Les gens qui mettent du ketchup sur des pâtes à la carbonara", "type":16},
{ "desc" : "Les gens qui entrent dans ton bureau sans frapper", "type":16},
{ "desc" : "Les gens qui sentent leur pet discrètement puis qui s'en vont", "type":16},
{ "desc" : "Les gens qui mangent ton dessert au frigo en disant \"je pensais que personne n'en voulait\"", "type":16},
{ "desc" : "Les gens qui touchent ton ventre quand tu es enceinte sans te demander", "type":16},
{ "desc" : "Les gens qui te disent \"il faut positiver\" quand tu traverses une période difficile", "type":16},
{ "desc" : "Les gens qui te font remarquer une faute d'orthographe en plein milieu d'une dispute", "type":16},
{ "desc" : "Les gens qui regardent ton écran de téléphone dans les transports", "type":16},
{ "desc" : "Les gens qui te tapent la discute alors que tu es aux toilettes publiques", "type":16},
{ "desc" : "Les gens qui te parlent pendant que tu essaies de lire", "type":16},
{ "desc" : "Les gens qui te racontent les mêmes anecdotes pour la 50ème fois", "type":16},
{ "desc" : "Les gens qui te doivent de l'argent mais qui t'invitent au restaurant", "type":16},
{ "desc" : "Les gens qui te posent une question et qui regardent leur téléphone pendant ta réponse", "type":16},
{ "desc" : "Les gens qui disent \"ah, il fait chaud aujourd'hui\" tous les jours de l'été", "type":16},
{ "desc" : "Les gens qui te font croire qu'ils sont experts alors qu'ils ont lu un article Wikipédia", "type":16},
{ "desc" : "Les gens qui jouent avec la nourriture au restaurant", "type":16},
{ "desc" : "Les gens qui te disent \"t'as qu'à...\" pour résoudre un problème complexe", "type":16},
{ "desc" : "Les gens qui te claquent la porte au nez alors que tu es juste derrière", "type":16},
{ "desc" : "Les gens qui te demandent \"ça va?\" sans attendre ta réponse", "type":16},
{ "desc" : "Les gens qui changent de sujet quand c'est à leur tour de payer l'addition", "type":16},
{ "desc" : "Les gens qui te fixent dans les yeux pendant qu'ils mangent une banane", "type":16},
{ "desc" : "Les gens qui vérifient toujours qui a mis un \"j'aime\" sur leurs photos", "type":16},
{ "desc" : "Les gens qui finissent ta phrase à ta place et se trompent complètement", "type":16},

];