const carddata2 = [{ desc : "Mime quelqu'un qui découvre une araignée dans sa douche" , type: 2},
{ desc : "Mime un supporter déçu après une défaite de son équipe" , type: 2},
{ desc : "Mime quelqu'un qui marche sur un LEGO pieds nus" , type: 2},
{ desc : "Mime une personne qui essaie de ne pas éternuer" , type: 2},
{ desc : "Mime quelqu'un qui essaye de séduire le joueur à ta droite" , type: 2},
{ desc : "Mime une personne qui découvre qu'elle a du papier toilette collé à sa chaussure" , type: 2},
{ desc : "Mime quelqu'un qui se fait flasher par un radar" , type: 2},
{ desc : "Mime un bébé qui fait ses premiers pas" , type: 2},
{ desc : "Mime quelqu'un qui essaie de contenir une envie pressante" , type: 2},
{ desc : "Mime une personne qui marche sur des talons pour la première fois" , type: 2},
{ desc : "Mime quelqu'un qui découvre une facture astronomique" , type: 2},
{ desc : "Mime une personne qui a la bouche brûlée par un plat trop épicé" , type: 2},
{ desc : "Mime un DJ en plein set" , type: 2},
{ desc : "Mime quelqu'un qui essaie de rentrer dans un jean trop petit" , type: 2},
{ desc : "Mime une personne qui marche dans une flaque d'eau avec des chaussettes" , type: 2},
{ desc : "Mime quelqu'un qui découvre des cheveux dans son plat au restaurant" , type: 2},
{ desc : "Mime une personne qui essaie de cacher une érection" , type: 2},
{ desc : "Mime un influenceur qui fait la promotion d'un produit douteux" , type: 2},
{ desc : "Mime quelqu'un qui mange un citron entier" , type: 2},
{ desc : "Mime une personne qui découvre des messages compromettants sur le téléphone de son/sa partenaire" , type: 2},
{ desc : "Mime quelqu'un qui découvre qu'il n'y a plus de papier toilette" , type: 2},
{ desc : "Mime une personne qui essaie de ne pas s'endormir en réunion" , type: 2},
{ desc : "Mime quelqu'un qui se fait contrôler par la police" , type: 2},
{ desc : "Mime une personne qui a marché dans une crotte de chien" , type: 2},
{ desc : "Mime quelqu'un qui se fait larguer en public" , type: 2},
{ desc : "Mime une personne qui essaie de cacher qu'elle vient de péter" , type: 2},
{ desc : "Mime quelqu'un qui essaie d'attraper une mouche" , type: 2},
{ desc : "Mime une personne qui se prend un poteau en regardant son téléphone" , type: 2},
{ desc : "Mime quelqu'un qui découvre un cafard dans son assiette" , type: 2},
{ desc : "Mime une personne qui essaie de garder son calme face à un client difficile" , type: 2},
{ desc : "Mime quelqu'un qui a une crampe en plein acte sexuel" , type: 2},
{ desc : "Mime une personne qui se fait surprendre en train de se masturber" , type: 2},
{ desc : "Mime quelqu'un qui découvre que son pantalon est déchiré en public" , type: 2},
{ desc : "Mime une personne qui a un fou rire incontrôlable dans un lieu inapproprié" , type: 2},
{ desc : "Mime quelqu'un qui se fait mal au petit orteil contre un meuble" , type: 2},
{ desc : "Mime une personne qui essaie de ne pas vomir dans les transports" , type: 2},
{ desc : "Mime quelqu'un qui se fait prendre en photo alors qu'il n'est pas prêt" , type: 2},
{ desc : "Mime une personne qui découvre une araignée dans ses toilettes" , type: 2},
{ desc : "Mime quelqu'un qui essaie de cacher son double menton sur une photo" , type: 2},
{ desc : "Mime une personne qui essaie de lire sans ses lunettes" , type: 2},
{ desc : "Mime quelqu'un qui découvre que son/sa partenaire le/la trompe" , type: 2},
{ desc : "Mime une personne qui essaie de traverser une rue très fréquentée" , type: 2},
{ desc : "Mime quelqu'un qui se fait draguer lourdement" , type: 2},
{ desc : "Mime une personne qui essaie de ne pas rire lors d'un enterrement" , type: 2},
{ desc : "Mime quelqu'un qui découvre qu'il a pris 10 kilos" , type: 2},
{ desc : "Mime une personne qui essaie de cacher son haleine" , type: 2},
{ desc : "Mime quelqu'un qui se fait surprendre en train de fouiller" , type: 2},
{ desc : "Mime une personne qui essaie de se retenir d'aller aux toilettes" , type: 2},
{ desc : "Mime quelqu'un qui découvre que son compte en banque est vide" , type: 2},
{ desc : "Mime une personne qui se fait piquer par une guêpe" , type: 2},
{ desc : "Mime quelqu'un qui découvre une araignée dans ses toilettes" , type: 2},
{ desc : "Mime un chien qui essaie de comprendre un tour de magie" , type: 2},
{ desc : "Mime une personne qui essaie d'attraper le dernier métro" , type: 2},
{ desc : "Mime quelqu'un qui essaie de manger très chaud sans se brûler" , type: 2},
{ desc : "Mime un touriste qui se fait voler son portefeuille" , type: 2},
{ desc : "Mime une personne qui fait semblant d'écouter une conversation ennuyeuse" , type: 2},
{ desc : "Mime un DJ complètement dépassé par sa playlist" , type: 2},
{ desc : "Mime quelqu'un qui essaie d'éteindre son réveil sans ouvrir les yeux" , type: 2},
{ desc : "Mime une grand-mère qui découvre TikTok" , type: 2},
{ desc : "Mime un présentateur météo face à une tempête en direct" , type: 2},
{ desc : "Mime quelqu'un qui fait semblant d'aimer un cadeau horrible" , type: 2},
{ desc : "Mime une personne qui essaie de danser sobre dans une boîte de nuit" , type: 2},
{ desc : "Mime un enfant qui fait semblant de ne pas avoir cassé un vase" , type: 2},
{ desc : "Mime quelqu'un qui se brûle la langue avec du café trop chaud" , type: 2},
{ desc : "Mime une personne qui essaie de faire du yoga pour la première fois" , type: 2},
{ desc : "Mime quelqu'un qui tente de monter un meuble IKEA sans notice" , type: 2},
{ desc : "Mime une personne qui essaie de prendre un selfie avantageux" , type: 2},
{ desc : "Mime quelqu'un qui rate une marche d'escalier en public" , type: 2},
{ desc : "Mime une personne qui essaie de cacher son rot en société" , type: 2},
{ desc : "Mime un serveur qui fait tomber un plateau rempli de verres" , type: 2},
{ desc : "Mime quelqu'un qui fait semblant de connaître les paroles d'une chanson" , type: 2},
{ desc : "Mime une personne qui essaie de ne pas éternuer pendant une réunion importante" , type: 2},
{ desc : "Mime quelqu'un qui tente de comprendre les nouvelles fonctionnalités de son téléphone" , type: 2},
{ desc : "Mime une personne qui conduit en étant complètement perdue" , type: 2},
{ desc : "Mime un policier qui essaie d'être cool avec les jeunes" , type: 2},
{ desc : "Mime quelqu'un qui essaie de rester éveillé pendant un cours ennuyeux" , type: 2},
{ desc : "Mime une personne qui fait semblant de comprendre une blague" , type: 2},
{ desc : "Mime quelqu'un qui croise son ex en ville avec sa nouvelle conquête" , type: 2},
{ desc : "Mime une personne qui regarde un film d'horreur" , type: 2},
{ desc : "Mime quelqu'un qui fait croire qu'il connaît le vin" , type: 2},
{ desc : "Mime une personne qui essaie de ne pas rire à un enterrement" , type: 2},
{ desc : "Mime quelqu'un qui se rend compte qu'il n'a plus de papier toilette" , type: 2},
{ desc : "Mime une personne qui fait semblant d'être sobre devant ses parents" , type: 2},
{ desc : "Mime quelqu'un qui fait un discours improvisé" , type: 2},
{ desc : "Mime une personne qui simule une crise pour éviter une réunion" , type: 2},
{ desc : "Mime quelqu'un qui essaie de séduire discrètement" , type: 2},
{ desc : "Mime une personne qui fait semblant de comprendre la politique" , type: 2},
{ desc : "Mime quelqu'un qui essaie de cacher son écran de téléphone dans le métro" , type: 2},
{ desc : "Mime une personne sur un appel Zoom qui ne sait pas que sa caméra est allumée" , type: 2},
{ desc : "Mime quelqu'un qui prétend connaître une célébrité" , type: 2},
{ desc : "Mime une personne qui apprend qu'elle a gagné au loto" , type: 2},
{ desc : "Mime quelqu'un qui essaie de fermer sa valise trop pleine" , type: 2},
{ desc : "Mime une personne qui se rend compte que sa braguette est ouverte en public" , type: 2},
{ desc : "Mime quelqu'un qui fait semblant d'être intéressé par la collection de timbres d'un collègue" , type: 2},
{ desc : "Mime une personne qui essaie de faire du skate pour la première fois" , type: 2},
{ desc : "Mime quelqu'un qui se fait contrôler par les douanes avec quelque chose à cacher" , type: 2},
{ desc : "Mime une personne qui découvre son premier cheveu blanc" , type: 2},
{ desc : "Mime quelqu'un qui essaie de prendre l'air intelligent lors d'une conversation sur l'art contemporain" , type: 2},
{ desc : "Mime une personne qui tente de suivre une chorégraphie compliquée" , type: 2},
{ desc : "Mime quelqu'un qui a une panne d'oreillette pendant une traduction simultanée" , type: 2},
{ desc : "Mime une personne qui essaie de faire croire qu'elle sait nager" , type: 2},
{ desc : "Mime quelqu'un qui se réveille en retard pour un entretien d'embauche" , type: 2},
{ desc : "Mime une personne qui essaie d'impressionner ses beaux-parents" , type: 2},
{ desc : "Mime quelqu'un qui fait semblant de savoir jouer d'un instrument" , type: 2},
{ desc : "Mime une personne qui a perdu ses clés mais fait semblant que tout va bien" , type: 2},
{ desc : "Mime quelqu'un qui se fait surprendre en train de fouiller dans le frigo à minuit" , type: 2},
{ desc : "Mime une personne qui essaie de changer une couche pour la première fois" , type: 2},
{ desc : "Mime quelqu'un qui prétend être malade pour éviter une soirée" , type: 2},
{ desc : "Mime une personne qui fait du playback sur une chanson qu'elle ne connaît pas" , type: 2},
{ desc : "Mime quelqu'un qui essaie de cacher une tache embarrassante sur son pantalon" , type: 2},
{ desc : "Mime une personne qui se rend compte qu'elle a envoyé un message au mauvais destinataire" , type: 2},
{ desc : "Mime quelqu'un qui essaie de paraître mystérieux" , type: 2},
{ desc : "Mime une personne qui se prend pour un super-héros" , type: 2},
{ desc : "Mime quelqu'un qui tente de manger élégamment des spaghettis" , type: 2},
{ desc : "Mime une personne qui essaie de contrôler un fou rire pendant une situation sérieuse" , type: 2},
{ desc : "Mime quelqu'un qui se fait attaquer par des mouettes à la plage" , type: 2},
{ desc : "Mime une personne qui découvre un insecte dans son plat au restaurant" , type: 2},
{ desc : "Mime quelqu'un qui essaie de faire du beatbox" , type: 2},
{ desc : "Mime une personne qui tente de prendre une photo de groupe où tout le monde soit bien" , type: 2},
{ desc : "Mime quelqu'un qui fait semblant d'être intéressé par les bitcoins" , type: 2},
{ desc : "Mime une personne qui essaie de faire un régime mais craque en secret" , type: 2},
{ desc : "Mime quelqu'un qui se prend pour un mannequin sur un podium" , type: 2},
{ desc : "Mime une personne qui tente de garder son calme face à un enfant capricieux" , type: 2},
{ desc : "Mime quelqu'un qui essaie de passer incognito" , type: 2},
{ desc : "Mime une personne qui fait semblant d'être occupée au travail quand le boss passe" , type: 2},
{ desc : "Mime quelqu'un qui tente de sortir discrètement d'une soirée ennuyeuse" , type: 2},
{ desc : "Mime une personne sous l'effet d'une anesthésie dentaire" , type: 2},
{ desc : "Mime quelqu'un qui prétend être un expert en vin dans un restaurant chic" , type: 2},
{ desc : "Mime une personne qui essaie de faire un selfie avec un monument célèbre" , type: 2},
{ desc : "Mime quelqu'un qui tente de paraître naturel sur une photo d'identité" , type: 2},
{ desc : "Mime une personne qui fait semblant d'apprécier un cadeau décevant" , type: 2},
{ desc : "Mime quelqu'un qui essaie de passer pour un local en vacances" , type: 2},
{ desc : "Mime une personne qui découvre sa nouvelle coupe de cheveux ratée" , type: 2},
{ desc : "Mime quelqu'un qui tente de marcher avec élégance en talons hauts" , type: 2},
{ desc : "Mime une personne qui essaie de cacher qu'elle a trop bu à un dîner professionnel" , type: 2},
{ desc : "Mime quelqu'un qui fait semblant de comprendre une langue étrangère" , type: 2},
{ desc : "Mime une personne qui essaie de paraître cool devant des adolescents" , type: 2},
{ desc : "Mime quelqu'un qui fait un discours de mariage improvisé" , type: 2},
{ desc : "Mime une personne qui tente de danser la salsa sans savoir comment faire" , type: 2},
{ desc : "Mime quelqu'un qui essaie de faire croire qu'il a lu un livre dont tout le monde parle" , type: 2},
{ desc : "Mime une personne qui fait semblant d'être malade pour rester à la maison" , type: 2},
{ desc : "Mime quelqu'un qui essaie de ne pas s'endormir pendant une réunion interminable" , type: 2},
{ desc : "Mime une personne qui tente de cacher sa gueule de bois au travail" , type: 2},
{ desc : "Mime quelqu'un qui essaie d'impressionner quelqu'un à la salle de sport" , type: 2},
{ desc : "Mime une personne qui fait semblant de comprendre la cryptomonnaie" , type: 2},
{ desc : "Mime quelqu'un qui tente de prendre une photo \"naturelle\" pour les réseaux sociaux" , type: 2},
{ desc : "Mime une personne qui essaie de garder son sérieux pendant une blague nulle" , type: 2},
{ desc : "Mime quelqu'un qui fait semblant d'être surpris à une fête surprise" , type: 2},
{ desc : "mime un animal, les autres doivent deviner lequel." , type: 2},
{ desc : "mime une scène de film célèbre sans parler, les autres doivent deviner." , type: 2},
{ desc : "mime un métier, le premier qui devine gagne un point." , type: 2},
{ desc : "mime un gorille à la recherche de nourriture" , type: 2},
{ desc : "mime quelqu'un qui découvre une araignée dans sa douche" , type: 2},
{ desc : "mime un mannequin sur un podium" , type: 2},
{ desc : "mime quelqu'un qui essaie de manger une soupe très chaude" , type: 2},
{ desc : "mime un zombie en quête de cerveau" , type: 2},
{ desc : "mime quelqu'un qui essaie de monter des escaliers invisibles" , type: 2},
{ desc : "mime un pilote d'avion en pleine turbulence" , type: 2},
{ desc : "mime une personne qui découvre que ses lacets sont attachés ensemble" , type: 2},
{ desc : "mime un chien qui essaie d'attraper sa queue" , type: 2},
{ desc : "mime quelqu'un qui marche sur des braises ardentes" , type: 2},
{ desc : "mime une personne essayant de déverrouiller sa porte avec les mauvaises clés" , type: 2},
{ desc : "mime un joueur de tennis professionnel" , type: 2},
{ desc : "mime quelqu'un qui essaie de faire tenir un château de cartes" , type: 2},
{ desc : "mime une personne faisant du shopping frénétique pendant les soldes" , type: 2},
{ desc : "mime quelqu'un qui essaie de manger un burger géant" , type: 2},
{ desc : "mime quelqu'un qui marche sur la Lune" , type: 2},
{ desc : "mime une personne essayant de faire du patin à glace pour la première fois" , type: 2},
{ desc : "mime un cambrioleur essayant d'être discret" , type: 2},
{ desc : "mime quelqu'un qui se fait attaquer par des abeilles" , type: 2},
{ desc : "mime un jardinier tentant de tuer une taupe" , type: 2},
{ desc : "mime un mannequin qui trébuche sur le podium" , type: 2},
{ desc : "mime une personne qui découvre que son pantalon est déchiré en public" , type: 2},
{ desc : "mime un saut en parachute" , type: 2},
{ desc : "mime un serveur maladroit dans un restaurant chic" , type: 2},
{ desc : "mime quelqu'un qui fait du shopping pendant les soldes" , type: 2},
{ desc : "mime un chanteur d'opéra passionné" , type: 2},
{ desc : "mime une personne coincée dans un ascenseur" , type: 2},
{ desc : "mime un gorille dans un zoo" , type: 2},
{ desc : "mime un magicien dont les tours échouent" , type: 2},
{ desc : "mime quelqu'un qui démêle des écouteurs" , type: 2},
{ desc : "mime une personne qui se réveille en retard pour le travail" , type: 2},
{ desc : "mime quelqu'un qui découvre une souris dans sa cuisine" , type: 2},
{ desc : "mime un touriste qui prend des photos de tout" , type: 2},
{ desc : "mime quelqu'un qui marche sous une pluie torrentielle sans parapluie" , type: 2},
{ desc : "mime un bébé qui apprend à marcher" , type: 2},
{ desc : "mime un individu qui essaie de dégonfler un matelas pneumatique" , type: 2},
{ desc : "mime quelqu'un qui met ses lentilles de contact pour la première fois" , type: 2},
{ desc : "mime une personne qui essaie d'attraper un papillon" , type: 2},
{ desc : "mime quelqu'un qui se fait voler son portefeuille dans le métro" , type: 2},
{ desc : "mime un professeur de fitness très enthousiaste" , type: 2},
{ desc : "mime quelqu'un qui essaie de tuer une araignée mais qui en a peur" , type: 2},
{ desc : "mime une personne qui mange une nourriture extrêmement épicée" , type: 2},
{ desc : "mime quelqu'un qui essaie de monter les escaliers avec trop de sacs de courses" , type: 2},
{ desc : "mime une personne qui fait semblant de travailler quand le patron arrive" , type: 2},
{ desc : "mime quelqu'un qui est pris dans une tempête de neige" , type: 2},
{ desc : "mime une personne qui s'est assise sur un chewing-gum" , type: 2},
{ desc : "mime quelqu'un qui essaie d'attirer l'attention d'un serveur dans un restaurant bondé" , type: 2},
{ desc : "mime une personne qui perd ses clés et les cherche frénétiquement" , type: 2},
{ desc : "mime quelqu'un qui essaie de parler à quelqu'un de très grand" , type: 2},
{ desc : "mime une personne qui fait du hula hoop" , type: 2},
{ desc : "mime quelqu'un qui essaie de danser la salsa sans savoir comment" , type: 2},
{ desc : "mime une personne qui fait un discours et oublie ce qu'elle voulait dire" , type: 2},
{ desc : "mime quelqu'un qui essaie d'ouvrir un pot de cornichons très serré" , type: 2},
{ desc : "mime une personne qui se regarde dans le miroir et se trouve magnifique" , type: 2},
{ desc : "mime quelqu'un qui tente de faire du yoga pour la première fois" , type: 2},
{ desc : "mime une personne qui essaie de ne pas éternuer pendant une réunion importante" , type: 2},
{ desc : "mime quelqu'un qui marche sur des Lego pieds nus" , type: 2},
{ desc : "mime une personne qui essaie de faire un selfie parfait" , type: 2},
{ desc : "mime quelqu'un qui a oublié qu'il était en visioconférence et fait des choses embarrassantes" , type: 2},
{ desc : "mime une personne qui essaie de lire sans ses lunettes" , type: 2},
{ desc : "mime quelqu'un qui tente de rattraper un bus qui vient de partir" , type: 2},
{ desc : "mime une personne qui survit à une attaque de zombies" , type: 2},
{ desc : "mime quelqu'un qui essaie de garder l'équilibre sur un bateau en pleine tempête" , type: 2},
{ desc : "mime une personne qui a mangé quelque chose de périmé" , type: 2},
{ desc : "mime quelqu'un qui fait semblant de comprendre une langue étrangère" , type: 2},
{ desc : "Mime Nicolas Sarkozy en train de faire son jogging." , type: 2},
{ desc : "Mime Jean-Luc Mélenchon pendant l'une de ses colères légendaires." , type: 2},
{ desc : "Mime Céline Dion en plein concert avec ses grands gestes." , type: 2},
{ desc : "Mime Zinedine Zidane donnant un coup de tête à Materazzi." , type: 2},
{ desc : "Mime Emmanuel Macron qui essaie de convaincre des gilets jaunes." , type: 2},
{ desc : "Mime Nicolas Sarkozy en train de faire son jogging." , type: 2},
{ desc : "Mime Jean-Luc Mélenchon pendant l'une de ses colères légendaires." , type: 2},
{ desc : "Mime Céline Dion en plein concert avec ses grands gestes." , type: 2},
{ desc : "Mime Zinedine Zidane donnant un coup de tête à Materazzi." , type: 2},
{ desc : "Mime Emmanuel Macron qui essaie de convaincre des gilets jaunes." , type: 2},
{ desc : "Mime Jacques Chirac qui saute un tourniquet de métro." , type: 2},
{ desc : "Mime une pub de parfum de luxe ridiculement intense." , type: 2},
{ desc : "Mime Jamel Debbouze dans une scène typique." , type: 2},
{ desc : "Mime Jean Dujardin dans OSS 117." , type: 2},
{ desc : "Mime Catherine Deneuve qui fume une cigarette avec dédain." , type: 2},
{ desc : "Mime Édouard Philippe qui essaie de se coiffer par grand vent." , type: 2},
{ desc : "Mime un candidat stressé qui passe le bac." , type: 2},
{ desc : "Mime Cyril Hanouna en pleine émission." , type: 2},
{ desc : "Mime Claude François qui se prend une décharge électrique." , type: 2},
{ desc : "Mime Brigitte Macron qui fait du shopping incognito." , type: 2},
{ desc : "Mime une pub Orangina où tout se secoue." , type: 2},
{ desc : "Mime Michel Drucker qui interviewe un invité ennuyeux." , type: 2},
{ desc : "Mime Gérard Depardieu qui goûte du vin." , type: 2},
{ desc : "Mime un joueur de foot qui simule une blessure grave." , type: 2},
{ desc : "Mime un touriste parisien qui découvre le prix d'un café sur les Champs-Élysées." , type: 2},
{ desc : "Mime Marine Le Pen qui apprend qu'elle a perdu les élections." , type: 2},
{ desc : "Mime Mireille Mathieu qui se coiffe." , type: 2},
{ desc : "Mime Louis de Funès dans une colère explosive." , type: 2},
{ desc : "Mime Thierry Henry qui fait sa célébration iconique." , type: 2},
{ desc : "Mime François Hollande sous la pluie sans parapluie." , type: 2},
{ desc : "Mime Zidane qui donne ses instructions depuis le banc de touche." , type: 2},
{ desc : "Mime Kad Merad dans \"Bienvenue chez les Ch'tis\"." , type: 2},
{ desc : "Mime un présentateur météo face à une tempête inattendue." , type: 2},
{ desc : "Mime Didier Deschamps qui célèbre un but de l'équipe de France." , type: 2},
{ desc : "Mime Mimie Mathy dans Joséphine Ange Gardien qui disparaît." , type: 2},
{ desc : "Mime Johnny Hallyday en plein concert qui fait son déhanché." , type: 2},
{ desc : "Mime Nabilla qui dit \"Allô, non mais allô quoi !\"." , type: 2},
{ desc : "Mime Patrick Sébastien qui anime \"Le plus grand cabaret du monde\"." , type: 2},
{ desc : "Mime Éric Zemmour pendant un débat houleux." , type: 2},
{ desc : "Mime Kylian Mbappé qui fête un but." , type: 2},
{ desc : "Mime Amélie Poulain qui casse la croûte d'une crème brûlée." , type: 2},
{ desc : "Mime Renaud qui chante \"Mistral Gagnant\"." , type: 2},
{ desc : "Mime un agent SNCF qui annonce un retard important." , type: 2},
{ desc : "Mime Omar Sy dans Intouchables sur sa chaise roulante." , type: 2},
{ desc : "Mime un serveur parisien snob." , type: 2},
{ desc : "Mime Claude François dansant sur \"Cette année-là\"." , type: 2},
{ desc : "Mime Carla Bruni défilant sur un podium." , type: 2},
{ desc : "Mime Alain Delon qui séduit avec son regard." , type: 2},
{ desc : "Mime Christophe Dechavanne qui anime un jeu télévisé chaotique." , type: 2},
{ desc : "Mime Astérix qui boit de la potion magique." , type: 2},
{ desc : "Mime Zinedine Zidane qui exécute son célèbre roulette." , type: 2},
{ desc : "Mime Laurent Ruquier qui présente \"On n'est pas couché\"." , type: 2},
{ desc : "Mime Edith Piaf qui chante \"Non, je ne regrette rien\"." , type: 2},
{ desc : "Mime Gad Elmaleh faisant son sketch sur la boîte de nuit." , type: 2},
{ desc : "Mime Michel Platini qui tire un penalty décisif." , type: 2},


];