const carddata12 = [
    { desc : "Kylian Mbappé" , type: 12, subType:1},
{ desc : "Emmanuel Macron" , type: 12, subType:1},
{ desc : "Marie Curie" , type: 12, subType:1},
{ desc : "Cristiano Ronaldo" , type: 12, subType:1},
{ desc : "Lady Gaga" , type: 12, subType:1},
{ desc : "Batman" , type: 12, subType:1},
{ desc : "Céline Dion" , type: 12, subType:1},
{ desc : "Jean-Luc Mélenchon" , type: 12, subType:1},
{ desc : "Beyoncé" , type: 12, subType:1},
{ desc : "Spider-Man" , type: 12, subType:1},
{ desc : "Angela Merkel" , type: 12, subType:1},
{ desc : "Lionel Messi" , type: 12, subType:1},
{ desc : "Marine Le Pen" , type: 12, subType:1},
{ desc : "Michael Jackson" , type: 12, subType:1},
{ desc : "Harry Potter" , type: 12, subType:1},
{ desc : "Donald Trump" , type: 12, subType:1},
{ desc : "Winnie l'Ourson" , type: 12, subType:1},
{ desc : "Bob l'Éponge" , type: 12, subType:1},
{ desc : "Madonna" , type: 12, subType:1},
{ desc : "Brigitte Macron" , type: 12, subType:1},
{ desc : "Bart Simpson" , type: 12, subType:1},
{ desc : "Zidane" , type: 12, subType:1},
{ desc : "Wonder Woman" , type: 12, subType:1},
{ desc : "Astérix" , type: 12, subType:1},
{ desc : "Michel Drucker" , type: 12, subType:1},
{ desc : "Iron Man" , type: 12, subType:1},
{ desc : "Jean Dujardin" , type: 12, subType:1},
{ desc : "Simone Veil" , type: 12, subType:1},
{ desc : "Daft Punk" , type: 12, subType:1},
{ desc : "Dark Vador" , type: 12, subType:1},
{ desc : "Ariana Grande" , type: 12, subType:1},
{ desc : "Kev Adams" , type: 12, subType:1},
{ desc : "Mario Bros" , type: 12, subType:1},
{ desc : "Omar Sy" , type: 12, subType:1},
{ desc : "Elsa (La Reine des Neiges)" , type: 12, subType:1},
{ desc : "Jeff Bezos" , type: 12, subType:1},
{ desc : "Nabilla" , type: 12, subType:1},
{ desc : "Shrek" , type: 12, subType:1},
{ desc : "Édith Piaf" , type: 12, subType:1},
{ desc : "Pikachu" , type: 12, subType:1},
{ desc : "Gims" , type: 12, subType:1},
{ desc : "Barbie" , type: 12, subType:1},
{ desc : "Homer Simpson" , type: 12, subType:1},
{ desc : "M. Pokora" , type: 12, subType:1},
{ desc : "La Joconde" , type: 12, subType:1},
{ desc : "Thanos" , type: 12, subType:1},
{ desc : "Orelsan" , type: 12, subType:1},
{ desc : "Le Pape François" , type: 12, subType:1},
{ desc : "Captain America" , type: 12, subType:1},
{ desc : "Mimie Mathy" , type: 12, subType:1},
{ desc : "Patrick Sébastien" , type: 12, subType:1},
{ desc : "Katniss Everdeen" , type: 12, subType:1},
{ desc : "Cyril Hanouna" , type: 12, subType:1},
{ desc : "Voldemort" , type: 12, subType:1},
{ desc : "Angèle" , type: 12, subType:1},
{ desc : "Sonic" , type: 12, subType:1},
{ desc : "Vladimir Poutine" , type: 12, subType:1},
{ desc : "Yoda" , type: 12, subType:1},
{ desc : "Dora l'exploratrice" , type: 12, subType:1},
{ desc : "Bernard Arnault" , type: 12, subType:1},
{ desc : "Thomas Pesquet" , type: 12, subType:1},
{ desc : "Joker" , type: 12, subType:1},
{ desc : "Johnny Hallyday" , type: 12, subType:1},
{ desc : "Elton John" , type: 12, subType:1},
{ desc : "Greta Thunberg" , type: 12, subType:1},
{ desc : "Batman" , type: 12, subType:1},
{ desc : "Aya Nakamura" , type: 12, subType:1},
{ desc : "Hulk" , type: 12, subType:1},
{ desc : "Blanche Neige" , type: 12, subType:1},
{ desc : "Stromae" , type: 12, subType:1},
{ desc : "Squeezie" , type: 12, subType:1},
{ desc : "Terminator" , type: 12, subType:1},
{ desc : "Neymar" , type: 12, subType:1},
{ desc : "Rihanna" , type: 12, subType:1},
{ desc : "Jamel Debbouze" , type: 12, subType:1},
{ desc : "Deadpool" , type: 12, subType:1},
{ desc : "Anne Hidalgo" , type: 12, subType:1},
{ desc : "Booba" , type: 12, subType:1},
{ desc : "La Belle au bois dormant" , type: 12, subType:1},
{ desc : "Nicolas Sarkozy" , type: 12, subType:1},
{ desc : "Billie Eilish" , type: 12, subType:1},
{ desc : "Le Père Noël" , type: 12, subType:1},
{ desc : "Léa Salamé" , type: 12, subType:1},
{ desc : "Leonardo DiCaprio" , type: 12, subType:1},
{ desc : "Amélie Poulain" , type: 12, subType:1},
{ desc : "Elon Musk" , type: 12, subType:1},
{ desc : "Soprano" , type: 12, subType:1},
{ desc : "La Schtroumpfette" , type: 12, subType:1},
{ desc : "Jack Sparrow" , type: 12, subType:1},
{ desc : "Britney Spears" , type: 12, subType:1},
{ desc : "Gandalf" , type: 12, subType:1},
{ desc : "Florence Foresti" , type: 12, subType:1},
{ desc : "Black Panther" , type: 12, subType:1},
{ desc : "Sophie Marceau" , type: 12, subType:1},
{ desc : "McFly et Carlito" , type: 12, subType:1},
{ desc : "Thor" , type: 12, subType:1},
{ desc : "Adèle" , type: 12, subType:1},
{ desc : "Buzz l'Éclair" , type: 12, subType:1},
{ desc : "Nagui" , type: 12, subType:1},
{ desc : "BTS" , type: 12, subType:1},
{ desc : "Mulan" , type: 12, subType:1},
{ desc : "Gérard Depardieu" , type: 12, subType:1},
{ desc : "Freddie Mercury" , type: 12, subType:1},
{ desc : "Hermione Granger" , type: 12, subType:1},
{ desc : "Jacques Chirac" , type: 12, subType:1},
{ desc : "Scarlett Johansson" , type: 12, subType:1},
{ desc : "Le Grinch" , type: 12, subType:1},
{ desc : "Louane" , type: 12, subType:1},
{ desc : "Gru" , type: 12, subType:1},
{ desc : "Kim Kardashian" , type: 12, subType:1},
{ desc : "Mickey Mouse" , type: 12, subType:1},
{ desc : "Stéphane Plaza" , type: 12, subType:1},
{ desc : "Serena Williams" , type: 12, subType:1},
{ desc : "E.T." , type: 12, subType:1},
{ desc : "Jenifer" , type: 12, subType:1},
{ desc : "Aquaman" , type: 12, subType:1},
{ desc : "François Hollande" , type: 12, subType:1},
{ desc : "Sia" , type: 12, subType:1},
{ desc : "Ron Weasley" , type: 12, subType:1},
{ desc : "Hanouna" , type: 12, subType:1},
{ desc : "Shakira" , type: 12, subType:1},
{ desc : "Sherlock Holmes" , type: 12, subType:1},
{ desc : "Zazie" , type: 12, subType:1},
{ desc : "Groot" , type: 12, subType:1},
{ desc : "Julie Gayet" , type: 12, subType:1},
{ desc : "Superman" , type: 12, subType:1},
{ desc : "Maître Gims" , type: 12, subType:1},
{ desc : "Nicki Minaj" , type: 12, subType:1},
{ desc : "Le Comte de Monte-Cristo" , type: 12, subType:1},
{ desc : "Michel Cymes" , type: 12, subType:1},
{ desc : "Wolverine" , type: 12, subType:1},
{ desc : "Vianney" , type: 12, subType:1},
{ desc : "Naruto" , type: 12, subType:1},
{ desc : "Juliette Binoche" , type: 12, subType:1},
{ desc : "Eminem" , type: 12, subType:1},
{ desc : "Cruella d'Enfer" , type: 12, subType:1},
{ desc : "Laurent Ruquier" , type: 12, subType:1},
{ desc : "Christine and the Queens" , type: 12, subType:1},
{ desc : "Albus Dumbledore" , type: 12, subType:1},
{ desc : "Teddy Riner" , type: 12, subType:1},
{ desc : "Ratatouille" , type: 12, subType:1},
{ desc : "Kaaris" , type: 12, subType:1},
{ desc : "Cardi B" , type: 12, subType:1},
{ desc : "Tintin" , type: 12, subType:1},
{ desc : "Pamela Anderson" , type: 12, subType:1},
{ desc : "Capitaine Crochet" , type: 12, subType:1},
{ desc : "Kad Merad" , type: 12, subType:1},
{ desc : "Pocahontas" , type: 12, subType:1},
{ desc : "Steve Jobs" , type: 12, subType:1},
{ desc : "Ségolène Royal" , type: 12, subType:1},
{ desc : "Rocky Balboa" , type: 12, subType:1},
{ desc : "Anne-Sophie Lapix" , type: 12, subType:1},
{ desc : "Kanye West" , type: 12, subType:1},
{ desc : "La Petite Sirène" , type: 12, subType:1},
{ desc : "Christophe Colomb" , type: 12, subType:1},
{ desc : "La fée Clochette" , type: 12, subType:1},
{ desc : "Jul" , type: 12, subType:1},
{ desc : "Jennifer Lawrence" , type: 12, subType:1},
{ desc : "Darth Maul" , type: 12, subType:1},
{ desc : "Calogero" , type: 12, subType:1},
{ desc : "La Bête (La Belle et la Bête)" , type: 12, subType:1},
{ desc : "Zlatan Ibrahimovic" , type: 12, subType:1},
{ desc : "Sylvie Vartan" , type: 12, subType:1},
{ desc : "Luke Skywalker" , type: 12, subType:1},
{ desc : "Cyril Lignac" , type: 12, subType:1},
{ desc : "Reine Elizabeth II" , type: 12, subType:1},
{ desc : "Coluche" , type: 12, subType:1},
{ desc : "Justin Bieber" , type: 12, subType:1},
{ desc : "Jeanne d'Arc" , type: 12, subType:1},
{ desc : "Drake" , type: 12, subType:1},
{ desc : "Petit Ours Brun" , type: 12, subType:1},
{ desc : "Bill Gates" , type: 12, subType:1},
{ desc : "Léa Seydoux" , type: 12, subType:1},
{ desc : "Kermit la grenouille" , type: 12, subType:1},
{ desc : "Zinedine Zidane" , type: 12, subType:1},
{ desc : "Snoop Dogg" , type: 12, subType:1},
{ desc : "Tchoupi" , type: 12, subType:1},
{ desc : "Valérie Damidot" , type: 12, subType:1},
{ desc : "Gordon Ramsay" , type: 12, subType:1},
{ desc : "Jack Bauer" , type: 12, subType:1},
{ desc : "Clara Luciani" , type: 12, subType:1},
{ desc : "Mike Tyson" , type: 12, subType:1},
{ desc : "Le Roi Lion" , type: 12, subType:1},
{ desc : "Patrick Bruel" , type: 12, subType:1},
{ desc : "Dumbo" , type: 12, subType:1},
{ desc : "Laurent Delahousse" , type: 12, subType:1},
{ desc : "Ursula" , type: 12, subType:1},
{ desc : "Éric Zemmour" , type: 12, subType:1},
{ desc : "Mylène Farmer" , type: 12, subType:1},
{ desc : "Jon Snow" , type: 12, subType:1},
{ desc : "Big Flo et Oli" , type: 12, subType:1},
{ desc : "Amy Winehouse" , type: 12, subType:1},
{ desc : "Spiderman" , type: 12, subType:1},
{ desc : "Shy'm" , type: 12, subType:1},
{ desc : "Barack Obama" , type: 12, subType:1},
{ desc : "Belle (La Belle et la Bête)" , type: 12, subType:1},
{ desc : "David Guetta" , type: 12, subType:1},
{ desc : "Le Chapelier Fou" , type: 12, subType:1},
{ desc : "Kendji Girac" , type: 12, subType:1},
{ desc : "Kylie Jenner" , type: 12, subType:1},
{ desc : "Luffy (One Piece)" , type: 12, subType:1},
{ desc : "Charlotte Gainsbourg" , type: 12, subType:1},
{ desc : "Doctor Strange" , type: 12, subType:1},
{ desc : "Alizée" , type: 12, subType:1},
{ desc : "Les Minions" , type: 12, subType:1},
{ desc : "Dwayne \"The Rock\" Johnson" , type: 12, subType:1},
{ desc : "Chantal Goya" , type: 12, subType:1},
{ desc : "Sauron" , type: 12, subType:1},
{ desc : "Camille Combal" , type: 12, subType:1},
{ desc : "Taylor Swift" , type: 12, subType:1},
{ desc : "Scooby-Doo" , type: 12, subType:1},
{ desc : "Isabelle Adjani" , type: 12, subType:1},
{ desc : "John Cena" , type: 12, subType:1},
{ desc : "Christina Cordula" , type: 12, subType:1},
{ desc : "Dark Vador" , type: 12, subType:1},
{ desc : "Lorie" , type: 12, subType:1},
{ desc : "Bob Marley" , type: 12, subType:1},
{ desc : "Peppa Pig" , type: 12, subType:1},
{ desc : "Pascal Obispo" , type: 12, subType:1},
{ desc : "Cersei Lannister" , type: 12, subType:1},
{ desc : "Usain Bolt" , type: 12, subType:1},
{ desc : "Amel Bent" , type: 12, subType:1},
{ desc : "Woody (Toy Story)" , type: 12, subType:1},
{ desc : "Michel Sardou" , type: 12, subType:1},
{ desc : "Lara Croft" , type: 12, subType:1},
{ desc : "Kamel le magicien" , type: 12, subType:1},
{ desc : "Marge Simpson" , type: 12, subType:1},
{ desc : "Tony Stark" , type: 12, subType:1},
{ desc : "Christine Bravo" , type: 12, subType:1},
{ desc : "Son Goku" , type: 12, subType:1},
{ desc : "Audrey Tautou" , type: 12, subType:1},
{ desc : "Les Teletubbies" , type: 12, subType:1},
{ desc : "Didier Deschamps" , type: 12, subType:1},
{ desc : "Catwoman" , type: 12, subType:1},
{ desc : "Bigard" , type: 12, subType:1},
{ desc : "Daenerys Targaryen" , type: 12, subType:1},
{ desc : "Yann Barthès" , type: 12, subType:1},
{ desc : "Bilbo le Hobbit" , type: 12, subType:1},
{ desc : "Cristina Cordula" , type: 12, subType:1},
{ desc : "Tom Cruise" , type: 12, subType:1},
{ desc : "Hello Kitty" , type: 12, subType:1},
{ desc : "Pierre Niney" , type: 12, subType:1},
{ desc : "Black Widow" , type: 12, subType:1},
{ desc : "Michel Berger" , type: 12, subType:1},
{ desc : "Schtroumpf grognon" , type: 12, subType:1},
{ desc : "Ségolène Royal" , type: 12, subType:1},
{ desc : "Homer Simpson" , type: 12, subType:1},
{ desc : "Louane" , type: 12, subType:1},
{ desc : "Loki" , type: 12, subType:1},
{ desc : "Valérie Pécresse" , type: 12, subType:1},
{ desc : "Elvis Presley" , type: 12, subType:1},
{ desc : "Princesse Leia" , type: 12, subType:1},
{ desc : "Nicolas Canteloup" , type: 12, subType:1},
{ desc : "Dua Lipa" , type: 12, subType:1},
{ desc : "Indiana Jones" , type: 12, subType:1},
{ desc : "Caroline Receveur" , type: 12, subType:1},
{ desc : "Obi-Wan Kenobi" , type: 12, subType:1},
{ desc : "Jenifer" , type: 12, subType:1},
{ desc : "Darty Man" , type: 12, subType:1},
{ desc : "Lady Diana" , type: 12, subType:1},
{ desc : "Travis Scott" , type: 12, subType:1},
{ desc : "Olive et Tom" , type: 12, subType:1},
{ desc : "Vanessa Paradis" , type: 12, subType:1},
{ desc : "Dobby" , type: 12, subType:1},
{ desc : "Bernard Laporte" , type: 12, subType:1},
{ desc : "Maître Yoda" , type: 12, subType:1},
{ desc : "Lara Fabian" , type: 12, subType:1},
{ desc : "Sheldon Cooper" , type: 12, subType:1},
{ desc : "Marilyn Monroe" , type: 12, subType:1},
{ desc : "One Direction" , type: 12, subType:1},
{ desc : "Alice au pays des merveilles" , type: 12, subType:1},
{ desc : "Alain Delon" , type: 12, subType:1},
{ desc : "Angelina Jolie" , type: 12, subType:1},
{ desc : "Casper le fantôme" , type: 12, subType:1},
{ desc : "Michel Polnareff" , type: 12, subType:1},
{ desc : "Bruno Mars" , type: 12, subType:1},
{ desc : "La Panthère Rose" , type: 12, subType:1},
{ desc : "Louis de Funès" , type: 12, subType:1},
{ desc : "Chewbacca" , type: 12, subType:1},
{ desc : "Loana" , type: 12, subType:1},
{ desc : "Optimus Prime" , type: 12, subType:1},
{ desc : "Karim Benzema" , type: 12, subType:1},
{ desc : "Britney Spears" , type: 12, subType:1},
{ desc : "Sherlock Holmes" , type: 12, subType:1},
{ desc : "Ophélie Winter" , type: 12, subType:1},
{ desc : "Patrick l'étoile de mer" , type: 12, subType:1},
{ desc : "Mimie Mathy" , type: 12, subType:1},
{ desc : "Captain Jack Sparrow" , type: 12, subType:1},
{ desc : "Diam's" , type: 12, subType:1},
{ desc : "Capitaine America" , type: 12, subType:1},
{ desc : "Brigitte Bardot" , type: 12, subType:1},
{ desc : "Ken (Barbie)" , type: 12, subType:1},
{ desc : "Line Renaud" , type: 12, subType:1},
{ desc : "Harry Styles" , type: 12, subType:1},
{ desc : "Brice de Nice" , type: 12, subType:1},
{ desc : "Mélanie Laurent" , type: 12, subType:1},
{ desc : "Cro-Magnon" , type: 12, subType:1},
{ desc : "Tex Avery" , type: 12, subType:1},
{ desc : "Rita Mitsouko" , type: 12, subType:1},
{ desc : "Rambo" , type: 12, subType:1},
{ desc : "Albert Einstein" , type: 12, subType:1},
{ desc : "Teddy Riner" , type: 12, subType:1},
{ desc : "La Reine des Neiges" , type: 12, subType:1},
{ desc : "Charles de Gaulle" , type: 12, subType:1},
{ desc : "Anne-Sophie Lapix" , type: 12, subType:1},
{ desc : "Obiwan Kenobi" , type: 12, subType:1},
{ desc : "Carla Bruni" , type: 12, subType:1},
{ desc : "Yannick Noah" , type: 12, subType:1},
{ desc : "La Sorcière de Blanche-Neige" , type: 12, subType:1},
{ desc : "Larry Page" , type: 12, subType:1},
{ desc : "Dracula" , type: 12, subType:1},
{ desc : "Ségolène Royal" , type: 12, subType:1},
{ desc : "Jar Jar Binks" , type: 12, subType:1},
{ desc : "Laure Manaudou" , type: 12, subType:1},
{ desc : "Bruce Lee" , type: 12, subType:1},
{ desc : "Edith Piaf" , type: 12, subType:1},
{ desc : "Tinky Winky" , type: 12, subType:1},
{ desc : "Benjamin Castaldi" , type: 12, subType:1},
{ desc : "Aragorn" , type: 12, subType:1},
{ desc : "Mylène Farmer" , type: 12, subType:1},
{ desc : "Platon" , type: 12, subType:1},
{ desc : "Brigitte Fontaine" , type: 12, subType:1},
{ desc : "Le Capitaine Crochet" , type: 12, subType:1},
{ desc : "Loana" , type: 12, subType:1},
{ desc : "Alain Chabat" , type: 12, subType:1},
{ desc : "Amy Winehouse" , type: 12, subType:1},
{ desc : "Pumbaa" , type: 12, subType:1},
{ desc : "Valérie Damidot" , type: 12, subType:1},
{ desc : "Léonard de Vinci" , type: 12, subType:1},
{ desc : "L'inspecteur Gadget" , type: 12, subType:1},
{ desc : "Alessandra Sublet" , type: 12, subType:1},
{ desc : "Jésus" , type: 12, subType:1},
{ desc : "François Bayrou" , type: 12, subType:1},
{ desc : "Shuri (Black Panther)" , type: 12, subType:1},
{ desc : "Laurence Boccolini" , type: 12, subType:1},
{ desc : "Will Smith" , type: 12, subType:1},
{ desc : "Julie Lescaut" , type: 12, subType:1},
{ desc : "Wejdene" , type: 12, subType:1},
{ desc : "L'homme invisible" , type: 12, subType:1},
{ desc : "Diam's" , type: 12, subType:1},
{ desc : "Karl Lagerfeld" , type: 12, subType:1},
{ desc : "Simba" , type: 12, subType:1},
{ desc : "Yann Moix" , type: 12, subType:1},
{ desc : "Napoléon Bonaparte" , type: 12, subType:1},
{ desc : "Chantal Ladesou" , type: 12, subType:1},
{ desc : "Sangoku" , type: 12, subType:1},
{ desc : "Frida Kahlo" , type: 12, subType:1},
{ desc : "Brice de Nice" , type: 12, subType:1},
{ desc : "Christiane Taubira" , type: 12, subType:1},
{ desc : "Sully (Monstres & Cie)" , type: 12, subType:1},
{ desc : "Agathe Christie" , type: 12, subType:1},
{ desc : "Kaamelott" , type: 12, subType:1},
{ desc : "Laurence Ferrari" , type: 12, subType:1},
{ desc : "Guy Fieri" , type: 12, subType:1},
{ desc : "La petite sirène" , type: 12, subType:1},
{ desc : "Francis Cabrel" , type: 12, subType:1},
{ desc : "La Veuve Noire" , type: 12, subType:1},
{ desc : "Antoine Griezmann" , type: 12, subType:1},
{ desc : "Kylie Minogue" , type: 12, subType:1},
{ desc : "Goldorak" , type: 12, subType:1},
{ desc : "Amélie Nothomb" , type: 12, subType:1},
{ desc : "Rayman" , type: 12, subType:1},
{ desc : "Anne Roumanoff" , type: 12, subType:1},
{ desc : "Robin des Bois" , type: 12, subType:1},
{ desc : "Cauet" , type: 12, subType:1},
{ desc : "Rey (Star Wars)" , type: 12, subType:1},
{ desc : "Bruno Solo" , type: 12, subType:1},
{ desc : "Charli XCX" , type: 12, subType:1},
{ desc : "Obélix" , type: 12, subType:1},
{ desc : "Sarah Connor" , type: 12, subType:1},
{ desc : "Fred (Scooby-Doo)" , type: 12, subType:1},
{ desc : "Jenifer Lopez" , type: 12, subType:1},
{ desc : "Sacha (Pokémon)" , type: 12, subType:1},
{ desc : "Véronique Genest" , type: 12, subType:1},
{ desc : "Harvey Weinstein" , type: 12, subType:1},
{ desc : "Willy Wonka" , type: 12, subType:1},
{ desc : "Josiane Balasko" , type: 12, subType:1},
{ desc : "Poutine" , type: 12, subType:1},
{ desc : "Cléopâtre" , type: 12, subType:1},
{ desc : "Gal Gadot" , type: 12, subType:1},
{ desc : "Mustapha El Atrassi" , type: 12, subType:1},
{ desc : "Olivia Ruiz" , type: 12, subType:1},
{ desc : "Goldorak" , type: 12, subType:1},
{ desc : "Roselyne Bachelot" , type: 12, subType:1},
{ desc : "Bill Cosby" , type: 12, subType:1},
{ desc : "Mary Poppins" , type: 12, subType:1},
{ desc : "Doc Gynéco" , type: 12, subType:1},
{ desc : "Rachel (Friends)" , type: 12, subType:1},
{ desc : "Zinedine Soualem" , type: 12, subType:1},
{ desc : "Buzz l'Éclair" , type: 12, subType:1},
{ desc : "Isabelle Balkany" , type: 12, subType:1},
{ desc : "Lance Armstrong" , type: 12, subType:1},
{ desc : "Princesse Leïa" , type: 12, subType:1},
{ desc : "Pierre Bellemare" , type: 12, subType:1},
{ desc : "Chucky" , type: 12, subType:1},
{ desc : "Lio" , type: 12, subType:1},
{ desc : "Gollum" , type: 12, subType:1},
{ desc : "Zazie" , type: 12, subType:1},
{ desc : "Louis XIV" , type: 12, subType:1},
{ desc : "Björk" , type: 12, subType:1},
{ desc : "Gandhi" , type: 12, subType:1},
{ desc : "Virginie Efira" , type: 12, subType:1},
{ desc : "Thanos" , type: 12, subType:1},
{ desc : "Marguerite Duras" , type: 12, subType:1},
{ desc : "Nelson Monfort" , type: 12, subType:1},
{ desc : "Wendie Renard" , type: 12, subType:1},
{ desc : "Robocop" , type: 12, subType:1},
{ desc : "Sylvie Tellier" , type: 12, subType:1},
{ desc : "David Pujadas" , type: 12, subType:1},
{ desc : "Rosie la grosse" , type: 12, subType:1},
{ desc : "Yann Barthès" , type: 12, subType:1},
{ desc : "Dr. Phil" , type: 12, subType:1},
{ desc : "James Bond" , type: 12, subType:1},
{ desc : "Pauline Déroulède" , type: 12, subType:1},
{ desc : "Denis Brogniart" , type: 12, subType:1},
{ desc : "Morticia Adams" , type: 12, subType:1},
{ desc : "Cédric Villani" , type: 12, subType:1},
{ desc : "Simone Veil" , type: 12, subType:1},
{ desc : "Dr. Who" , type: 12, subType:1},
{ desc : "Céline Dion" , type: 12, subType:1},
{ desc : "Chris Rock" , type: 12, subType:1},
{ desc : "Betty Boop" , type: 12, subType:1},
{ desc : "Guillaume Canet" , type: 12, subType:1},
{ desc : "Billie Eilish" , type: 12, subType:1},
{ desc : "Gaston Lagaffe" , type: 12, subType:1},
{ desc : "Christophe Maé" , type: 12, subType:1},
{ desc : "Janet Jackson" , type: 12, subType:1},
{ desc : "Capitaine Marleau" , type: 12, subType:1},
{ desc : "Dominique Strauss-Kahn" , type: 12, subType:1},
{ desc : "Arielle Dombasle" , type: 12, subType:1},
{ desc : "Flash McQueen" , type: 12, subType:1},
{ desc : "Christine Boutin" , type: 12, subType:1},
{ desc : "Borat" , type: 12, subType:1},
{ desc : "Geneviève de Fontenay" , type: 12, subType:1},
{ desc : "Jigsaw" , type: 12, subType:1},
{ desc : "Carole Bouquet" , type: 12, subType:1},
{ desc : "Joey Starr" , type: 12, subType:1},
{ desc : "Katy Perry" , type: 12, subType:1},
{ desc : "Freud" , type: 12, subType:1},
{ desc : "Clara Morgane" , type: 12, subType:1},
{ desc : "Vercingétorix" , type: 12, subType:1},
{ desc : "Angelina Jolie" , type: 12, subType:1},
{ desc : "Ken le survivant" , type: 12, subType:1},
{ desc : "Firmine Richard" , type: 12, subType:1},
{ desc : "Baloo" , type: 12, subType:1},
{ desc : "Marie-Antoinette" , type: 12, subType:1},
{ desc : "Tony Montana" , type: 12, subType:1},
{ desc : "Vanessa Paradis" , type: 12, subType:1},
{ desc : "Sébastien Chabal" , type: 12, subType:1},
{ desc : "Greta Thunberg" , type: 12, subType:1},
{ desc : "Victor Hugo" , type: 12, subType:1},
{ desc : "Luana Belmondo" , type: 12, subType:1},
{ desc : "Le Joker" , type: 12, subType:1},
{ desc : "Jane Birkin" , type: 12, subType:1},
{ desc : "Dominique de Villepin" , type: 12, subType:1},
{ desc : "Wednesday Addams" , type: 12, subType:1},
{ desc : "Marcel Pagnol" , type: 12, subType:1},
{ desc : "Romy Schneider" , type: 12, subType:1},
{ desc : "Sangoku" , type: 12, subType:1},
{ desc : "Michèle Bernier" , type: 12, subType:1},
{ desc : "Le Grand Schtroumpf" , type: 12, subType:1},
{ desc : "Florence Foresti" , type: 12, subType:1},
{ desc : "Jean Castex" , type: 12, subType:1},
{ desc : "Anne Sinclair" , type: 12, subType:1},
{ desc : "Docteur Maboul" , type: 12, subType:1},
{ desc : "Sheila" , type: 12, subType:1},
{ desc : "Sébastien Loeb" , type: 12, subType:1},
{ desc : "Kurt Cobain" , type: 12, subType:1},
{ desc : "Titeuf" , type: 12, subType:1},
{ desc : "Mike Brant" , type: 12, subType:1},
{ desc : "Minnie Mouse" , type: 12, subType:1},
{ desc : "Sylvester Stallone" , type: 12, subType:1},
{ desc : "Laurence Fishburne" , type: 12, subType:1},
{ desc : "Philippe Etchebest" , type: 12, subType:1},
{ desc : "La fée Carabosse" , type: 12, subType:1},
{ desc : "Valérie Trierweiler" , type: 12, subType:1},
{ desc : "Bébé Yoda" , type: 12, subType:1},
{ desc : "Sylvie Vartan" , type: 12, subType:1},
{ desc : "Renaud" , type: 12, subType:1},
{ desc : "Kaa (Le Livre de la Jungle)" , type: 12, subType:1},
{ desc : "Madame Doubtfire" , type: 12, subType:1},
{ desc : "Alain Juppé" , type: 12, subType:1},
{ desc : "Arya Stark" , type: 12, subType:1},
{ desc : "Marcel Desailly" , type: 12, subType:1},
{ desc : "Charlotte Gainsbourg" , type: 12, subType:1},
{ desc : "Scooby-Doo" , type: 12, subType:1},
{ desc : "Hillary Clinton" , type: 12, subType:1},
{ desc : "Jean-Pierre Foucault" , type: 12, subType:1},
{ desc : "Julia Roberts" , type: 12, subType:1},
{ desc : "Inspecteur Columbo" , type: 12, subType:1},
{ desc : "Emmanuelle Béart" , type: 12, subType:1},
{ desc : "Travis Scott" , type: 12, subType:1},
{ desc : "La Petite Souris" , type: 12, subType:1},
{ desc : "Isaac Newton" , type: 12, subType:1},
{ desc : "Miss Météo Canal+" , type: 12, subType:1},
{ desc : "Lucifer" , type: 12, subType:1},
{ desc : "Anne-Elisabeth Lemoine" , type: 12, subType:1},
{ desc : "Lionel Jospin" , type: 12, subType:1},
{ desc : "Lolita Lempicka" , type: 12, subType:1},
{ desc : "Raymond Domenech" , type: 12, subType:1},
{ desc : "Meryl Streep" , type: 12, subType:1},
{ desc : "Inspecteur Harry" , type: 12, subType:1},
{ desc : "Evelyne Dhéliat" , type: 12, subType:1},
{ desc : "Le Dalaï-Lama" , type: 12, subType:1},
{ desc : "Barbie" , type: 12, subType:1},
{ desc : "Mister Bean" , type: 12, subType:1},
{ desc : "Jeanne d'Arc" , type: 12, subType:1},
{ desc : "Louis de Funès" , type: 12, subType:1},
{ desc : "Halle Berry" , type: 12, subType:1},
{ desc : "Mussolini" , type: 12, subType:1},
{ desc : "Laurence Parisot" , type: 12, subType:1},
{ desc : "Nicolas Hulot" , type: 12, subType:1},
{ desc : "Victoria Beckham" , type: 12, subType:1},
{ desc : "King Kong" , type: 12, subType:1},
{ desc : "Diane Kruger" , type: 12, subType:1},
{ desc : "Le Roi Arthur" , type: 12, subType:1},
{ desc : "Marilou Berry" , type: 12, subType:1},
{ desc : "Cyril Lignac" , type: 12, subType:1},
{ desc : "Audrey Hepburn" , type: 12, subType:1},
{ desc : "Le Roi Lion" , type: 12, subType:1},
{ desc : "Kate Middleton" , type: 12, subType:1},
{ desc : "Novak Djokovic" , type: 12, subType:1},
{ desc : "Cruella" , type: 12, subType:1},
{ desc : "Yves Montand" , type: 12, subType:1},
{ desc : "Le Marsupilami" , type: 12, subType:1},
{ desc : "Brigitte Macron" , type: 12, subType:1},
{ desc : "Jean Alesi" , type: 12, subType:1},
{ desc : "Josiane Balasko" , type: 12, subType:1},
{ desc : "Merlin l'Enchanteur" , type: 12, subType:1},
{ desc : "Sheila" , type: 12, subType:1},
{ desc : "Cristiano Ronaldo" , type: 12, subType:1},
{ desc : "Diane Kruger" , type: 12, subType:1},
{ desc : "Le Capitaine Haddock" , type: 12, subType:1},
{ desc : "Sylvie Jenaly" , type: 12, subType:1},
{ desc : "Mick Jagger" , type: 12, subType:1},
{ desc : "Christine Angot" , type: 12, subType:1},
{ desc : "Batman" , type: 12, subType:1},
{ desc : "Ophélie Winter" , type: 12, subType:1},
{ desc : "Le Comte Dracula" , type: 12, subType:1},
{ desc : "Elle Macpherson" , type: 12, subType:1},
{ desc : "Jacques Dutronc" , type: 12, subType:1},
{ desc : "Margaret Thatcher" , type: 12, subType:1},
{ desc : "Tyrion Lannister" , type: 12, subType:1},
{ desc : "Marianne James" , type: 12, subType:1},
{ desc : "Gordon Ramsey" , type: 12, subType:1},
{ desc : "Elsa Zylberstein" , type: 12, subType:1},
{ desc : "Le Chapelier Fou" , type: 12, subType:1},
{ desc : "Michèle Obama" , type: 12, subType:1},
{ desc : "Tex Avery" , type: 12, subType:1},
{ desc : "Claire Chazal" , type: 12, subType:1},
{ desc : "Jojo Lapin" , type: 12, subType:1},
{ desc : "Eva Longoria" , type: 12, subType:1},
{ desc : "Picasso" , type: 12, subType:1},
{ desc : "Estelle Denis" , type: 12, subType:1},
{ desc : "James Hetfield" , type: 12, subType:1},
{ desc : "Brigitte Lahaie" , type: 12, subType:1},
{ desc : "Le Comte de Monte-Cristo" , type: 12, subType:1},
{ desc : "Flavie Flament" , type: 12, subType:1},
{ desc : "Florent Pagny" , type: 12, subType:1},
{ desc : "Rihanna" , type: 12, subType:1},
{ desc : "Ken (de Barbie)" , type: 12, subType:1},
{ desc : "Rachida Dati" , type: 12, subType:1},
{ desc : "Le Bonhomme de Neige" , type: 12, subType:1},
{ desc : "Madonna" , type: 12, subType:1},
{ desc : "Le loup de Tex Avery" , type: 12, subType:1},
{ desc : "Queen Latifah" , type: 12, subType:1},
{ desc : "Fabien Barthez" , type: 12, subType:1},
{ desc : "Whoopi Goldberg" , type: 12, subType:1},
{ desc : "Freddy Krueger" , type: 12, subType:1},
{ desc : "Marlène Schiappa" , type: 12, subType:1},
{ desc : "Alain Prost" , type: 12, subType:1},
{ desc : "Juliette Binoche" , type: 12, subType:1},
{ desc : "Marty McFly" , type: 12, subType:1},
{ desc : "Elizabeth II" , type: 12, subType:1},
{ desc : "Sébastien Cauet" , type: 12, subType:1},
{ desc : "Monica Bellucci" , type: 12, subType:1},
{ desc : "Guignol" , type: 12, subType:1},
{ desc : "Muriel Robin" , type: 12, subType:1},
{ desc : "Hannibal Lecter" , type: 12, subType:1},
{ desc : "Julie Depardieu" , type: 12, subType:1},
{ desc : "Rambo" , type: 12, subType:1},
{ desc : "Marie Drucker" , type: 12, subType:1},
{ desc : "Gaston (La Belle et la Bête)" , type: 12, subType:1},
{ desc : "Sophie Favier" , type: 12, subType:1},
{ desc : "Aragorn" , type: 12, subType:1},
{ desc : "Bruce Willis" , type: 12, subType:1},
{ desc : "Salma Hayek" , type: 12, subType:1},
{ desc : "Charles Manson" , type: 12, subType:1},
{ desc : "José Garcia" , type: 12, subType:1},
{ desc : "Cara Delevingne" , type: 12, subType:1},
{ desc : "Lucky Luke" , type: 12, subType:1},
{ desc : "Maïté" , type: 12, subType:1},
{ desc : "Ghostface (Scream)" , type: 12, subType:1},
{ desc : "Alain Souchon" , type: 12, subType:1},
{ desc : "Buffy" , type: 12, subType:1},
{ desc : "David Lynch" , type: 12, subType:1},
{ desc : "Adriana Karembeu" , type: 12, subType:1},
{ desc : "La Panthère Rose" , type: 12, subType:1},
{ desc : "Carole Rousseau" , type: 12, subType:1},
{ desc : "L'abominable Homme des neiges" , type: 12, subType:1},
{ desc : "Adolf Hitler" , type: 12, subType:1},
{ desc : "Satan" , type: 12, subType:1},
{ desc : "P. Diddy" , type: 12, subType:1},
{ desc : "Émile Louis" , type: 12, subType:1},
{ desc : "Marc Dutroux" , type: 12, subType:1},
{ desc : "Le Pape François" , type: 12, subType:1},
{ desc : "Jeffrey Epstein" , type: 12, subType:1},
{ desc : "Kim Jong-un" , type: 12, subType:1},
{ desc : "Harvey Weinstein" , type: 12, subType:1},
{ desc : "Hannibal Lecter" , type: 12, subType:1},
{ desc : "Fidel Castro" , type: 12, subType:1},
{ desc : "Joseph Staline" , type: 12, subType:1},
{ desc : "Saddam Hussein" , type: 12, subType:1},
{ desc : "Michael Jackson" , type: 12, subType:1},
{ desc : "Satan" , type: 12, subType:1},
{ desc : "Pablo Escobar" , type: 12, subType:1},
{ desc : "Ben Laden" , type: 12, subType:1},
{ desc : "Mike Tyson" , type: 12, subType:1},
{ desc : "R. Kelly" , type: 12, subType:1},
{ desc : "Jack l'Éventreur" , type: 12, subType:1},
{ desc : "Poutine" , type: 12, subType:1},
{ desc : "Leopold II de Belgique" , type: 12, subType:1},
{ desc : "Bill Cosby" , type: 12, subType:1},
{ desc : "Jimmy Savile" , type: 12, subType:1},
{ desc : "Marilyn Manson" , type: 12, subType:1},
{ desc : "Charles Manson" , type: 12, subType:1},
{ desc : "Ted Bundy" , type: 12, subType:1},
{ desc : "Michel Fourniret" , type: 12, subType:1},
{ desc : "Guy Georges" , type: 12, subType:1},
{ desc : "Patrick Balkany" , type: 12, subType:1},
{ desc : "Gilbert Rozon" , type: 12, subType:1},
{ desc : "Pol Pot" , type: 12, subType:1},
{ desc : "Francis Heaulme" , type: 12, subType:1},
{ desc : "Dominique Strauss-Kahn" , type: 12, subType:1},
{ desc : "Benito Mussolini" , type: 12, subType:1},
{ desc : "Francis Lalanne" , type: 12, subType:1},
{ desc : "L'Ayatollah Khomeini" , type: 12, subType:1},
{ desc : "Tariq Ramadan" , type: 12, subType:1},
{ desc : "Jean-Luc Lahaye" , type: 12, subType:1},
{ desc : "Bernard Madoff" , type: 12, subType:1},
{ desc : "Klaus Barbie" , type: 12, subType:1},
{ desc : "Pierre Palmade" , type: 12, subType:1},
{ desc : "Al Capone" , type: 12, subType:1},
{ desc : "Jean-Marie Le Pen" , type: 12, subType:1},
{ desc : "Dieudonné" , type: 12, subType:1},
{ desc : "Lance Armstrong" , type: 12, subType:1},
{ desc : "Farid Benyettou" , type: 12, subType:1},
{ desc : "Christian Quesada" , type: 12, subType:1},
{ desc : "George W. Bush" , type: 12, subType:1},
{ desc : "Kevin Spacey" , type: 12, subType:1},
{ desc : "Jacques Chirac" , type: 12, subType:1},
{ desc : "La Bête du Gévaudan" , type: 12, subType:1},
{ desc : "Landru" , type: 12, subType:1},
{ desc : "Jair Bolsonaro" , type: 12, subType:1},
{ desc : "Nicolas Sarkozy" , type: 12, subType:1},
{ desc : "Jean Tiberi" , type: 12, subType:1},
{ desc : "Hunter Biden" , type: 12, subType:1},
{ desc : "Henry VIII" , type: 12, subType:1},
{ desc : "Donald Trump" , type: 12, subType:1},
{ desc : "Amy Winehouse" , type: 12, subType:1},
{ desc : "Gengis Khan" , type: 12, subType:1},
{ desc : "Mahmoud Ahmadinejad" , type: 12, subType:1},
{ desc : "Silvio Berlusconi" , type: 12, subType:1},
{ desc : "La Cicciolina" , type: 12, subType:1},
{ desc : "Omar El-Béchir" , type: 12, subType:1},
{ desc : "Jacques Mesrine" , type: 12, subType:1},
{ desc : "Gisèle Pelicot" , type: 12, subType:1},
{ desc : "Nabilla" , type: 12, subType:1},
{ desc : "Henri Désiré Landru" , type: 12, subType:1},
{ desc : "Chris Brown" , type: 12, subType:1},
{ desc : "El Chapo" , type: 12, subType:1},
{ desc : "Jacques Lacan" , type: 12, subType:1},
{ desc : "Michel Foucault" , type: 12, subType:1},
{ desc : "Docteur Mengele" , type: 12, subType:1},
{ desc : "Un Gilet Jaune" , type: 12, subType:1},
{ desc : "Un membre de QAnon" , type: 12, subType:1},
{ desc : "Un Témoin de Jéhovah" , type: 12, subType:1},
{ desc : "Le père Noël" , type: 12, subType:1},
{ desc : "Un extraterrestre" , type: 12, subType:1},
{ desc : "Un Minion" , type: 12, subType:1},
{ desc : "Le Marsupilami" , type: 12, subType:1},
{ desc : "Jon Venables" , type: 12, subType:1},
{ desc : "Robert Thompson" , type: 12, subType:1},
{ desc : "Le Petit Grégory" , type: 12, subType:1},
{ desc : "Justin Bieber" , type: 12, subType:1},
{ desc : "Un Antivax" , type: 12, subType:1},
{ desc : "Un Platiste" , type: 12, subType:1},
{ desc : "Un membre d'Anonymous" , type: 12, subType:1},
{ desc : "Un Smiley" , type: 12, subType:1},
{ desc : "Eric Zemmour" , type: 12, subType:1},
{ desc : "Jean-Luc Mélenchon" , type: 12, subType:1},
{ desc : "Xavier Dupont de Ligonnès" , type: 12, subType:1},
{ desc : "Zahia" , type: 12, subType:1},
{ desc : "Un camé" , type: 12, subType:1},
{ desc : "Un dealer" , type: 12, subType:1},
{ desc : "Un troll russe" , type: 12, subType:1},
{ desc : "Un agent du Mossad" , type: 12, subType:1},
{ desc : "Un clochard" , type: 12, subType:1},
{ desc : "Un douanier" , type: 12, subType:1},
{ desc : "Un djihadiste" , type: 12, subType:1},
{ desc : "Un neo-nazi" , type: 12, subType:1},
{ desc : "Un Hooligan" , type: 12, subType:1},
{ desc : "Un membre de la secte des Raëliens" , type: 12, subType:1},
{ desc : "Un membre de la Scientologie" , type: 12, subType:1},
{ desc : "Un SDF" , type: 12, subType:1},
{ desc : "Un skinhead" , type: 12, subType:1},
{ desc : "Un vieux pervers" , type: 12, subType:1},
{ desc : "Rocco Siffredi" , type: 12, subType:1},
{ desc : "Lara Croft" , type: 12, subType:1},
{ desc : "Un gilet jaune" , type: 12, subType:1},
{ desc : "Tiger Woods" , type: 12, subType:1},
{ desc : "Amy Schumer" , type: 12, subType:1},
{ desc : "Jacques Mesrine" , type: 12, subType:1},
{ desc : "Bernard Tapie" , type: 12, subType:1},
{ desc : "Bernard Arnault" , type: 12, subType:1},
{ desc : "Un Membre des Hells Angels" , type: 12, subType:1},
{ desc : "Un Yakuza" , type: 12, subType:1},
{ desc : "Un trader de Wall Street" , type: 12, subType:1},
{ desc : "Kanye West" , type: 12, subType:1},
{ desc : "Pete Davidson" , type: 12, subType:1},
{ desc : "Ghislaine Maxwell" , type: 12, subType:1},
{ desc : "Andrew Tate" , type: 12, subType:1},
{ desc : "Donald Trump Jr." , type: 12, subType:1},
{ desc : "Vladimir Poutine" , type: 12, subType:1},
{ desc : "Un sosie d'Elvis" , type: 12, subType:1},
{ desc : "Un chatbot IA" , type: 12, subType:1},
{ desc : "Un membre des Illuminati" , type: 12, subType:1},
{ desc : "Un Franc-maçon" , type: 12, subType:1},
{ desc : "Un adepte de QAnon" , type: 12, subType:1},
{ desc : "Un flat-earther" , type: 12, subType:1},
{ desc : "Un accro à TikTok" , type: 12, subType:1},
{ desc : "Britney Spears" , type: 12, subType:1},
{ desc : "Johnny Depp" , type: 12, subType:1},
{ desc : "Amber Heard" , type: 12, subType:1},
{ desc : "Will Smith" , type: 12, subType:1},
{ desc : "Un clown d'anniversaire" , type: 12, subType:1},
{ desc : "Un membre du KKK" , type: 12, subType:1},
{ desc : "Un flat-earther" , type: 12, subType:1},
{ desc : "Un incel" , type: 12, subType:1},
{ desc : "Le gendarme de Saint-Tropez" , type: 12, subType:1},
{ desc : "Un prêtre exorciste" , type: 12, subType:1},
{ desc : "Un chiropracteur" , type: 12, subType:1},
{ desc : "Un sorcier vaudou" , type: 12, subType:1},
{ desc : "Un éleveur de chats" , type: 12, subType:1},
{ desc : "Margaret Thatcher" , type: 12, subType:1},
{ desc : "Un pickpocket" , type: 12, subType:1},
{ desc : "Un escroc d'internet" , type: 12, subType:1},
{ desc : "Un conducteur de bus" , type: 12, subType:1},
{ desc : "Un éboueur" , type: 12, subType:1},
{ desc : "Un comptable" , type: 12, subType:1},
{ desc : "Un chirurgien esthétique" , type: 12, subType:1},
{ desc : "Un gardien de prison" , type: 12, subType:1},
{ desc : "Un Schtroumpf" , type: 12, subType:1},
{ desc : "Le Vieux Sage" , type: 12, subType:1},
{ desc : "Un Oompa Loompa" , type: 12, subType:1},
{ desc : "Un Terminator" , type: 12, subType:1},
{ desc : "Un membre des Avengers" , type: 12, subType:1},
{ desc : "Un plombier" , type: 12, subType:1},
{ desc : "Un boulanger" , type: 12, subType:1},
{ desc : "Un routier" , type: 12, subType:1},
{ desc : "Un Jedi" , type: 12, subType:1},
{ desc : "Un Sith" , type: 12, subType:1},
{ desc : "Un Hobbit" , type: 12, subType:1},
{ desc : "Un Orc" , type: 12, subType:1},
{ desc : "Un elfe" , type: 12, subType:1},
{ desc : "Une sirène" , type: 12, subType:1},
{ desc : "Un vampire" , type: 12, subType:1},
{ desc : "Un loup-garou" , type: 12, subType:1},
{ desc : "Un zombie" , type: 12, subType:1},
{ desc : "Un Gremlins" , type: 12, subType:1},
{ desc : "Un extraterrestre" , type: 12, subType:1},
{ desc : "Un ninja" , type: 12, subType:1},
{ desc : "Un samouraï" , type: 12, subType:1},
{ desc : "Un gladiateur" , type: 12, subType:1},
{ desc : "Un chevalier" , type: 12, subType:1},
{ desc : "Un pirate" , type: 12, subType:1},
{ desc : "Un astronaute" , type: 12, subType:1},
{ desc : "Un pilote de chasse" , type: 12, subType:1},
{ desc : "Un pilote de F1" , type: 12, subType:1},
{ desc : "Un footballeur" , type: 12, subType:1},
{ desc : "Un tennisman" , type: 12, subType:1},
{ desc : "Un rugbyman" , type: 12, subType:1},
{ desc : "Un catcheur" , type: 12, subType:1},
{ desc : "Un boxeur" , type: 12, subType:1},
{ desc : "Un nageur" , type: 12, subType:1},
{ desc : "Un marathonien" , type: 12, subType:1},
{ desc : "Un cycliste" , type: 12, subType:1},
{ desc : "Un golfeur" , type: 12, subType:1},
{ desc : "Un joueur de poker" , type: 12, subType:1},
{ desc : "Un joueur d'échecs" , type: 12, subType:1},
{ desc : "Un mannequin" , type: 12, subType:1},
{ desc : "Un photographe" , type: 12, subType:1},
{ desc : "Un peintre" , type: 12, subType:1},
{ desc : "Un écrivain" , type: 12, subType:1},
{ desc : "Un chanteur" , type: 12, subType:1},
{ desc : "Un musicien" , type: 12, subType:1},
{ desc : "Un acteur" , type: 12, subType:1},
{ desc : "Un réalisateur" , type: 12, subType:1},
{ desc : "Un producteur" , type: 12, subType:1},
{ desc : "Un politicien" , type: 12, subType:1},
{ desc : "Un médecin" , type: 12, subType:1},
{ desc : "Un infirmier" , type: 12, subType:1},
{ desc : "Un pharmacien" , type: 12, subType:1},
{ desc : "Un dentiste" , type: 12, subType:1},
{ desc : "Un vétérinaire" , type: 12, subType:1},
{ desc : "Un avocat" , type: 12, subType:1},
{ desc : "Un juge" , type: 12, subType:1},
{ desc : "Un policier" , type: 12, subType:1},
{ desc : "Un pompier" , type: 12, subType:1},
{ desc : "Un militaire" , type: 12, subType:1},
{ desc : "Un espion" , type: 12, subType:1},
{ desc : "Un hacker" , type: 12, subType:1},
{ desc : "Un banquier" , type: 12, subType:1},
{ desc : "Un PDG" , type: 12, subType:1},
{ desc : "Un SDF" , type: 12, subType:1},
{ desc : "Un millionnaire" , type: 12, subType:1},
{ desc : "Un milliardaire" , type: 12, subType:1},
{ desc : "Un influenceur" , type: 12, subType:1},
{ desc : "Un YouTuber" , type: 12, subType:1},
{ desc : "Un streamer" , type: 12, subType:1},
{ desc : "Un tiktoker" , type: 12, subType:1},
{ desc : "Un instagrammeur" , type: 12, subType:1},
{ desc : "Un blogueur" , type: 12, subType:1},
{ desc : "Un voyant" , type: 12, subType:1},
{ desc : "Un médium" , type: 12, subType:1},
{ desc : "Un cartomancien" , type: 12, subType:1},
{ desc : "Un astrologue" , type: 12, subType:1},
{ desc : "Un moine shaolin" , type: 12, subType:1},
{ desc : "Un gourou" , type: 12, subType:1},
{ desc : "Un hippie" , type: 12, subType:1},
{ desc : "Un punk" , type: 12, subType:1},
{ desc : "Un gothique" , type: 12, subType:1},
{ desc : "Un metalhead" , type: 12, subType:1},
{ desc : "Un rappeur" , type: 12, subType:1},
{ desc : "Un DJ" , type: 12, subType:1},
{ desc : "Un rave" , type: 12, subType:1},
{ desc : "Un clubber" , type: 12, subType:1},
{ desc : "Un danseur" , type: 12, subType:1},
{ desc : "Un chorégraphe" , type: 12, subType:1},
{ desc : "Un architecte" , type: 12, subType:1},
{ desc : "Un ingénieur" , type: 12, subType:1},
{ desc : "Un scientifique" , type: 12, subType:1},
{ desc : "Un mathématicien" , type: 12, subType:1},
{ desc : "Un philosophe" , type: 12, subType:1},
{ desc : "Un psychologue" , type: 12, subType:1},
{ desc : "Un psychiatre" , type: 12, subType:1},
{ desc : "Un professeur" , type: 12, subType:1},
{ desc : "Un instituteur" , type: 12, subType:1},
{ desc : "Un étudiant" , type: 12, subType:1},
{ desc : "Un élève" , type: 12, subType:1},
{ desc : "Un enfant" , type: 12, subType:1},
{ desc : "Un bébé" , type: 12, subType:1},
{ desc : "Un vieillard" , type: 12, subType:1},
{ desc : "Un jumeau" , type: 12, subType:1},
{ desc : "Un clone" , type: 12, subType:1},
{ desc : "Un robot" , type: 12, subType:1},
{ desc : "Un cyborg" , type: 12, subType:1},
{ desc : "Un androïde" , type: 12, subType:1},
{ desc : "Un dragon" , type: 12, subType:1},
{ desc : "Un monstre" , type: 12, subType:1},
{ desc : "Un ogre" , type: 12, subType:1},
{ desc : "Un troll" , type: 12, subType:1},
{ desc : "Un centaure" , type: 12, subType:1},
{ desc : "Un minotaure" , type: 12, subType:1},
{ desc : "Un sphinx" , type: 12, subType:1},
{ desc : "Un phénix" , type: 12, subType:1},
{ desc : "Un griffon" , type: 12, subType:1},
{ desc : "Un licorne" , type: 12, subType:1},
{ desc : "Un pégase" , type: 12, subType:1},
{ desc : "Un cyclope" , type: 12, subType:1},
{ desc : "Un géant" , type: 12, subType:1},
{ desc : "Un lutin" , type: 12, subType:1},
{ desc : "Un gnome" , type: 12, subType:1},
{ desc : "Un farfadet" , type: 12, subType:1},
{ desc : "Un leprechaun" , type: 12, subType:1},
{ desc : "Un gremlin" , type: 12, subType:1},
{ desc : "Un schtroumpf" , type: 12, subType:1},
{ desc : "Un pokemon" , type: 12, subType:1},
{ desc : "Un digimon" , type: 12, subType:1},
{ desc : "Un autobot" , type: 12, subType:1},
{ desc : "Un decepticon" , type: 12, subType:1},
{ desc : "Un jedi" , type: 12, subType:1},
{ desc : "Un sith" , type: 12, subType:1},
{ desc : "Un ewok" , type: 12, subType:1},
{ desc : "Un wookie" , type: 12, subType:1},
{ desc : "Un klingon" , type: 12, subType:1},
{ desc : "Un vulcain" , type: 12, subType:1},
{ desc : "Un dalek" , type: 12, subType:1},
{ desc : "Un cyberman" , type: 12, subType:1},
{ desc : "Un weeping angel" , type: 12, subType:1},
{ desc : "Un white walker" , type: 12, subType:1},
{ desc : "Un troll des montagnes" , type: 12, subType:1},
{ desc : "Un orc" , type: 12, subType:1},
{ desc : "Un elfe" , type: 12, subType:1},
{ desc : "Un nain" , type: 12, subType:1},
{ desc : "Un hobbit" , type: 12, subType:1},
{ desc : "Un magicien" , type: 12, subType:1},
{ desc : "Un sorcier" , type: 12, subType:1},
{ desc : "Un démon" , type: 12, subType:1},
{ desc : "Un ange" , type: 12, subType:1},
{ desc : "Fait du yoga" , type: 12, subType:2},
{ desc : "Prend un selfie" , type: 12, subType:2},
{ desc : "Danse la Macarena" , type: 12, subType:2},
{ desc : "S'est pris une porte" , type: 12, subType:2},
{ desc : "Fait une raclette" , type: 12, subType:2},
{ desc : "Aux toilettes" , type: 12, subType:2},
{ desc : "En train de voter" , type: 12, subType:2},
{ desc : "À un enterrement" , type: 12, subType:2},
{ desc : "Fait du karaoké" , type: 12, subType:2},
{ desc : "Perd ses cheveux" , type: 12, subType:2},
{ desc : "À Disneyland" , type: 12, subType:2},
{ desc : "Mange un Big Mac" , type: 12, subType:2},
{ desc : "Fait du ski" , type: 12, subType:2},
{ desc : "Pris dans les embouteillages" , type: 12, subType:2},
{ desc : "En pyjama" , type: 12, subType:2},
{ desc : "Fait la vaisselle" , type: 12, subType:2},
{ desc : "Aux soldes" , type: 12, subType:2},
{ desc : "À Koh-Lanta" , type: 12, subType:2},
{ desc : "Perd au casino" , type: 12, subType:2},
{ desc : "Chante sous la douche" , type: 12, subType:2},
{ desc : "Fait un régime" , type: 12, subType:2},
{ desc : "À son mariage" , type: 12, subType:2},
{ desc : "En cours de sport" , type: 12, subType:2},
{ desc : "Tombe dans les escaliers" , type: 12, subType:2},
{ desc : "Danse la salsa" , type: 12, subType:2},
{ desc : "Fait du shopping" , type: 12, subType:2},
{ desc : "En train de ronfler" , type: 12, subType:2},
{ desc : "Fait du jardinage" , type: 12, subType:2},
{ desc : "Dans un ascenseur en panne" , type: 12, subType:2},
{ desc : "Au permis de conduire" , type: 12, subType:2},
{ desc : "Fait la queue à La Poste" , type: 12, subType:2},
{ desc : "Pique-nique aux Tuileries" , type: 12, subType:2},
{ desc : "Twerke" , type: 12, subType:2},
{ desc : "Fait ses courses chez Lidl" , type: 12, subType:2},
{ desc : "À l'Élysée" , type: 12, subType:2},
{ desc : "Dans Star Wars" , type: 12, subType:2},
{ desc : "Fait du CrossFit" , type: 12, subType:2},
{ desc : "À un concert de Jul" , type: 12, subType:2},
{ desc : "Joue à la pétanque" , type: 12, subType:2},
{ desc : "Pendant un coup de foudre" , type: 12, subType:2},
{ desc : "Fait un TikTok" , type: 12, subType:2},
{ desc : "En télétravail" , type: 12, subType:2},
{ desc : "Dans une montagne russe" , type: 12, subType:2},
{ desc : "Fait un doigt d'honneur" , type: 12, subType:2},
{ desc : "Mange des sushis" , type: 12, subType:2},
{ desc : "Fait un bain de minuit" , type: 12, subType:2},
{ desc : "À un test Covid" , type: 12, subType:2},
{ desc : "Joue au Monopoly" , type: 12, subType:2},
{ desc : "Ivre mort" , type: 12, subType:2},
{ desc : "Fait du paddle" , type: 12, subType:2},
{ desc : "Fait la bise à Macron" , type: 12, subType:2},
{ desc : "Chez le gynécologue" , type: 12, subType:2},
{ desc : "Dans une émission de télé-réalité" , type: 12, subType:2},
{ desc : "Fait un marathon" , type: 12, subType:2},
{ desc : "Danse sur Techno Parade" , type: 12, subType:2},
{ desc : "Fait un karaoké" , type: 12, subType:2},
{ desc : "À Pôle Emploi" , type: 12, subType:2},
{ desc : "Vomit dans un sac" , type: 12, subType:2},
{ desc : "Fait une demande en mariage" , type: 12, subType:2},
{ desc : "À Ikea" , type: 12, subType:2},
{ desc : "Joue à Pokémon Go" , type: 12, subType:2},
{ desc : "Fait un barbecue" , type: 12, subType:2},
{ desc : "Coincé dans les toilettes" , type: 12, subType:2},
{ desc : "Dans une pub pour Meetic" , type: 12, subType:2},
{ desc : "Attaque un distributeur" , type: 12, subType:2},
{ desc : "Fait un paintball" , type: 12, subType:2},
{ desc : "Au ski sans neige" , type: 12, subType:2},
{ desc : "Fait des crêpes" , type: 12, subType:2},
{ desc : "Sur un site de rencontres" , type: 12, subType:2},
{ desc : "Joue à Fornite" , type: 12, subType:2},
{ desc : "Dans un McDrive" , type: 12, subType:2},
{ desc : "À un speed dating" , type: 12, subType:2},
{ desc : "Au hammam" , type: 12, subType:2},
{ desc : "Fait du toboggan" , type: 12, subType:2},
{ desc : "Mange une fondue" , type: 12, subType:2},
{ desc : "Déguisé en père Noël" , type: 12, subType:2},
{ desc : "Fait sa première fois" , type: 12, subType:2},
{ desc : "À une bar-mitzvah" , type: 12, subType:2},
{ desc : "Se trompe de toilettes" , type: 12, subType:2},
{ desc : "Aux urgences" , type: 12, subType:2},
{ desc : "Chante l'hymne national" , type: 12, subType:2},
{ desc : "Prend le métro à l'heure de pointe" , type: 12, subType:2},
{ desc : "Fait un escape game" , type: 12, subType:2},
{ desc : "En manque de PQ" , type: 12, subType:2},
{ desc : "Saute en parachute" , type: 12, subType:2},
{ desc : "À son premier Tinder" , type: 12, subType:2},
{ desc : "Se fait flasher" , type: 12, subType:2},
{ desc : "À Pôle Emploi" , type: 12, subType:2},
{ desc : "Fait sa manucure" , type: 12, subType:2},
{ desc : "Danse à un mariage" , type: 12, subType:2},
{ desc : "Dans un film d'horreur" , type: 12, subType:2},
{ desc : "Fait des abdos" , type: 12, subType:2},
{ desc : "Oublie son anniversaire de mariage" , type: 12, subType:2},
{ desc : "Dans un jacuzzi" , type: 12, subType:2},
{ desc : "Achète des préservatifs" , type: 12, subType:2},
{ desc : "Fait un discours politique" , type: 12, subType:2},
{ desc : "Dans un sauna" , type: 12, subType:2},
{ desc : "Fait cuire des pâtes" , type: 12, subType:2},
{ desc : "Chasse des Pokémon" , type: 12, subType:2},
{ desc : "À la salle de muscu" , type: 12, subType:2},
{ desc : "Pleure devant The Voice" , type: 12, subType:2},
{ desc : "Rate un penalty" , type: 12, subType:2},
{ desc : "Fait un burnout" , type: 12, subType:2},
{ desc : "Pose pour Playboy" , type: 12, subType:2},
{ desc : "À Roland Garros" , type: 12, subType:2},
{ desc : "Avec un string qui dépasse" , type: 12, subType:2},
{ desc : "Joue au Loto" , type: 12, subType:2},
{ desc : "À une soirée années 80" , type: 12, subType:2},
{ desc : "Perd son maillot de bain" , type: 12, subType:2},
{ desc : "Fait une manif" , type: 12, subType:2},
{ desc : "Passe le bac" , type: 12, subType:2},
{ desc : "Joue au strip poker" , type: 12, subType:2},
{ desc : "À la cantine" , type: 12, subType:2},
{ desc : "Fait du trampoline" , type: 12, subType:2},
{ desc : "Joue aux échecs" , type: 12, subType:2},
{ desc : "Achète des bitcoins" , type: 12, subType:2},
{ desc : "Avec une gueule de bois" , type: 12, subType:2},
{ desc : "Mange du saucisson" , type: 12, subType:2},
{ desc : "Prépare une ratatouille" , type: 12, subType:2},
{ desc : "À un enterrement de vie de garçon" , type: 12, subType:2},
{ desc : "Lance un startup" , type: 12, subType:2},
{ desc : "Prie à la mosquée" , type: 12, subType:2},
{ desc : "À Secret Story" , type: 12, subType:2},
{ desc : "Dans le métro sans masque" , type: 12, subType:2},
{ desc : "Fait un câlin à un arbre" , type: 12, subType:2},
{ desc : "En train de méditer" , type: 12, subType:2},
{ desc : "Danse la Zumba" , type: 12, subType:2},
{ desc : "Au tribunal" , type: 12, subType:2},
{ desc : "À la messe" , type: 12, subType:2},
{ desc : "Vend ses vêtements sur Vinted" , type: 12, subType:2},
{ desc : "Fait un marathon Netflix" , type: 12, subType:2},
{ desc : "À un blind test" , type: 12, subType:2},
{ desc : "Sur son lit de mort" , type: 12, subType:2},
{ desc : "Essaie des sous-vêtements" , type: 12, subType:2},
{ desc : "À un mariage forcé" , type: 12, subType:2},
{ desc : "Fait du moonwalk" , type: 12, subType:2},
{ desc : "À la piscine municipale" , type: 12, subType:2},
{ desc : "Répare une machine à laver" , type: 12, subType:2},
{ desc : "Dans Game of Thrones" , type: 12, subType:2},
{ desc : "Invente une recette" , type: 12, subType:2},
{ desc : "À la fête de la musique" , type: 12, subType:2},
{ desc : "Drague un policier" , type: 12, subType:2},
{ desc : "Fait la queue aux WC" , type: 12, subType:2},
{ desc : "Lit un livre érotique" , type: 12, subType:2},
{ desc : "Fait le ménage" , type: 12, subType:2},
{ desc : "Rencontre ses beaux-parents" , type: 12, subType:2},
{ desc : "Joue au golf" , type: 12, subType:2},
{ desc : "Au karting" , type: 12, subType:2},
{ desc : "Perd son dentier" , type: 12, subType:2},
{ desc : "Fête son divorce" , type: 12, subType:2},
{ desc : "Fait un AVC" , type: 12, subType:2},
{ desc : "Dans une secte" , type: 12, subType:2},
{ desc : "Fait une infection urinaire" , type: 12, subType:2},
{ desc : "À l'Eurovision" , type: 12, subType:2},
{ desc : "Se fait tatouer" , type: 12, subType:2},
{ desc : "Conduit un tracteur" , type: 12, subType:2},
{ desc : "Pose pour Instagram" , type: 12, subType:2},
{ desc : "À un cours de danse classique" , type: 12, subType:2},
{ desc : "Se fait épiler les sourcils" , type: 12, subType:2},
{ desc : "Dans un centre naturiste" , type: 12, subType:2},
{ desc : "Fait du ski nautique" , type: 12, subType:2},
{ desc : "À un cours de cuisine" , type: 12, subType:2},
{ desc : "En lévitation" , type: 12, subType:2},
{ desc : "À un safari photo" , type: 12, subType:2},
{ desc : "Tient une chandelle" , type: 12, subType:2},
{ desc : "Fait son testament" , type: 12, subType:2},
{ desc : "À un meeting politique" , type: 12, subType:2},
{ desc : "Joue à la Switch" , type: 12, subType:2},
{ desc : "Se met du vernis à ongles" , type: 12, subType:2},
{ desc : "Fait une demande de crédit" , type: 12, subType:2},
{ desc : "À une baby shower" , type: 12, subType:2},
{ desc : "Mange du caviar" , type: 12, subType:2},
{ desc : "Se teint les cheveux" , type: 12, subType:2},
{ desc : "À une fête d'anniversaire pour enfants" , type: 12, subType:2},
{ desc : "Fait du pole dance" , type: 12, subType:2},
{ desc : "Essaie un nouveau déodorant" , type: 12, subType:2},
{ desc : "À la plage en hiver" , type: 12, subType:2},
{ desc : "Fait des mots croisés" , type: 12, subType:2},
{ desc : "Dans un SPA" , type: 12, subType:2},
{ desc : "Danse avec son chat" , type: 12, subType:2},
{ desc : "Sur un tapis rouge" , type: 12, subType:2},
{ desc : "Prend le train sans billet" , type: 12, subType:2},
{ desc : "Sur un site porno" , type: 12, subType:2},
{ desc : "Repeint son salon" , type: 12, subType:2},
{ desc : "À la CAF" , type: 12, subType:2},
{ desc : "Tombe à vélo" , type: 12, subType:2},
{ desc : "Boit une tisane" , type: 12, subType:2},
{ desc : "Sur un quad" , type: 12, subType:2},
{ desc : "Fait une crise d'adolescence" , type: 12, subType:2},
{ desc : "En train de dealer" , type: 12, subType:2},
{ desc : "Passe un examen médical" , type: 12, subType:2},
{ desc : "Danse la tectonique" , type: 12, subType:2},
{ desc : "À un enterrement de vie de jeune fille" , type: 12, subType:2},
{ desc : "Fait du jardinage" , type: 12, subType:2},
{ desc : "À un cours de yoga" , type: 12, subType:2},
{ desc : "En prison" , type: 12, subType:2},
{ desc : "Perd ses clés" , type: 12, subType:2},
{ desc : "Fait de la sophrologie" , type: 12, subType:2},
{ desc : "Au marché de Noël" , type: 12, subType:2},
{ desc : "Se déguise en licorne" , type: 12, subType:2},
{ desc : "Fait une séance de spiritisme" , type: 12, subType:2},
{ desc : "Dans un embouteillage" , type: 12, subType:2},
{ desc : "Apprend le polonais" , type: 12, subType:2},
{ desc : "Fait du shopping en ligne" , type: 12, subType:2},
{ desc : "À la plage nudiste" , type: 12, subType:2},
{ desc : "Organise un goûter d'anniversaire" , type: 12, subType:2},
{ desc : "Regarde Amour Gloire et Beauté" , type: 12, subType:2},
{ desc : "Fait du saut à l'élastique" , type: 12, subType:2},
{ desc : "Au drive McDonald's" , type: 12, subType:2},
{ desc : "Fait une crise d'allergie" , type: 12, subType:2},
{ desc : "Écoute de l'ASMR" , type: 12, subType:2},
{ desc : "Joue à la belote" , type: 12, subType:2},
{ desc : "Fait du Pilates" , type: 12, subType:2},
{ desc : "À son pot de départ" , type: 12, subType:2},
{ desc : "Se fait prendre en excès de vitesse" , type: 12, subType:2},
{ desc : "À une soirée pyjama" , type: 12, subType:2},
{ desc : "Fait de la poterie" , type: 12, subType:2},
{ desc : "Dans un cours d'aquaponey" , type: 12, subType:2},
{ desc : "Au Hellfest" , type: 12, subType:2},
{ desc : "Fait sa déclaration d'impôts" , type: 12, subType:2},
{ desc : "Dans un parc d'attractions" , type: 12, subType:2},
{ desc : "Noue sa cravate" , type: 12, subType:2},
{ desc : "Mange un kebab" , type: 12, subType:2},
{ desc : "Fait une échographie" , type: 12, subType:2},
{ desc : "Arrose ses plantes" , type: 12, subType:2},
{ desc : "Achète des sextoys" , type: 12, subType:2},
{ desc : "Fait une soirée raclette" , type: 12, subType:2},
{ desc : "Dans une émission de téléréalité" , type: 12, subType:2},
{ desc : "Bloqué aux toilettes" , type: 12, subType:2},
{ desc : "Fait les magasins IKEA" , type: 12, subType:2},
{ desc : "En thérapie" , type: 12, subType:2},
{ desc : "Chante à un karaoké" , type: 12, subType:2},
{ desc : "Mange un escargot" , type: 12, subType:2},
{ desc : "Chez le proctologue" , type: 12, subType:2},
{ desc : "À un défilé de mode" , type: 12, subType:2},
{ desc : "Fait du camping sauvage" , type: 12, subType:2},
{ desc : "Cherche ses lunettes" , type: 12, subType:2},
{ desc : "À la pêche aux canards" , type: 12, subType:2},
{ desc : "En chaussettes-claquettes" , type: 12, subType:2},
{ desc : "Cuit un œuf au plat" , type: 12, subType:2},
{ desc : "À une convention de cosplay" , type: 12, subType:2},
{ desc : "Fait un trou dans son mur" , type: 12, subType:2},
{ desc : "Pendant une panne d'électricité" , type: 12, subType:2},
{ desc : "Apprend à faire du vélo" , type: 12, subType:2},
{ desc : "Chez le dentiste" , type: 12, subType:2},
{ desc : "Fait un jogging" , type: 12, subType:2},
{ desc : "En train de bouder" , type: 12, subType:2},
{ desc : "Au Parc Astérix" , type: 12, subType:2},
{ desc : "Fait une coloscopie" , type: 12, subType:2},
{ desc : "Dans un Uber" , type: 12, subType:2},
{ desc : "Prend sa douche" , type: 12, subType:2},
{ desc : "Pendant une crise de couple" , type: 12, subType:2},
{ desc : "Fait un malaise" , type: 12, subType:2},
{ desc : "Fait un live TikTok" , type: 12, subType:2},
{ desc : "À un cours de claquettes" , type: 12, subType:2},
{ desc : "Fait son coming out" , type: 12, subType:2},
{ desc : "En pleine méditation" , type: 12, subType:2},
{ desc : "Fait un piercing" , type: 12, subType:2},
{ desc : "En train de lire ses horoscopes" , type: 12, subType:2},
{ desc : "Fait du baby-sitting" , type: 12, subType:2},
{ desc : "Au service militaire" , type: 12, subType:2},
{ desc : "Fait de la pâtisserie" , type: 12, subType:2},
{ desc : "Pendant un date Tinder" , type: 12, subType:2},
{ desc : "Dans une réunion Tupperware" , type: 12, subType:2},
{ desc : "Fait un jeûne intermittent" , type: 12, subType:2},
{ desc : "Pendant un entretien d'embauche" , type: 12, subType:2},
{ desc : "Fait des selfies" , type: 12, subType:2},
{ desc : "Se rase la tête" , type: 12, subType:2},
{ desc : "Fait un cours de Bachata" , type: 12, subType:2},
{ desc : "Fait les vendanges" , type: 12, subType:2},
{ desc : "À la fête foraine" , type: 12, subType:2},
{ desc : "Fait un régime Keto" , type: 12, subType:2},
{ desc : "À un dîner de famille" , type: 12, subType:2},
{ desc : "Joue aux cartes Pokemon" , type: 12, subType:2},
{ desc : "Fait des pancakes" , type: 12, subType:2},
{ desc : "Se fait poser des ongles" , type: 12, subType:2},
{ desc : "Joue à Action ou Vérité" , type: 12, subType:2},
{ desc : "Fait un triathlon" , type: 12, subType:2},
{ desc : "Aux puces de Saint-Ouen" , type: 12, subType:2},
{ desc : "Joue à la console" , type: 12, subType:2},
{ desc : "Avec une gueule de bois" , type: 12, subType:2},
{ desc : "À une rave party" , type: 12, subType:2},
{ desc : "Fait du jardinage" , type: 12, subType:2},
{ desc : "Essaie un parfum" , type: 12, subType:2},
{ desc : "À Bercy" , type: 12, subType:2},
{ desc : "Passe le code de la route" , type: 12, subType:2},
{ desc : "Au festival de Cannes" , type: 12, subType:2},
{ desc : "Fait les magasins pendant les soldes" , type: 12, subType:2},
{ desc : "Se baigne dans la Seine" , type: 12, subType:2},
{ desc : "À un mariage princier" , type: 12, subType:2},
{ desc : "Fait du curling" , type: 12, subType:2},
{ desc : "En train d'accoucher" , type: 12, subType:2},
{ desc : "Fait sa valise" , type: 12, subType:2},
{ desc : "À l'oral du bac" , type: 12, subType:2},
{ desc : "Fait du bénévolat" , type: 12, subType:2},
{ desc : "À un dîner romantique" , type: 12, subType:2},
{ desc : "Fait un selfie" , type: 12, subType:2},
{ desc : "Pendant une canicule" , type: 12, subType:2},
{ desc : "Fait une crise de la quarantaine" , type: 12, subType:2},
{ desc : "Essaie de monter un meuble Ikea" , type: 12, subType:2},
{ desc : "Fait un sauna" , type: 12, subType:2},
{ desc : "À un concert de metal" , type: 12, subType:2},
{ desc : "Lutte contre un moustique" , type: 12, subType:2},
{ desc : "Râle dans les bouchons" , type: 12, subType:2},
{ desc : "Dans une course de chars" , type: 12, subType:2},
{ desc : "Passe une IRM" , type: 12, subType:2},
{ desc : "Achète un sex-toy" , type: 12, subType:2},
{ desc : "Avec le hoquet" , type: 12, subType:2},
{ desc : "Prépare une ratatouille" , type: 12, subType:2},
{ desc : "Fait une randonnée" , type: 12, subType:2},
{ desc : "Fait une demande de prêt" , type: 12, subType:2},
{ desc : "Sur un podium de F1" , type: 12, subType:2},
{ desc : "Passe un contrôle fiscal" , type: 12, subType:2},
{ desc : "Vend des calendriers" , type: 12, subType:2},
{ desc : "Chez le notaire" , type: 12, subType:2},
{ desc : "Déguste du vin" , type: 12, subType:2},
{ desc : "À un enterrement de vie de jeune fille" , type: 12, subType:2},
{ desc : "Tient un stand à la fête foraine" , type: 12, subType:2},
{ desc : "Joue à cache-cache" , type: 12, subType:2},
{ desc : "Dans une boîte de strip-tease" , type: 12, subType:2},
{ desc : "Fait une bataille d'eau" , type: 12, subType:2},
{ desc : "Découvre Internet" , type: 12, subType:2},
{ desc : "À un blind test" , type: 12, subType:2},
{ desc : "En train d'éternuer" , type: 12, subType:2},
{ desc : "Fait un sondage politique" , type: 12, subType:2},
{ desc : "À la foire du trône" , type: 12, subType:2},
{ desc : "Fait une grève de la faim" , type: 12, subType:2},
{ desc : "À une convention de cosplay" , type: 12, subType:2},
{ desc : "Après une rupture" , type: 12, subType:2},
{ desc : "En plein déménagement" , type: 12, subType:2},
{ desc : "Au défilé du 14 juillet" , type: 12, subType:2},
{ desc : "Devient vegan" , type: 12, subType:2},
{ desc : "Fait un câlin à un arbre" , type: 12, subType:2},
{ desc : "Prend un cours de pole dance" , type: 12, subType:2},
{ desc : "À une vente aux enchères" , type: 12, subType:2},
{ desc : "Trouve un trésor" , type: 12, subType:2},
{ desc : "À un mariage surprise" , type: 12, subType:2},
{ desc : "Fait un jeûne intermittent" , type: 12, subType:2},
{ desc : "Avec un coup de soleil" , type: 12, subType:2},
{ desc : "Dans un fast-food" , type: 12, subType:2},
{ desc : "Fait un slam" , type: 12, subType:2},
{ desc : "Au tribunal" , type: 12, subType:2},
{ desc : "En train de promener son chien" , type: 12, subType:2},
{ desc : "Goûte des insectes" , type: 12, subType:2},
{ desc : "Pendant un échange linguistique" , type: 12, subType:2},
{ desc : "Fait une dédicace" , type: 12, subType:2},
{ desc : "Sous hypnose" , type: 12, subType:2},
{ desc : "Fait un footing matinal" , type: 12, subType:2},
{ desc : "Cherche le sommeil" , type: 12, subType:2},
{ desc : "À un Dîner Presque Parfait" , type: 12, subType:2},
{ desc : "Joue aux fléchettes" , type: 12, subType:2},
{ desc : "Fait du shopping pour Noël" , type: 12, subType:2},
{ desc : "Fait une farce téléphonique" , type: 12, subType:2},
{ desc : "À une convention naturiste" , type: 12, subType:2},
{ desc : "En train de brûler des calories" , type: 12, subType:2},
{ desc : "Apprend la guitare" , type: 12, subType:2},
{ desc : "En quarantaine" , type: 12, subType:2},
{ desc : "Fait un Safari photo" , type: 12, subType:2},
{ desc : "Braque une banque" , type: 12, subType:2},
{ desc : "Fête son divorce" , type: 12, subType:2},
{ desc : "À un cours de Pilates" , type: 12, subType:2},
{ desc : "Joue du ukulélé" , type: 12, subType:2},
{ desc : "Perd sa carte bancaire" , type: 12, subType:2},
{ desc : "À une séance de dédicaces" , type: 12, subType:2},
{ desc : "Apprend à nager" , type: 12, subType:2},
{ desc : "Fait une blague qui tombe à plat" , type: 12, subType:2},
{ desc : "Pendant une leçon de conduite" , type: 12, subType:2},
{ desc : "Réceptionne un colis" , type: 12, subType:2},
{ desc : "Prend un bain de soleil" , type: 12, subType:2},
{ desc : "Dans un kebab" , type: 12, subType:2},
{ desc : "Fait sa première fois" , type: 12, subType:2},
{ desc : "À une brocante" , type: 12, subType:2},
{ desc : "Joue à la poupée" , type: 12, subType:2},
{ desc : "Attend le médecin" , type: 12, subType:2},
{ desc : "Prépare un apéro" , type: 12, subType:2},
{ desc : "Fait du patinage artistique" , type: 12, subType:2},
{ desc : "Donne le sein" , type: 12, subType:2},
{ desc : "Avec des hémorroïdes" , type: 12, subType:2},
{ desc : "Joue au poker" , type: 12, subType:2},
{ desc : "En train de faire un barbecue" , type: 12, subType:2},
{ desc : "Coupe un arbre" , type: 12, subType:2},
{ desc : "Dans une réunion téléphonique" , type: 12, subType:2},
{ desc : "Prend l'avion pour la première fois" , type: 12, subType:2},
{ desc : "Rencontre sa belle-mère" , type: 12, subType:2},
{ desc : "Pleure devant un film" , type: 12, subType:2},
{ desc : "Rate le bus" , type: 12, subType:2},
{ desc : "À un dîner mondain" , type: 12, subType:2},
{ desc : "Fait du yoga" , type: 12, subType:2},
{ desc : "À une dégustation de vin" , type: 12, subType:2},
{ desc : "Avec une extinction de voix" , type: 12, subType:2},
{ desc : "Fait du kite-surf" , type: 12, subType:2},
{ desc : "Joue à la bataille navale" , type: 12, subType:2},
{ desc : "Fait une course de caddie" , type: 12, subType:2},
{ desc : "Au Club Med" , type: 12, subType:2},
{ desc : "En procès pour divorce" , type: 12, subType:2},
{ desc : "À un lancer de nains" , type: 12, subType:2},
{ desc : "Chez le coiffeur" , type: 12, subType:2},
{ desc : "À un cours de twerk" , type: 12, subType:2},
{ desc : "Fait un régime Keto" , type: 12, subType:2},
{ desc : "Dans un train qui déraille" , type: 12, subType:2},
{ desc : "Au baptême de son neveu" , type: 12, subType:2},
{ desc : "Fait de la sophrologie" , type: 12, subType:2},
{ desc : "Essaie des chaussures" , type: 12, subType:2},
{ desc : "Vend des calendriers des pompiers" , type: 12, subType:2},
{ desc : "Fait du porte-à-porte" , type: 12, subType:2},
{ desc : "Prend un cours de théâtre" , type: 12, subType:2},
{ desc : "Après un lifting" , type: 12, subType:2},
{ desc : "Joue à Colin-Maillard" , type: 12, subType:2},
{ desc : "À une cérémonie des Césars" , type: 12, subType:2},
{ desc : "En train de chercher ses clés" , type: 12, subType:2},
{ desc : "Dévalise un mini-market" , type: 12, subType:2},
{ desc : "Joue à Candy Crush" , type: 12, subType:2},
{ desc : "Dans un bar à oxygène" , type: 12, subType:2},
{ desc : "À un match de foot" , type: 12, subType:2},
{ desc : "Essaie un parfum" , type: 12, subType:2},
{ desc : "Fait du Géocaching" , type: 12, subType:2},
{ desc : "Avec une prothèse dentaire" , type: 12, subType:2},
{ desc : "Pendant un braquage" , type: 12, subType:2},
{ desc : "Pendant une tornade" , type: 12, subType:2},
{ desc : "Avec un appareil auditif" , type: 12, subType:2},
{ desc : "À une soirée déguisée années 80" , type: 12, subType:2},
{ desc : "Fait un exorcisme" , type: 12, subType:2},
{ desc : "Échoue à un examen" , type: 12, subType:2},
{ desc : "Fait une crise de jalousie" , type: 12, subType:2},
{ desc : "Danse la Bachata" , type: 12, subType:2},
{ desc : "Fait une partie de bowling" , type: 12, subType:2},
{ desc : "Sur le point d'accoucher" , type: 12, subType:2},
{ desc : "Dans un bar à chats" , type: 12, subType:2},
{ desc : "Fait du bruit en mangeant" , type: 12, subType:2},
{ desc : "Au parc d'attraction" , type: 12, subType:2},
{ desc : "Prend un cours de cuisine italienne" , type: 12, subType:2},
{ desc : "Dans une machine à laver" , type: 12, subType:2},
{ desc : "Pendant un rendez-vous Tinder" , type: 12, subType:2},
{ desc : "Fait une teinture maison" , type: 12, subType:2},
{ desc : "Mange une pizza" , type: 12, subType:2},
{ desc : "À la fête de la musique" , type: 12, subType:2},
{ desc : "Rate un avion" , type: 12, subType:2},
{ desc : "Apprend à faire du vélo" , type: 12, subType:2},
{ desc : "Cherche un appartement" , type: 12, subType:2},
{ desc : "Perd à la roulette" , type: 12, subType:2},
{ desc : "Révise son permis" , type: 12, subType:2},
{ desc : "Attend la livraison d'un canapé" , type: 12, subType:2},
{ desc : "Fait une bataille de boules de neige" , type: 12, subType:2},
{ desc : "En train de faire son bilan sanguin" , type: 12, subType:2},
{ desc : "Apprend la salsa" , type: 12, subType:2},
{ desc : "Visite un château hanté" , type: 12, subType:2},
{ desc : "En cure de désintoxication" , type: 12, subType:2},
{ desc : "Avec un rhume" , type: 12, subType:2},
{ desc : "Fait un selfie avec un tigre" , type: 12, subType:2},
{ desc : "À un anniversaire surprise" , type: 12, subType:2},
{ desc : "Passe une radio des dents" , type: 12, subType:2},
{ desc : "Échoue à un entretien d'embauche" , type: 12, subType:2},
{ desc : "À un cours de poterie" , type: 12, subType:2},
{ desc : "En voyage scolaire" , type: 12, subType:2},
{ desc : "Fait un soin du visage" , type: 12, subType:2},
{ desc : "Dans un film X" , type: 12, subType:2},
{ desc : "Prend un cours d'espagnol" , type: 12, subType:2},
{ desc : "Fait une chute à vélo" , type: 12, subType:2},
{ desc : "Fait son coming-out" , type: 12, subType:2},
{ desc : "Au service des objets trouvés" , type: 12, subType:2},
{ desc : "Danse la country" , type: 12, subType:2},
{ desc : "Dans un sauna finlandais" , type: 12, subType:2},
{ desc : "Découvre les jeux vidéo" , type: 12, subType:2},
{ desc : "Fait un tour en montgolfière" , type: 12, subType:2},
{ desc : "À un brunch du dimanche" , type: 12, subType:2},
{ desc : "Pendant un cambriolage" , type: 12, subType:2},
{ desc : "Prépare un gâteau d'anniversaire" , type: 12, subType:2},
{ desc : "Répare une crevaison" , type: 12, subType:2},
{ desc : "Dans une salle d'attente" , type: 12, subType:2},
{ desc : "Joue au lancer de hache" , type: 12, subType:2},
{ desc : "Tourne un Tik Tok" , type: 12, subType:2},
{ desc : "Se fait larguer" , type: 12, subType:2},
{ desc : "Chute dans les escaliers" , type: 12, subType:2},
{ desc : "Achète un matelas" , type: 12, subType:2},
{ desc : "Fait semblant d'être malade" , type: 12, subType:2},
{ desc : "À un karaoke" , type: 12, subType:2},
{ desc : "Fait une overdose de sucre" , type: 12, subType:2},
{ desc : "En train de faire la queue à la Poste" , type: 12, subType:2},
{ desc : "Pendant un défilé de mode" , type: 12, subType:2},
{ desc : "À un saut à l'élastique" , type: 12, subType:2},
{ desc : "Apprend à jouer de la batterie" , type: 12, subType:2},
{ desc : "Fait une gastro" , type: 12, subType:2},
{ desc : "En train de faire une liste de courses" , type: 12, subType:2},
{ desc : "Adopte un enfant" , type: 12, subType:2},
{ desc : "Fait un triathlon" , type: 12, subType:2},
{ desc : "Se fait arrêter par la police" , type: 12, subType:2},
{ desc : "Demande une augmentation" , type: 12, subType:2},
{ desc : "Gagne un concours de sosies" , type: 12, subType:2},
{ desc : "Se fait piquer par une guêpe" , type: 12, subType:2},
{ desc : "Déprime un dimanche soir" , type: 12, subType:2},
{ desc : "Saute d'un avion" , type: 12, subType:2},
{ desc : "Piétine dans une file d'attente" , type: 12, subType:2},
{ desc : "Apprend à conduire en boîte manuelle" , type: 12, subType:2},
{ desc : "Fait un footing" , type: 12, subType:2},
{ desc : "Fait un album photo" , type: 12, subType:2},
{ desc : "En visite à la maison de retraite" , type: 12, subType:2},
{ desc : "Essaie des chaussures de ski" , type: 12, subType:2},
{ desc : "Fait un cours de français" , type: 12, subType:2},
{ desc : "En camping sauvage" , type: 12, subType:2},
{ desc : "Au festival de Cannes" , type: 12, subType:2},
{ desc : "Fait le tri dans ses vêtements" , type: 12, subType:2},
{ desc : "Renverse sa boisson" , type: 12, subType:2},
{ desc : "À une conférence TED" , type: 12, subType:2},
{ desc : "Découvre une araignée dans sa douche" , type: 12, subType:2},
{ desc : "Achète des places de concert" , type: 12, subType:2},
{ desc : "S'endort au cinéma" , type: 12, subType:2},
{ desc : "Fait un karting" , type: 12, subType:2},
{ desc : "À un cours de chant" , type: 12, subType:2},
{ desc : "Échoue un tour de magie" , type: 12, subType:2},
{ desc : "Pendant un orage" , type: 12, subType:2},
{ desc : "Dans une galerie d'art" , type: 12, subType:2},
{ desc : "Fait un test de grossesse" , type: 12, subType:2},
{ desc : "Prend le métro à l'heure de pointe" , type: 12, subType:2},
{ desc : "Se fait appeler \"Monsieur\" ou \"Madame\"" , type: 12, subType:2},
{ desc : "Est en retard à un rendez-vous" , type: 12, subType:2},
{ desc : "Pendant un cours de natation" , type: 12, subType:2},
{ desc : "Lance une entreprise de dropshipping" , type: 12, subType:2},
{ desc : "Dans un magasin de bricolage" , type: 12, subType:2},
{ desc : "Achète des préservatifs" , type: 12, subType:2},
{ desc : "Perd ses dents" , type: 12, subType:2},
{ desc : "Pendant une coupure d'électricité" , type: 12, subType:2},
{ desc : "Fait une crémaillère" , type: 12, subType:2},
{ desc : "Suit un régime intermittent" , type: 12, subType:2},
{ desc : "Mange des escargots" , type: 12, subType:2},
{ desc : "Pendant un mariage forcé" , type: 12, subType:2},
{ desc : "Fait un trou dans un mur" , type: 12, subType:2},
{ desc : "À un concours de beauté canine" , type: 12, subType:2},
{ desc : "Apprend le chinois" , type: 12, subType:2},
{ desc : "À un repas de famille tendu" , type: 12, subType:2},
{ desc : "Pendant une invasion d'extraterrestres" , type: 12, subType:2},
{ desc : "Joue à la marelle" , type: 12, subType:2},
{ desc : "Fait un rodéo" , type: 12, subType:2},
{ desc : "À un débat présidentiel" , type: 12, subType:2},
{ desc : "Passe un examen gynécologique" , type: 12, subType:2},
{ desc : "Vole des vieilles dames" , type: 12, subType:2},
{ desc : "Trafique des organes" , type: 12, subType:2},
{ desc : "Blanchit de l'argent" , type: 12, subType:2},
{ desc : "En pleine partouze" , type: 12, subType:2},
{ desc : "Fait un pacte avec le diable" , type: 12, subType:2},
{ desc : "Se fait pipi dessus" , type: 12, subType:2},
{ desc : "Lance des excréments" , type: 12, subType:2},
{ desc : "Fraude les impôts" , type: 12, subType:2},
{ desc : "Conduit bourré" , type: 12, subType:2},
{ desc : "Fait un procès à ses parents" , type: 12, subType:2},
{ desc : "Pratique l'inceste" , type: 12, subType:2},
{ desc : "Fait du chantage" , type: 12, subType:2},
{ desc : "À un exorcisme" , type: 12, subType:2},
{ desc : "Pratique un sacrifice humain" , type: 12, subType:2},
{ desc : "Fait un coup d'État" , type: 12, subType:2},
{ desc : "Vend des substances illicites" , type: 12, subType:2},
{ desc : "Raconte des blagues racistes" , type: 12, subType:2},
{ desc : "Fait un strip-tease pour des enfants" , type: 12, subType:2},
{ desc : "Se fait expulser d'un avion" , type: 12, subType:2},
{ desc : "Simule un handicap" , type: 12, subType:2},
{ desc : "Croit aux reptiliens" , type: 12, subType:2},
{ desc : "Pratique la nécrophilie" , type: 12, subType:2},
{ desc : "Est condamné pour fraude" , type: 12, subType:2},
{ desc : "Fait une fausse alerte à la bombe" , type: 12, subType:2},
{ desc : "Craque un pet dans l'ascenseur" , type: 12, subType:2},
{ desc : "Sniffe de la coke" , type: 12, subType:2},
{ desc : "Se fait arrêter à l'aéroport" , type: 12, subType:2},
{ desc : "Boit de l'eau des toilettes" , type: 12, subType:2},
{ desc : "Paye avec de la fausse monnaie" , type: 12, subType:2},
{ desc : "Pratique le cannibalisme" , type: 12, subType:2},
{ desc : "Fait un burn-out" , type: 12, subType:2},
{ desc : "Massacre à la tronçonneuse" , type: 12, subType:2},
{ desc : "Pose une bombe" , type: 12, subType:2},
{ desc : "A la diarrhée en public" , type: 12, subType:2},
{ desc : "Se cache dans une maison abandonnée" , type: 12, subType:2},
{ desc : "Avoue un crime" , type: 12, subType:2},
{ desc : "Fait des selfies avec un cadavre" , type: 12, subType:2},
{ desc : "En test de paternité" , type: 12, subType:2},
{ desc : "Fait un coming out raté" , type: 12, subType:2},
{ desc : "Mets du poison dans la nourriture" , type: 12, subType:2},
{ desc : "Dénonce des juifs" , type: 12, subType:2},
{ desc : "En pleine crise de démence" , type: 12, subType:2},
{ desc : "Cambriole une banque" , type: 12, subType:2},
{ desc : "Instaure une dictature" , type: 12, subType:2},
{ desc : "Prend des stéroïdes" , type: 12, subType:2},
{ desc : "Fait un contrôle fiscal" , type: 12, subType:2},
{ desc : "Fait une overdose" , type: 12, subType:2},
{ desc : "En pleine crise de paranoïa" , type: 12, subType:2},
{ desc : "Au tribunal pour fraude" , type: 12, subType:2},
{ desc : "Triche aux examens" , type: 12, subType:2},
{ desc : "Arnaque des personnes âgées" , type: 12, subType:2},
{ desc : "Lance des rumeurs" , type: 12, subType:2},
{ desc : "Vend des armes à des pays en guerre" , type: 12, subType:2},
{ desc : "Se fait lyncher" , type: 12, subType:2},
{ desc : "En pleine crise d'épilepsie" , type: 12, subType:2},
{ desc : "Se fait expulser d'un pays" , type: 12, subType:2},
{ desc : "À un cours d'éducation sexuelle" , type: 12, subType:2},
{ desc : "Fait un discours nazi" , type: 12, subType:2},
{ desc : "Déshérite ses enfants" , type: 12, subType:2},
{ desc : "Se masturbe en public" , type: 12, subType:2},
{ desc : "Avec une MST" , type: 12, subType:2},
{ desc : "Boit son urine" , type: 12, subType:2},
{ desc : "Fait une tentative de suicide" , type: 12, subType:2},
{ desc : "Vole à l'étalage" , type: 12, subType:2},
{ desc : "Harcèle son ex" , type: 12, subType:2},
{ desc : "Fait un chantage émotionnel" , type: 12, subType:2},
{ desc : "Kidnappe un enfant" , type: 12, subType:2},
{ desc : "Vend ses organes" , type: 12, subType:2},
{ desc : "Se fait retirer un kyste" , type: 12, subType:2},
{ desc : "Devient SDF" , type: 12, subType:2},
{ desc : "Pirate des comptes" , type: 12, subType:2},
{ desc : "Mange des cafards" , type: 12, subType:2},
{ desc : "Assassine le président" , type: 12, subType:2},
{ desc : "A une crise cardiaque" , type: 12, subType:2},
{ desc : "Se venge de son ex" , type: 12, subType:2},
{ desc : "Est expulsé de son logement" , type: 12, subType:2},
{ desc : "Fait chanter une célébrité" , type: 12, subType:2},
{ desc : "Coupe la tête de quelqu'un" , type: 12, subType:2},
{ desc : "Pratique l'automutilation" , type: 12, subType:2},
{ desc : "Danse nu dans la rue" , type: 12, subType:2},
{ desc : "Dans une secte" , type: 12, subType:2},
{ desc : "Se fait violer" , type: 12, subType:2},
{ desc : "A une hallucination" , type: 12, subType:2},
{ desc : "Se prend pour Jésus" , type: 12, subType:2},
{ desc : "Pratique le shibari" , type: 12, subType:2},
{ desc : "Se fait tabasser" , type: 12, subType:2},
{ desc : "Dirige un réseau de prostitution" , type: 12, subType:2},
{ desc : "Menace de se suicider" , type: 12, subType:2},
{ desc : "Se prend pour un animal" , type: 12, subType:2},
{ desc : "Fait du porno amateur" , type: 12, subType:2},
{ desc : "Insulte des handicapés" , type: 12, subType:2},
{ desc : "Fait une thérapie de conversion" , type: 12, subType:2},
{ desc : "S'évade de prison" , type: 12, subType:2},
{ desc : "Abandonne son bébé" , type: 12, subType:2},
{ desc : "Pratique l'avortement clandestin" , type: 12, subType:2},
{ desc : "Dans un camp de nudistes" , type: 12, subType:2},
{ desc : "Crée une secte" , type: 12, subType:2},
{ desc : "Frappe sa grand-mère" , type: 12, subType:2},
{ desc : "Est contrôlé positif au dopage" , type: 12, subType:2},
{ desc : "Fait semblant d'être sourd" , type: 12, subType:2},
{ desc : "S'autoflagelle" , type: 12, subType:2},
{ desc : "Vend des médicaments contrefaits" , type: 12, subType:2},
{ desc : "Torture des animaux" , type: 12, subType:2},
{ desc : "Fait une fixation sur un pied" , type: 12, subType:2},
{ desc : "Se radicalise sur internet" , type: 12, subType:2},
{ desc : "Triche aux Jeux Olympiques" , type: 12, subType:2},
{ desc : "Se prend pour un vampire" , type: 12, subType:2},
{ desc : "Prêche la fin du monde" , type: 12, subType:2},
{ desc : "Insulte un contrôleur" , type: 12, subType:2},
{ desc : "Mange un animal vivant" , type: 12, subType:2},
{ desc : "Fait une crise d'hystérie" , type: 12, subType:2},
{ desc : "Se prostitue pour de la drogue" , type: 12, subType:2},
{ desc : "Fait une scène dans un restaurant" , type: 12, subType:2},
{ desc : "Reçoit un diagnostic de cancer" , type: 12, subType:2},
{ desc : "Rate son suicide" , type: 12, subType:2},
{ desc : "Colle des affiches racistes" , type: 12, subType:2},
{ desc : "Se fait vomir" , type: 12, subType:2},
{ desc : "Est témoin d'un meurtre" , type: 12, subType:2},
{ desc : "Fait un plan à trois" , type: 12, subType:2},
{ desc : "Se fait plaquer pour son meilleur ami" , type: 12, subType:2},
{ desc : "Fait de la prison" , type: 12, subType:2},
{ desc : "En pleine crise d'angoisse" , type: 12, subType:2},
{ desc : "Vole un nouveau-né" , type: 12, subType:2},
{ desc : "À un casting porno" , type: 12, subType:2},
{ desc : "Est accusé d'agression sexuelle" , type: 12, subType:2},
{ desc : "Snobe une célébrité" , type: 12, subType:2},
{ desc : "Fait un vœu de chasteté" , type: 12, subType:2},
{ desc : "Verse du laxatif dans un punch" , type: 12, subType:2},
{ desc : "Est dans le déni" , type: 12, subType:2},
{ desc : "Fait du tourisme sexuel" , type: 12, subType:2},
{ desc : "À une thérapie de groupe" , type: 12, subType:2},
{ desc : "Se bat avec un SDF" , type: 12, subType:2},
{ desc : "Se rend à la police" , type: 12, subType:2},
{ desc : "Gagne à un jeu d'argent" , type: 12, subType:2},
{ desc : "Fume un joint" , type: 12, subType:2},
{ desc : "Fait un enfant dans le dos" , type: 12, subType:2},
{ desc : "Pratique du nudisme" , type: 12, subType:2},
{ desc : "Pratique l'échangisme" , type: 12, subType:2},
{ desc : "Boit du sang" , type: 12, subType:2},
{ desc : "N'a pas pris sa douche depuis un mois" , type: 12, subType:2},
{ desc : "Fait la manche" , type: 12, subType:2},
{ desc : "Organise un combat de chiens" , type: 12, subType:2},
{ desc : "Répand des fake news" , type: 12, subType:2},
{ desc : "Prend une photo sous une jupe" , type: 12, subType:2},
{ desc : "Se fait expulser d'un magasin" , type: 12, subType:2},
{ desc : "Lance des objets par la fenêtre" , type: 12, subType:2},
{ desc : "Fait un rituel satanique" , type: 12, subType:2},
{ desc : "Avec un retard de règles" , type: 12, subType:2},
{ desc : "Fait une remarque sexiste" , type: 12, subType:2},
{ desc : "Sous l'emprise de drogues" , type: 12, subType:2},
{ desc : "Prépare un attentat" , type: 12, subType:2},
{ desc : "Fait un procès à Dieu" , type: 12, subType:2},
{ desc : "Suce son pouce" , type: 12, subType:2},
{ desc : "Se fait tatouer \"maman\" sur le bras" , type: 12, subType:2},
{ desc : "Vole dans la caisse" , type: 12, subType:2},
{ desc : "Se croit persécuté" , type: 12, subType:2},
{ desc : "Fait du tourisme de catastrophe" , type: 12, subType:2},
{ desc : "Est interdit bancaire" , type: 12, subType:2},
{ desc : "Mange de l'herbe" , type: 12, subType:2},
{ desc : "Dort dans la rue" , type: 12, subType:2},
{ desc : "Hurle des obscénités" , type: 12, subType:2},
{ desc : "A une dette de jeu" , type: 12, subType:2},
{ desc : "Raconte sa vie sexuelle" , type: 12, subType:2},
{ desc : "Se cache dans un placard" , type: 12, subType:2},
{ desc : "Disparaît pendant 10 ans" , type: 12, subType:2},
{ desc : "Vole une voiture" , type: 12, subType:2},
{ desc : "A 50 chats" , type: 12, subType:2},
{ desc : "Urine dans une piscine" , type: 12, subType:2},
{ desc : "Se promène en sous-vêtements" , type: 12, subType:2},
{ desc : "Est allergique à l'eau" , type: 12, subType:2},
{ desc : "Se bat avec un handicapé" , type: 12, subType:2},
{ desc : "Chante faux" , type: 12, subType:2},
{ desc : "Fait une grève de la faim" , type: 12, subType:2},
{ desc : "A peur des clowns" , type: 12, subType:2},
{ desc : "Collectionne des ongles" , type: 12, subType:2},
{ desc : "A une double vie" , type: 12, subType:2},
{ desc : "Achète un diplôme" , type: 12, subType:2},
{ desc : "A une relation avec un élève" , type: 12, subType:2},
{ desc : "Est en dépression" , type: 12, subType:2},
{ desc : "Sent mauvais" , type: 12, subType:2},
{ desc : "Fait du chantage à la sexualité" , type: 12, subType:2},
{ desc : "Bloque des toilettes publiques" , type: 12, subType:2},
{ desc : "Fait une blague qui tourne mal" , type: 12, subType:2},
{ desc : "Ment sur son âge" , type: 12, subType:2},
{ desc : "Organise un cambriolage" , type: 12, subType:2},
{ desc : "A un TOC" , type: 12, subType:2},
{ desc : "Vend des photos de pieds" , type: 12, subType:2},
{ desc : "Vole de la nourriture" , type: 12, subType:2},
{ desc : "Fait une invasion de domicile" , type: 12, subType:2},
{ desc : "Vend des informations confidentielles" , type: 12, subType:2},
{ desc : "Est un agent double" , type: 12, subType:2},
{ desc : "Fait du braconnage" , type: 12, subType:2},
{ desc : "Fait une fausse déclaration" , type: 12, subType:2},
{ desc : "Est bourré au travail" , type: 12, subType:2},
{ desc : "Est addict au sexe" , type: 12, subType:2},
{ desc : "Fait une fugue" , type: 12, subType:2},
{ desc : "Créée une fausse identité" , type: 12, subType:2},
{ desc : "Est accro aux jeux d'argent" , type: 12, subType:2},
{ desc : "Vomit sur scène" , type: 12, subType:2},
{ desc : "Se fait mordre par un zombie" , type: 12, subType:2},
{ desc : "Triche à un jeu télévisé" , type: 12, subType:2},
{ desc : "Gaspille de la nourriture" , type: 12, subType:2},
{ desc : "Fait de la chirurgie plastique ratée" , type: 12, subType:2},
{ desc : "Construit une bombe" , type: 12, subType:2},
{ desc : "Simule un accident" , type: 12, subType:2},
{ desc : "Truque une élection" , type: 12, subType:2},
{ desc : "Fait du plagiat" , type: 12, subType:2},
{ desc : "Est en procès" , type: 12, subType:2},
{ desc : "Pollue volontairement" , type: 12, subType:2},
{ desc : "Reçoit un colis suspect" , type: 12, subType:2},
{ desc : "A une hallucination" , type: 12, subType:2},
{ desc : "Tombe dans les pommes" , type: 12, subType:2},
{ desc : "Est en surpoids" , type: 12, subType:2},
{ desc : "Fait semblant d'être aveugle" , type: 12, subType:2},
{ desc : "Fait une crise d'épilepsie" , type: 12, subType:2},
{ desc : "Joue au loto" , type: 12, subType:2},
{ desc : "Prend la fuite" , type: 12, subType:2},
{ desc : "Viole le couvre-feu" , type: 12, subType:2},
{ desc : "Raconte un mensonge" , type: 12, subType:2},
{ desc : "Reçoit un héritage" , type: 12, subType:2},
{ desc : "Fait une déclaration homophobe" , type: 12, subType:2},
{ desc : "S'évanouit en public" , type: 12, subType:2},
{ desc : "Fait une allergie" , type: 12, subType:2},
{ desc : "Danse la macarena" , type: 12, subType:2},
{ desc : "Mange des insectes" , type: 12, subType:2},
{ desc : "Pratique la coprophagie" , type: 12, subType:2},
{ desc : "Est dans le coma" , type: 12, subType:2},
{ desc : "Fait du saut à l'élastique" , type: 12, subType:2},
{ desc : "Fait du parachute" , type: 12, subType:2},
{ desc : "Joue à un jeu vidéo" , type: 12, subType:2},
{ desc : "Regarde un film porno" , type: 12, subType:2},
{ desc : "Fait une grève" , type: 12, subType:2},
{ desc : "Est en confinement" , type: 12, subType:2},
{ desc : "Fait une colère" , type: 12, subType:2},
{ desc : "Danse le flamenco" , type: 12, subType:2},
{ desc : "Est ivre" , type: 12, subType:2},
{ desc : "Fait un régime" , type: 12, subType:2},
{ desc : "Court un marathon" , type: 12, subType:2},
{ desc : "Nage dans la mer" , type: 12, subType:2},
{ desc : "Fait du vélo" , type: 12, subType:2},
{ desc : "Joue au football" , type: 12, subType:2},
{ desc : "Joue au tennis" , type: 12, subType:2},
{ desc : "Joue au basket" , type: 12, subType:2},
{ desc : "Joue au golf" , type: 12, subType:2},
{ desc : "Joue au baseball" , type: 12, subType:2},
{ desc : "Joue au rugby" , type: 12, subType:2},
{ desc : "Joue au hockey" , type: 12, subType:2},
{ desc : "Joue au cricket" , type: 12, subType:2},
{ desc : "Joue au volleyball" , type: 12, subType:2},
{ desc : "Joue au ping-pong" , type: 12, subType:2},
{ desc : "Joue aux échecs" , type: 12, subType:2},
{ desc : "Joue aux dames" , type: 12, subType:2},
{ desc : "Joue aux cartes" , type: 12, subType:2},
{ desc : "Joue à la roulette" , type: 12, subType:2},
{ desc : "Joue à la belote" , type: 12, subType:2},
{ desc : "Joue au tarot" , type: 12, subType:2},
{ desc : "Joue au poker" , type: 12, subType:2},
{ desc : "Joue au blackjack" , type: 12, subType:2},
{ desc : "Joue à la bataille" , type: 12, subType:2},
{ desc : "Joue à cache-cache" , type: 12, subType:2},
{ desc : "Joue à chat" , type: 12, subType:2},
{ desc : "Joue à la marelle" , type: 12, subType:2},
{ desc : "Joue à la corde à sauter" , type: 12, subType:2},
{ desc : "Joue au ballon prisonnier" , type: 12, subType:2},
{ desc : "Joue à la pétanque" , type: 12, subType:2},
{ desc : "Joue aux fléchettes" , type: 12, subType:2},
{ desc : "Joue au billard" , type: 12, subType:2},
{ desc : "Joue au bowling" , type: 12, subType:2},
{ desc : "Joue aux quilles" , type: 12, subType:2},
{ desc : "Joue au mini-golf" , type: 12, subType:2},
{ desc : "Joue au badminton" , type: 12, subType:2},
{ desc : "Joue au squash" , type: 12, subType:2},
{ desc : "Joue au racquetball" , type: 12, subType:2},
{ desc : "Joue au water-polo" , type: 12, subType:2},
{ desc : "Joue au handball" , type: 12, subType:2},
{ desc : "Joue au frisbee" , type: 12, subType:2},
{ desc : "Joue au disc-golf" , type: 12, subType:2},
{ desc : "Joue au football américain" , type: 12, subType:2},
{ desc : "Joue au football canadien" , type: 12, subType:2},
{ desc : "Joue au football australien" , type: 12, subType:2},
{ desc : "Joue au rugby à XIII" , type: 12, subType:2},
{ desc : "Joue au rugby à XV" , type: 12, subType:2},
{ desc : "Joue au cricket" , type: 12, subType:2},
{ desc : "Joue au curling" , type: 12, subType:2},
{ desc : "Joue au ski" , type: 12, subType:2},
{ desc : "Joue au snowboard" , type: 12, subType:2},
{ desc : "Joue au skateboard" , type: 12, subType:2},
{ desc : "Joue au roller" , type: 12, subType:2},
{ desc : "Joue au patin à glace" , type: 12, subType:2},
{ desc : "Joue au surf" , type: 12, subType:2},
{ desc : "Joue au windsurf" , type: 12, subType:2},
{ desc : "Joue au kitesurf" , type: 12, subType:2},



];