const carddata13 = [
{ "desc" : "Un métier" , "type": 13},
{ "desc" : "Un chanteur de rap" , "type": 13},
{ "desc" : "un comédien débutant" , "type": 13},
{ "desc" : "Une expression ou un jeu de mots" , "type": 13},
{ "desc" : "Un pays" , "type": 13},
{ "desc" : "Une ville" , "type": 13},
{ "desc" : "Ce qui décolle" , "type": 13},
{ "desc" : "Ce qui scintille" , "type": 13},
{ "desc" : "Chose qui fond dans la bouche" , "type": 13},
{ "desc" : "Chose qui fond dans la bouche" , "type": 13},
{ "desc" : "Quelque chose qui pue" , "type": 13},
{ "desc" : "Problème gênant en pharmacie" , "type": 13},
{ "desc" : "Un pays" , "type": 13},
{ "desc" : "Une ville" , "type": 13},
{ "desc" : "Un animal" , "type": 13},
{ "desc" : "Un sport" , "type": 13},
{ "desc" : "Un fruit ou légume" , "type": 13},
{ "desc" : "Un métier" , "type": 13},
{ "desc" : "Un instrument de musique" , "type": 13},
{ "desc" : "Un plat traditionnel" , "type": 13},
{ "desc" : "Une boisson" , "type": 13},
{ "desc" : "Un moyen de transport" , "type": 13},
{ "desc" : "Un personnage de film/série" , "type": 13},
{ "desc" : "Un superhéros/supervilain" , "type": 13},
{ "desc" : "Un pokémon" , "type": 13},
{ "desc" : "Un artiste/chanteur" , "type": 13},
{ "desc" : "Une marque de voiture" , "type": 13},
{ "desc" : "Un jeu vidéo" , "type": 13},
{ "desc" : "Un type d'arme" , "type": 13},
{ "desc" : "Un personnage historique" , "type": 13},
{ "desc" : "Un groupe de musique" , "type": 13},
{ "desc" : "Un monument célèbre" , "type": 13},
{ "desc" : "Quelque chose qu'on trouve dans une salle de bain" , "type": 13},
{ "desc" : "Quelque chose qu'on met dans un sac" , "type": 13},
{ "desc" : "Une chose qui fait du bruit" , "type": 13},
{ "desc" : "Quelque chose qu'on peut casser facilement" , "type": 13},
{ "desc" : "Une chose qu'on trouve à la plage" , "type": 13},
{ "desc" : "Quelque chose de collant" , "type": 13},
{ "desc" : "Une situation embarrassante" , "type": 13},
{ "desc" : "Une excuse pour arriver en retard" , "type": 13},
{ "desc" : "Quelque chose qui donne faim" , "type": 13},
{ "desc" : "Une raison de pleurer" , "type": 13},
{ "desc" : "Un surnom ridicule pour quelqu'un" , "type": 13},
{ "desc" : "Une façon étrange de mourir" , "type": 13},
{ "desc" : "Un mauvais cadeau d'anniversaire" , "type": 13},
{ "desc" : "Une chose à ne jamais dire à un premier rendez-vous" , "type": 13},
{ "desc" : "Un titre de film qui n'existe pas" , "type": 13},
{ "desc" : "Une chanson inventée" , "type": 13},
{ "desc" : "Un objet inutile" , "type": 13},
{ "desc" : "Une phobie inventée" , "type": 13},
{ "desc" : "Une combinaison alimentaire dégoûtante" , "type": 13},
{ "desc" : "Une excuse improbable" , "type": 13},
{ "desc" : "Un animal sauvage" , "type": 13},
{ "desc" : "Un animal domestique" , "type": 13},
{ "desc" : "Un animal marin" , "type": 13},
{ "desc" : "Un insecte" , "type": 13},
{ "desc" : "Un oiseau" , "type": 13},
{ "desc" : "Un reptile" , "type": 13},
{ "desc" : "Un mammifère" , "type": 13},
{ "desc" : "Un poisson" , "type": 13},
{ "desc" : "Un amphibien" , "type": 13},
{ "desc" : "Un animal préhistorique" , "type": 13},
{ "desc" : "Un animal nocturne" , "type": 13},
{ "desc" : "Un animal qui hiberne" , "type": 13},
{ "desc" : "Un animal venimeux" , "type": 13},
{ "desc" : "Un arbre" , "type": 13},
{ "desc" : "Une fleur" , "type": 13},
{ "desc" : "Un légume" , "type": 13},
{ "desc" : "Un fruit" , "type": 13},
{ "desc" : "Une plante d'intérieur" , "type": 13},
{ "desc" : "Une herbe aromatique" , "type": 13},
{ "desc" : "Un champignon" , "type": 13},
{ "desc" : "Un pays d'Europe" , "type": 13},
{ "desc" : "Un pays d'Asie" , "type": 13},
{ "desc" : "Un pays d'Afrique" , "type": 13},
{ "desc" : "Un pays d'Amérique" , "type": 13},
{ "desc" : "Un pays d'Océanie" , "type": 13},
{ "desc" : "Une capitale" , "type": 13},
{ "desc" : "Une grande ville" , "type": 13},
{ "desc" : "Une chaîne de montagnes" , "type": 13},
{ "desc" : "Une rivière" , "type": 13},
{ "desc" : "Un océan" , "type": 13},
{ "desc" : "Une mer" , "type": 13},
{ "desc" : "Un lac" , "type": 13},
{ "desc" : "Une île" , "type": 13},
{ "desc" : "Un désert" , "type": 13},
{ "desc" : "Une forêt" , "type": 13},
{ "desc" : "Un parc national" , "type": 13},
{ "desc" : "Un monument naturel" , "type": 13},
{ "desc" : "Un phénomène météorologique" , "type": 13},
{ "desc" : "Un type de nuage" , "type": 13},
{ "desc" : "Une constellation" , "type": 13},
{ "desc" : "Un plat traditionnel français" , "type": 13},
{ "desc" : "Un plat asiatique" , "type": 13},
{ "desc" : "Un plat italien" , "type": 13},
{ "desc" : "Un plat mexicain" , "type": 13},
{ "desc" : "Un dessert" , "type": 13},
{ "desc" : "Une pâtisserie" , "type": 13},
{ "desc" : "Un type de pain" , "type": 13},
{ "desc" : "Une confiserie" , "type": 13},
{ "desc" : "Un fromage" , "type": 13},
{ "desc" : "Une épice" , "type": 13},
{ "desc" : "Une sauce" , "type": 13},
{ "desc" : "Un alcool" , "type": 13},
{ "desc" : "Un cocktail" , "type": 13},
{ "desc" : "Une boisson chaude" , "type": 13},
{ "desc" : "Une boisson gazeuse" , "type": 13},
{ "desc" : "Un type de thé" , "type": 13},
{ "desc" : "Un type de café" , "type": 13},
{ "desc" : "Un fruit exotique" , "type": 13},
{ "desc" : "Un légume ancien" , "type": 13},
{ "desc" : "Un ingrédient rare" , "type": 13},
{ "desc" : "Un genre musical" , "type": 13},
{ "desc" : "Un instrument de musique" , "type": 13},
{ "desc" : "Un groupe de rock" , "type": 13},
{ "desc" : "Un artiste pop" , "type": 13},
{ "desc" : "Un rappeur/une rappeuse" , "type": 13},
{ "desc" : "Un compositeur classique" , "type": 13},
{ "desc" : "Un danseur/une danseuse célèbre" , "type": 13},
{ "desc" : "Un acteur/une actrice" , "type": 13},
{ "desc" : "Un réalisateur/une réalisatrice" , "type": 13},
{ "desc" : "Un film d'action" , "type": 13},
{ "desc" : "Un film d'horreur" , "type": 13},
{ "desc" : "Un film d'animation" , "type": 13},
{ "desc" : "Une comédie" , "type": 13},
{ "desc" : "Une série TV" , "type": 13},
{ "desc" : "Un personnage de dessin animé" , "type": 13},
{ "desc" : "Un super-héros" , "type": 13},
{ "desc" : "Un super-vilain" , "type": 13},
{ "desc" : "Un personnage de jeu vidéo" , "type": 13},
{ "desc" : "Un jeu vidéo" , "type": 13},
{ "desc" : "Un jeu de société" , "type": 13},
{ "desc" : "Un pokémon" , "type": 13},
{ "desc" : "Un personnage de manga/anime" , "type": 13},
{ "desc" : "Un type d'anime" , "type": 13},
{ "desc" : "Un livre célèbre" , "type": 13},
{ "desc" : "Un auteur/une autrice" , "type": 13},
{ "desc" : "Un genre littéraire" , "type": 13},
{ "desc" : "Un magazine" , "type": 13},
{ "desc" : "Un journal" , "type": 13},
{ "desc" : "Un personnage de BD" , "type": 13},
{ "desc" : "Une émission de télévision" , "type": 13},
{ "desc" : "Un animateur/une animatrice TV" , "type": 13},
{ "desc" : "Un YouTubeur/une YouTubeuse" , "type": 13},
{ "desc" : "Un influenceur/une influenceuse" , "type": 13},
{ "desc" : "Un mème internet" , "type": 13},
{ "desc" : "Un réseau social" , "type": 13},
{ "desc" : "Un site web populaire" , "type": 13},
{ "desc" : "Une application mobile" , "type": 13},
{ "desc" : "Un podcast" , "type": 13},
{ "desc" : "Un festival" , "type": 13},
{ "desc" : "Un musée" , "type": 13},
{ "desc" : "Un sport olympique" , "type": 13},
{ "desc" : "Un sport d'hiver" , "type": 13},
{ "desc" : "Un sport nautique" , "type": 13},
{ "desc" : "Un sport extrême" , "type": 13},
{ "desc" : "Un sport collectif" , "type": 13},
{ "desc" : "Un sport individuel" , "type": 13},
{ "desc" : "Un footballeur/une footballeuse" , "type": 13},
{ "desc" : "Un basketteur/une basketteuse" , "type": 13},
{ "desc" : "Un tennisman/une tenniswoman" , "type": 13},
{ "desc" : "Un athlète olympique" , "type": 13},
{ "desc" : "Un équipement sportif" , "type": 13},
{ "desc" : "Une compétition sportive" , "type": 13},
{ "desc" : "Un club de football" , "type": 13},
{ "desc" : "Un mouvement de danse" , "type": 13},
{ "desc" : "Un jeu d'extérieur" , "type": 13},
{ "desc" : "Un hobby créatif" , "type": 13},
{ "desc" : "Un instrument de jardinage" , "type": 13},
{ "desc" : "Un équipement de camping" , "type": 13},
{ "desc" : "Un type de collection" , "type": 13},
{ "desc" : "Une activité de vacances" , "type": 13},
{ "desc" : "Un élément chimique" , "type": 13},
{ "desc" : "Un minéral" , "type": 13},
{ "desc" : "Un outil scientifique" , "type": 13},
{ "desc" : "Un appareil électronique" , "type": 13},
{ "desc" : "Un composant d'ordinateur" , "type": 13},
{ "desc" : "Un langage de programmation" , "type": 13},
{ "desc" : "Un système d'exploitation" , "type": 13},
{ "desc" : "Une marque technologique" , "type": 13},
{ "desc" : "Un dinosaure" , "type": 13},
{ "desc" : "Une partie du corps humain" , "type": 13},
{ "desc" : "Un organe" , "type": 13},
{ "desc" : "Un os" , "type": 13},
{ "desc" : "Un muscle" , "type": 13},
{ "desc" : "Une maladie" , "type": 13},
{ "desc" : "Un médicament" , "type": 13},
{ "desc" : "Une spécialité médicale" , "type": 13},
{ "desc" : "Un pionnier scientifique" , "type": 13},
{ "desc" : "Une découverte scientifique" , "type": 13},
{ "desc" : "Une théorie scientifique" , "type": 13},
{ "desc" : "Une invention du 20e siècle" , "type": 13},
{ "desc" : "Une marque de voiture" , "type": 13},
{ "desc" : "Un modèle de voiture" , "type": 13},
{ "desc" : "Une pièce automobile" , "type": 13},
{ "desc" : "Un type de moto" , "type": 13},
{ "desc" : "Un véhicule de construction" , "type": 13},
{ "desc" : "Un bateau" , "type": 13},
{ "desc" : "Un avion" , "type": 13},
{ "desc" : "Un train" , "type": 13},
{ "desc" : "Un moyen de transport urbain" , "type": 13},
{ "desc" : "Un véhicule militaire" , "type": 13},
{ "desc" : "Un véhicule spatial" , "type": 13},
{ "desc" : "Un outil de bricolage" , "type": 13},
{ "desc" : "Une machine industrielle" , "type": 13},
{ "desc" : "Un type de moteur" , "type": 13},
{ "desc" : "Un combustible" , "type": 13},
{ "desc" : "Un meuble" , "type": 13},
{ "desc" : "Un appareil électroménager" , "type": 13},
{ "desc" : "Un ustensile de cuisine" , "type": 13},
{ "desc" : "Un outil de jardinage" , "type": 13},
{ "desc" : "Un instrument d'écriture" , "type": 13},
{ "desc" : "Un vêtement" , "type": 13},
{ "desc" : "Un accessoire de mode" , "type": 13},
{ "desc" : "Un bijou" , "type": 13},
{ "desc" : "Un type de chaussure" , "type": 13},
{ "desc" : "Un chapeau ou couvre-chef" , "type": 13},
{ "desc" : "Un sac" , "type": 13},
{ "desc" : "Un tissu" , "type": 13},
{ "desc" : "Un matériau de construction" , "type": 13},
{ "desc" : "Un type de verre" , "type": 13},
{ "desc" : "Un type de plastique" , "type": 13},
{ "desc" : "Un métal" , "type": 13},
{ "desc" : "Un instrument de mesure" , "type": 13},
{ "desc" : "Un objet décoratif" , "type": 13},
{ "desc" : "Un objet antique" , "type": 13},
{ "desc" : "Un objet trouvé dans une salle de bain" , "type": 13},
{ "desc" : "Un objet trouvé dans une cuisine" , "type": 13},
{ "desc" : "Un objet trouvé dans un garage" , "type": 13},
{ "desc" : "Un objet trouvé dans un bureau" , "type": 13},
{ "desc" : "Un objet trouvé dans une chambre" , "type": 13},
{ "desc" : "Un objet scolaire" , "type": 13},
{ "desc" : "Un métier manuel" , "type": 13},
{ "desc" : "Un métier artistique" , "type": 13},
{ "desc" : "Un métier médical" , "type": 13},
{ "desc" : "Un métier scientifique" , "type": 13},
{ "desc" : "Un métier de la restauration" , "type": 13},
{ "desc" : "Un métier dans l'éducation" , "type": 13},
{ "desc" : "Un métier juridique" , "type": 13},
{ "desc" : "Un métier dans les médias" , "type": 13},
{ "desc" : "Un métier du bâtiment" , "type": 13},
{ "desc" : "Un métier de la mode" , "type": 13},
{ "desc" : "Un métier de l'informatique" , "type": 13},
{ "desc" : "Un métier du sport" , "type": 13},
{ "desc" : "Un métier du spectacle" , "type": 13},
{ "desc" : "Un métier d'autrefois" , "type": 13},
{ "desc" : "Un métier dangereux" , "type": 13},
{ "desc" : "Un métier rare" , "type": 13},
{ "desc" : "Un métier de nuit" , "type": 13},
{ "desc" : "Un métier saisonnier" , "type": 13},
{ "desc" : "Un métier bien payé" , "type": 13},
{ "desc" : "Un métier mal payé" , "type": 13},
{ "desc" : "Un personnage historique" , "type": 13},
{ "desc" : "Un monument célèbre" , "type": 13},
{ "desc" : "Un site archéologique" , "type": 13},
{ "desc" : "Une bataille" , "type": 13},
{ "desc" : "Une guerre" , "type": 13},
{ "desc" : "Une civilisation ancienne" , "type": 13},
{ "desc" : "Un empereur/une impératrice" , "type": 13},
{ "desc" : "Un roi/une reine" , "type": 13},
{ "desc" : "Un président/une présidente" , "type": 13},
{ "desc" : "Un dictateur" , "type": 13},
{ "desc" : "Un révolutionnaire" , "type": 13},
{ "desc" : "Un philosophe" , "type": 13},
{ "desc" : "Un explorateur" , "type": 13},
{ "desc" : "Un événement historique" , "type": 13},
{ "desc" : "Une invention ancienne" , "type": 13},
{ "desc" : "Une période historique" , "type": 13},
{ "desc" : "Un homme/une femme politique actuel(le)" , "type": 13},
{ "desc" : "Un mouvement social" , "type": 13},
{ "desc" : "Une organisation internationale" , "type": 13},
{ "desc" : "Une devise (monnaie)" , "type": 13},
{ "desc" : "Un trait de caractère positif" , "type": 13},
{ "desc" : "Un trait de caractère négatif" , "type": 13},
{ "desc" : "Une émotion" , "type": 13},
{ "desc" : "Un sentiment" , "type": 13},
{ "desc" : "Une couleur" , "type": 13},
{ "desc" : "Une forme géométrique" , "type": 13},
{ "desc" : "Une texture" , "type": 13},
{ "desc" : "Une odeur agréable" , "type": 13},
{ "desc" : "Une odeur désagréable" , "type": 13},
{ "desc" : "Une saveur" , "type": 13},
{ "desc" : "Un adjectif pour décrire le temps" , "type": 13},
{ "desc" : "Un adjectif pour décrire un paysage" , "type": 13},
{ "desc" : "Un adjectif pour décrire une personne" , "type": 13},
{ "desc" : "Un adjectif pour décrire un repas" , "type": 13},
{ "desc" : "Un adjectif pour décrire un film" , "type": 13},
{ "desc" : "Un adjectif pour décrire une musique" , "type": 13},
{ "desc" : "Un adjectif pour décrire un vêtement" , "type": 13},
{ "desc" : "Un adjectif pour décrire une maison" , "type": 13},
{ "desc" : "Un adjectif pour décrire une voiture" , "type": 13},
{ "desc" : "Un adjectif pour décrire un animal" , "type": 13},
{ "desc" : "Quelque chose qui fait du bruit" , "type": 13},
{ "desc" : "Quelque chose qui brille" , "type": 13},
{ "desc" : "Quelque chose qui coule" , "type": 13},
{ "desc" : "Quelque chose qui vole" , "type": 13},
{ "desc" : "Quelque chose qui pique" , "type": 13},
{ "desc" : "Quelque chose qui gratte" , "type": 13},
{ "desc" : "Quelque chose qui pue" , "type": 13},
{ "desc" : "Quelque chose de doux" , "type": 13},
{ "desc" : "Quelque chose de dur" , "type": 13},
{ "desc" : "Quelque chose de froid" , "type": 13},
{ "desc" : "Quelque chose de chaud" , "type": 13},
{ "desc" : "Quelque chose qu'on trouve à la plage" , "type": 13},
{ "desc" : "Quelque chose qu'on trouve en montagne" , "type": 13},
{ "desc" : "Quelque chose qu'on trouve dans une forêt" , "type": 13},
{ "desc" : "Quelque chose qu'on trouve dans le désert" , "type": 13},
{ "desc" : "Quelque chose qu'on trouve au pôle nord" , "type": 13},
{ "desc" : "Quelque chose qu'on trouve dans l'espace" , "type": 13},
{ "desc" : "Quelque chose qui se mange cru" , "type": 13},
{ "desc" : "Quelque chose qui se mange cuit" , "type": 13},
{ "desc" : "Quelque chose qu'on ne mange pas" , "type": 13},
{ "desc" : "Quelque chose qui fond dans la bouche" , "type": 13},
{ "desc" : "Quelque chose qui craque sous la dent" , "type": 13},
{ "desc" : "Quelque chose qui colle aux doigts" , "type": 13},
{ "desc" : "Quelque chose qui tache" , "type": 13},
{ "desc" : "Quelque chose qui se casse facilement" , "type": 13},
{ "desc" : "Quelque chose qu'on peut plier" , "type": 13},
{ "desc" : "Quelque chose qu'on peut étirer" , "type": 13},
{ "desc" : "Quelque chose qui flotte" , "type": 13},
{ "desc" : "Quelque chose qui coule" , "type": 13},
{ "desc" : "Quelque chose qui rebondit" , "type": 13},
{ "desc" : "Une raison d'être en retard" , "type": 13},
{ "desc" : "Une excuse pour ne pas aller travailler" , "type": 13},
{ "desc" : "Une raison de pleurer" , "type": 13},
{ "desc" : "Une raison de rire" , "type": 13},
{ "desc" : "Une raison de crier" , "type": 13},
{ "desc" : "Une raison d'avoir peur" , "type": 13},
{ "desc" : "Une raison d'être fier" , "type": 13},
{ "desc" : "Une raison d'être gêné" , "type": 13},
{ "desc" : "Une situation embarrassante" , "type": 13},
{ "desc" : "Une situation dangereuse" , "type": 13},
{ "desc" : "Une situation romantique" , "type": 13},
{ "desc" : "Une situation comique" , "type": 13},
{ "desc" : "Une célébration" , "type": 13},
{ "desc" : "Un type de fête" , "type": 13},
{ "desc" : "Un événement sportif" , "type": 13},
{ "desc" : "Un événement culturel" , "type": 13},
{ "desc" : "Un événement familial" , "type": 13},
{ "desc" : "Un événement scolaire" , "type": 13},
{ "desc" : "Un événement professionnel" , "type": 13},
{ "desc" : "Un désastre naturel" , "type": 13},
{ "desc" : "Un type de magasin" , "type": 13},
{ "desc" : "Un commerce alimentaire" , "type": 13},
{ "desc" : "Un lieu de divertissement" , "type": 13},
{ "desc" : "Un lieu culturel" , "type": 13},
{ "desc" : "Un lieu d'apprentissage" , "type": 13},
{ "desc" : "Un lieu religieux" , "type": 13},
{ "desc" : "Un lieu sportif" , "type": 13},
{ "desc" : "Un lieu touristique" , "type": 13},
{ "desc" : "Un lieu abandonné" , "type": 13},
{ "desc" : "Un lieu effrayant" , "type": 13},
{ "desc" : "Un lieu romantique" , "type": 13},
{ "desc" : "Un lieu bruyant" , "type": 13},
{ "desc" : "Un lieu calme" , "type": 13},
{ "desc" : "Un type de restaurant" , "type": 13},
{ "desc" : "Un type d'hôtel" , "type": 13},
{ "desc" : "Un type de bar" , "type": 13},
{ "desc" : "Un type de parc" , "type": 13},
{ "desc" : "Un lieu où l'on ne veut pas être coincé" , "type": 13},
{ "desc" : "Un lieu où l'on aimerait passer ses vacances" , "type": 13},
{ "desc" : "Un lieu où l'on ne va jamais seul" , "type": 13},
{ "desc" : "Un surnom ridicule" , "type": 13},
{ "desc" : "Une façon étrange de mourir" , "type": 13},
{ "desc" : "Un mauvais cadeau d'anniversaire" , "type": 13},
{ "desc" : "Un sujet de conversation à éviter en famille" , "type": 13},
{ "desc" : "Une chose à ne jamais dire à un premier rendez-vous" , "type": 13},
{ "desc" : "Une chose à ne jamais dire à son patron" , "type": 13},
{ "desc" : "Une chose à ne jamais dire à un policier" , "type": 13},
{ "desc" : "Un mensonge courant" , "type": 13},
{ "desc" : "Une superstition" , "type": 13},
{ "desc" : "Une phobie réelle" , "type": 13},
{ "desc" : "Une phobie inventée" , "type": 13},
{ "desc" : "Un titre de film qui n'existe pas" , "type": 13},
{ "desc" : "Un titre de chanson inventé" , "type": 13},
{ "desc" : "Un nom de groupe de musique inventé" , "type": 13},
{ "desc" : "Un slogan publicitaire inventé" , "type": 13},
{ "desc" : "Une combinaison alimentaire dégoûtante" , "type": 13},
{ "desc" : "Une mode vestimentaire ridicule" , "type": 13},
{ "desc" : "Un moyen de transport improbable" , "type": 13},
{ "desc" : "Un sport imaginaire" , "type": 13},
{ "desc" : "Un super-pouvoir inutile" , "type": 13},
{ "desc" : "Un symptôme" , "type": 13},
{ "desc" : "Une maladie" , "type": 13},
{ "desc" : "Un traitement médical" , "type": 13},
{ "desc" : "Un médicament" , "type": 13},
{ "desc" : "Un problème de santé embarrassant" , "type": 13},
{ "desc" : "Une blessure commune" , "type": 13},
{ "desc" : "Une partie du corps qu'on peut se casser" , "type": 13},
{ "desc" : "Un problème dentaire" , "type": 13},
{ "desc" : "Un problème de peau" , "type": 13},
{ "desc" : "Un problème digestif" , "type": 13},
{ "desc" : "Une allergie" , "type": 13},
{ "desc" : "Un remède de grand-mère" , "type": 13},
{ "desc" : "Un type de régime" , "type": 13},
{ "desc" : "Un exercice physique" , "type": 13},
{ "desc" : "Une position de yoga" , "type": 13},
{ "desc" : "Un type de massage" , "type": 13},
{ "desc" : "Un symptôme de grossesse" , "type": 13},
{ "desc" : "Une raison d'aller chez le médecin" , "type": 13},
{ "desc" : "Une raison d'aller à la pharmacie" , "type": 13},
{ "desc" : "Une raison d'aller aux urgences" , "type": 13},
{ "desc" : "Une technologie du futur" , "type": 13},
{ "desc" : "Un gadget high-tech" , "type": 13},
{ "desc" : "Un métier qui n'existe pas encore" , "type": 13},
{ "desc" : "Une invention futuriste" , "type": 13},
{ "desc" : "Un mode de transport futuriste" , "type": 13},
{ "desc" : "Un aliment du futur" , "type": 13},
{ "desc" : "Un robot domestique" , "type": 13},
{ "desc" : "Une fonctionnalité de smartphone" , "type": 13},
{ "desc" : "Une intelligence artificielle" , "type": 13},
{ "desc" : "Une application mobile utile" , "type": 13},
{ "desc" : "Une expression française" , "type": 13},
{ "desc" : "Un proverbe" , "type": 13},
{ "desc" : "Une citation célèbre" , "type": 13},
{ "desc" : "Un mot d'argot" , "type": 13},
{ "desc" : "Un mot vieilli" , "type": 13},
{ "desc" : "Un mot étranger utilisé en français" , "type": 13},
{ "desc" : "Un mot qui n'existe pas mais devrait exister" , "type": 13},
{ "desc" : "Un mot difficile à prononcer" , "type": 13},
{ "desc" : "Un euphémisme" , "type": 13},
{ "desc" : "Une insulte polie" , "type": 13},
{ "desc" : "Un monstre mythologique" , "type": 13},
{ "desc" : "Une créature fantastique" , "type": 13},
{ "desc" : "Un personnage de conte de fées" , "type": 13},
{ "desc" : "Un type de fantôme" , "type": 13},
{ "desc" : "Un type de vampire" , "type": 13},
{ "desc" : "Un type de loup-garou" , "type": 13},
{ "desc" : "Un type d'extraterrestre" , "type": 13},
{ "desc" : "Un type de zombie" , "type": 13},
{ "desc" : "Un type de robot" , "type": 13},
{ "desc" : "Un animal imaginaire" , "type": 13},
{ "desc" : "Une arme à feu" , "type": 13},
{ "desc" : "Une arme blanche" , "type": 13},
{ "desc" : "Une arme médiévale" , "type": 13},
{ "desc" : "Une arme improvisée" , "type": 13},
{ "desc" : "Une arme dans un jeu vidéo" , "type": 13},
{ "desc" : "Une arme futuriste" , "type": 13},
{ "desc" : "Une arme d'un super-héros" , "type": 13},
{ "desc" : "Un piège" , "type": 13},
{ "desc" : "Un explosif" , "type": 13},
{ "desc" : "Un poison" , "type": 13},
{ "desc" : "Un pouvoir magique" , "type": 13},
{ "desc" : "Un sortilège" , "type": 13},
{ "desc" : "Un objet magique" , "type": 13},
{ "desc" : "Une créature magique" , "type": 13},
{ "desc" : "Un type de sorcier" , "type": 13},
{ "desc" : "Un type de guerrier" , "type": 13},
{ "desc" : "Un type de vaisseau spatial" , "type": 13},
{ "desc" : "Un métier dans un univers fantastique" , "type": 13},
{ "desc" : "Un lieu dans un univers de science-fiction" , "type": 13},
{ "desc" : "Une planète fictive" , "type": 13},
{ "desc" : "Une race de chien" , "type": 13},
{ "desc" : "Une race de chat" , "type": 13},
{ "desc" : "Un type de poisson d'aquarium" , "type": 13},
{ "desc" : "Un reptile domestique" , "type": 13},
{ "desc" : "Un oiseau de compagnie" , "type": 13},
{ "desc" : "Un insecte utile" , "type": 13},
{ "desc" : "Un insecte nuisible" , "type": 13},
{ "desc" : "Un animal de la ferme" , "type": 13},
{ "desc" : "Un légume de saison" , "type": 13},
{ "desc" : "Un fruit exotique" , "type": 13},
{ "desc" : "Une fleur sauvage" , "type": 13},
{ "desc" : "Un arbre fruitier" , "type": 13},
{ "desc" : "Un champignon comestible" , "type": 13},
{ "desc" : "Un champignon toxique" , "type": 13},
{ "desc" : "Une plante médicinale" , "type": 13},
{ "desc" : "Une plante carnivore" , "type": 13},
{ "desc" : "Un poisson comestible" , "type": 13},
{ "desc" : "Un fruit de mer" , "type": 13},
{ "desc" : "Un coquillage" , "type": 13},
{ "desc" : "Un fossile" , "type": 13},
{ "desc" : "Un type de chapeau" , "type": 13},
{ "desc" : "Un bijou précieux" , "type": 13},
{ "desc" : "Un accessoire de mode vintage" , "type": 13},
{ "desc" : "Un style vestimentaire" , "type": 13},
{ "desc" : "Un motif de tissu" , "type": 13},
{ "desc" : "Un parfum" , "type": 13},
{ "desc" : "Un ingrédient cosmétique" , "type": 13},
{ "desc" : "Un produit de beauté" , "type": 13},
{ "desc" : "Un outil de maquillage" , "type": 13},
{ "desc" : "Un style de coiffure" , "type": 13},
{ "desc" : "Un type de barbe" , "type": 13},
{ "desc" : "Un style de moustache" , "type": 13},
{ "desc" : "Un type de lunettes" , "type": 13},
{ "desc" : "Un type de sac" , "type": 13},
{ "desc" : "Un type de chaussures" , "type": 13},
{ "desc" : "Un type de montre" , "type": 13},
{ "desc" : "Un type de gant" , "type": 13},
{ "desc" : "Un type d'écharpe" , "type": 13},
{ "desc" : "Un accessoire de plage" , "type": 13},
{ "desc" : "Un accessoire de sport" , "type": 13},
{ "desc" : "Un cadeau de Noël" , "type": 13},
{ "desc" : "Un costume d'Halloween" , "type": 13},
{ "desc" : "Un plat de Thanksgiving" , "type": 13},
{ "desc" : "Un accessoire de fête du Nouvel An" , "type": 13},
{ "desc" : "Un cadeau pour la fête des mères" , "type": 13},
{ "desc" : "Un cadeau pour la fête des pères" , "type": 13},
{ "desc" : "Un cadeau de naissance" , "type": 13},
{ "desc" : "Un cadeau de mariage" , "type": 13},
{ "desc" : "Un cadeau d'anniversaire" , "type": 13},
{ "desc" : "Un cadeau de Saint-Valentin" , "type": 13},
{ "desc" : "Une activité estivale" , "type": 13},
{ "desc" : "Une activité hivernale" , "type": 13},
{ "desc" : "Une activité automnale" , "type": 13},
{ "desc" : "Une activité printanière" , "type": 13},
{ "desc" : "Une tradition de Noël" , "type": 13},
{ "desc" : "Une tradition de Pâques" , "type": 13},
{ "desc" : "Une décoration festive" , "type": 13},
{ "desc" : "Un type de feu d'artifice" , "type": 13},
{ "desc" : "Un jeu de plein air" , "type": 13},
{ "desc" : "Un type de barbecue" , "type": 13},
{ "desc" : "Quelque chose qu'on ne devrait jamais goûter" , "type": 13},
{ "desc" : "Quelque chose qu'on ne prête pas" , "type": 13},
{ "desc" : "Un endroit où cacher quelque chose" , "type": 13},
{ "desc" : "Une chose qu'on fait quand personne ne regarde" , "type": 13},
{ "desc" : "Une chose qu'on fait dans la salle de bain" , "type": 13},
{ "desc" : "Une chose qu'on ramasse sur la plage" , "type": 13},
{ "desc" : "Une chose qu'on trouve sous un lit" , "type": 13},
{ "desc" : "Une chose qu'on trouve dans un sac à main" , "type": 13},
{ "desc" : "Une chose qu'on regrette d'avoir achetée" , "type": 13},
{ "desc" : "Une chose qu'on oublie souvent" , "type": 13},
{ "desc" : "Une chose qu'on collectionne" , "type": 13},
{ "desc" : "Une chose qu'on n'avoue pas posséder" , "type": 13},
{ "desc" : "Une chose qu'on garde \"au cas où\"" , "type": 13},
{ "desc" : "Une chose qui donne faim" , "type": 13},
{ "desc" : "Une chose qui donne soif" , "type": 13},
{ "desc" : "Une chose qui fait peur aux enfants" , "type": 13},
{ "desc" : "Une chose qui fait rire les enfants" , "type": 13},
{ "desc" : "Une chose qui énerve les parents" , "type": 13},
{ "desc" : "Une chose qui rend heureux" , "type": 13},
{ "desc" : "Une chose qui rend triste" , "type": 13},
{ "desc" : "Un hashtag populaire" , "type": 13},
{ "desc" : "Une tendance TikTok" , "type": 13},
{ "desc" : "Un type de selfie" , "type": 13},
{ "desc" : "Un filtre photo" , "type": 13},
{ "desc" : "Un type de mème" , "type": 13},
{ "desc" : "Un challenge viral" , "type": 13},
{ "desc" : "Une danse tendance" , "type": 13},
{ "desc" : "Un type de podcast" , "type": 13},
{ "desc" : "Un format de vidéo YouTube" , "type": 13},
{ "desc" : "Un sujet de débat sur les réseaux sociaux" , "type": 13},
{ "desc" : "Une célébrité controversée" , "type": 13},
{ "desc" : "Un événement virtuel" , "type": 13},
{ "desc" : "Un type de streaming" , "type": 13},
{ "desc" : "Un type d'influenceur" , "type": 13},
{ "desc" : "Un acronyme du web" , "type": 13},
{ "desc" : "Un emoji fréquemment utilisé" , "type": 13},
{ "desc" : "Un type de contenu sponsorisé" , "type": 13},
{ "desc" : "Une façon de devenir viral" , "type": 13},
{ "desc" : "Une raison de \"cancel\" quelqu'un" , "type": 13},
{ "desc" : "Une théorie du complot" , "type": 13},
{ "desc" : "Une chose qu'on ne devrait jamais dire à ses beaux-parents" , "type": 13},
{ "desc" : "Un cadeau qui ferait fuir votre rencard" , "type": 13},
{ "desc" : "Un surnom inapproprié pour un enseignant" , "type": 13},
{ "desc" : "Une chose à ne jamais crier dans un avion" , "type": 13},
{ "desc" : "Une chose à ne jamais dire à un coiffeur pendant qu'il coupe vos cheveux" , "type": 13},
{ "desc" : "Un endroit où il est gênant d'être reconnu" , "type": 13},
{ "desc" : "Une chanson embarrassante à chanter sous la douche" , "type": 13},
{ "desc" : "Un métier inventé qui sonne réel" , "type": 13},
{ "desc" : "Une chose que les extraterrestres trouveraient bizarre chez les humains" , "type": 13},
{ "desc" : "Une chose à ne pas dire lors d'un entretien d'embauche" , "type": 13},
{ "desc" : "Un nom ridicule pour un animal de compagnie" , "type": 13},
{ "desc" : "Une raison improbable d'être en retard au travail" , "type": 13},
{ "desc" : "Un plat qui ne devrait jamais exister" , "type": 13},
{ "desc" : "Un sport qui n'existe pas mais qui devrait" , "type": 13},
{ "desc" : "Une façon étrange de saluer quelqu'un" , "type": 13},
{ "desc" : "Une façon inhabituelle de rompre avec quelqu'un" , "type": 13},
{ "desc" : "Une chose à ne pas faire en public" , "type": 13},
{ "desc" : "Un mensonge évident que tout le monde raconte" , "type": 13},
{ "desc" : "Une chose à ne pas goûter deux fois" , "type": 13},
{ "desc" : "Un endroit où il ne faut pas s'endormir" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un policier qui vous arrête" , "type": 13},
{ "desc" : "Un sujet de conversation pour tuer l'ambiance" , "type": 13},
{ "desc" : "Un signe que votre journée va être terrible" , "type": 13},
{ "desc" : "Une chose qu'on ne devrait jamais googler" , "type": 13},
{ "desc" : "Un mauvais nom pour un restaurant" , "type": 13},
{ "desc" : "Un super-pouvoir inutile" , "type": 13},
{ "desc" : "Une chose à ne pas faire dans un ascenseur" , "type": 13},
{ "desc" : "Une raison étrange de rompre une amitié" , "type": 13},
{ "desc" : "Un message qu'on ne veut pas recevoir à 3h du matin" , "type": 13},
{ "desc" : "Une chose à ne pas dire à haute voix dans une bibliothèque" , "type": 13},
{ "desc" : "Une activité qui paraît suspecte la nuit" , "type": 13},
{ "desc" : "Un cadeau inapproprié pour une grand-mère" , "type": 13},
{ "desc" : "Une chose qu'on regrette d'avoir mise sur les réseaux sociaux" , "type": 13},
{ "desc" : "Un nom terrible pour un enfant" , "type": 13},
{ "desc" : "Un objet qu'on ne veut pas trouver dans son lit" , "type": 13},
{ "desc" : "Une chose que personne n'admet faire" , "type": 13},
{ "desc" : "Un moyen inhabituel de séduire quelqu'un" , "type": 13},
{ "desc" : "Une chose qu'on ne devrait jamais bricoler soi-même" , "type": 13},
{ "desc" : "Un mauvais conseil à donner à un adolescent" , "type": 13},
{ "desc" : "Une chose à ne pas dire lors d'un mariage" , "type": 13},
{ "desc" : "Un lieu improbable pour un premier rendez-vous" , "type": 13},
{ "desc" : "Une chose à ne pas dire lors d'un enterrement" , "type": 13},
{ "desc" : "Un aliment qui ne devrait jamais être sur une pizza" , "type": 13},
{ "desc" : "Une chose qu'on dit en dormant" , "type": 13},
{ "desc" : "Un accessoire de mode ridicule" , "type": 13},
{ "desc" : "Un mot inventé qui semble réel" , "type": 13},
{ "desc" : "Une phobie ridicule mais plausible" , "type": 13},
{ "desc" : "Une raison absurde de se disputer en couple" , "type": 13},
{ "desc" : "Un talent inutile à mettre sur un CV" , "type": 13},
{ "desc" : "Une chose à ne pas faire lors d'un dîner chic" , "type": 13},
{ "desc" : "Une chose embarrassante à acheter" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un médecin" , "type": 13},
{ "desc" : "Une chose qu'on ne veut pas entendre dire par un pilote d'avion" , "type": 13},
{ "desc" : "Un signe que vous êtes devenu trop vieux" , "type": 13},
{ "desc" : "Une question à ne pas poser à un premier rendez-vous" , "type": 13},
{ "desc" : "Une chose à ne pas faire lors d'un examen" , "type": 13},
{ "desc" : "Un titre de film qui semble réel mais n'existe pas" , "type": 13},
{ "desc" : "Un nom ridicule pour un groupe de musique" , "type": 13},
{ "desc" : "Une chose à ne pas dire à son professeur" , "type": 13},
{ "desc" : "Une chose que vous ne voulez pas que votre téléphone fasse en public" , "type": 13},
{ "desc" : "Un mauvais prétexte pour appeler son ex" , "type": 13},
{ "desc" : "Une chose à ne pas mettre dans un micro-ondes" , "type": 13},
{ "desc" : "Un conseil de grand-mère douteux" , "type": 13},
{ "desc" : "Une raison étrange d'être célèbre" , "type": 13},
{ "desc" : "Une chose qu'on ne devrait jamais acheter d'occasion" , "type": 13},
{ "desc" : "Un animal qui serait terrible comme animal de compagnie" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un entretien d'embauche" , "type": 13},
{ "desc" : "Un cadeau de mariage inapproprié" , "type": 13},
{ "desc" : "Une chose à ne pas dire à une femme enceinte" , "type": 13},
{ "desc" : "Un mauvais moment pour éternuer" , "type": 13},
{ "desc" : "Une chose à ne pas porter à un entretien d'embauche" , "type": 13},
{ "desc" : "Un lieu où il est gênant de croiser son patron" , "type": 13},
{ "desc" : "Une chose à ne pas laisser dans sa voiture en été" , "type": 13},
{ "desc" : "Un endroit où il vaut mieux ne pas oublier son portefeuille" , "type": 13},
{ "desc" : "Une chose à ne pas dire lors d'une rupture" , "type": 13},
{ "desc" : "Un nom ridicule pour un sandwich" , "type": 13},
{ "desc" : "Une chose qu'on fait quand on est seul à la maison" , "type": 13},
{ "desc" : "Un mauvais nom pour un parfum" , "type": 13},
{ "desc" : "Une chose à ne pas crier en pleine rue" , "type": 13},
{ "desc" : "Un mauvais nom pour une équipe sportive" , "type": 13},
{ "desc" : "Une chose qu'on ne veut pas trouver dans sa nourriture" , "type": 13},
{ "desc" : "Un mauvais sujet de conversation pour un premier dîner avec les beaux-parents" , "type": 13},
{ "desc" : "Une chose qu'on ne devrait jamais dire à un enfant" , "type": 13},
{ "desc" : "Un objet qu'on ne veut pas voir dans les mains d'un enfant" , "type": 13},
{ "desc" : "Un passe-temps suspect" , "type": 13},
{ "desc" : "Une chose à ne pas faire sur son lieu de travail" , "type": 13},
{ "desc" : "Un mauvais slogan pour une campagne politique" , "type": 13},
{ "desc" : "Une chose à ne pas dire à son dentiste" , "type": 13},
{ "desc" : "Un mauvais nom pour un médicament" , "type": 13},
{ "desc" : "Une habitude inavouable" , "type": 13},
{ "desc" : "Une chose qu'on ne devrait jamais emprunter" , "type": 13},
{ "desc" : "Une réponse inappropriée à \"Comment vas-tu ?\"" , "type": 13},
{ "desc" : "Un mensonge que tout le monde dit" , "type": 13},
{ "desc" : "Un mauvais nom pour un salon de coiffure" , "type": 13},
{ "desc" : "Une chose à ne pas dire à une personne qui vient de se faire larguer" , "type": 13},
{ "desc" : "Un métier qui n'existera plus dans 100 ans" , "type": 13},
{ "desc" : "Un objet qu'on ne devrait jamais customiser" , "type": 13},
{ "desc" : "Une chose qui n'a pas sa place dans un musée" , "type": 13},
{ "desc" : "Un mauvais surnom pour son partenaire" , "type": 13},
{ "desc" : "Une chose à ne pas dire à ses parents" , "type": 13},
{ "desc" : "Un mauvais nom pour une application de rencontres" , "type": 13},
{ "desc" : "Une chose à ne pas faire à un mariage" , "type": 13},
{ "desc" : "Une chose à ne pas chercher sur Internet" , "type": 13},
{ "desc" : "Un mauvais moment pour faire une blague" , "type": 13},
{ "desc" : "Une chose qu'on ne veut pas entendre d'un chirurgien avant une opération" , "type": 13},
{ "desc" : "Un mauvais alibi" , "type": 13},
{ "desc" : "Une chose à ne pas faire dans une piscine publique" , "type": 13},
{ "desc" : "Un cadeau inapproprié pour un enfant" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un discours" , "type": 13},
{ "desc" : "Un mauvais nom pour un bar" , "type": 13},
{ "desc" : "Une chose à ne pas dire lors d'un dîner en famille" , "type": 13},
{ "desc" : "Un mauvais déguisement pour Halloween" , "type": 13},
{ "desc" : "Une façon inhabituelle de quitter un emploi" , "type": 13},
{ "desc" : "Un objet inutile à emporter en vacances" , "type": 13},
{ "desc" : "Un mauvais moment pour faire une demande en mariage" , "type": 13},
{ "desc" : "Une chose qu'on ne veut pas entendre au milieu de la nuit" , "type": 13},
{ "desc" : "Un mauvais thème pour une fête d'anniversaire" , "type": 13},
{ "desc" : "Un endroit où il vaut mieux ne pas tomber en panne" , "type": 13},
{ "desc" : "Un mauvais nom pour un jouet pour enfants" , "type": 13},
{ "desc" : "Une chose à ne pas dire lors d'une réunion de travail" , "type": 13},
{ "desc" : "Un signe que votre ami est peut-être un extraterrestre" , "type": 13},
{ "desc" : "Une chose à ne pas faire lors d'une photo de groupe" , "type": 13},
{ "desc" : "Un mauvais nom pour une école" , "type": 13},
{ "desc" : "Une chose à ne pas avouer à ses parents" , "type": 13},
{ "desc" : "Un objet qu'on ne devrait jamais prêter" , "type": 13},
{ "desc" : "Une chose à ne pas faire lors d'un safari" , "type": 13},
{ "desc" : "Un mauvais cadeau pour la Saint-Valentin" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un officier de police" , "type": 13},
{ "desc" : "Un mauvais moment pour avoir le hoquet" , "type": 13},
{ "desc" : "Une chose à ne pas faire lors d'une visite chez le vétérinaire" , "type": 13},
{ "desc" : "Un produit qui n'existera jamais" , "type": 13},
{ "desc" : "Une chose à ne pas demander à un serveur" , "type": 13},
{ "desc" : "Une façon inhabituelle de célébrer son anniversaire" , "type": 13},
{ "desc" : "Un mauvais nom pour une compagnie aérienne" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un tatoueur" , "type": 13},
{ "desc" : "Un mauvais nom pour un hôtel" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un concert" , "type": 13},
{ "desc" : "Un mauvais nom pour un plat cuisiné" , "type": 13},
{ "desc" : "Une chose qu'on ne devrait jamais publier sur les réseaux sociaux" , "type": 13},
{ "desc" : "Un mauvais moment pour un appel vidéo" , "type": 13},
{ "desc" : "Une excuse bizarre pour refuser une invitation" , "type": 13},
{ "desc" : "Un mauvais nom pour un superhéros" , "type": 13},
{ "desc" : "Une chose à ne pas dire pendant une minute de silence" , "type": 13},
{ "desc" : "Un mauvais endroit pour faire une sieste" , "type": 13},
{ "desc" : "Une chose qu'on ne devrait jamais avouer à ses collègues" , "type": 13},
{ "desc" : "Un mauvais nom pour un robot domestique" , "type": 13},
{ "desc" : "Une chose à ne pas faire dans un magasin" , "type": 13},
{ "desc" : "Un mauvais nom pour un spa" , "type": 13},
{ "desc" : "Une chose à ne pas dire pendant une cérémonie religieuse" , "type": 13},
{ "desc" : "Un mauvais moment pour que votre téléphone sonne" , "type": 13},
{ "desc" : "Une chose à ne pas mettre dans une valise pour l'avion" , "type": 13},
{ "desc" : "Un mauvais nom pour un hamster" , "type": 13},
{ "desc" : "Une chose à ne pas dire pendant une visite médicale" , "type": 13},
{ "desc" : "Un mauvais endroit pour perdre ses clés" , "type": 13},
{ "desc" : "Une chose qu'on ne devrait jamais mélanger" , "type": 13},
{ "desc" : "Un mauvais mot de passe" , "type": 13},
{ "desc" : "Une chose à ne pas faire lors d'une randonnée" , "type": 13},
{ "desc" : "Un mauvais nom pour un parfum" , "type": 13},
{ "desc" : "Une chose à ne pas dire à sa belle-mère" , "type": 13},
{ "desc" : "Un mauvais lieu pour prendre un selfie" , "type": 13},
{ "desc" : "Une chose qu'on ne devrait jamais manger avant un rendez-vous" , "type": 13},
{ "desc" : "Un mauvais nom pour une entreprise de pompes funèbres" , "type": 13},
{ "desc" : "Une chose à ne pas faire dans un musée" , "type": 13},
{ "desc" : "Un mauvais slogan pour une campagne de sécurité routière" , "type": 13},
{ "desc" : "Une chose à ne pas dire à son patron" , "type": 13},
{ "desc" : "Un mauvais nom pour un groupe de rock" , "type": 13},
{ "desc" : "Une chose à ne pas faire dans une librairie" , "type": 13},
{ "desc" : "Un mauvais nom pour un produit de nettoyage" , "type": 13},
{ "desc" : "Une chose qu'on ne devrait jamais faire au volant" , "type": 13},
{ "desc" : "Un mauvais costume pour une fête d'entreprise" , "type": 13},
{ "desc" : "Une chose à ne pas demander à un grand-parent" , "type": 13},
{ "desc" : "Un mauvais nom pour un site de rencontres" , "type": 13},
{ "desc" : "Une chose qu'on ne devrait jamais frire" , "type": 13},
{ "desc" : "Un mauvais cadeau d'anniversaire pour un enfant" , "type": 13},
{ "desc" : "Une chose à ne pas dire lors d'un cours de yoga" , "type": 13},
{ "desc" : "Un mauvais nom pour un chat" , "type": 13},
{ "desc" : "Une chose à ne pas faire lors d'une réunion familiale" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de vêtements" , "type": 13},
{ "desc" : "Une chose à ne pas faire dans un avion" , "type": 13},
{ "desc" : "Un mauvais slogan pour une crèche" , "type": 13},
{ "desc" : "Une chose à ne pas dire lors d'une conférence" , "type": 13},
{ "desc" : "Un mauvais nom pour un cheval" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un film au cinéma" , "type": 13},
{ "desc" : "Un mauvais slogan pour un dentiste" , "type": 13},
{ "desc" : "Une chose à ne pas dire à quelqu'un qui a un rhume" , "type": 13},
{ "desc" : "Un mauvais nom pour une équipe e-sport" , "type": 13},
{ "desc" : "Une chose à ne pas faire lors d'un cours de cuisine" , "type": 13},
{ "desc" : "Un mauvais nom pour un groupe de K-pop" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un agent de sécurité" , "type": 13},
{ "desc" : "Un mauvais moment pour avoir une coupure de courant" , "type": 13},
{ "desc" : "Une chose qu'on ne devrait jamais acheter en ligne" , "type": 13},
{ "desc" : "Un mauvais nom pour une garderie" , "type": 13},
{ "desc" : "Une chose à ne pas faire dans un restaurant chic" , "type": 13},
{ "desc" : "Un mauvais slogan pour une maison de retraite" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un bibliothécaire" , "type": 13},
{ "desc" : "Un mauvais nom pour un club de lecture" , "type": 13},
{ "desc" : "Une chose à ne pas faire lors d'une visite chez le coiffeur" , "type": 13},
{ "desc" : "Un mauvais thème pour une fête d'entreprise" , "type": 13},
{ "desc" : "Une chose à ne pas dire à son ex pendant une rencontre fortuite" , "type": 13},
{ "desc" : "Un mauvais nom pour un parc d'attractions" , "type": 13},
{ "desc" : "Une chose à ne pas faire lors d'un karaoké" , "type": 13},
{ "desc" : "Un mauvais slogan pour une banque" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un arbitre" , "type": 13},
{ "desc" : "Un mauvais nom pour un groupe de hip-hop" , "type": 13},
{ "desc" : "Une chose à ne pas faire dans un ascenseur" , "type": 13},
{ "desc" : "Un mauvais slogan pour un hôpital" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un serveur" , "type": 13},
{ "desc" : "Un mauvais nom pour un festival" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un spectacle" , "type": 13},
{ "desc" : "Un mauvais slogan pour une compagnie d'assurance" , "type": 13},
{ "desc" : "Une chose à ne pas dire à son voisin" , "type": 13},
{ "desc" : "Un mauvais nom pour un jeu vidéo" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une présentation" , "type": 13},
{ "desc" : "Un mauvais slogan pour une école de conduite" , "type": 13},
{ "desc" : "Une chose à ne pas dire dans un aéroport" , "type": 13},
{ "desc" : "Un mauvais nom pour une salle de sport" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un enterrement" , "type": 13},
{ "desc" : "Un mauvais slogan pour un zoo" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un vendeur" , "type": 13},
{ "desc" : "Un mauvais nom pour une boulangerie" , "type": 13},
{ "desc" : "Une chose à ne pas faire lors d'un premier jour de travail" , "type": 13},
{ "desc" : "Un mauvais slogan pour une pharmacie" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un chauffeur de taxi" , "type": 13},
{ "desc" : "Un mauvais nom pour une application mobile" , "type": 13},
{ "desc" : "Une chose à ne pas faire lors d'une visite chez le dentiste" , "type": 13},
{ "desc" : "Un mauvais slogan pour un opticien" , "type": 13},
{ "desc" : "Une chose à ne pas dire à quelqu'un qui fait un régime" , "type": 13},
{ "desc" : "Un mauvais nom pour un groupe de musique classique" , "type": 13},
{ "desc" : "Une chose à ne pas faire lors d'une pause café au travail" , "type": 13},
{ "desc" : "Un mauvais slogan pour un service de babysitting" , "type": 13},
{ "desc" : "Une chose à ne pas dire durant une partie de cartes" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de chaussures" , "type": 13},
{ "desc" : "Une chose à ne pas faire lors d'une conférence de presse" , "type": 13},
{ "desc" : "Un mauvais slogan pour une agence de voyage" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un photographe" , "type": 13},
{ "desc" : "Un mauvais nom pour une ligne de maquillage" , "type": 13},
{ "desc" : "Une chose à ne pas faire lors d'un cours de danse" , "type": 13},
{ "desc" : "Un mauvais slogan pour un service de livraison" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un tatoueur" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de céréales" , "type": 13},
{ "desc" : "Une chose à ne pas faire lors d'une audition" , "type": 13},
{ "desc" : "Un mauvais slogan pour une auto-école" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un plombier" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de yaourt" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un rendez-vous chez le médecin" , "type": 13},
{ "desc" : "Un mauvais slogan pour un salon de beauté" , "type": 13},
{ "desc" : "Une chose qu'on ne devrait jamais faire à une fête surprise" , "type": 13},
{ "desc" : "Un mauvais nom pour une chaîne de fast-food" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une visite d'appartement" , "type": 13},
{ "desc" : "Un mauvais slogan pour un cabinet d'avocats" , "type": 13},
{ "desc" : "Une chose à ne pas dire à quelqu'un qui vient de perdre son travail" , "type": 13},
{ "desc" : "Un mauvais nom pour un centre commercial" , "type": 13},
{ "desc" : "Une chose à ne pas faire lors d'un blind date" , "type": 13},
{ "desc" : "Un mauvais slogan pour un fleuriste" , "type": 13},
{ "desc" : "Une chose à ne pas dire à quelqu'un qui vient de se couper les cheveux" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de parfum" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un cours de peinture" , "type": 13},
{ "desc" : "Un mauvais slogan pour une entreprise de déménagement" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un prof de sport" , "type": 13},
{ "desc" : "Un mauvais nom pour une chaîne d'hôtels" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une réunion en ligne" , "type": 13},
{ "desc" : "Un mauvais slogan pour une animalerie" , "type": 13},
{ "desc" : "Une chose à ne pas dire à quelqu'un qui est malade" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de jouets" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une cérémonie de remise de diplômes" , "type": 13},
{ "desc" : "Un mauvais slogan pour une agence immobilière" , "type": 13},
{ "desc" : "Une chose à ne pas dire à quelqu'un qui vient d'avoir un bébé" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de voitures" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une leçon de conduite" , "type": 13},
{ "desc" : "Un mauvais slogan pour une compagnie d'électricité" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un jardinier" , "type": 13},
{ "desc" : "Un mauvais nom pour une boîte de nuit" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un concert classique" , "type": 13},
{ "desc" : "Un mauvais slogan pour une entreprise de plomberie" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un DJ" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de montres" , "type": 13},
{ "desc" : "Une chose à ne pas faire lors d'un spectacle de magie" , "type": 13},
{ "desc" : "Un mauvais slogan pour un service de rencontres" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un électricien" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de chips" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un discours de mariage" , "type": 13},
{ "desc" : "Un mauvais slogan pour une agence funéraire" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un cuisinier" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de meubles" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un test de QI" , "type": 13},
{ "desc" : "Un mauvais slogan pour une entreprise de sécurité" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un astronaute" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de boissons énergisantes" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un cours de méditation" , "type": 13},
{ "desc" : "Un mauvais slogan pour une clinique vétérinaire" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un agent immobilier" , "type": 13},
{ "desc" : "Un mauvais nom pour un fitness tracker" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une visite chez le gynécologue" , "type": 13},
{ "desc" : "Un mauvais slogan pour une entreprise de nettoyage" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un psychologue" , "type": 13},
{ "desc" : "Un mauvais nom pour une chaîne de cafés" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un speed dating" , "type": 13},
{ "desc" : "Un mauvais slogan pour une agence de recrutement" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un prêtre" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de literie" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une séance de spiritisme" , "type": 13},
{ "desc" : "Un mauvais slogan pour une entreprise de pompes funèbres" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un pilote" , "type": 13},
{ "desc" : "Un mauvais nom pour une application de fitness" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un vernissage" , "type": 13},
{ "desc" : "Un mauvais slogan pour une clinique dentaire" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un tatoueur juste avant qu'il commence" , "type": 13},
{ "desc" : "Un mauvais nom pour une émission de télé-réalité" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un enterrement de vie de garçon/jeune fille" , "type": 13},
{ "desc" : "Un mauvais slogan pour une ligne aérienne" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un astrologue" , "type": 13},
{ "desc" : "Un mauvais nom pour un parfum d'ambiance" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une panne d'électricité" , "type": 13},
{ "desc" : "Un mauvais slogan pour une entreprise de réparation d'ordinateurs" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un tatoueur pendant qu'il vous tatoue" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de lingerie" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une séance photo" , "type": 13},
{ "desc" : "Un mauvais slogan pour une boutique de vêtements pour enfants" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un masseur" , "type": 13},
{ "desc" : "Un mauvais nom pour une série télé" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un repas formel" , "type": 13},
{ "desc" : "Un mauvais slogan pour une entreprise de jardinage" , "type": 13},
{ "desc" : "Une chose à ne pas dire lors d'une visite chez le notaire" , "type": 13},
{ "desc" : "Un mauvais nom pour un livre d'auto-amélioration" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un cours de théâtre" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de préservatifs" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un juge" , "type": 13},
{ "desc" : "Un mauvais nom pour un blog" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une réunion de parents d'élèves" , "type": 13},
{ "desc" : "Un mauvais slogan pour un chirurgien esthétique" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un surveillant d'examen" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de couches" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une séance d'hypnose" , "type": 13},
{ "desc" : "Un mauvais slogan pour une entreprise de pompes funèbres" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un pompier" , "type": 13},
{ "desc" : "Un mauvais nom pour une émission pour enfants" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un blind test" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de laxatifs" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un huissier" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de nourriture pour chiens" , "type": 13},
{ "desc" : "Une chose à ne pas faire lors d'une inspection à domicile" , "type": 13},
{ "desc" : "Un mauvais slogan pour une entreprise de désinsectisation" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un douanier" , "type": 13},
{ "desc" : "Un mauvais nom pour une application de navigation" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une réunion d'anciens élèves" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de sous-vêtements" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un contrôleur de billets" , "type": 13},
{ "desc" : "Un mauvais nom pour un podcast" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une visite guidée" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de produits capillaires" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un médecin légiste" , "type": 13},
{ "desc" : "Un mauvais nom pour un cocktail" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une fête prénatale" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de crème solaire" , "type": 13},
{ "desc" : "Une chose à ne pas dire lors d'une séance de dédicaces" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de produits pour bébés" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une visite dans un pays étranger" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de teinture capillaire" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un astronome" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de sodas" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un cours de cuisine" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de déodorants" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un archéologue" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de jus de fruits" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une manifestation" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de lessive" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un biologiste" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de nourriture surgelée" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une séance de psychanalyse" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de chaussettes" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un géologue" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de glaces" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une élection" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de thé" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un zoologue" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de shampoing" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une cérémonie religieuse" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de café" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un botaniste" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de biscuits" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un débat politique" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de chocolat" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un météorologue" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de pâtes" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une éclipse solaire" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de riz" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un paléontologue" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de pain" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une coupure d'eau" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de dentifrice" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un océanographe" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de confiture" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une alerte météo" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de savon" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un entomologiste" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de miel" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une éruption volcanique" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de brosses à dents" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un volcanologue" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de bonbons" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un tremblement de terre" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de papier toilette" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un sismologue" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de chewing-gum" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une tornade" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de rasoirs" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un ornithologue" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de céréales" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une panne d'eau" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de couches-culottes" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un ichtyologue" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de crème glacée" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une panne de réseau" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de coton-tiges" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un primatologue" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de ketchup" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un cours de premiers secours" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de biberons" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un généticien" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de mayonnaise" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un don du sang" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de mousse à raser" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un immunologiste" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de moutarde" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un examen médical" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de crème anti-rides" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un virologue" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de soupe en conserve" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une épidémie" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de crème pour les mains" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un épidémiologiste" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de cornichons" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une pandémie" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de produits contre l'acné" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un bactériologiste" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de cookies" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une grève des transports" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de tapis de yoga" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un neurologue" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de sauces pour pâtes" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une conférence de presse" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de chaussures de sport" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un cardiologue" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de popcorn" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une opération à cœur ouvert" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de serviettes hygiéniques" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un pneumologue" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de chips" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un scanner IRM" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de tampons" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un dermatologue" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de snacks" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une radiographie" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de produits capillaires" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un gynécologue" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de soda diététique" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un test de grossesse" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de gants en latex" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un obstétricien" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de sucettes" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un accouchement" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de couches pour adultes" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un pédiatre" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de barres chocolatées" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant un baptême" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de thermomètres" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un chirurgien" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de beurre de cacahuètes" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une circoncision" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de bandages" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un anesthésiste" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de craquelins" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une séance de chimiothérapie" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de désinfectants" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un radiologue" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de sirop pour la toux" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une séance de radiothérapie" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de pansements" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un oncologiste" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de pastilles pour la gorge" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une biopsie" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de vitamines" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un psychiatre" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de médicaments contre le rhume" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une séance de thérapie" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de compléments alimentaires" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un psychanalyste" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de pilules amaigrissantes" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une séance d'orthophonie" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de produits pour les hémorroïdes" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un orthophoniste" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de spray nasal" , "type": 13},
{ "desc" : "Une chose à ne pas faire pendant une séance de kinésithérapie" , "type": 13},
{ "desc" : "Un mauvais slogan pour une marque de somnifères" , "type": 13},
{ "desc" : "Une chose à ne pas dire à un kinésithérapeute" , "type": 13},
{ "desc" : "Un mauvais nom pour une marque de pilules contre les brûlures d'estomac" , "type": 13},
{ "desc" : "Un animal" , "type": 13},
{ "desc" : "Un pays" , "type": 13},
{ "desc" : "Un océan" , "type": 13},
{ "desc" : "Un type de musique" , "type": 13},
{ "desc" : "Un écrivain" , "type": 13},
{ "desc" : "Un événement historique" , "type": 13},
{ "desc" : "Une invention" , "type": 13},
{ "desc" : "Un film" , "type": 13},
{ "desc" : "Un personnage fictif" , "type": 13},
{ "desc" : "Une œuvre d'art" , "type": 13},
{ "desc" : "Un monument" , "type": 13},
{ "desc" : "Un sport" , "type": 13},
{ "desc" : "Une langue" , "type": 13},
{ "desc" : "Un fleuve" , "type": 13},
{ "desc" : "Une constellation" , "type": 13},
{ "desc" : "Un appareil électronique" , "type": 13},
{ "desc" : "Une marque de voiture" , "type": 13},
{ "desc" : "Une série télévisée" , "type": 13},
{ "desc" : "Une ville" , "type": 13},
{ "desc" : "Un plat traditionnel" , "type": 13},
{ "desc" : "Un fromage" , "type": 13},
{ "desc" : "Une fête traditionnelle" , "type": 13},
{ "desc" : "Un acteur" , "type": 13},
{ "desc" : "Un chanteur" , "type": 13},
{ "desc" : "Un instrument de musique" , "type": 13},
{ "desc" : "Une période historique" , "type": 13},
{ "desc" : "Une arme à feu" , "type": 13},
{ "desc" : "Une légende urbaine" , "type": 13},
{ "desc" : "Une marque de vêtement" , "type": 13},
{ "desc" : "Un jeu vidéo" , "type": 13},
{ "desc" : "Un Pokémon" , "type": 13},
{ "desc" : "Un personnage de bande dessinée" , "type": 13},
{ "desc" : "Un personnage de roman" , "type": 13},
{ "desc" : "Une personnalité politique" , "type": 13},
{ "desc" : "Une monnaie" , "type": 13},
{ "desc" : "Un super-héros" , "type": 13},
{ "desc" : "Un super-vilain" , "type": 13},
{ "desc" : "Un dinosaure" , "type": 13},
{ "desc" : "Un scientifique" , "type": 13},
{ "desc" : "Une ville mythique" , "type": 13},
{ "desc" : "Un pays asiatique" , "type": 13},
{ "desc" : "Un pays européen" , "type": 13},
{ "desc" : "Un pays d'Afrique" , "type": 13},
{ "desc" : "Une île" , "type": 13},
{ "desc" : "Un drapeau" , "type": 13},
{ "desc" : "Une équipe de football" , "type": 13},
{ "desc" : "Une chaîne YouTube" , "type": 13},
{ "desc" : "Un streamer" , "type": 13},
{ "desc" : "Un groupe de rock" , "type": 13},
{ "desc" : "Un genre littéraire" , "type": 13},
{ "desc" : "Une civilisation ancienne" , "type": 13},
{ "desc" : "Une plante" , "type": 13},
{ "desc" : "Un arbre" , "type": 13},
{ "desc" : "Un insecte" , "type": 13},
{ "desc" : "Un oiseau" , "type": 13},
{ "desc" : "Un mammifère" , "type": 13},
{ "desc" : "Un reptile" , "type": 13},
{ "desc" : "Un poisson" , "type": 13},
{ "desc" : "Un amphibien" , "type": 13},
{ "desc" : "Une montagne" , "type": 13},
{ "desc" : "Un volcan" , "type": 13},
{ "desc" : "Un désert" , "type": 13},
{ "desc" : "Un animal marin" , "type": 13},
{ "desc" : "Un vaisseau spatial" , "type": 13},
{ "desc" : "Une planète" , "type": 13},
{ "desc" : "Un satellite naturel" , "type": 13},
{ "desc" : "Un espace intersidéral" , "type": 13},
{ "desc" : "Un festival" , "type": 13},
{ "desc" : "Une marque de téléphone" , "type": 13},
{ "desc" : "Un modèle de voiture" , "type": 13},
{ "desc" : "Un genre de film" , "type": 13},
{ "desc" : "Un personnage de film d’animation" , "type": 13},
{ "desc" : "Une couleur" , "type": 13},
{ "desc" : "Un type de danse" , "type": 13},
{ "desc" : "Un jeu de société" , "type": 13},
{ "desc" : "Un parc d’attractions" , "type": 13},
{ "desc" : "Une fête populaire" , "type": 13},
{ "desc" : "Une légende" , "type": 13},
{ "desc" : "Un proverbe" , "type": 13},
{ "desc" : "Un conte de fée" , "type": 13},
{ "desc" : "Un auteur de science-fiction" , "type": 13},
{ "desc" : "Une arme blanche" , "type": 13},
{ "desc" : "Une tradition culinaire" , "type": 13},
{ "desc" : "Une créature mythologique" , "type": 13},
{ "desc" : "Un géant" , "type": 13},
{ "desc" : "Une civilisation disparue" , "type": 13},
{ "desc" : "Un empereur romain" , "type": 13},
{ "desc" : "Un pharaon égyptien" , "type": 13},
{ "desc" : "Un roi de France" , "type": 13},
{ "desc" : "Une époque de l’histoire" , "type": 13},
{ "desc" : "Une langue morte" , "type": 13},
{ "desc" : "Un type de médaille" , "type": 13},
{ "desc" : "Un mot d’origine étrangère" , "type": 13},
{ "desc" : "Une structure géologique" , "type": 13},
{ "desc" : "Une grotte" , "type": 13},
{ "desc" : "Une scène de film culte" , "type": 13},
{ "desc" : "Une personnalité de la télévision" , "type": 13},
{ "desc" : "Un événement scientifique" , "type": 13},
{ "desc" : "Un scientifique célèbre" , "type": 13},
{ "desc" : "Une région viticole" , "type": 13},
{ "desc" : "Un type de bateau" , "type": 13},
{ "desc" : "Un dirigeant d’entreprise" , "type": 13},
{ "desc" : "Une marque de sport" , "type": 13},
{ "desc" : "Une marque de cosmétiques" , "type": 13},
{ "desc" : "Un modèle de chaussure" , "type": 13},
{ "desc" : "Un modèle d’horloge" , "type": 13},
{ "desc" : "Une application mobile" , "type": 13},
{ "desc" : "Un réseau social" , "type": 13},
{ "desc" : "Un type de musique électronique" , "type": 13},
{ "desc" : "Un objet du quotidien" , "type": 13},
{ "desc" : "Un mode de transport" , "type": 13},
{ "desc" : "Un bâtiment emblématique" , "type": 13},
{ "desc" : "Un point de repère géographique" , "type": 13},
{ "desc" : "Un outil de jardinage" , "type": 13},
{ "desc" : "Un objet de collection" , "type": 13},
{ "desc" : "Une matière chimique" , "type": 13},
{ "desc" : "Un événement sportif international" , "type": 13},
{ "desc" : "Un sportif célèbre" , "type": 13},
{ "desc" : "Un champion olympique" , "type": 13},
{ "desc" : "Un jeu en ligne" , "type": 13},
{ "desc" : "Une chaîne de télévision" , "type": 13},
{ "desc" : "Une série documentaire" , "type": 13},
{ "desc" : "Un court-métrage" , "type": 13},
{ "desc" : "Un film primé" , "type": 13},
{ "desc" : "Un film d’animation" , "type": 13},
{ "desc" : "Un manga" , "type": 13},
{ "desc" : "Un anime" , "type": 13},
{ "desc" : "Un créateur de mode" , "type": 13},
{ "desc" : "Une revue scientifique" , "type": 13},
{ "desc" : "Une bande-son de film" , "type": 13},
{ "desc" : "Une entreprise de haute technologie" , "type": 13},
{ "desc" : "Un type de publicité" , "type": 13},
{ "desc" : "Une méthode de cuisine" , "type": 13},
{ "desc" : "Un aliment diététique" , "type": 13},
{ "desc" : "Une épice" , "type": 13},
{ "desc" : "Une technique de peinture" , "type": 13},
{ "desc" : "Un artiste peintre" , "type": 13},
{ "desc" : "Un type de poésie" , "type": 13},
{ "desc" : "Un mouvement littéraire" , "type": 13},
{ "desc" : "Un style architectural" , "type": 13},
{ "desc" : "Un type de vêtement" , "type": 13},
{ "desc" : "Un accessoire de mode" , "type": 13},
{ "desc" : "Un motif de tissu" , "type": 13},
{ "desc" : "Un style musical" , "type": 13},
{ "desc" : "Un chanteur de pop" , "type": 13},
{ "desc" : "Un compositeur de musique classique" , "type": 13},
{ "desc" : "Un producteur de musique" , "type": 13},
{ "desc" : "Un DJ célèbre" , "type": 13},
{ "desc" : "Une agence spatiale" , "type": 13},
{ "desc" : "Un astronaute" , "type": 13},
{ "desc" : "Un météore" , "type": 13},
{ "desc" : "Une station spatiale" , "type": 13},
{ "desc" : "Un rover martien" , "type": 13},
{ "desc" : "Un genre de littérature fantastique" , "type": 13},
{ "desc" : "Une récompense littéraire" , "type": 13},
{ "desc" : "Un livre de science-fiction" , "type": 13},
{ "desc" : "Une saga littéraire" , "type": 13},
{ "desc" : "Un roman policier" , "type": 13},
{ "desc" : "Un thriller" , "type": 13},
{ "desc" : "Un poème" , "type": 13},
{ "desc" : "Un film de super-héros" , "type": 13},
{ "desc" : "Un film de science-fiction" , "type": 13},
{ "desc" : "Un film d’horreur" , "type": 13},
{ "desc" : "Une série policière" , "type": 13},
{ "desc" : "Un personnage de série" , "type": 13},
{ "desc" : "Un personnage de film" , "type": 13},
{ "desc" : "Un personnage de jeu vidéo" , "type": 13},
{ "desc" : "Un métier" , "type": 13},
{ "desc" : "Un professionnel de la santé" , "type": 13},
{ "desc" : "Une profession artistique" , "type": 13},
{ "desc" : "Un métier de la tech" , "type": 13},
{ "desc" : "Un métier du cinéma" , "type": 13},
{ "desc" : "Un écrivain de thriller" , "type": 13},
{ "desc" : "Un auteur jeunesse" , "type": 13},
{ "desc" : "Un scénariste" , "type": 13},
{ "desc" : "Un réalisateur" , "type": 13},
{ "desc" : "Un metteur en scène" , "type": 13},
{ "desc" : "Un critique de cinéma" , "type": 13},
{ "desc" : "Un animateur radio" , "type": 13},
{ "desc" : "Un influenceur" , "type": 13},
{ "desc" : "Un photographe célèbre" , "type": 13},
{ "desc" : "Une influence sur les réseaux sociaux" , "type": 13},
{ "desc" : "Un créateur de contenu" , "type": 13},
{ "desc" : "Un chef cuisinier" , "type": 13},
{ "desc" : "Un expert en nutrition" , "type": 13},
{ "desc" : "Un nutritionniste" , "type": 13},
{ "desc" : "Un pharmacien" , "type": 13},
{ "desc" : "Un médecin" , "type": 13},
{ "desc" : "Un vétérinaire" , "type": 13},
{ "desc" : "Un enseignant" , "type": 13},
{ "desc" : "Un astronome" , "type": 13},
{ "desc" : "Un chimiste" , "type": 13},
{ "desc" : "Un biologiste" , "type": 13},
{ "desc" : "Un géographe" , "type": 13},
{ "desc" : "Un mathématicien" , "type": 13},
{ "desc" : "Un historien" , "type": 13},
{ "desc" : "Un géologue" , "type": 13},
{ "desc" : "Un physicien" , "type": 13},
{ "desc" : "Un chercheur en IA" , "type": 13},
{ "desc" : "Un informaticien" , "type": 13},
{ "desc" : "Un biologiste marin" , "type": 13},
{ "desc" : "Un volcanologue" , "type": 13},
{ "desc" : "Un paléontologue" , "type": 13},
{ "desc" : "Un zoologiste" , "type": 13},
{ "desc" : "Un ingénieur" , "type": 13},
{ "desc" : "Un architecte" , "type": 13},
{ "desc" : "Un détective" , "type": 13},
{ "desc" : "Un juriste" , "type": 13},
{ "desc" : "Un avocat" , "type": 13},
{ "desc" : "Un juge" , "type": 13},
{ "desc" : "Un prisonnier célèbre" , "type": 13},
{ "desc" : "Un criminel notoire" , "type": 13},
{ "desc" : "Un tueur en série" , "type": 13},
{ "desc" : "Un vol légendaire" , "type": 13},
{ "desc" : "Un braquage célèbre" , "type": 13},
{ "desc" : "Un criminel historique" , "type": 13},
{ "desc" : "Un gangster" , "type": 13},
{ "desc" : "Un espion" , "type": 13},
{ "desc" : "Un détective privé" , "type": 13},
{ "desc" : "Un voleur" , "type": 13},
{ "desc" : "Un traducteur" , "type": 13},
{ "desc" : "Un linguiste" , "type": 13},
{ "desc" : "Un linguiste célèbre" , "type": 13},
{ "desc" : "Un polyglotte" , "type": 13},
{ "desc" : "Un écrivain engagé" , "type": 13},
{ "desc" : "Un auteur de biographies" , "type": 13},
{ "desc" : "Un politicien célèbre" , "type": 13},
{ "desc" : "Un activiste" , "type": 13},
{ "desc" : "Un diplomate" , "type": 13},
{ "desc" : "Un président" , "type": 13},
{ "desc" : "Un ministre" , "type": 13},
{ "desc" : "Un maire" , "type": 13},
{ "desc" : "Un parlementaire" , "type": 13},
{ "desc" : "Un ambassadeur" , "type": 13},
{ "desc" : "Un économiste" , "type": 13},
{ "desc" : "Un chef d’État" , "type": 13},
{ "desc" : "Un roi actuel" , "type": 13},
{ "desc" : "Un dirigeant d’opposition" , "type": 13},
{ "desc" : "Un homme d’affaires" , "type": 13},
{ "desc" : "Un industriel" , "type": 13},
{ "desc" : "Un investisseur" , "type": 13},
{ "desc" : "Un trader" , "type": 13},
{ "desc" : "Un capitaliste" , "type": 13},
{ "desc" : "Un syndic" , "type": 13},
{ "desc" : "Un collectionneur" , "type": 13},
{ "desc" : "Un conservateur" , "type": 13},
{ "desc" : "Un restaurateur d'art" , "type": 13},
{ "desc" : "Un critique d’art" , "type": 13},
{ "desc" : "Un musicien de jazz" , "type": 13},
{ "desc" : "Un compositeur de musique de film" , "type": 13},
{ "desc" : "Un acteur de théâtre" , "type": 13},
{ "desc" : "Un réalisateur de documentaires" , "type": 13},
{ "desc" : "Un scénariste de série télévisée" , "type": 13},
{ "desc" : "Un romancier" , "type": 13},
{ "desc" : "Un producteur de musique" , "type": 13},
{ "desc" : "Un guitariste célèbre" , "type": 13},
{ "desc" : "Un bassiste" , "type": 13},
{ "desc" : "Un batteur" , "type": 13},
{ "desc" : "Un pianiste" , "type": 13},
{ "desc" : "Un violoniste" , "type": 13},
{ "desc" : "Un harpiste" , "type": 13},
{ "desc" : "Un trompettiste" , "type": 13},
{ "desc" : "Un saxophoniste" , "type": 13},
{ "desc" : "Un flûtiste" , "type": 13},
{ "desc" : "Un chef d’orchestre" , "type": 13},
{ "desc" : "Un chorégraphe" , "type": 13},
{ "desc" : "Un danseur étoile" , "type": 13},
{ "desc" : "Un athlète de haut niveau" , "type": 13},
{ "desc" : "Un record mondial" , "type": 13},
{ "desc" : "Un concours sportif" , "type": 13},
{ "desc" : "Une médaille olympique" , "type": 13},
{ "desc" : "Un champion du monde" , "type": 13},
{ "desc" : "Un joueur de football célèbre" , "type": 13},
{ "desc" : "Un entraîneur" , "type": 13},
{ "desc" : "Un arbitre" , "type": 13},
{ "desc" : "Un journaliste sportif" , "type": 13},
{ "desc" : "Un commentateur" , "type": 13},
{ "desc" : "Un fan de sport" , "type": 13},
{ "desc" : "Un stade" , "type": 13},
{ "desc" : "Une salle de concert" , "type": 13},
{ "desc" : "Un cirque" , "type": 13},
{ "desc" : "Un spectacle de danse" , "type": 13},
{ "desc" : "Un festival de musique" , "type": 13},
{ "desc" : "Un groupe de musique de rue" , "type": 13},
{ "desc" : "Un orchestre symphonique" , "type": 13},
{ "desc" : "Un ensemble de musique baroque" , "type": 13},
{ "desc" : "Un groupe de musique classique" , "type": 13},
{ "desc" : "Un groupe de musique punk" , "type": 13},
{ "desc" : "Un groupe de musique metal" , "type": 13},
{ "desc" : "Un groupe de musique hip-hop" , "type": 13},
{ "desc" : "Un groupe de musique rock alternatif" , "type": 13},
{ "desc" : "Un groupe de musique folk" , "type": 13},
{ "desc" : "Un groupe de musique électronique" , "type": 13},
{ "desc" : "Un groupe de musique pop" , "type": 13},
{ "desc" : "Un groupe de musique indie" , "type": 13},
{ "desc" : "Un artiste de la scène musicale française" , "type": 13},
{ "desc" : "Un artiste de la scène musicale américaine" , "type": 13},
{ "desc" : "Un artiste de la scène musicale latino-américaine" , "type": 13},
{ "desc" : "Un artiste de la scène musicale asiatique" , "type": 13},
{ "desc" : "Un écrivain engagé" , "type": 13},
{ "desc" : "Un écrivain à succès" , "type": 13},
{ "desc" : "Un écrivain classique" , "type": 13},
{ "desc" : "Un écrivain de science-fiction" , "type": 13},
{ "desc" : "Un animal en voie de disparition" , "type": 13},
{ "desc" : "Un pays et sa culture" , "type": 13},
{ "desc" : "Une période historique importante" , "type": 13},
{ "desc" : "Une invention révolutionnaire" , "type": 13},
{ "desc" : "Un sport et ses règles" , "type": 13},
{ "desc" : "Un chanteur de rap ou de musique populaire" , "type": 13},
{ "desc" : "Un personnage mythologique" , "type": 13},
{ "desc" : "Un Pokémon" , "type": 13},
{ "desc" : "Un film d'animation et ses influences culturelles" , "type": 13},
{ "desc" : "Une arme à feu historique ou moderne" , "type": 13},
{ "desc" : "Un auteur ou une œuvre littéraire" , "type": 13},
{ "desc" : "Une série télévisée emblématique" , "type": 13},
{ "desc" : "Une plateforme de jeux vidéo" , "type": 13},
{ "desc" : "Un animal mythique" , "type": 13},
{ "desc" : "Un instrument de musique" , "type": 13},
{ "desc" : "Un événement politique marquant" , "type": 13}
];