const carddata9 = [
    { desc : "Classez les personnes présentes de la plus susceptible à la moins susceptible de devenir président" , type: 9},
{ desc : "Classez les personnes présentes de la plus drôle à la moins drôle" , type: 9},
{ desc : "Classez les personnes présentes de la plus organisée à la plus bordélique" , type: 9},
{ desc : "Classez les personnes présentes de la plus susceptible à la moins susceptible de survivre à une apocalypse zombie" , type: 9},
{ desc : "Classez les personnes présentes de la plus susceptible à la moins susceptible de commettre un crime parfait" , type: 9},
{ desc : "Classez les personnes présentes de la meilleure à la pire conseillère sentimentale" , type: 9},
{ desc : "Classez les personnes présentes de la plus susceptible à la moins susceptible d'apparaître dans une télé-réalité" , type: 9},
{ desc : "Classez les personnes présentes de la plus susceptible à la moins susceptible d'être arrêtée pour quelque chose d'absurde" , type: 9},
{ desc : "Classez les personnes présentes de la plus susceptible à la moins susceptible de devenir millionnaire" , type: 9},
{ desc : "Classez les personnes présentes de la plus susceptible à la moins susceptible de quitter la ville sur un coup de tête" , type: 9},
{ desc : "Classez les personnes présentes de la plus susceptible à la moins susceptible de s'endormir pendant un film" , type: 9},
{ desc : "Classez les personnes présentes de la plus susceptible à la moins susceptible d'avoir un compte Instagram secret" , type: 9},
{ desc : "Classez les personnes présentes de la plus susceptible à la moins susceptible de pleurer devant un film triste" , type: 9},
{ desc : "Classez les personnes présentes de la plus susceptible à la moins susceptible de devenir influenceur/euse" , type: 9},
{ desc : "Classez les personnes présentes de la plus susceptible à la moins susceptible de gagner à un jeu télévisé" , type: 9},
{ desc : "Classez les joueurs du plus probable au moins probable de devenir millionnaire." , type: 9},
{ desc : "Classez les joueurs du plus au moins susceptible de survivre à une apocalypse zombie." , type: 9},
{ desc : "Classez les joueurs selon qui ferait le meilleur animateur de télé-réalité." , type: 9},
{ desc : "Classez les personnes présentes de la plus organisée à la plus bordélique." , type: 9},
{ desc : "Classez les joueurs selon qui serait le plus susceptible de finir en prison et pourquoi." , type: 9},
{ desc : "Classez les personnes présentes du plus branché au moins tendance." , type: 9},
{ desc : "Classez les joueurs de celui/celle qui raconte les meilleures anecdotes à celui/celle qui en raconte le moins." , type: 9},
{ desc : "Classez les participants selon leur capacité à tenir un discours improvisé." , type: 9},
{ desc : "Classez les personnes présentes de la plus sexy à la moins sexy (humour inclus)." , type: 9},
{ desc : "Classez les joueurs du plus grand fêtard au plus casanier." , type: 9},
{ desc : "Classez les participants par leur “coolitude” générale." , type: 9},
{ desc : "Classez les personnes présentes du plus créatif au moins inventif." , type: 9},
{ desc : "Classez les joueurs selon leur sens de l’humour, du plus hilarant au plus pince-sans-rire." , type: 9},
{ desc : "Classez les participants du plus fort en danse au moins rythmé." , type: 9},
{ desc : "Classez les personnes présentes de celui/celle qui a les meilleures histoires à raconter à celui/celle qui en a le moins." , type: 9},
{ desc : "Classez les joueurs du plus audacieux au plus réservé." , type: 9},
{ desc : "Classez les participants du plus romantique au plus terre-à-terre." , type: 9},
{ desc : "Classez les personnes présentes par leur “style” vestimentaire du plus original au plus classique." , type: 9},
{ desc : "Classez les joueurs du plus dépaysé au plus traditionnel." , type: 9},
{ desc : "Classez les participants selon leur capacité à improviser, du plus spontané au moins surprenant." , type: 9},
{ desc : "Classez les personnes présentes du plus “bad boy/girl” au plus sage." , type: 9},
{ desc : "Classez les joueurs du plus bavard au plus silencieux." , type: 9},
{ desc : "Classez les participants de celui/celle qui a le meilleur goût musical à celui/celle qui en a le moins." , type: 9},
{ desc : "Classez les personnes présentes du plus aventureux au plus prudent." , type: 9},
{ desc : "Classez les joueurs du plus charismatique au plus discret." , type: 9},
{ desc : "Classez les participants selon leur niveau de “drague”, du plus séducteur au moins aguerri." , type: 9},
{ desc : "Classez les personnes présentes du plus extravagant au plus classique." , type: 9},
{ desc : "Classez les joueurs du plus accro aux réseaux sociaux au plus déconnecté." , type: 9},
{ desc : "Classez les participants du plus “rock’n’roll” au plus “country”." , type: 9},
{ desc : "Classez les personnes présentes de celui/celle qui a toujours la meilleure répartie à celui/celle qui hésite." , type: 9},
{ desc : "Classez les joueurs du plus tendance sur Instagram au moins photogénique." , type: 9},
{ desc : "Classez les participants du plus généreux en compliments au plus réservé." , type: 9},
{ desc : "Classez les personnes présentes du plus “drôle” au plus “lourd”." , type: 9},
{ desc : "Classez les joueurs du plus théâtral au plus minimaliste dans leurs expressions." , type: 9},
{ desc : "Classez les participants du plus “hype” au moins “branché”." , type: 9},
{ desc : "Classez les personnes présentes de celui/celle qui fait toujours sensation à celui/celle qui passe inaperçu(e)." , type: 9},
{ desc : "Classez les joueurs du plus ambitieux en challenge au plus modeste." , type: 9},
{ desc : "Classez les participants du plus “surprise” au plus prévisible." , type: 9},
{ desc : "Classez les personnes présentes de celui/celle qui ose tout à celui/celle qui reste dans sa zone de confort." , type: 9},
{ desc : "Classez les joueurs du plus “fêtard invétéré” au plus casanier." , type: 9},
{ desc : "Classez les participants du plus “pétillant” au plus “terne”." , type: 9},
{ desc : "Classez les personnes présentes de celui/celle qui raconte toujours les meilleures blagues au plus sérieux." , type: 9},
{ desc : "Classez les joueurs du plus “rockeur” au plus “chill”." , type: 9},
{ desc : "Classez les participants du plus “avant-gardiste” au plus traditionnel." , type: 9},
{ desc : "Classez les personnes présentes de celui/celle qui prend le plus de risques à celui/celle qui reste prudent(e)." , type: 9},
{ desc : "Classez les joueurs du plus “imprévisible” au plus prévisible." , type: 9},
{ desc : "Classez les participants selon leur capacité à surprendre, du plus inventif au plus banal." , type: 9},
{ desc : "Classez les personnes présentes du plus “extraverti” au plus “introverti”." , type: 9},
{ desc : "Classez les joueurs du plus \"showman\" au plus discret." , type: 9},
{ desc : "Classez les participants du plus “hot” au plus “glacial” (avec humour)." , type: 9},
{ desc : "Classez les personnes présentes du plus “audacieux” au plus “timoré”." , type: 9},
{ desc : "Classez les joueurs du plus “populaire” au moins en vue." , type: 9},
{ desc : "Classez les participants selon leur aisance en public, du plus à l’aise au plus gêné." , type: 9},
{ desc : "Classez les personnes présentes du plus “réfléchi” au plus impulsif." , type: 9},
{ desc : "Classez les joueurs du plus “charismatique” au moins “magnétique”." , type: 9},
{ desc : "Classez les personnes présentes de la plus bavarde à la plus silencieuse en situation de stress." , type: 9},
{ desc : "Classez les joueurs du plus extravagant en accessoires à celui qui en porte le moins." , type: 9},
{ desc : "Classez les participants du plus crédible au plus invraisemblable dans leurs anecdotes de soirées." , type: 9},
{ desc : "Classez les personnes présentes de celui/celle qui imite le mieux un animal à celui/celle qui échoue lamentablement." , type: 9},
{ desc : "Classez les joueurs du plus susceptible d’organiser la prochaine fête à celui qui refuse systématiquement." , type: 9},
{ desc : "Classez les participants du plus romancé au plus terre-à-terre dans leurs récits d’aventures." , type: 9},
{ desc : "Classez les personnes présentes selon leur style de danse, du plus fluide au plus hésitant." , type: 9},
{ desc : "Classez les joueurs du plus apte à devenir une star de cinéma au plus maladroit." , type: 9},
{ desc : "Classez les participants du plus spontané en improvisation aux plus réservés." , type: 9},
{ desc : "Classez les personnes présentes de celui/celle qui a toujours une blague à celui/celle qui reste muet(e)." , type: 9},
{ desc : "Classez les joueurs du plus souvent en retard aux ponctuels invétérés." , type: 9},
{ desc : "Classez les participants du plus audacieux au plus timide dans l’art du flirt." , type: 9},
{ desc : "Classez les personnes présentes du plus prétentieux au plus humble." , type: 9},
{ desc : "Classez les joueurs du plus ouvert aux nouvelles expériences aux plus conservateurs." , type: 9},
{ desc : "Classez les participants du plus aventureux aux plus casaniers en matière de voyages." , type: 9},
{ desc : "Classez les personnes présentes selon leur aisance à raconter des anecdotes embarrassantes." , type: 9},
{ desc : "Classez les joueurs du plus grand séducteur aux plus discrets." , type: 9},
{ desc : "Classez les participants du plus enclin aux gaffes aux plus prudents." , type: 9},
{ desc : "Classez les personnes présentes de celui qui oserait porter le costume le plus fou à celui qui resterait classique." , type: 9},
{ desc : "Classez les joueurs du plus adepte du second degré aux plus sérieux." , type: 9},
{ desc : "Classez les participants du plus créatif en déguisements aux plus prévisibles." , type: 9},
{ desc : "Classez les personnes présentes du plus réactif dans un débat aux plus réservées." , type: 9},
{ desc : "Classez les joueurs du plus doué pour le karaoké aux plus silencieux." , type: 9},
{ desc : "Classez les participants du plus branchés sur les réseaux sociaux aux plus déconnectés." , type: 9},
{ desc : "Classez les personnes présentes selon leur capacité à improviser une chanson humoristique." , type: 9},
{ desc : "Classez les joueurs du plus habile en danse latine aux moins rythmés." , type: 9},
{ desc : "Classez les participants du plus enclin à raconter des histoires incroyables aux plus sceptiques." , type: 9},
{ desc : "Classez les personnes présentes selon leur niveau de confiance lors des défis." , type: 9},
{ desc : "Classez les joueurs du plus fort en mimes aux plus gauche." , type: 9},
{ desc : "Classez les participants du plus charismatique aux plus terre-à-terre." , type: 9},
{ desc : "Classez les personnes présentes du plus à l’aise avec l’humour noir aux plus sensibles." , type: 9},
{ desc : "Classez les joueurs du plus passionné de musique aux moins mélomanes." , type: 9},
{ desc : "Classez les participants du meilleur imitateur d’accents aux moins convaincants." , type: 9},
{ desc : "Classez les personnes présentes du plus enclin à relever des défis absurdes aux plus réticents." , type: 9},
{ desc : "Classez les joueurs du plus audacieux en mode vestimentaire aux plus classiques." , type: 9},
{ desc : "Classez les participants du plus apte à improviser un discours aux plus hésitants." , type: 9},
{ desc : "Classez les personnes présentes du plus aventureux en cuisine aux plus réticents." , type: 9},
{ desc : "Classez les joueurs du plus susceptible de lancer une blague osée aux plus prudents." , type: 9},
{ desc : "Classez les participants du plus imaginatif pour des histoires farfelues aux plus réalistes." , type: 9},
{ desc : "Classez les personnes présentes du plus extraverti aux plus introvertis." , type: 9},
{ desc : "Classez les joueurs selon leur capacité à inventer des répliques comiques sous pression." , type: 9},
{ desc : "Classez les participants du plus adepte des défis sportifs aux plus casaniers." , type: 9},
{ desc : "Classez les personnes présentes du plus extravagant en accessoires aux plus sobres." , type: 9},
{ desc : "Classez les joueurs du plus enclin à se lancer dans le chant au plus réservé." , type: 9},
{ desc : "Classez les participants du plus audacieux en flirt aux plus timides." , type: 9},
{ desc : "Classez les personnes présentes du plus « fêtard » aux plus discrets." , type: 9},
{ desc : "Classez les joueurs du plus créatif en déguisements aux plus classiques." , type: 9},
{ desc : "Classez les participants du plus efficace en improvisation d'histoires aux plus hésitants." , type: 9},
{ desc : "Classez les personnes présentes selon leur potentiel à devenir influenceur sur Instagram." , type: 9},
{ desc : "Classez les joueurs du plus original en répliques comiques aux plus convenus." , type: 9},
{ desc : "Classez les personnes présentes de celle qui ferait le meilleur cadavre exquis à celle qui ressemble le moins à un zombie." , type: 9},
{ desc : "Classez les joueurs du plus apocalyptique au plus enclin à survivre à l’horreur." , type: 9},
{ desc : "Classez les participants selon leur capacité à faire peur, du plus terrifiant au plus inoffensif." , type: 9},
{ desc : "Classez les personnes présentes du meilleur imitateur de mourant à celui qui simule le moins bien sa dernière heure." , type: 9},
{ desc : "Classez les joueurs du plus « funéraire chic » au plus « enterrement raté »." , type: 9},
{ desc : "Classez les participants selon leur talent pour raconter une histoire macabre, du plus glaçant au plus douteux." , type: 9},
{ desc : "Classez les personnes présentes du plus « apocalypse zombie » au plus « fin de soirée triste »." , type: 9},
{ desc : "Classez les joueurs selon leur ressemblance à un personnage de film d’horreur, du plus convaincant au plus caricatural." , type: 9},
{ desc : "Classez les participants du plus apocalyptique en maquillage au moins effrayant." , type: 9},
{ desc : "Classez les personnes présentes du plus doué pour imiter la mort au moins dramatique." , type: 9},
{ desc : "Classez les joueurs du plus sombre en ambiance à celui qui garde une lueur d’espoir ridicule." , type: 9},
{ desc : "Classez les participants du plus morose au plus cynique en évoquant l’inéluctable destin." , type: 9},
{ desc : "Classez les personnes présentes selon leur aisance à plaisanter sur la mort, du plus ironique au plus solennel." , type: 9},
{ desc : "Classez les joueurs du plus « fataliste » au plus « chanceux » dans l’acceptation du destin." , type: 9},
{ desc : "Classez les participants du plus macabre en histoire au plus rêveur malgré tout." , type: 9},
{ desc : "Classez les personnes présentes selon leur capacité à transformer l’horreur en humour, du plus hilarant au plus pathétique." , type: 9},
{ desc : "Classez les joueurs du plus « enterrement rock » au plus « funéraire ennuyeux »." , type: 9},
{ desc : "Classez les participants du plus cynique au plus sentimental face aux fins tragiques." , type: 9},
{ desc : "Classez les personnes présentes de celui qui rirait d’un film d’horreur à celui qui pleurerait devant une épopée tragique." , type: 9},
{ desc : "Classez les joueurs du plus doué pour imiter la mort subite au moins convaincu." , type: 9},
{ desc : "Classez les participants du plus morbide au plus optimiste dans leur vision de l’après-vie." , type: 9},
{ desc : "Classez les personnes présentes selon leur capacité à faire de l’humour noir sur le destin, du plus mordant au plus réservé." , type: 9},
{ desc : "Classez les joueurs du plus habile en blagues sur l’enfer au plus effrayé par l’idée d’un purgatoire." , type: 9},
{ desc : "Classez les participants du plus apocalyptique dans leur style vestimentaire au plus sobre." , type: 9},
{ desc : "Classez les personnes présentes du plus inspiré par un scénario de film d’horreur au plus banal." , type: 9},
{ desc : "Classez les joueurs selon leur aptitude à raconter des anecdotes morbides, du plus divertissant au plus sinistre." , type: 9},
{ desc : "Classez les participants du plus obsédé par l’imaginaire macabre au plus rationnel." , type: 9},
{ desc : "Classez les personnes présentes de celui qui ferait le meilleur mort-vivant à celui qui a peur des cimetières." , type: 9},
{ desc : "Classez les joueurs du plus cynique en plaisanteries sur la mort au plus émouvé par la vie." , type: 9},
{ desc : "Classez les participants du plus sombre en grimaces sinistres au plus souriant malgré tout." , type: 9},
{ desc : "Classez les personnes présentes selon leur capacité à faire un toast funèbre, du plus dramatique au plus absurde." , type: 9},
{ desc : "Classez les joueurs du plus doué pour des blagues sur la fin du monde au plus hésitant." , type: 9},
{ desc : "Classez les participants du plus convaincu qu’il y aura une suite apocalyptique au plus blasé." , type: 9},
{ desc : "Classez les personnes présentes selon leur goût pour l’humour morbide, du plus insensible au plus affecté." , type: 9},
{ desc : "Classez les joueurs du plus prêt à enterrer leurs secrets au moins dramatique." , type: 9},
{ desc : "Classez les participants du plus apocalyptique en prévisions à celui qui fait toujours rire malgré tout." , type: 9},
{ desc : "Classez les personnes présentes selon leur potentiel de survie en cas d’apocalypse zombie, du plus fort au plus faible." , type: 9},
{ desc : "Classez les joueurs du plus inspiré par des scénarios macabres au plus rationnel." , type: 9},
{ desc : "Classez les participants du plus enclin à rire de l’inéluctable fin au plus pessimiste." , type: 9},
{ desc : "Classez les personnes présentes selon leur talent à faire de l’humour noir sur leur passé, du plus audacieux au plus réservé." , type: 9},
{ desc : "Classez les joueurs du plus fan de films d’horreur au plus amateur de comédies sentimentales." , type: 9},
{ desc : "Classez les participants du plus capable de simuler un enterrement hilarant au moins convaincu." , type: 9},
{ desc : "Classez les personnes présentes du plus cynique face à la fatalité au plus naïf." , type: 9},
{ desc : "Classez les joueurs selon leur capacité à faire des jeux de mots macabres, du plus inventif au plus lourd." , type: 9},
{ desc : "Classez les participants du plus fan des blagues sur la mort au moins intéressé par le morbide." , type: 9},
{ desc : "Classez les personnes présentes du plus sombre en répliques à celui qui se contente du banal." , type: 9},
{ desc : "Classez les joueurs du plus apocalyptique dans leur vision de l’avenir au plus optimiste." , type: 9},
{ desc : "Classez les participants du plus adepte du « rire de la mort » au plus sérieux." , type: 9},
{ desc : "Classez les personnes présentes selon leur humour noir en situations tragiques, du plus mordant au plus insensible." , type: 9},
{ desc : "Classez les joueurs du plus inspiré par un scénario d’horreur à celui qui préfère les fins heureuses, même si c’est ironique." , type: 9},
{ desc : "Classez les personnes présentes du plus sexy du soir au plus farfelu en matière de flirt." , type: 9},
{ desc : "Classez les joueurs selon leur capacité à lancer des compliments coquins, du plus charmant au plus osé." , type: 9},
{ desc : "Classez les participants du plus doué pour la séduction aux techniques les plus improbables." , type: 9},
{ desc : "Classez les personnes présentes en fonction de leur « sex-appeal » version décalée, du plus hot au plus rigolo." , type: 9},
{ desc : "Classez les joueurs du plus glamour en lingerie (même imaginaire) au plus déjanté." , type: 9},
{ desc : "Classez les participants selon leur aisance à raconter des anecdotes torrides, du plus audacieux au plus timide." , type: 9},
{ desc : "Classez les personnes présentes du meilleur danseur sensuel au plus maladroit dans le flirt." , type: 9},
{ desc : "Classez les joueurs du plus adepte du « talk sexy » aux répliques les plus rouillées." , type: 9},
{ desc : "Classez les participants du plus créatif en phrases d’accroche aux plus clichés." , type: 9},
{ desc : "Classez les personnes présentes du plus sexy des poses pour un selfie coquin au plus hésitant." , type: 9},
{ desc : "Classez les joueurs selon leur talent pour le strip-tease imaginaire, du plus érotique au plus burlesque." , type: 9},
{ desc : "Classez les participants du plus doué pour imiter des scènes de films torrides au plus décalé." , type: 9},
{ desc : "Classez les personnes présentes du plus charismatique en amour aux plus farfelues en séduction." , type: 9},
{ desc : "Classez les joueurs du plus romantique aux déclarations les plus improbables en matière de passion." , type: 9},
{ desc : "Classez les participants selon leur capacité à transformer un compliment en véritable œuvre d’art, du plus élégant au plus exagéré." , type: 9},
{ desc : "Classez les personnes présentes du plus convaincant en « amour fou » au plus terre-à-terre." , type: 9},
{ desc : "Classez les joueurs du plus sexy dans leur démarche au plus comique dans leur approche." , type: 9},
{ desc : "Classez les participants du plus expérimenté en anecdotes coquines au plus novice dans le domaine." , type: 9},
{ desc : "Classez les personnes présentes du plus inspiré par la passion à celui qui fait toujours rire en parlant d’amour." , type: 9},
{ desc : "Classez les joueurs selon leur aisance à improviser un dialogue érotique, du plus naturel au plus forcé." , type: 9},
{ desc : "Classez les participants du plus téméraire en séduction aux répliques les plus maladroites." , type: 9},
{ desc : "Classez les personnes présentes du plus glamour en accessoires coquins au plus minimaliste." , type: 9},
{ desc : "Classez les joueurs du plus inspiré par les films romantiques osés au plus décalé dans leurs références." , type: 9},
{ desc : "Classez les participants selon leur talent pour raconter leurs « aventures d’un soir » les plus improbables." , type: 9},
{ desc : "Classez les personnes présentes du plus audacieux dans leurs propositions au plus réservé." , type: 9},
{ desc : "Classez les joueurs du plus imaginatif en déclarations d’amour aux plus classiques." , type: 9},
{ desc : "Classez les participants selon leur efficacité à faire rire avec des sous-entendus sexy, du plus subtil au plus direct." , type: 9},
{ desc : "Classez les personnes présentes du plus doué pour un clin d’œil suggestif au plus timide." , type: 9},
{ desc : "Classez les joueurs selon leur maîtrise du langage coquin, du plus élégant au plus barbare." , type: 9},
{ desc : "Classez les participants du plus passionné dans leur storytelling amoureux au plus banalisé." , type: 9},
{ desc : "Classez les personnes présentes du plus extravagant en dédicaces sensuelles au plus discret." , type: 9},
{ desc : "Classez les joueurs du plus créatif en flirt virtuel au plus traditionnel." , type: 9},
{ desc : "Classez les participants du plus habile pour imiter des scènes torrides au plus caricatural." , type: 9},
{ desc : "Classez les personnes présentes du plus audacieux en mode « love hacking » au plus conservateur." , type: 9},
{ desc : "Classez les joueurs du plus inspiré par l’art du baiser aux déclarations les plus invraisemblables." , type: 9},
{ desc : "Classez les participants du plus sexy en accessoires (réels ou imaginaires) au moins pointus." , type: 9},
{ desc : "Classez les personnes présentes du plus « hot » dans leurs répliques aux plus teintées de romantisme kitsch." , type: 9},
{ desc : "Classez les joueurs selon leur potentiel de star d’un clip sexy parodique, du plus convaincant au plus improbable." , type: 9},
{ desc : "Classez les participants du plus inventif en déclarations d’amour loufoques au plus standard." , type: 9},
{ desc : "Classez les personnes présentes du plus assuré en « game de drague » au plus hésitant." , type: 9},
{ desc : "Classez les joueurs du plus inspiré par des rencontres torrides au plus rêveur." , type: 9},
{ desc : "Classez les participants du plus convaincu qu’un clin d’œil peut tout changer au plus réservé." , type: 9},
{ desc : "Classez les personnes présentes selon leur talent à enflammer une conversation avec humour, du plus charismatique au plus timide." , type: 9},
{ desc : "Classez les joueurs du plus créatif en phrases d’accroche visuelles (mime) aux plus verbaux." , type: 9},
{ desc : "Classez les participants du plus tendance en mode sexy décalé au plus rétro dans leurs approches." , type: 9},
{ desc : "Classez les personnes présentes selon leur aisance à relever un défi de séduction imaginaire, du plus engagé au plus hésitant." , type: 9},
{ desc : "Classez les joueurs du plus spontané en improvisations amoureuses aux plus calculés." , type: 9},
{ desc : "Classez les participants du plus sexy dans leur démarche au plus maladroit dans leur sourire charmeur." , type: 9},
{ desc : "Classez les personnes présentes du plus inspiré par l’amour passionnel au plus amusé par la situation." , type: 9},
{ desc : "Classez les joueurs selon leur capacité à faire d’un compliment coquin un moment inoubliable, du plus mémorable au plus farfelu." , type: 9},


];