const carddata20 = [{ "desc" : "poitrine, les mythos [csq]", "type":20},
{ "desc" : "Chacun balance sa ville de naissance, le joueur qui vient du plus gros trou paumé de [bourgeois;paysan] [csq]", "type":20},
{ "desc" : "Les fumeurs [csq] + [csq] s'ils n'ont plus de clopes", "type":20},
{ "desc" : "Tu détestes picoler en solo, [csq] à quelqu'un chaque fois que tu bois [tmp]", "type":20},
{ "desc" : "Ceux qui ont déjà pécho la meuf/mec d'un pote [csq] + 🍺 si vous êtes toujours ensemble", "type":20},
{ "desc" : "À trois, pointez le joueur le plus en chien. L'heureux élu [csq]", "type":20},
{ "desc" : "Imite une star du X pendant 30 secondes ou [csq]", "type":20},
{ "desc" : "Si t'as déjà pissé dans une piscine, [csq]. Si t'as chié dans la mer, [csq]", "type":20},
{ "desc" : "Le joueur avec le plus de poils visibles [csq]", "type":20},
{ "desc" : "Tous ceux qui ont déjà vomi à cause de l'alcool [csq]", "type":20},
{ "desc" : "Celui qui a le téléphone avec le moins de batterie [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà fait une partouze racontent ou [csq]", "type":20},
{ "desc" : "Ceux qui sont venus en [voiture;transport en commun] [csq]", "type":20},
{ "desc" : "Si t'es célibataire depuis plus de 6 mois, [csq] pour noyer ton désespoir", "type":20},
{ "desc" : "Balance le prénom de la personne avec qui t'as eu ton meilleur orgasme ou [csq]", "type":20},
{ "desc" : "Si t'as déjà pété pendant une baise [csq]", "type":20},
{ "desc" : "Pour chaque tatouage visible, [csq]. Double dose pour les tatouages de merde", "type":20},
{ "desc" : "Le joueur avec le plus de rouge à lèvres [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà niqué dans les chiottes d'un bar [csq]", "type":20},
{ "desc" : "Fais un strip-tease pendant 30 secondes ou [csq]", "type":20},
{ "desc" : "Les joueurs qui portent un sous-vêtement [noir;rouge] [csq]", "type":20},
{ "desc" : "Si t'as déjà stalké ton ex sur Insta cette semaine, [csq] espèce de psychopathe", "type":20},
{ "desc" : "Le joueur le plus bourré doit faire 10 pompes ou [csq]", "type":20},
{ "desc" : "Le plus jeune [csq] pour son manque d'expérience", "type":20},
{ "desc" : "Si t'as le moindre piercing, [csq]. Double dose pour ceux sur les parties intimes", "type":20},
{ "desc" : "Raconte ta pire expérience de cuite ou [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà envoyé un nude [csq]", "type":20},
{ "desc" : "Imite l'orgasme d'un autre joueur ou [csq]", "type":20},
{ "desc" : "Si t'as déjà fait une gaterie dans un lieu public [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà pris une photo de leur crotte [csq], espèces d'obsédés", "type":20},
{ "desc" : "Le propriétaire de l'appart/maison [csq] pour nous accueillir", "type":20},
{ "desc" : "Ceux qui ont plus de 3 exs dans leur téléphone [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un plan cul régulier, [csq]", "type":20},
{ "desc" : "Laisse un joueur envoyer un message à qui il veut avec ton téléphone ou [csq]", "type":20},
{ "desc" : "Les fumeurs de beuh [csq] + 🍺 si vous êtes défoncés actuellement", "type":20},
{ "desc" : "Si t'as déjà fait semblant de jouir, [csq] espèce de faux-cul", "type":20},
{ "desc" : "Montre la dernière photo que t'as prise ou [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà fait l'amour avec quelqu'un présent dans la pièce [csq]", "type":20},
{ "desc" : "Raconte ta plus grosse honte sexuelle ou [csq]", "type":20},
{ "desc" : "Pour chaque nuit passée sans se brosser les dents cette semaine, [csq] gros dégueulasse", "type":20},
{ "desc" : "Ceux qui ont déjà fait une sextape [csq]", "type":20},
{ "desc" : "Si t'as déjà pris un râteau cette année, [csq] pour te remonter le moral", "type":20},
{ "desc" : "Le joueur à qui tu donnerais un 10/10 en physique doit [csq]", "type":20},
{ "desc" : "Si t'as déjà envoyé un message à ton ex bourré, [csq]", "type":20},
{ "desc" : "Le joueur avec le moins de followers sur Insta [csq], looser", "type":20},
{ "desc" : "Les joueurs qui ont déjà fait un trip à trois [csq]", "type":20},
{ "desc" : "Balance le truc le plus cher que t'as volé ou [csq]", "type":20},
{ "desc" : "Ceux qui se sont déjà fait gauler en train de se branler [csq]", "type":20},
{ "desc" : "Si t'as déjà baisé dans une voiture, [csq]. Double dose si c'était au volant", "type":20},
{ "desc" : "Le joueur avec la plus grosse gueule de bois en ce moment [csq]", "type":20},
{ "desc" : "Si tu t'es déjà réveillé à côté d'un(e) inconnu(e), [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà utilisé un sextoy sur quelqu'un [csq]", "type":20},
{ "desc" : "Montre ton historique Google ou [csq]", "type":20},
{ "desc" : "Le joueur qui a couché avec le plus de personnes [csq]", "type":20},
{ "desc" : "Si t'as déjà été infidèle, [csq] sale traître", "type":20},
{ "desc" : "Les joueurs qui se sont déjà fait larguer par SMS [csq]", "type":20},
{ "desc" : "Si tu t'es déjà endormi pendant un plan cul, [csq]", "type":20},
{ "desc" : "Le joueur avec le plus gros cul [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà pratiqué le [fist;anulingus] [csq]", "type":20},
{ "desc" : "Le joueur avec le moins de poils pubiens [csq]", "type":20},
{ "desc" : "Si t'as déjà menti pour pécho, [csq]", "type":20},
{ "desc" : "Le dernier à avoir eu un rapport sexuel [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà chié dans leur froc après leurs 10 ans [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un accident pendant un cunni/fellation, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà dormi avec plus de 3 personnes dans le même lit [csq]", "type":20},
{ "desc" : "Donne le surnom le plus ridicule qu'on t'ait déjà donné ou [csq]", "type":20},
{ "desc" : "Le joueur à la position 69 [csq], parce que... voilà", "type":20},
{ "desc" : "Si t'as déjà fait une tournée des bars tout seul, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà utilisé une appli de rencontre [csq]", "type":20},
{ "desc" : "Montre ton dernier selfie ou [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà vomi sur quelqu'un [csq]", "type":20},
{ "desc" : "Si tu t'es déjà envoyé en l'air avec un collègue/camarade de classe, [csq]", "type":20},
{ "desc" : "Le joueur qui a bu le plus vite son dernier verre [csq]", "type":20},
{ "desc" : "Si t'as déjà fait un test de MST, [csq]", "type":20},
{ "desc" : "Les joueurs qui n'ont jamais fait de cunni/fellation [csq]", "type":20},
{ "desc" : "Raconte ta pire expérience avec la belle-famille ou [csq]", "type":20},
{ "desc" : "Ceux qui se sont déjà fait larguer pour leur performance au lit [csq]", "type":20},
{ "desc" : "Si t'as déjà flirté avec le parent d'un(e) pote, [csq]", "type":20},
{ "desc" : "Le joueur avec le plus de dettes [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà pris une photo de leurs parties intimes [csq]", "type":20},
{ "desc" : "Si t'as déjà pissé au lit après tes 15 ans, [csq]", "type":20},
{ "desc" : "Les joueurs avec un compte OnlyFans [csq]", "type":20},
{ "desc" : "Raconte la chose la plus dégueulasse que t'as mangée ou [csq]", "type":20},
{ "desc" : "Si t'as déjà fantasmé sur un personnage de dessin animé, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà été arrêtés par les flics [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un orgasme en moins d'une minute, [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà fait caca chez leur crush sans tirer la chasse [csq]", "type":20},
{ "desc" : "Le joueur le plus vieux [csq], respect l'ancêtre", "type":20},
{ "desc" : "Si t'as déjà eu un plan cul avec quelqu'un dont tu ne te rappelles plus le prénom, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà léché des pieds [csq]", "type":20},
{ "desc" : "Montre le dernier message que t'as envoyé ou [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà couché avec quelqu'un de plus de 10 ans d'écart [csq]", "type":20},
{ "desc" : "Si t'as déjà pissé dans une bouteille, [csq]", "type":20},
{ "desc" : "Le joueur qui a le plus de poils sur les jambes [csq]", "type":20},
{ "desc" : "Si t'as déjà joui dans ton froc, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà fait semblant d'être bourrés [csq]", "type":20},
{ "desc" : "Raconte ton pire date ou [csq]", "type":20},
{ "desc" : "Si t'as déjà ramené quelqu'un chez toi alors que tes parents/colocs étaient là, [csq]", "type":20},
{ "desc" : "Les joueurs qui n'ont jamais vu de film porno [csq]", "type":20},
{ "desc" : "Si t'as déjà baisé avec un ex, [csq]", "type":20},
{ "desc" : "Le joueur avec le plus gros nez [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà été pris en flag en train de se toucher [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un plan cul avec quelqu'un de cette soirée, vous buvez tous les deux 🍺🍺", "type":20},
{ "desc" : "Les joueurs qui ont déjà fait une partouze [csq]", "type":20},
{ "desc" : "Montre ta photo la plus embarrassante ou [csq]", "type":20},
{ "desc" : "Si t'as déjà eu une MST, [csq]", "type":20},
{ "desc" : "Le joueur qui a le plus de poils sur le torse [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà pratiqué la sodomie [csq]", "type":20},
{ "desc" : "Raconte ta technique de drague la plus foireuse ou [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un crush sur le parent d'un pote, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà fait l'amour dans un lieu insolite [csq]", "type":20},
{ "desc" : "Si t'as déjà vomi sur quelqu'un, [csq]", "type":20},
{ "desc" : "Le joueur le plus grand [csq] au plus petit", "type":20},
{ "desc" : "Ceux qui ont déjà fait pipi dans une piscine [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un plan cul d'un soir, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà fait une fausse déclaration d'amour pour pécho [csq]", "type":20},
{ "desc" : "Montre les 3 dernières photos de ton téléphone ou [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un orgasme pendant un rêve, [csq]", "type":20},
{ "desc" : "Le joueur avec le plus de tatouages [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà fantasmé sur un prof [csq]", "type":20},
{ "desc" : "Si t'as déjà fait l'amour dans la maison de tes parents, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont un compte secret sur les réseaux [csq]", "type":20},
{ "desc" : "Raconte ta plus grande gaffe en soirée ou [csq]", "type":20},
{ "desc" : "Si t'as déjà chié dans la nature, [csq]", "type":20},
{ "desc" : "Le joueur avec la barbe la plus longue/fournie [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà fait un strip poker [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un accident vestimentaire en public, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà vomi dans un taxi/Uber [csq]", "type":20},
{ "desc" : "Raconte ta pire cuite ou [csq]", "type":20},
{ "desc" : "Si t'as déjà kissé quelqu'un du même sexe, [csq]", "type":20},
{ "desc" : "Le joueur le plus sobre [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà eu un plan cul avec quelqu'un de plus de 15 ans d'écart [csq]", "type":20},
{ "desc" : "Si t'as déjà fait une gaffe monumentale au travail/école, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà été menottés [csq]", "type":20},
{ "desc" : "Montre la personne avec qui tu échanges le plus de messages ou [csq]", "type":20},
{ "desc" : "Si t'as déjà été viré, [csq]", "type":20},
{ "desc" : "Le joueur le plus radin [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà fait l'amour dans l'eau [csq]", "type":20},
{ "desc" : "Raconte ton pire râteau ou [csq]", "type":20},
{ "desc" : "Si t'as déjà fait un trip sous acide/champis, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà été hospitalisés à cause de l'alcool [csq]", "type":20},
{ "desc" : "Si t'as déjà fait une dépression, [csq]", "type":20},
{ "desc" : "Le joueur avec le plus de piercings [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà fait une coloration ratée [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un crush sur ton/ta prof, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà fait une déclaration d'amour bourrés [csq]", "type":20},
{ "desc" : "Raconte ton fantasme le plus bizarre ou [csq]", "type":20},
{ "desc" : "Si t'as déjà pris un laxatif par erreur, [csq]", "type":20},
{ "desc" : "Le joueur le plus grand des pieds [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà eu des relations sexuelles dans un lieu public [csq]", "type":20},
{ "desc" : "Si t'as déjà fait un french kiss à quelqu'un que tu détestes, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà utilisé la brosse à dents de quelqu'un d'autre [csq]", "type":20},
{ "desc" : "Montre ta plus récente recherche Google ou [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un crush sur quelqu'un de cette soirée, [csq]", "type":20},
{ "desc" : "Le joueur avec le plus de chance en amour [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà dit \"je t'aime\" sans le penser [csq]", "type":20},
{ "desc" : "Si t'as déjà fait semblant d'être intéressé par quelqu'un juste pour la baise, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu une relation toxique [csq]", "type":20},
{ "desc" : "Raconte ton plus grand regret sexuel ou [csq]", "type":20},
{ "desc" : "Si t'as déjà fait un coming out, [csq]", "type":20},
{ "desc" : "Le joueur le plus intelligent [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà fait une colère en public [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un trou noir à cause de l'alcool, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà mangé des insectes [csq]", "type":20},
{ "desc" : "Montre la photo la plus embarrassante de toi ou [csq]", "type":20},
{ "desc" : "Si t'as déjà pris la pilule du lendemain, [csq]", "type":20},
{ "desc" : "Le joueur avec les ongles les plus longs [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà vomi dans leur bouche et l'ont ravalé [csq]", "type":20},
{ "desc" : "Raconte la chose la plus dégueulasse que t'as faite ou [csq]", "type":20},
{ "desc" : "Si t'as déjà pensé à un ex pendant l'amour avec quelqu'un d'autre, [csq]", "type":20},
{ "desc" : "Le joueur avec le plus de chance [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà bandé/mouillé en public sans raison [csq]", "type":20},
{ "desc" : "Si t'as déjà été infidèle plus d'une fois, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu une addiction [csq]", "type":20},
{ "desc" : "Montre ton dernier achat en ligne ou [csq]", "type":20},
{ "desc" : "Si t'as déjà fait une thérapie, [csq]", "type":20},
{ "desc" : "Le joueur qui a le plus de followers sur les réseaux [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà eu des rapports non protégés avec un(e) inconnu(e) [csq]", "type":20},
{ "desc" : "Raconte ton pire cauchemar ou [csq]", "type":20},
{ "desc" : "Si t'as déjà pris des médicaments qui ne t'étaient pas prescrits, [csq]", "type":20},
{ "desc" : "Les joueurs qui n'ont jamais fumé [csq]", "type":20},
{ "desc" : "Si t'as déjà regardé un film pour adultes avec quelqu'un d'autre, [csq]", "type":20},
{ "desc" : "Le joueur qui a le moins dormi la nuit dernière [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà eu une expérience avec quelqu'un du même sexe [csq]", "type":20},
{ "desc" : "Si t'as déjà fait semblant d'être bourré pour pécho, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un crush sur un ami [csq]", "type":20},
{ "desc" : "Raconte ta pire rupture ou [csq]", "type":20},
{ "desc" : "Si t'as déjà ghosté quelqu'un, [csq]", "type":20},
{ "desc" : "Le joueur avec le plus d'ex [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà fantasmé sur une célébrité de plus de 60 ans [csq]", "type":20},
{ "desc" : "Si t'as déjà fait une grosse colère parce que t'étais bourré, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà fait une cure de désintox [csq]", "type":20},
{ "desc" : "Montre ta dernière facture d'alcool ou [csq]", "type":20},
{ "desc" : "Si t'as déjà eu une relation à distance, [csq]", "type":20},
{ "desc" : "Le joueur avec le moins d'expérience sexuelle [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà eu des hallucinations [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un trou de mémoire à cause de l'alcool cette année, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà fait du sexting [csq]", "type":20},
{ "desc" : "Raconte ton plus gros mensonge ou [csq]", "type":20},
{ "desc" : "Si t'as déjà fait une crise de jalousie, [csq]", "type":20},
{ "desc" : "Le joueur avec le plus d'argent sur son compte [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà couché avec quelqu'un pour se venger [csq]", "type":20},
{ "desc" : "Si t'as déjà eu une érection/excitation pendant un massage pro, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu une aventure avec un(e) marié(e) [csq]", "type":20},
{ "desc" : "Montre ton dernier screenshot ou [csq]", "type":20},
{ "desc" : "Si t'as déjà pratiqué le BDSM, [csq]", "type":20},
{ "desc" : "Le joueur avec la plus grosse bite/les plus gros seins [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà fait l'amour dans une voiture [csq]", "type":20},
{ "desc" : "Raconte ton premier baiser ou [csq]", "type":20},
{ "desc" : "Si t'as déjà eu une relation avec ton boss/prof, [csq]", "type":20},
{ "desc" : "Le joueur avec le plus d'enfants [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà été attirés par la mère/le père d'un(e) ami(e) [csq]", "type":20},
{ "desc" : "Si t'as déjà stalké le nouveau/la nouvelle de ton ex, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà fait un strip-tease [csq]", "type":20},
{ "desc" : "Montre ton dernier texto reçu ou [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un plan cul qui habite dans ton immeuble, [csq]", "type":20},
{ "desc" : "Le joueur avec le moins de vêtements actuellement [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà fait l'amour dans un lieu public [csq]", "type":20},
{ "desc" : "Raconte ton pire plan drague ou [csq]", "type":20},
{ "desc" : "Si t'as déjà fait l'amour bourré et regretté le lendemain, [csq]", "type":20},
{ "desc" : "Le joueur avec le sourire le plus charmeur [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà fait l'amour avec un(e) ex de leur pote [csq]", "type":20},
{ "desc" : "Si t'as déjà été arrêté par les flics, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà fait un triolisme [csq]", "type":20},
{ "desc" : "Montre la personne la plus sexy dans ton téléphone ou [csq]", "type":20},
{ "desc" : "Si t'as déjà fait semblant d'être quelqu'un d'autre pour pécho, [csq]", "type":20},
{ "desc" : "Le joueur avec le plus de chance au jeu [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà fait l'amour avec plus de 3 personnes différentes en une semaine [csq]", "type":20},
{ "desc" : "Raconte la chose la plus illégale que t'as faite ou [csq]", "type":20},
{ "desc" : "Si t'as déjà fait un test de paternité, [csq]", "type":20},
{ "desc" : "Le joueur avec la plus grande collection de sex toys [csq]", "type":20},
{ "desc" : "Ceux qui n'ont jamais été bourrés [csq]", "type":20},
{ "desc" : "Si t'as déjà stalké le compte d'un ex pendant plus d'une heure, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un accident gênant pendant les préliminaires [csq]", "type":20},
{ "desc" : "Montre ta photo de profil Tinder/Bumble ou [csq]", "type":20},
{ "desc" : "Si t'as déjà fait des avances à quelqu'un et t'es pris un gros râteau, [csq]", "type":20},
{ "desc" : "Le joueur avec le plus d'amis [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà fait l'amour dans le lit de leurs parents [csq]", "type":20},
{ "desc" : "Raconte ta plus grande peur ou [csq]", "type":20},
{ "desc" : "Si t'as déjà eu une relation secrète, [csq]", "type":20},
{ "desc" : "Le joueur avec le plus de chance en amour [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà eu un plan cul régulier pendant plus de 6 mois [csq]", "type":20},
{ "desc" : "Si t'as déjà fait une demande en mariage, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport sexuel avec plus de 20 personnes [csq]", "type":20},
{ "desc" : "Montre ton dernier achat embarrassant ou [csq]", "type":20},
{ "desc" : "Si t'as déjà fait un rêve érotique avec quelqu'un de cette soirée, [csq]", "type":20},
{ "desc" : "Le joueur le plus maigre [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà eu une relation avec quelqu'un de leur famille (par alliance) [csq]", "type":20},
{ "desc" : "Raconte ta plus grande réussite ou [csq]", "type":20},
{ "desc" : "Si t'as déjà pratiqué l'échangisme, [csq]", "type":20},
{ "desc" : "Le joueur le plus gros fumeur [csq]", "type":20},
{ "desc" : "Ceux qui se touchent plus de 3 fois par semaine [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un crush sur une célébrité ridicule, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà fait l'amour devant quelqu'un [csq]", "type":20},
{ "desc" : "Montre ta plus belle photo ou [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un orgasme sans pénétration, [csq]", "type":20},
{ "desc" : "Le joueur avec le moins d'hygiène [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà eu une relation avec quelqu'un rencontré le jour même [csq]", "type":20},
{ "desc" : "Raconte ton pire job ou [csq]", "type":20},
{ "desc" : "Si t'as déjà été viré pour faute grave, [csq]", "type":20},
{ "desc" : "Le joueur le plus porté sur le sexe [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà fait des photos dénudées [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un plan cul avec un(e) inconnu(e), [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà pratiqué le sexe anal [csq]", "type":20},
{ "desc" : "Montre ton fond d'écran ou [csq]", "type":20},
{ "desc" : "Si t'as déjà eu une relation avec quelqu'un de plus jeune/vieux de 10 ans, [csq]", "type":20},
{ "desc" : "Le joueur avec le plus de phobies [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà fait une fellation/cunnilingus dans un lieu public [csq]", "type":20},
{ "desc" : "Raconte ta pire expérience de rencard ou [csq]", "type":20},
{ "desc" : "Si t'as déjà eu une relation avec quelqu'un de ton travail/école, [csq]", "type":20},
{ "desc" : "Le joueur avec le plus de secrets [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà eu des rapports pendant leurs règles [csq]", "type":20},
{ "desc" : "Si t'as déjà été témoin d'un acte sexuel, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà participé à un jeu à boire et fini à l'hôpital [csq]", "type":20},
{ "desc" : "Montre ton dernier achat de plus de 100€ ou [csq]", "type":20},
{ "desc" : "Si t'as déjà été attiré par le parent d'un(e) ami(e), [csq]", "type":20},
{ "desc" : "Le joueur le plus gros dormeur [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà eu une relation toxique de plus d'un an [csq]", "type":20},
{ "desc" : "Raconte ton pire échec ou [csq]", "type":20},
{ "desc" : "Si t'as déjà pratiqué le voyeurisme, [csq]", "type":20},
{ "desc" : "Le joueur avec le plus d'argent dépensé en alcool ce mois-ci [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà eu des rapports non protégés avec un(e) inconnu(e) [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un crush sur ton/ta thérapeute, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu une érection/excitation en public [csq]", "type":20},
{ "desc" : "Montre la dernière chose que t'as achetée ou [csq]", "type":20},
{ "desc" : "Si t'as déjà eu une aventure avec une personne mariée, [csq]", "type":20},
{ "desc" : "Le joueur avec le plus gros appétit [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà eu un orgasme pendant une fellation/cunnilingus [csq]", "type":20},
{ "desc" : "Raconte ton plus gros complexe ou [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un plan cul avec quelqu'un de cette pièce, vous deux [csq]", "type":20},
{ "desc" : "Le joueur avec le plus d'applications de rencontre [csq]", "type":20},
{ "desc" : "Ceux qui ont déjà eu une relation longue distance [csq]", "type":20},
{ "desc" : "Si t'as déjà fantasmé sur un personnage fictif, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport sexuel dans l'eau [csq]", "type":20},
{ "desc" : "Montre ton dernier chat bizarre ou [csq]", "type":20},
{ "desc" : "Si t'as déjà eu une relation secrète avec ton/ta collègue, [csq]", "type":20},
{ "desc" : "Le joueur avec le plus de chance ce soir [csq]", "type":20},
{ "desc" : "ion sexuelle préférée avec un objet", "type":20},
{ "desc" : "Tu dois appeler ton dernier plan cul et lui dire que tu veux remettre ça ce soir", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport non protégé avec un inconnu [csq]", "type":20},
{ "desc" : "Mets le doigt dans la bouche du joueur à ta gauche pendant 5 secondes", "type":20},
{ "desc" : "Raconte ton pire râteau en détail", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un orgasme sans se toucher [csq]", "type":20},
{ "desc" : "Si t'as déjà joui en moins de 30 secondes, [csq]", "type":20},
{ "desc" : "Montre comment tu embrasserais le joueur le plus attirant de la pièce", "type":20},
{ "desc" : "Les joueurs qui ont déjà fait l'amour dans un avion/train [csq]", "type":20},
{ "desc" : "Enlève le haut ou le bas pour le reste du jeu ou prends 3 shots", "type":20},
{ "desc" : "Raconte ta plus grosse expérience de tromperie", "type":20},
{ "desc" : "Les joueurs qui ont déjà fait des avances à un prof [csq]", "type":20},
{ "desc" : "Tu dois faire semblant d'être excité chaque fois que tu parles [tmp]", "type":20},
{ "desc" : "Les joueurs avec une culotte/un caleçon [noir;rouge] [csq]", "type":20},
{ "desc" : "Balance la taille de ton engin ou le tour de ta poitrine", "type":20},
{ "desc" : "Lèche le cou de la personne à ta droite ou [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un plan cul avec quelqu'un dans cette pièce se dévoilent ou [csq]", "type":20},
{ "desc" : "Raconte ta plus grosse déception au lit", "type":20},
{ "desc" : "Tu dois parler de façon vulgaire [tmp]", "type":20},
{ "desc" : "Les joueurs qui ont déjà fait l'amour avec plus de 10 personnes [csq]", "type":20},
{ "desc" : "Si t'as déjà fait l'amour alors que tes parents/colocs étaient dans la pièce d'à côté, [csq]", "type":20},
{ "desc" : "Fais un bisou sur le front de tous les joueurs", "type":20},
{ "desc" : "Les joueurs qui ont déjà pratiqué le sexe anal [csq]", "type":20},
{ "desc" : "Raconte ton plus gros délire sexuel", "type":20},
{ "desc" : "Le joueur le plus jeune doit s'asseoir sur les genoux du plus vieux [tmp]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un plan cul avec quelqu'un de plus de 15 ans de différence [csq]", "type":20},
{ "desc" : "Simule un orgasme de façon convaincante pendant 20 secondes", "type":20},
{ "desc" : "Laisse les autres joueurs écrire un message au dernier contact que tu as eu sur ton téléphone", "type":20},
{ "desc" : "Les joueurs qui ont déjà pratiqué la zoophilie boivent tout leur verre (et devraient consulter)", "type":20},
{ "desc" : "Balance le prénom de la dernière personne avec qui t'as couché", "type":20},
{ "desc" : "Tu dois lécher le visage du joueur à ta gauche", "type":20},
{ "desc" : "Les joueurs qui ont déjà pratiqué le roleplay au lit [csq]", "type":20},
{ "desc" : "Si t'as déjà fait une gaterie à quelqu'un pendant qu'il/elle conduisait, [csq]", "type":20},
{ "desc" : "Tu dois rouler un patin au joueur de ton choix ou [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un threesome [csq]", "type":20},
{ "desc" : "Raconte un de tes rêves érotiques récents en détail", "type":20},
{ "desc" : "Tu dois enlever un vêtement au joueur en face de toi", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec un membre de la famille d'un ami, [csq]", "type":20},
{ "desc" : "Fais semblant de jouir bruyamment pendant 15 secondes", "type":20},
{ "desc" : "Les joueurs qui ont déjà consulté pour une addiction au sexe [csq]", "type":20},
{ "desc" : "Tu dois tenir la main du joueur à ta droite [tmp] et la caresser sensiblement", "type":20},
{ "desc" : "Si t'as déjà utilisé un sextoy sur quelqu'un d'autre, [csq]", "type":20},
{ "desc" : "Raconte ta plus grande peur pendant l'acte sexuel", "type":20},
{ "desc" : "Les joueurs qui ont déjà pratiqué la sodomie [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un pépin avec un préservatif, [csq]", "type":20},
{ "desc" : "Tu dois faire un massage sensuel au joueur de ton choix pendant 30 secondes", "type":20},
{ "desc" : "Les joueurs qui ont déjà couché avec quelqu'un pour se venger [csq]", "type":20},
{ "desc" : "Raconte ta plus grosse gaffe pendant l'acte", "type":20},
{ "desc" : "Pendant les 3 prochains tours, tu dois te caresser sensiblement quand tu parles", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu des rapports sexuels dans une piscine [csq]", "type":20},
{ "desc" : "Si t'as déjà couché avec plus d'une personne dans la même journée, [csq]", "type":20},
{ "desc" : "Tu dois faire un slow avec le joueur en face de toi", "type":20},
{ "desc" : "Les joueurs qui ont déjà uriné sur quelqu'un ou se sont fait uriner dessus [csq]", "type":20},
{ "desc" : "Raconte comment tu préfères qu'on te donne du plaisir", "type":20},
{ "desc" : "Tu dois t'asseoir sur les genoux du joueur en face de toi [tmp]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport dans des toilettes publiques [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec quelqu'un de plus âgé que tes parents, [csq]", "type":20},
{ "desc" : "Tu dois sucer le doigt du joueur à ta droite pendant 10 secondes", "type":20},
{ "desc" : "Les joueurs qui ont déjà pratiqué le fisting [csq]", "type":20},
{ "desc" : "Raconte la chose la plus trashy que t'as faite bourré(e)", "type":20},
{ "desc" : "Tu dois te mettre à quatre pattes et faire le chien en chaleur pendant 15 secondes", "type":20},
{ "desc" : "Si t'as déjà eu un orgasme multiple, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà utilisé des jouets anaux [csq]", "type":20},
{ "desc" : "Tu dois faire un lap dance au joueur de ton choix ou [csq]", "type":20},
{ "desc" : "Raconte ton dernier rêve érotique sans filtre", "type":20},
{ "desc" : "Si t'as déjà fait l'amour avec quelqu'un dont tu ne connaissais pas le nom, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà pratiqué l'exhibitionnisme [csq]", "type":20},
{ "desc" : "Montre comment tu dragues quelqu'un en boîte", "type":20},
{ "desc" : "Tu dois lécher l'intérieur du poignet du joueur à ta droite", "type":20},
{ "desc" : "Les joueurs qui ont déjà pratiqué le bondage [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un crush sur le parent d'un ami, [csq]", "type":20},
{ "desc" : "Tu dois mimer une position du kamasutra avec le joueur de ton choix", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport sexuel au travail/école [csq]", "type":20},
{ "desc" : "Raconte comment tu t'y prendrais pour séduire quelqu'un dans cette pièce", "type":20},
{ "desc" : "Si t'as déjà fait semblant de jouir, [csq]", "type":20},
{ "desc" : "Tu dois masser les épaules du joueur à ta gauche de façon sensuelle pendant 30 secondes", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport sexuel avec quelqu'un rencontré le jour même [csq]", "type":20},
{ "desc" : "Lèche la joue du joueur de ton choix ou prends un shot", "type":20},
{ "desc" : "Si t'as déjà pratiqué l'échangisme, [csq]", "type":20},
{ "desc" : "Raconte ta plus grande déception amoureuse", "type":20},
{ "desc" : "Tu dois parler avec une voix ultra sexy [tmp]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu des rapports avec plus de 20 personnes [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un rapport pendant tes règles/ses règles, [csq]", "type":20},
{ "desc" : "Tu dois caresser les cheveux du joueur en face de toi pendant qu'il/elle parle [tmp]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un orgasme en public [csq]", "type":20},
{ "desc" : "Raconte ta pire cuite et ce que t'as fait sous l'effet de l'alcool", "type":20},
{ "desc" : "Tu dois lécher le lobe d'oreille du joueur à ta gauche", "type":20},
{ "desc" : "Si t'as déjà eu un crush sur le frère/la sœur d'un ami, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport avec quelqu'un du même sexe [csq]", "type":20},
{ "desc" : "Tu dois mimer ta position préférée avec le joueur de ton choix", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec quelqu'un en couple, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà pratiqué le sexe téléphonique [csq]", "type":20},
{ "desc" : "Raconte le lieu le plus bizarre où t'as fait l'amour", "type":20},
{ "desc" : "Tu dois embrasser le nombril du joueur en face de toi", "type":20},
{ "desc" : "Si t'as déjà eu un rapport sexuel à plus de quatre, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un crush sur une personne ici présente [csq]", "type":20},
{ "desc" : "Tu dois enlever un vêtement du joueur de ton choix avec les dents", "type":20},
{ "desc" : "Si t'as déjà regardé un film porno avec tes amis, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà fait un striptease pour quelqu'un [csq]", "type":20},
{ "desc" : "Raconte ton pire plan cul en détail", "type":20},
{ "desc" : "Tu dois toucher les fesses du joueur à ta droite", "type":20},
{ "desc" : "Si t'as déjà eu un rapport sexuel dans l'eau, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà été attachés pendant l'acte [csq]", "type":20},
{ "desc" : "Tu dois faire un suçon au joueur de ton choix ou [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec un collègue/camarade de classe, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà utilisé un sextoy en public [csq]", "type":20},
{ "desc" : "Raconte ton premier rapport sexuel en détail", "type":20},
{ "desc" : "Tu dois enlever un vêtement et le donner au joueur en face de toi [tmp]", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec plus d'une personne à la fois, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un crush sur un prof [csq]", "type":20},
{ "desc" : "Tu dois faire un massage des pieds au joueur de ton choix pendant 30 secondes", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec quelqu'un que tu détestais, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport avec quelqu'un de marié [csq]", "type":20},
{ "desc" : "Raconte ta plus grande expérience de friendzone", "type":20},
{ "desc" : "Tu dois mordiller l'oreille du joueur à ta gauche", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec quelqu'un rencontré sur une appli, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà été infidèles [csq]", "type":20},
{ "desc" : "Tu dois choisir qui a l'air d'être le/la meilleur(e) au lit dans cette pièce", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec quelqu'un de plus de 15 ans d'écart, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà pratiqué la domination/soumission [csq]", "type":20},
{ "desc" : "Raconte la chose la plus coquine que t'as faite en public", "type":20},
{ "desc" : "Tu dois rester en sous-vêtements [tmp] ou prendre 3 shots", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec une célébrité, [csq] (et prouve-le)", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport avec quelqu'un dans cette pièce [csq] et se dévoilent", "type":20},
{ "desc" : "Tu dois faire un petit mordillement dans le cou du joueur à ta droite", "type":20},
{ "desc" : "Si t'as déjà fait un plan cul avec un inconnu, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà pratiqué le voyeurisme [csq]", "type":20},
{ "desc" : "Raconte ta rupture la plus douloureuse", "type":20},
{ "desc" : "Tu dois prendre une photo compromettante avec le joueur de ton choix", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec quelqu'un d'engagé, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport dans un lieu de travail/école [csq]", "type":20},
{ "desc" : "Tu dois embrasser le joueur qui a les plus beaux yeux", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec ton ex après votre rupture, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport avec un(e) inconnu(e) [csq]", "type":20},
{ "desc" : "Raconte ton plus gros kink/fétiche sans honte", "type":20},
{ "desc" : "Tu dois caresser le visage du joueur en face de toi pendant 15 secondes", "type":20},
{ "desc" : "Si t'as déjà eu un rapport dans les toilettes d'un bar/club, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport avec quelqu'un qu'ils venaient de rencontrer [csq]", "type":20},
{ "desc" : "Tu dois faire un slow très sensuel avec le joueur de ton choix", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec un(e) ami(e) proche, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà fait des préliminaires en public [csq]", "type":20},
{ "desc" : "Raconte ce qui t'excite le plus chez un partenaire", "type":20},
{ "desc" : "Tu dois caresser la cuisse du joueur à ta droite pendant 20 secondes", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec plusieurs personnes dans la même journée, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport avec un(e) supérieur(e) hiérarchique [csq]", "type":20},
{ "desc" : "Tu dois faire un compliment très sexuel à chaque joueur", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec quelqu'un que tu venais de rencontrer, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport dans une voiture [csq]", "type":20},
{ "desc" : "Raconte ton plus grand regret sexuel", "type":20},
{ "desc" : "Tu dois t'asseoir sur les genoux du joueur de ton choix [tmp]", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec quelqu'un de ta famille (par alliance), [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport dans un lieu public [csq]", "type":20},
{ "desc" : "Tu dois lécher la joue du joueur à ta gauche", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec quelqu'un que tu as payé, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport avec plus de 3 personnes différentes en une semaine [csq]", "type":20},
{ "desc" : "Raconte la chose la plus humiliante qui t'est arrivée pendant l'acte", "type":20},
{ "desc" : "Tu dois faire un french kiss à la personne de ton choix ou [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec quelqu'un d'engagé alors que tu l'étais aussi, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport avec quelqu'un de plus de 20 ans d'écart [csq]", "type":20},
{ "desc" : "Tu dois montrer comment tu t'y prendrais pour séduire quelqu'un en boîte", "type":20},
{ "desc" : "Si t'as déjà baisé pour te venger, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà filmé leurs ébats [csq]", "type":20},
{ "desc" : "Raconte ton premier baiser en détail", "type":20},
{ "desc" : "Tu dois faire un cunni/fellation imaginaire devant tout le monde pendant 15 secondes", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec plus de 5 personnes différentes en un mois, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport avec quelqu'un qu'ils n'aimaient pas [csq]", "type":20},
{ "desc" : "Tu dois appeler ton ex et lui dire que tu penses encore à lui/elle", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec quelqu'un qui était dans une relation, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport avec quelqu'un du même sexe [csq]", "type":20},
{ "desc" : "Raconte ta plus grande honte en matière de drague", "type":20},
{ "desc" : "Tu dois embrasser la main du joueur à ta droite de façon sensuelle", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec un(e) ami(e) de ton frère/ta sœur, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport à plus de 3 [csq]", "type":20},
{ "desc" : "Tu dois faire un strip-tease de 30 secondes ou [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec quelqu'un de ta famille (éloignée), [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un orgasme en moins d'une minute [csq]", "type":20},
{ "desc" : "Raconte ton fantasme le plus inavouable", "type":20},
{ "desc" : "Tu dois lécher le bras du joueur en face de toi", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec quelqu'un de beaucoup plus âgé, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport à plus de 4 [csq]", "type":20},
{ "desc" : "Tu dois simuler une position du kamasutra avec le joueur de ton choix", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec quelqu'un de beaucoup plus jeune (légalement), [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport avec quelqu'un de leur travail/école [csq]", "type":20},
{ "desc" : "Raconte ta plus grosse erreur amoureuse", "type":20},
{ "desc" : "Tu dois faire un suçon au joueur de ton choix ou [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec quelqu'un que tu connaissais depuis moins de 24h, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport avec quelqu'un de leur famille par alliance [csq]", "type":20},
{ "desc" : "Tu dois embrasser la personne que tu trouves la plus attirante dans la pièce", "type":20},
{ "desc" : "Si t'as déjà eu un rapport dans un lieu vraiment public, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport avec plus de 30 personnes différentes [csq]", "type":20},
{ "desc" : "Raconte ton plus grand regret amoureux", "type":20},
{ "desc" : "Tu dois tenir la main du joueur à ta gauche de façon sensuelle [tmp]", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec quelqu'un de ta belle-famille, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport avec plus de 2 personnes à la fois [csq]", "type":20},
{ "desc" : "Tu dois masser les épaules du joueur en face de toi pendant 30 secondes", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec quelqu'un de beaucoup trop jeune/vieux pour toi, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport avec quelqu'un qu'ils détestaient [csq]", "type":20},
{ "desc" : "Raconte ton plus grand fantasme non réalisé", "type":20},
{ "desc" : "Tu dois embrasser le joueur qui te semble le plus attirant ou [csq]", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec quelqu'un que tu venais de rencontrer dans un bar, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport avec quelqu'un rencontré en ligne [csq]", "type":20},
{ "desc" : "Tu dois lécher le cou du joueur à ta droite", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec quelqu'un de célèbre (même localement), [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport avec quelqu'un de leur promotion/classe [csq]", "type":20},
{ "desc" : "Raconte ton moment le plus embarrassant en matière de sexe", "type":20},
{ "desc" : "Tu dois mimer une fellation pendant 15 secondes", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec quelqu'un pendant tes règles/ses règles, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport avec un(e) inconnu(e) rencontré(e) le soir même [csq]", "type":20},
{ "desc" : "Tu dois lécher le doigt du joueur en face de toi", "type":20},
{ "desc" : "Si t'as déjà eu un rapport non protégé avec quelqu'un que tu ne connaissais pas bien, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà pratiqué le sexe oral en public [csq]", "type":20},
{ "desc" : "Raconte ta plus grande honte sexuelle", "type":20},
{ "desc" : "Tu dois toucher les cheveux du joueur de ton choix de façon sensuelle pendant 20 secondes", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec quelqu'un de beaucoup plus âgé/jeune que toi, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport avec quelqu'un alors qu'ils étaient en couple avec une autre personne [csq]", "type":20},
{ "desc" : "Tu dois faire un french kiss à la bouteille/verre pendant 10 secondes", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec l'ex d'un(e) ami(e), [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport avec quelqu'un de leur famille (par alliance) [csq]", "type":20},
{ "desc" : "Raconte ta technique pour faire jouir quelqu'un", "type":20},
{ "desc" : "Tu dois caresser la joue du joueur à ta gauche pendant qu'il/elle parle [tmp]", "type":20},
{ "desc" : "Si t'as déjà eu un rapport avec quelqu'un alors que tu étais en couple, [csq]", "type":20},
{ "desc" : "Les joueurs qui ont déjà eu un rapport avec quelqu'un alors qu'ils étaient ivres [csq]", "type":20},
{ "desc" : "Tu dois embrasser le joueur à ta droite sur la joue de façon sensuelle", "type":20}
];