const carddata5 = [
{ desc : "quelle est la chose la plus bizarre que tu as faite quand tu étais seul(e) ?" , type: 5},
{ desc : "Qui dans cette pièce penses-tu qu'il survivrait le plus longtemps dans une apocalypse zombie ?" , type: 5},
{ desc : "quel secret as-tu gardé pour toi jusqu'à maintenant ?" , type: 5},
{ desc : "Si tu devais choisir deux personnes dans cette pièce pour t'accompagner sur une île déserte, qui choisirais-tu et pourquoi ?" , type: 5},
{ desc : "quelle est ton habitude la plus inavouable ?" , type: 5},
{ desc : "quel est ton plus grand regret ?" , type: 5},
{ desc : "quelle est la chose la plus folle que tu as faite par amour ?" , type: 5},
{ desc : "as-tu déjà menti à quelqu'un présent ici ? À propos de quoi ?" , type: 5},
{ desc : "quelle est ta plus grande peur inavouable ?" , type: 5},
{ desc : "quel est le mensonge le plus important que tu as dit à tes parents ?" , type: 5},
{ desc : "Si tu pouvais sortir avec une célébrité, qui serait-ce ?" , type: 5},
{ desc : "quelle est la chose la plus chère que tu as volée ou cassée ?" , type: 5},
{ desc : "quelle est la chose la plus embarrassante que tes parents t'ont surprise en train de faire ?" , type: 5},
{ desc : "quel est ton fantasme le plus étrange ?" , type: 5},
{ desc : "Qui dans cette pièce penses-tu qu'il ferait le meilleur partenaire amoureux ?" , type: 5},
{ desc : "quelle application utilises-tu le plus sur ton téléphone ?" , type: 5},
{ desc : "quelle est la chose la plus dégoûtante que tu as mangée ?" , type: 5},
{ desc : "quel est le pire cadeau que tu as reçu et de qui ?" , type: 5},
{ desc : "quelle est ta plus mauvaise habitude ?" , type: 5},
{ desc : "qu'est-ce qui te fait pleurer à coup sûr ?" , type: 5},
{ desc : "quelle est la chose la plus bizarre que tu fais quand tu es seul(e) ?" , type: 5},
{ desc : "Si tu devais éliminer une personne dans cette pièce d'un jeu de survie, qui serait-ce ?" , type: 5},
{ desc : "quel est ton crush célébrité embarrassant ?" , type: 5},
{ desc : "quelle est la chose la plus stupide pour laquelle tu as dépensé beaucoup d'argent ?" , type: 5},
{ desc : "quelle est la chose la plus embarrassante dans ton historique de recherche internet ?" , type: 5},
{ desc : "as-tu déjà eu le béguin pour le partenaire d'un(e) ami(e) ?" , type: 5},
{ desc : "quelle est la chose la plus illégale que tu as faite ?" , type: 5},
{ desc : "quel secret gardes-tu de ta famille ?" , type: 5},
{ desc : "as-tu déjà espionné le téléphone de quelqu'un ? De qui et pourquoi ?" , type: 5},
{ desc : "Qui dans cette pièce penses-tu qu'il serait le plus susceptible de survivre à une apocalypse ?" , type: 5},
{ desc : "si tu devais te faire tatouer aujourd'hui, que te ferais-tu tatouer et où ?" , type: 5},
{ desc : "raconte ta pire expérience de date" , type: 5},
{ desc : "quelle est la chose la plus embarrassante qui t'est arrivée à l'école/travail ?" , type: 5},
{ desc : "quel est ton plus grand complexe physique ?" , type: 5},
{ desc : "quelle est la chose la plus bizarre que tu as recherchée sur internet ?" , type: 5},
{ desc : "si tu pouvais effacer un souvenir de ta mémoire, lequel serait-ce ?" , type: 5},
{ desc : "quelle est la chose la plus étrange que tu aies jamais mangée ?" , type: 5},
{ desc : "quel est le pire cadeau que tu as offert à quelqu'un ?" , type: 5},
{ desc : "quelle est ta plus grande insécurité ?" , type: 5},
{ desc : "quel secret as-tu gardé de tes amis présents ici ?" , type: 5},
{ desc : "quelle est la chose la plus illégale que tu as envisagé de faire ?" , type: 5},
{ desc : "quelle est la chose la plus chère que tu as cassée ?" , type: 5},
{ desc : "quelle est ta pire habitude en matière d'hygiène ?" , type: 5},
{ desc : "quel est le mensonge le plus élaboré que tu as raconté ?" , type: 5},
{ desc : "quelle est la chose la plus gênante que tes parents t'ont dit ?" , type: 5},
{ desc : "quel est ton plus grand fantasme inavouable ?" , type: 5},
{ desc : "qui dans cette pièce a le plus mauvais goût vestimentaire selon toi ?" , type: 5},
{ desc : "quel est ton plus grand échec professionnel ou scolaire ?" , type: 5},
{ desc : "as-tu déjà triché à un examen ? Comment ?" , type: 5},
{ desc : "quelle est la chose la plus méchante que tu aies dite sur quelqu'un dans son dos ?" , type: 5},
{ desc : "as-tu déjà eu un crush sur l'un des amis présents ici ?" , type: 5},
{ desc : "quel est le pire rendez-vous amoureux que tu aies jamais eu ?" , type: 5},
{ desc : "quelle est la chose la plus embarrassante que tes parents possèdent à ton sujet ?" , type: 5},
{ desc : "si tu pouvais changer une chose de ton apparence, que serait-ce ?" , type: 5},
{ desc : "quelle est ta plus grande peur irrationnelle ?" , type: 5},
{ desc : "qui parmi tes amis penses-tu qu'il ferait le pire parent ?" , type: 5},
{ desc : "as-tu déjà été attiré(e) par le partenaire d'un(e) ami(e) ?" , type: 5},
{ desc : "quelle est la chose la plus bizarre que tu aies faite seul(e) ?" , type: 5},
{ desc : "quelle est ta plus grande obsession ?" , type: 5},
{ desc : "quel est ton péché mignon alimentaire le plus honteux ?" , type: 5},
{ desc : "as-tu déjà fouillé dans le téléphone de quelqu'un ? Qu'as-tu trouvé ?" , type: 5},
{ desc : "quelle est la chose la plus embarrassante que tu aies achetée ?" , type: 5},
{ desc : "quelle est la pire chose que tu aies faite sous l'influence de l'alcool ?" , type: 5},
{ desc : "quel est ton pire souvenir d'adolescence ?" , type: 5},
{ desc : "quelle est la pire dispute que tu aies eue avec tes parents ?" , type: 5},
{ desc : "quelle est la chose la plus stupide pour laquelle tu as pleuré ?" , type: 5},
{ desc : "quel secret de famille pourrais-tu révéler ?" , type: 5},
{ desc : "quelle est la chose la plus désagréable que tu aies découverte sur quelqu'un ?" , type: 5},
{ desc : "as-tu déjà fait semblant d'aimer un cadeau ? Lequel ?" , type: 5},
{ desc : "quelle est la pire chose que tu aies dite à un enseignant ?" , type: 5},
{ desc : "as-tu déjà volé quelque chose ? Quoi ?" , type: 5},
{ desc : "quelle est ta plus grande jalousie envers quelqu'un dans cette pièce ?" , type: 5},
{ desc : "quel est le mensonge le plus flagrant que tu racontes sur toi-même ?" , type: 5},
{ desc : "quelle est l'habitude la plus dégoûtante que tu as en privé ?" , type: 5},
{ desc : "as-tu déjà été viré(e) ou forcé(e) de démissionner ? Pourquoi ?" , type: 5},
{ desc : "quel est ton moment le plus gênant en public ?" , type: 5},
{ desc : "quelle est la chose la plus folle que tu aies faite pour impressionner quelqu'un ?" , type: 5},
{ desc : "quelle est la chose la plus embarrassante que tu aies faite devant un crush ?" , type: 5},
{ desc : "quelle est la pire chose que tu aies publiée sur les réseaux sociaux ?" , type: 5},
{ desc : "quel message as-tu envoyé que tu as immédiatement regretté ?" , type: 5},
{ desc : "quelle est ta plus grande frustration actuelle ?" , type: 5},
{ desc : "quel objectif personnel as-tu abandonné ?" , type: 5},
{ desc : "quelle est la chose la plus malhonnête que tu fais régulièrement ?" , type: 5},
{ desc : "quelle est la chose la plus embarrassante dans ton historique YouTube ?" , type: 5},
{ desc : "si tu pouvais échanger ta vie avec quelqu'un dans cette pièce, qui choisirais-tu et pourquoi ?" , type: 5},
{ desc : "Quel est le mensonge le plus absurde que tu aies dit pour séduire quelqu'un?" , type: 5},
{ desc : "Quelle célébrité française te dégoûte le plus et pourquoi?" , type: 5},
{ desc : "Raconte ta pire expérience de \"lendemain de soirée\"." , type: 5},
{ desc : "Quelle est la chose la plus chère que tu aies cassée chez quelqu'un d'autre?" , type: 5},
{ desc : "Si tu pouvais effacer un souvenir de ta vie, lequel choisirais-tu?" , type: 5},
{ desc : "Quel est le mensonge le plus absurde que tu aies dit pour séduire quelqu'un?" , type: 5},
{ desc : "Quelle célébrité française te dégoûte le plus et pourquoi?" , type: 5},
{ desc : "Raconte ta pire expérience de \"lendemain de soirée\"." , type: 5},
{ desc : "Quelle est la chose la plus chère que tu aies cassée chez quelqu'un d'autre?" , type: 5},
{ desc : "Si tu pouvais effacer un souvenir de ta vie, lequel choisirais-tu?" , type: 5},
{ desc : "Quelle est la chose la plus bizarre que tu as faite quand tu étais seul(e)?" , type: 5},
{ desc : "Quel est ton fantasme le plus inavouable?" , type: 5},
{ desc : "Raconte ta rupture la plus humiliante." , type: 5},
{ desc : "Quelle est la chose la plus illégale que tu aies jamais faite?" , type: 5},
{ desc : "As-tu déjà eu un béguin pour le partenaire d'un(e) ami(e)?" , type: 5},
{ desc : "Quel est ton plus grand regret?" , type: 5},
{ desc : "Quelle est la chose la plus gênante que tes parents t'aient surprise à faire?" , type: 5},
{ desc : "Raconte le pire cadeau que tu aies jamais offert ou reçu." , type: 5},
{ desc : "Quelle est la plus grosse somme d'argent que tu as dépensée impulsivement et pour quoi?" , type: 5},
{ desc : "Quel est le pire conseil que tu aies jamais donné à quelqu'un?" , type: 5},
{ desc : "Raconte ton pire moment de malaise en public." , type: 5},
{ desc : "De quelle série ou film \"culte\" tu n'as en réalité jamais vu un seul épisode?" , type: 5},
{ desc : "Quelle est la chose la plus embarrassante dans ton historique de recherche?" , type: 5},
{ desc : "Quelle est la chose la plus mesquine que tu aies faite par jalousie?" , type: 5},
{ desc : "Quel mensonge continues-tu de raconter?" , type: 5},
{ desc : "Quelle est ta plus grande peur irrationnelle?" , type: 5},
{ desc : "Quel est ton talent caché dont tu n'es pas particulièrement fier?" , type: 5},
{ desc : "Quelle est la chose la plus dégoûtante que tu aies mangée?" , type: 5},
{ desc : "Quel est ton pire défaut selon ton/ta partenaire?" , type: 5},
{ desc : "As-tu déjà triché à un examen? Comment?" , type: 5},
{ desc : "Raconte un moment où tu as été vraiment hypocrite." , type: 5},
{ desc : "Quel est ton plus grand complexe physique?" , type: 5},
{ desc : "Quelle personne présente à cette soirée supportes-tu le moins?" , type: 5},
{ desc : "Quel est le pire texto que tu aies envoyé à la mauvaise personne?" , type: 5},
{ desc : "À quelle célébrité as-tu déjà rêvé de manière inappropriée?" , type: 5},
{ desc : "Quelle est ta plus grande honte familiale?" , type: 5},
{ desc : "Quelle habitude dégoûtante as-tu quand personne ne te regarde?" , type: 5},
{ desc : "Qu'est-ce que tu as prétendu aimer juste pour impressionner quelqu'un?" , type: 5},
{ desc : "Quel est le plus gros mensonge présent sur ton CV?" , type: 5},
{ desc : "Quelle est la chose la plus embarrassante que tu aies faite sous l'influence de l'alcool?" , type: 5},
{ desc : "Quelle est la chose la plus cruelle que tu aies dite à quelqu'un?" , type: 5},
{ desc : "As-tu déjà volé quelque chose? Quoi?" , type: 5},
{ desc : "Quel est ton plaisir coupable le plus gênant?" , type: 5},
{ desc : "Quel secret gardes-tu encore de tes parents?" , type: 5},
{ desc : "Raconte le pire rendez-vous amoureux que tu aies jamais eu." , type: 5},
{ desc : "Quelle est la chose la plus embarrassante que tu gardes depuis l'adolescence?" , type: 5},
{ desc : "As-tu déjà été viré(e)? Pourquoi?" , type: 5},
{ desc : "Quelle est ta plus grande insécurité professionnelle?" , type: 5},
{ desc : "Quel est le comportement le plus immature que tu as encore?" , type: 5},
{ desc : "Quelle personne célèbre détestes-tu sans raison valable?" , type: 5},
{ desc : "Quel est le pire surnom qu'on t'ait donné?" , type: 5},
{ desc : "Si tu pouvais changer une décision majeure de ta vie, laquelle serait-ce?" , type: 5},
{ desc : "Que fais-tu quand tu es sûr(e) que personne ne te voit?" , type: 5},
{ desc : "Quelle est la chose la plus gênante que tes voisins aient pu entendre chez toi?" , type: 5},
{ desc : "Quel est ton plus grand mensonge qui dure encore aujourd'hui?" , type: 5},
{ desc : "Dis-nous quel a été ton moment le plus embarrassant lors d’une soirée." , type: 5},
{ desc : "Quel est le secret le mieux gardé que tu n’as jamais osé révéler ?" , type: 5},
{ desc : "Raconte la dernière fois où tu as eu un coup de foudre." , type: 5},
{ desc : "Quelle est la chose la plus folle que tu aies faite par amour ou par attirance ?" , type: 5},
{ desc : "As-tu déjà eu un flirt sans lendemain ? Raconte-nous." , type: 5},
{ desc : "Quelle est ta plus grande honte dont tu as ri après coup ?" , type: 5},
{ desc : "Quel est le mensonge le plus extravagant que tu aies raconté pour t’en sortir ?" , type: 5},
{ desc : "Quelle est la situation la plus gênante dans laquelle tu t’es retrouvé(e) en public ?" , type: 5},
{ desc : "Quel est le fantasme le plus loufoque que tu aimerais réaliser ?" , type: 5},
{ desc : "As-tu déjà joué un rôle totalement différent pour impressionner quelqu’un ? Explique." , type: 5},
{ desc : "Quelle est la chose la plus risquée que tu aies faite dans une soirée ?" , type: 5},
{ desc : "Quel est le compliment le plus déplacé que tu aies jamais reçu ?" , type: 5},
{ desc : "Raconte un moment où tu as osé dire ce que tout le monde pensait mais n’osait pas avouer." , type: 5},
{ desc : "Quelle est ta pire expérience en rendez-vous galant ?" , type: 5},
{ desc : "As-tu déjà été surpris(e) en pleine situation embarrassante ? Détaille." , type: 5},
{ desc : "Quelle est la chose la plus insolente que tu aies faite pour draguer quelqu’un ?" , type: 5},
{ desc : "Quel est ton secret pour passer une soirée inoubliable ?" , type: 5},
{ desc : "As-tu déjà caché une histoire embarrassante à tes amis ? Raconte sans nommer de noms." , type: 5},
{ desc : "Quel est le pire rendez-vous que tu aies eu, et pourquoi ?" , type: 5},
{ desc : "Quelle est la question la plus osée qu’on t’ait jamais posée ?" , type: 5},
{ desc : "Quel est le compliment le plus étrange que tu aies donné à quelqu’un ?" , type: 5},
{ desc : "Quel est le défi le plus fou que tu accepterais sans hésiter ?" , type: 5},
{ desc : "Raconte la fois où tu as fait quelque chose de complètement inattendu en public." , type: 5},
{ desc : "Quel est ton “péché mignon” le plus honteux ?" , type: 5},
{ desc : "As-tu déjà regretté une décision prise sous l’emprise de l’alcool ? Explique." , type: 5},
{ desc : "Quelle est la chose la plus spontanée que tu aies faite lors d’une soirée ?" , type: 5},
{ desc : "Quel est le secret que tu as gardé pendant trop longtemps ?" , type: 5},
{ desc : "Quelle est la situation la plus drôle dans laquelle tu t’es retrouvé(e) après minuit ?" , type: 5},
{ desc : "Raconte un moment où tu as dû improviser pour sortir d’une situation embarrassante." , type: 5},
{ desc : "Quelle est la phrase la plus nulle que tu aies utilisée pour draguer ?" , type: 5},
{ desc : "As-tu déjà menti sur ton âge pour impressionner quelqu’un ? Détaille." , type: 5},
{ desc : "Quelle est la question la plus intime qu’on t’ait posée ?" , type: 5},
{ desc : "Quel est le pari le plus risqué que tu aies accepté ?" , type: 5},
{ desc : "Quelle est la chose la plus surprenante que tu aies découverte sur un ami ?" , type: 5},
{ desc : "Raconte ton moment le plus fou dans une soirée entre amis." , type: 5},
{ desc : "Quel est le secret que tu cacherais même à tes plus proches amis ?" , type: 5},
{ desc : "Quelle est la première chose à laquelle tu penses quand tu vois quelqu’un qui te plaît ?" , type: 5},
{ desc : "Quel est le compliment le plus étrange que tu aies fait à quelqu’un ?" , type: 5},
{ desc : "Quelle est la question la plus embarrassante que tu t’es posée à toi-même ?" , type: 5},
{ desc : "Quel est le défi intime que tu n’as jamais osé relever ?" , type: 5},
{ desc : "Quelle est la chose la plus drôle que tu aies faite pour séduire quelqu’un ?" , type: 5},
{ desc : "As-tu déjà eu un coup de cœur pour quelqu’un d’inattendu ? Raconte." , type: 5},
{ desc : "Quelle est la situation où tu t’es senti(e) le plus vulnérable ?" , type: 5},
{ desc : "Quel est le secret que tu révélerais pour gagner un défi ?" , type: 5},
{ desc : "Quelle est la chose la plus dingue que tu ferais pour de l’argent ?" , type: 5},
{ desc : "Quel est ton plus grand regret en amour ou en séduction ?" , type: 5},
{ desc : "Quelle est l’aventure la plus farfelue que tu aimerais tenter ?" , type: 5},
{ desc : "Quelle est la question que tu redoutes qu’on te pose ?" , type: 5},
{ desc : "Raconte une anecdote où tu as dû choisir entre le raisonnable et le totalement fou." , type: 5},
{ desc : "Quel est le compliment le plus sincère que tu aies jamais reçu, et pourquoi t’a-t-il marqué ?" , type: 5},
{ desc : "Quel est le rêve le plus absurde dont tu te souviennes ?" , type: 5},
{ desc : "Quelle est ta plus grande crainte lors d’une soirée entre amis ?" , type: 5},
{ desc : "As-tu déjà menti pour éviter une sortie ? Explique comment." , type: 5},
{ desc : "Quelle est la chose la plus surprenante que tu aies faite sous l’effet de l’alcool ?" , type: 5},
{ desc : "Quel est ton secret inavouable concernant tes goûts musicaux ?" , type: 5},
{ desc : "As-tu déjà vécu une expérience romantique complètement inattendue ? Raconte." , type: 5},
{ desc : "Quel est le compliment le plus étrange que tu aies jamais lancé ?" , type: 5},
{ desc : "Quelle action osée aimerais-tu tenter lors d’une soirée ?" , type: 5},
{ desc : "As-tu déjà utilisé une phrase d’accroche tellement nulle qu’elle est devenue culte ?" , type: 5},
{ desc : "Quelle est la pire excuse que tu aies inventée pour te sortir d’une situation embarrassante ?" , type: 5},
{ desc : "Quel fantasme loufoque gardes-tu pour toi, même en secret ?" , type: 5},
{ desc : "Raconte un moment où tu as agi sans réfléchir et que tu regrettes… ou pas !" , type: 5},
{ desc : "Quel secret as-tu gardé pendant longtemps sans jamais l’avouer ?" , type: 5},
{ desc : "As-tu déjà eu un coup de foudre pour quelqu’un d’inattendu ? Décris ce moment." , type: 5},
{ desc : "Quel est le mensonge le plus extravagant que tu aies utilisé pour te sortir d’un pétrin ?" , type: 5},
{ desc : "Quelle est la chose la plus ridicule que tu aies faite pour impressionner quelqu’un ?" , type: 5},
{ desc : "As-tu déjà regretté une décision prise sur un coup de tête ? Raconte en détail." , type: 5},
{ desc : "Quel est le compliment le plus osé que tu aies osé formuler ?" , type: 5},
{ desc : "Raconte un moment où tu as dû choisir entre le raisonnable et le complètement fou." , type: 5},
{ desc : "Quel souvenir embarrassant gardes-tu d’une soirée en famille ou entre amis ?" , type: 5},
{ desc : "As-tu déjà eu une conversation qui a totalement changé le cours de ta soirée ? Explique." , type: 5},
{ desc : "Quelle est la chose la plus risquée que tu aies faite pour attirer l’attention de quelqu’un ?" , type: 5},
{ desc : "Quel secret garderais-tu même s’il pouvait te causer des ennuis ?" , type: 5},
{ desc : "Raconte un moment où tu as fait preuve d’une audace inattendue en public." , type: 5},
{ desc : "Quelle est la question la plus gênante qu’on t’ait posée et à laquelle tu as répondu avec honnêteté ?" , type: 5},
{ desc : "As-tu déjà vécu une aventure digne d’un scénario de film ? Décris-la." , type: 5},
{ desc : "Quelle est la chose la plus étrange que tu aies trouvée attirante chez quelqu’un ?" , type: 5},
{ desc : "As-tu déjà tenté de séduire quelqu’un avec une approche décalée ? Raconte comment." , type: 5},
{ desc : "Quel secret te ferait rougir si jamais il était révélé ?" , type: 5},
{ desc : "Raconte la fois où tu as osé dévoiler un détail intime que tu gardais précieusement." , type: 5},
{ desc : "As-tu déjà eu un moment où tout te semblait irréel en pleine soirée ?" , type: 5},
{ desc : "Quelle action folle as-tu faite pour te sentir vraiment vivant(e) ?" , type: 5},
{ desc : "As-tu déjà eu un rendez-vous qui a complètement déraillé ? Décris-le." , type: 5},
{ desc : "Quel est le compliment le plus sincère que tu aies reçu lors d’une soirée ?" , type: 5},
{ desc : "As-tu déjà pris une décision impulsive qui a changé le cours de ta soirée ? Raconte." , type: 5},
{ desc : "Quelle est la chose la plus décalée que tu aies faite par pure curiosité ?" , type: 5},
{ desc : "As-tu déjà avoué quelque chose que tu pensais ne jamais pouvoir révéler ? Explique." , type: 5},
{ desc : "Quel secret as-tu découvert sur toi-même lors d’une soirée mouvementée ?" , type: 5},
{ desc : "As-tu déjà eu une conversation qui t’a fait voir les choses autrement ? Décris-la." , type: 5},
{ desc : "Quel souvenir insolite gardes-tu d’une soirée où tout a dérapé ?" , type: 5},
{ desc : "As-tu déjà vécu un moment de vérité qui t’a profondément marqué(e) ?" , type: 5},
{ desc : "Quelle situation cocasse t’a mis(e) face à un dilemme inattendu ?" , type: 5},
{ desc : "Raconte une expérience qui t’a fait douter de la normalité des soirées." , type: 5},
{ desc : "Quel compliment surprenant as-tu pu donner spontanément à quelqu’un ?" , type: 5},
{ desc : "As-tu déjà pris un risque qui s’est terminé de façon étonnamment positive ?" , type: 5},
{ desc : "Quelle action osée n’as-tu jamais osé avouer publiquement ?" , type: 5},
{ desc : "Raconte un moment où la soirée a pris une tournure presque irréelle." , type: 5},
{ desc : "Quel secret gardes-tu jalousement, même auprès de tes amis les plus proches ?" , type: 5},
{ desc : "As-tu déjà vécu un moment où l’imprévu t’a totalement envahi ? Décris-le." , type: 5},
{ desc : "Quelle est la question que tu redoutes le plus qu’on te pose en pleine soirée ?" , type: 5},
{ desc : "Quelle est la chose la plus morbide que tu aies jamais trouvée drôle ?" , type: 5},
{ desc : "Quel souvenir macabre te fait encore sourire malgré tout ?" , type: 5},
{ desc : "As-tu déjà eu une pensée morbide en plein fou rire ? Raconte." , type: 5},
{ desc : "Quelle serait, selon toi, la meilleure manière de « mourir de rire » lors d’une soirée ?" , type: 5},
{ desc : "Quel est ton film d’horreur préféré et pourquoi il te fait autant rire malgré son ambiance sombre ?" , type: 5},
{ desc : "Quelle est la blague la plus noire que tu aies osé raconter à un moment inapproprié ?" , type: 5},
{ desc : "As-tu déjà ri en entendant une anecdote sur la mort ? Laquelle ?" , type: 5},
{ desc : "Quelle est la situation la plus « fatalement drôle » que tu aies vécue ?" , type: 5},
{ desc : "Raconte une histoire où l’humour noir a transformé un moment tragique en éclat de rire." , type: 5},
{ desc : "Si tu devais écrire ton épitaphe humoristique, que dirais-tu ?" , type: 5},
{ desc : "Quelle est la chose la plus cynique que tu aies faite pour éviter l’ennui ?" , type: 5},
{ desc : "As-tu déjà simulé la mort pour échapper à une situation embarrassante ? Explique." , type: 5},
{ desc : "Quelle serait ta dernière volonté farfelue si tu savais que ton heure approche ?" , type: 5},
{ desc : "Raconte un moment où tu as ri de l’ironie de la vie, même dans l’adversité." , type: 5},
{ desc : "Quelle est la blague la plus noire que tu aies entendue lors d’un enterrement (réel ou fictif) ?" , type: 5},
{ desc : "As-tu déjà pensé que mourir pourrait être une aventure hilarante ? Décris pourquoi." , type: 5},
{ desc : "Quel est le paradoxe le plus absurde que tu as observé en matière de vie et de mort ?" , type: 5},
{ desc : "Quelle serait, selon toi, la meilleure façon d’organiser un enterrement « festive » ?" , type: 5},
{ desc : "As-tu déjà utilisé l’humour noir pour te sortir d’une situation désespérée ? Comment ?" , type: 5},
{ desc : "Quel personnage de fiction macabre t’inspire le plus pour rire face à l’inéluctable ?" , type: 5},
{ desc : "Raconte une situation où l’humour noir t’a aidé à relativiser une perte ou un échec." , type: 5},
{ desc : "Quelle est la chose la plus osée que tu admettrais dans un « dernier secret » ?" , type: 5},
{ desc : "As-tu déjà fait une blague sur le destin qui a choqué ton entourage ? Laquelle ?" , type: 5},
{ desc : "Quelle est la pensée la plus sombre qui te fait étrangement rire en y repensant ?" , type: 5},
{ desc : "Raconte un moment où tu as trouvé hilarant le contraste entre la vie et la mort." , type: 5},
{ desc : "As-tu déjà inventé un scénario apocalyptique pour rigoler de l’inévitable ? Décris-le." , type: 5},
{ desc : "Quelle est l’ironie la plus mordante que tu as vécue lors d’un événement tragique ?" , type: 5},
{ desc : "Quel conseil macabre donnerais-tu à un ami pour affronter les mauvais jours ?" , type: 5},
{ desc : "As-tu déjà ri en pensant à la fin du monde ? Raconte ton scénario idéal." , type: 5},
{ desc : "Quelle est la chose la plus irrévérencieuse que tu aies faite en plaisantant sur la mort ?" , type: 5},
{ desc : "Quel secret morbide garderais-tu même s’il pouvait te causer des ennuis ?" , type: 5},
{ desc : "Raconte une anecdote où ton humour noir a transformé une situation sinistre en moment de partage." , type: 5},
{ desc : "As-tu déjà pensé que l’humour pourrait ressusciter des souvenirs tristes ? Explique." , type: 5},
{ desc : "Quel est le pire (et le plus drôle) plan d’évasion que tu imaginerais pour fuir l’ennui mortel ?" , type: 5},
{ desc : "Raconte la fois où tu as ri d’un événement tragique en y trouvant une leçon de vie cynique." , type: 5},
{ desc : "As-tu déjà ri en évoquant ton propre destin ? Quelle serait ta phrase fétiche ?" , type: 5},
{ desc : "Quelle est la chose la plus noire que tu aies envisagée comme « plaisanterie d’enterrement » ?" , type: 5},
{ desc : "Quel personnage sombre et hilarant aimerais-tu incarner dans un film sur la mort ?" , type: 5},
{ desc : "As-tu déjà ri de manière incontrôlable en évoquant l’idée d’un « ultime départ » ?" , type: 5},
{ desc : "Quelle est la blague la plus cynique que tu aies imaginée sur l’après-vie ?" , type: 5},
{ desc : "Raconte un moment où tu as dû choisir entre une décision tragique et une réplique hilarante." , type: 5},
{ desc : "As-tu déjà utilisé l’ironie pour tourner en dérision un échec cuisant ? Comment ?" , type: 5},
{ desc : "Quelle est la situation la plus paradoxale que tu as trouvée en parlant de ton avenir funeste ?" , type: 5},
{ desc : "Quel serait ton ultime message à diffuser si tu devais « quitter la scène » avec panache ?" , type: 5},
{ desc : "Raconte une expérience où l’humour noir a permis de désamorcer une tension mortelle." , type: 5},
{ desc : "As-tu déjà ri d’un cliché morbide qui, rétrospectivement, te semble totalement absurde ?" , type: 5},
{ desc : "Quel est le dernier trait d’humour noir qui t’a fait réfléchir sur la vie et la mort ?" , type: 5},
{ desc : "Quelle est la confession la plus surprenante que tu aurais osé faire en plein « face-à-face » avec l’inéluctable ?" , type: 5},
{ desc : "Raconte comment une situation désespérée a pris une tournure hilarante grâce à ton esprit noir." , type: 5},
{ desc : "Si tu pouvais choisir une seule phrase pour résumer ta vision de l’humour sur la mort, quelle serait-elle ?" , type: 5},
{ desc : "Quel est le compliment le plus osé que tu aies jamais lancé, même s’il était un peu ridicule ?" , type: 5},
{ desc : "Raconte ton fantasme le plus farfelu, version comédie romantique décalée." , type: 5},
{ desc : "Quelle a été ta situation la plus embarrassante en tentant de draguer quelqu’un ?" , type: 5},
{ desc : "As-tu déjà utilisé une technique de séduction complètement absurde qui a pourtant marché ?" , type: 5},
{ desc : "Quel est le pire jeu de mots coquin que tu aies jamais tenté ?" , type: 5},
{ desc : "Quelle est la chose la plus inattendue qui t’ait fait rougir lors d’un flirt ?" , type: 5},
{ desc : "Raconte une anecdote où un compliment s’est transformé en situation hilarante." , type: 5},
{ desc : "Quel est le surnom le plus embarrassant que tu aies reçu à cause de tes talents de séducteur ?" , type: 5},
{ desc : "As-tu déjà fait une déclaration d’amour improvisée en public ? Comment cela s’est-il terminé ?" , type: 5},
{ desc : "Quel conseil farfelu as-tu donné ou reçu en matière de drague ?" , type: 5},
{ desc : "Quelle est la réplique de drague la plus ratée que tu aies lancée ?" , type: 5},
{ desc : "As-tu déjà tenté de séduire quelqu’un en imitant une scène de film romantique ? Raconte." , type: 5},
{ desc : "Quelle est la chose la plus drôle qui te soit arrivée pendant une soirée à thème sexy ?" , type: 5},
{ desc : "Quel accessoire insolite as-tu déjà utilisé pour tenter de séduire quelqu’un ?" , type: 5},
{ desc : "As-tu déjà participé à un jeu où le flirt devenait la règle ? Quelle en fut la conséquence ?" , type: 5},
{ desc : "Raconte une fois où une technique de drague audacieuse t’a fait éclater de rire… même si ce n’était pas prévu." , type: 5},
{ desc : "Quelle est ta pire expérience en matière de rendez-vous galant parodique ?" , type: 5},
{ desc : "As-tu déjà eu un « coup de foudre » pour un objet ou un accessoire insolite ?" , type: 5},
{ desc : "Quel est le conseil de séduction le plus absurde que tu aies entendu ?" , type: 5},
{ desc : "Quelle est la situation la plus comique qui t’est arrivée lors d’une tentative de drague spontanée ?" , type: 5},
{ desc : "As-tu déjà osé aborder quelqu’un avec une citation de film culte, version décalée ? Laquelle ?" , type: 5},
{ desc : "Raconte un moment où une approche sexy a pris une tournure complètement inattendue." , type: 5},
{ desc : "Quelle est la chose la plus ridicule que tu aies faite pour impressionner quelqu’un lors d’une soirée ?" , type: 5},
{ desc : "As-tu déjà fait un strip-tease improvisé, même en plaisantant ? Décris l’expérience." , type: 5},
{ desc : "Quel est ton secret (même absurde) pour faire rire quelqu’un tout en le séduisant ?" , type: 5},
{ desc : "Raconte comment un compliment enflammé s’est transformé en fous rires incontrôlables." , type: 5},
{ desc : "Quelle est la phrase d’accroche la plus improbable que tu aies utilisée ou entendue ?" , type: 5},
{ desc : "As-tu déjà organisé ou participé à un défi de drague durant une soirée ? Quel fut le résultat ?" , type: 5},
{ desc : "Quelle est la situation la plus surréaliste que tu aies vécue en tentant de séduire quelqu’un ?" , type: 5},
{ desc : "As-tu déjà regretté une approche trop audacieuse au point de devenir hilarante par la suite ?" , type: 5},
{ desc : "Quel est le geste le plus extravagant que tu aies fait pour attirer l’attention de quelqu’un ?" , type: 5},
{ desc : "Raconte un moment où l’humour et la séduction se sont mélangés pour créer une situation mémorable." , type: 5},
{ desc : "Quelle est la chose la plus farfelue que tu aies faite pour montrer ton intérêt amoureux ?" , type: 5},
{ desc : "As-tu déjà expérimenté un « défi de compliments » lors d’une soirée ? Comment ça s’est passé ?" , type: 5},
{ desc : "Quelle technique de séduction ridicule te fait le plus rire quand tu y repenses ?" , type: 5},
{ desc : "Quel est le surnom le plus coquin que tu aies inventé ou entendu lors d’une soirée ?" , type: 5},
{ desc : "As-tu déjà joué à un jeu où il fallait inventer des scénarios de rencontres improbables ? Partage le meilleur." , type: 5},
{ desc : "Quelle est la situation la plus hilarante qui t’est arrivée pendant une conversation à double sens ?" , type: 5},
{ desc : "Raconte comment une mauvaise blague de drague a fini par créer un moment inoubliable." , type: 5},
{ desc : "As-tu déjà eu un rendez-vous où les sous-entendus sexy étaient poussés à l’extrême ?" , type: 5},
{ desc : "Quelle est la chose la plus drôle que tu aies observée lors d’une compétition de compliments coquins ?" , type: 5},
{ desc : "As-tu déjà fait semblant d’être un expert en séduction juste pour provoquer l’hilarité ?" , type: 5},
{ desc : "Raconte une anecdote où un geste sexy a été interprété de manière complètement loufoque." , type: 5},
{ desc : "Quelle est la réplique de drague la plus mémorable que tu aies reçue lors d’une soirée ?" , type: 5},
{ desc : "As-tu déjà tenté de séduire quelqu’un en parodiant une scène culte ? Comment cela a-t-il été reçu ?" , type: 5},
{ desc : "Raconte ton expérience la plus drôle en mélangeant compliments, danses et gestes théâtraux." , type: 5},
{ desc : "Quelle serait ta technique de séduction ultime si tu devais la résumer en un slogan humoristique ?" , type: 5},
{ desc : "As-tu déjà ri de toi-même en essayant une technique de drague qui s’est révélée être un fiasco ?" , type: 5},
{ desc : "Quelle est la situation la plus cocasse que tu aies vécue en jouant à un jeu de séduction ?" , type: 5},
{ desc : "Si tu pouvais inventer un nouveau geste de flirt qui ferait le buzz, quel serait-il et pourquoi ?" , type: 5},


];