const carddata8 = [
    { desc : "[playerCurr] et [playerX], improvisez une scène de rupture amoureuse pendant 1 minute." , type: 8},
{ desc : "tu es un vendeur très insistant et [playerX] un client qui ne veut rien acheter." , type: 8},
{ desc : "imite un bulletin météo comme à la télévision." , type: 8},
{ desc : "tu es un extraterrestre qui découvre l'alcool pour la première fois, [playerX] est un barman patient" , type: 8},
{ desc : "tu es un coach sportif très strict, [playerX] est un client paresseux" , type: 8},
{ desc : "tu es une star de cinéma capricieuse, [playerX] est ton assistant fatigué" , type: 8},
{ desc : "tu es un politicien en campagne, essaie de convaincre tout le monde de voter pour toi en 30 secondes" , type: 8},
{ desc : "tu es un présentateur de télé-réalité, [playerX] est un candidat bizarre" , type: 8},
{ desc : "tu es un parent qui explique \"les fleurs et les abeilles\" à [playerX]" , type: 8},
{ desc : "tu es un voyageur du futur qui essaie d'expliquer la technologie de 2100 à [playerX]" , type: 8},
{ desc : "tu es un détective, [playerX] est un suspect louche que tu dois interroger" , type: 8},
{ desc : "tu es un chef cuisinier célèbre, [playerX] est un critique gastronomique difficile" , type: 8},
{ desc : "tu es un guide touristique enthousiaste pour un musée ennuyeux, [playerX] est un touriste qui pose des questions stupides" , type: 8},
{ desc : "tu es un trader en bourse paniqué, [playerX] est ton client dont les actions s'effondrent" , type: 8},
{ desc : "tu es un médium qui lit l'avenir de [playerX]" , type: 8},
{ desc : "tu es un entraîneur qui fait un discours motivant à son équipe avant la finale" , type: 8},
{ desc : "tu viens de gagner un Oscar, fais ton discours de remerciement" , type: 8},
{ desc : "tu es un agent immobilier essayant de vendre une maison hantée à [playerX]" , type: 8},
{ desc : "tu es un touriste américain à Paris qui ne comprend pas un mot de français, [playerX] est un serveur français qui ne parle pas anglais" , type: 8},
{ desc : "tu es un astronaute qui revient sur Terre après 10 ans dans l'espace, [playerX] tente de t'expliquer toutes les nouvelles technologies" , type: 8},
{ desc : "tu es un vampire qui essaie de cacher ta vraie nature, [playerX] est un chasseur de vampires suspicieux" , type: 8},
{ desc : "tu es un client mécontent dans un restaurant, [playerX] est un serveur qui essaie de te calmer" , type: 8},
{ desc : "tu es un super-héros qui a perdu ses pouvoirs, [playerX] est ton assistant qui essaie de t'aider" , type: 8},
{ desc : "tu es un mauvais magicien de rue, [playerX] est un spectateur enthousiaste" , type: 8},
{ desc : "tu es un voyageur temporel du futur, [playerX] est un historien qui t'interroge" , type: 8},
{ desc : "tu es un robot qui développe des émotions, [playerX] est ton créateur confus" , type: 8},
{ desc : "tu es un mannequin capricieux, [playerX] est ton photographe exaspéré" , type: 8},
{ desc : "tu es un fantôme qui hante une maison, [playerX] est le nouveau propriétaire qui essaie de te faire partir" , type: 8},
{ desc : "tu es un chien qui peut soudainement parler, [playerX] est ton propriétaire choqué" , type: 8},
{ desc : "tu es un genie sortant d'une lampe, [playerX] vient de te libérer et a trois vœux ridicules" , type: 8},
{ desc : "tu es un super-vilain qui dévoile ton plan machiavélique, [playerX] est le héros qui t'écoute avant de t'arrêter" , type: 8},
{ desc : "tu es un extraterrestre qui découvre la nourriture terrienne, [playerX] est un chef cuisinier qui te fait goûter" , type: 8},
{ desc : "tu es un enfant de 5 ans, [playerX] est ta baby-sitter qui essaie de te mettre au lit" , type: 8},
{ desc : "tu es un candidat à un poste pour lequel tu n'as aucune qualification, [playerX] est le recruteur qui t'interroge" , type: 8},
{ desc : "tu es un pirate qui a perdu son trésor, [playerX] est un pêcheur qui l'a trouvé" , type: 8},
{ desc : "tu es une célébrité qui voyage incognito, [playerX] est un fan qui t'a reconnu" , type: 8},
{ desc : "tu es un apprenti sorcier qui a fait une erreur, [playerX] est ton maître furieux" , type: 8},
{ desc : "tu es un voyageur perdu, [playerX] est un habitant local qui donne des directions compliquées" , type: 8},
{ desc : "tu es un vendeur de voitures louches, [playerX] est un client naïf" , type: 8},
{ desc : "tu es un chanteur qui a oublié les paroles en plein concert, [playerX] est un fan au premier rang" , type: 8},
{ desc : "tu es un roi/une reine arrogant(e), [playerX] est un paysan qui demande une faveur" , type: 8},
{ desc : "tu es un coach de vie sur-motivé, [playerX] est ton client déprimé" , type: 8},
{ desc : "tu es un chevalier en quête, [playerX] est un dragon qui veut négocier plutôt que combattre" , type: 8},
{ desc : "tu es un espion en mission secrète, [playerX] est un agent double" , type: 8},
{ desc : "tu es un élève qui n'a pas fait ses devoirs, [playerX] est un professeur suspicieux" , type: 8},
{ desc : "tu es un politicien qui essaie d'expliquer un scandale, [playerX] est un journaliste insistant" , type: 8},
{ desc : "tu es un auteur célèbre, [playerX] est un critique qui déteste ton dernier livre" , type: 8},
{ desc : "tu es un DJ en boîte de nuit, [playerX] est un client qui demande constamment des chansons" , type: 8},
{ desc : "tu es un maître ninja, [playerX] est ton élève maladroit" , type: 8},
{ desc : "tu es un influenceur qui fait la promotion d'un produit ridicule, [playerX] est ton manager qui doit gérer les commentaires négatifs" , type: 8},
{ desc : "tu es un marchand d'art essayant de vendre un faux, [playerX] est un expert suspicieux" , type: 8},
{ desc : "tu es un sauveteur sur une plage, [playerX] est un nageur qui simule une noyade pour attirer ton attention" , type: 8},
{ desc : "tu es un entraîneur d'une équipe qui perd tous ses matchs, [playerX] est le propriétaire qui menace de te virer" , type: 8},
{ desc : "tu es un acteur qui a oublié son texte, [playerX] est un réalisateur furieux" , type: 8},
{ desc : "tu es un superhéros avec un pouvoir inutile, [playerX] est un journaliste qui t'interviewe" , type: 8},
{ desc : "tu es un gargon/serveuse dans un restaurant chic, [playerX] est un client impossible à satisfaire" , type: 8},
{ desc : "tu es un détective privé ringard, [playerX] est un client avec une affaire bizarre" , type: 8},
{ desc : "tu es une rock star en cure de désintoxication, [playerX] est ton manager qui essaie de te faire revenir sur scène" , type: 8},
{ desc : "tu es Gérard Depardieu ivre qui essaie de convaincre [playerX] de financer ton prochain film." , type: 8},
{ desc : "tu es un vendeur Telecom qui essaie désespérément de vendre une Box internet à [playerX] qui joue un client très difficile." , type: 8},
{ desc : "tu es un candidat à \"L'amour est dans le pré\" qui fait sa présentation à [playerX], l'agriculteur/agricultrice." , type: 8},
{ desc : "tu es un influenceur qui essaie de convaincre [playerX] d'acheter ta formation en dropshipping." , type: 8},
{ desc : "joue François Hollande sous la pluie essayant d'emprunter un parapluie à [playerX]." , type: 8},
{ desc : "interprète une scène de drague façon James Bond avec [playerX]." , type: 8},
{ desc : "mime une dispute passionnée avec [playerX] (dialoguez sans parler, uniquement par des expressions)." , type: 8},
{ desc : "imite un animateur TV en présentant [playerX] comme invité vedette." , type: 8},
{ desc : "fais une imitation de ton rockstar préférée en compagnie de [playerX]." , type: 8},
{ desc : "recrée une scène culte d’un film célèbre avec [playerX] en duo." , type: 8},
{ desc : "incarne un coach de vie qui conseille [playerX] sur sa dernière galère." , type: 8},
{ desc : "joue le rôle d’un séducteur à l’ancienne, et [playerX] doit réagir." , type: 8},
{ desc : "fais semblant d’être un célèbre humoriste et fais rire [playerX] en improvisant une blague." , type: 8},
{ desc : "interprète un détective interrogeant [playerX] sur un “crime” imaginaire." , type: 8},
{ desc : "mime une confession dramatique à [playerX] comme dans une série télé culte." , type: 8},
{ desc : "imite un personnage de dessin animé et dialogue avec [playerX]." , type: 8},
{ desc : "prends le rôle d’un coach sportif extrême et motive [playerX] à faire un exercice ridicule." , type: 8},
{ desc : "incarne un gourou spirituel et donne des conseils farfelus à [playerX]." , type: 8},
{ desc : "joue une scène d’horreur humoristique avec [playerX] dans le rôle du victime/survivant." , type: 8},
{ desc : "imite un célèbre personnage de pub pour convaincre [playerX] d’acheter un produit imaginaire." , type: 8},
{ desc : "adopte le rôle d’un influenceur extravagant et fais la promotion d’un objet insolite auprès de [playerX]." , type: 8},
{ desc : "sois un expert en séduction version années 80 et tente de charmer [playerX]." , type: 8},
{ desc : "interprète une scène romantique en duo avec [playerX], à la manière d’un soap opera." , type: 8},
{ desc : "mime une scène de retrouvailles émouvante avec [playerX] après de longues années." , type: 8},
{ desc : "deviens le présentateur d’un jeu télé et fais participer [playerX] à un “quiz” délirant." , type: 8},
{ desc : "incarne un super-héros qui sauve [playerX] d’un “danger” imaginaire." , type: 8},
{ desc : "joue le rôle d’un politicien charismatique et convaincs [playerX] de voter pour toi." , type: 8},
{ desc : "imite un chef cuisinier en direct et explique à [playerX] comment préparer une recette improbable." , type: 8},
{ desc : "fais semblant d’être en retard à un rendez-vous galant avec [playerX] et trouve une excuse farfelue." , type: 8},
{ desc : "interprète un psychanalyste extravagant et analyse en profondeur le comportement de [playerX]." , type: 8},
{ desc : "sois un guide touristique passionné et fais visiter un “lieu mythique” à [playerX] (même si c’est dans le salon)." , type: 8},
{ desc : "joue une scène de réconciliation explosive entre toi et [playerX]." , type: 8},
{ desc : "adopte le personnage d’un coach de vie ultra-motivant et donne une leçon à [playerX]." , type: 8},
{ desc : "mime une conversation téléphonique dramatique avec [playerX] qui joue le rôle de l’interlocuteur." , type: 8},
{ desc : "incarne un séducteur romantique des années 50 et tente de charmer [playerX]." , type: 8},
{ desc : "interprète un mauvais imitateur de célébrité et fais rire [playerX]." , type: 8},
{ desc : "joue un rôle d’espion infiltré et tente de soutirer un secret à [playerX]." , type: 8},
{ desc : "mime un divorce explosif avec [playerX] comme partenaire de scène." , type: 8},
{ desc : "sois un animateur de téléréalité déjanté et organise un défi ridicule avec [playerX]." , type: 8},
{ desc : "incarne un astrologue loufoque et prédis l’avenir de [playerX]." , type: 8},
{ desc : "fais semblant d’être un rockeur en pleine tournée mondiale et recrute [playerX] comme roadie." , type: 8},
{ desc : "joue une scène dramatique de retrouvailles entre ex, avec [playerX] dans le rôle opposé." , type: 8},
{ desc : "imite un célèbre humoriste en recréant une de ses sketches avec [playerX]." , type: 8},
{ desc : "mime une situation de “premier rendez-vous” catastrophique avec [playerX]." , type: 8},
{ desc : "deviens le roi/la reine du karaoke et fais une performance improvisée en duo avec [playerX]." , type: 8},
{ desc : "incarne un coach sportif motivant [playerX] dans un exercice ridicule." , type: 8},
{ desc : "prends le rôle d’un astrologue et annonce à [playerX] son “destin amoureux”." , type: 8},
{ desc : "joue un marchand de rêves et essaie de vendre un objet imaginaire à [playerX]." , type: 8},
{ desc : "mime un personnage de série dramatique qui avoue un secret à [playerX]." , type: 8},
{ desc : "incarne un célèbre imitateur d’accents et fais deviner à [playerX] de quelle région tu viens." , type: 8},
{ desc : "joue une scène de réconciliation épique avec [playerX] après une “guerre” imaginaire." , type: 8},
{ desc : "deviens un guide spirituel extravagant et donne une “leçon de vie” à [playerX]." , type: 8},
{ desc : "mime une scène de film d’action avec [playerX] comme partenaire d’aventure." , type: 8},
{ desc : "interprète un personnage de sitcom en pleine crise existentielle avec [playerX]." , type: 8},
{ desc : "imite une star de cinéma en train de recevoir un prix, et [playerX] est le présentateur officiel." , type: 8},
{ desc : "fais semblant d'être un chef cuisinier étoilé et présente un plat imaginaire à [playerX]." , type: 8},
{ desc : "incarne un horloger un peu fou qui explique à [playerX] pourquoi le temps s'arrête parfois." , type: 8},
{ desc : "deviens un astrologue mystérieux qui lit l’avenir de [playerX] dans sa tasse de café." , type: 8},
{ desc : "joue le rôle d’un vendeur de voitures de luxe et tente de convaincre [playerX] d’acheter une auto invisible." , type: 8},
{ desc : "interprète un professeur excentrique qui donne une leçon de danse à [playerX]." , type: 8},
{ desc : "incarne un agent secret en mission et demande à [playerX] de décrypter un code secret." , type: 8},
{ desc : "fais comme un rockeur déjanté et demande à [playerX] de jouer un solo de guitare imaginaire." , type: 8},
{ desc : "deviens une star de cinéma qui improvise un discours de remerciement en s’adressant à [playerX]." , type: 8},
{ desc : "prends le rôle d’un pirate moderne et demande à [playerX] de t’aider à retrouver un trésor caché." , type: 8},
{ desc : "fais semblant d’être un styliste pointilleux qui critique avec humour la tenue de [playerX]." , type: 8},
{ desc : "incarne un gourou zen qui propose une méditation absurde à [playerX]." , type: 8},
{ desc : "deviens un humoriste de stand-up qui improvise une scène comique avec [playerX] en duo." , type: 8},
{ desc : "fais semblant d’être un DJ enflammé et incite [playerX] à danser sur un rythme imaginaire." , type: 8},
{ desc : "joue le rôle d’un animateur de concours de beauté en présentant [playerX] comme concurrent(e)." , type: 8},
{ desc : "imite un sportif en pleine compétition et demande à [playerX] d’être ton coach." , type: 8},
{ desc : "fais le vendeur d’un bien immobilier fictif et essaie de convaincre [playerX] d’acheter un appartement imaginaire." , type: 8},
{ desc : "incarne un écrivain en panne d’inspiration et demande à [playerX] de lui raconter une histoire rocambolesque." , type: 8},
{ desc : "adopte le rôle d’un chef d’orchestre extravagant qui dirige [playerX] dans un morceau inventé." , type: 8},
{ desc : "joue un séducteur médiéval qui courtise [playerX] en usant de compliments en vieux français." , type: 8},
{ desc : "deviens un inventeur excentrique qui présente à [playerX] sa dernière invention farfelue." , type: 8},
{ desc : "fais le guide d’un musée imaginaire et décris une œuvre d’art fictive à [playerX]." , type: 8},
{ desc : "incarne un joueur de poker invétéré et tente de convaincre [playerX] de miser sur un bluff hilarant." , type: 8},
{ desc : "prends le rôle d’un agent de voyage qui propose à [playerX] un circuit touristique dans un lieu fictif." , type: 8},
{ desc : "deviens un romancier passionné et récite une déclaration d’amour théâtrale à [playerX]." , type: 8},
{ desc : "imite un humoriste qui transforme chaque phrase en jeu de mots, avec [playerX] réagissant à chaque punchline." , type: 8},
{ desc : "incarne un chef d’orchestre qui choisit [playerX] comme soliste pour une performance imaginaire." , type: 8},
{ desc : "fais le juge d’un concours de talents en critiquant avec exagération la prestation de [playerX]." , type: 8},
{ desc : "joue un coach de vie ultra positif qui motive [playerX] à relever un défi farfelu." , type: 8},
{ desc : "deviens un détective excentrique qui mène une enquête loufoque sur [playerX]." , type: 8},
{ desc : "incarne un présentateur météo qui annonce des prévisions aussi dramatiques qu’absurdes à [playerX]." , type: 8},
{ desc : "fais semblant d’être un scientifique fou qui explique à [playerX] pourquoi le fromage sauvera le monde." , type: 8},
{ desc : "prends le rôle d’un agent de sécurité extravagant qui interroge [playerX] sur son comportement suspect." , type: 8},
{ desc : "incarne un astronaute égaré dans l’espace et demande à [playerX] de t’aider à retrouver la Terre." , type: 8},
{ desc : "fais le critique de mode rétro qui donne des conseils improbables à [playerX]." , type: 8},
{ desc : "adopte le rôle d’un instituteur sévère et fais semblant de donner un cours à [playerX] pour être à l’heure." , type: 8},
{ desc : "incarne un vendeur de potions magiques et essaie de convaincre [playerX] d’acheter ta “potion miracle”." , type: 8},
{ desc : "joue un animateur de télé-achat en tentant de vendre un objet imaginaire à [playerX]." , type: 8},
{ desc : "fais le coach sportif décalé qui motive [playerX] à effectuer des exercices improbables." , type: 8},
{ desc : "incarne un auteur de romans policiers et raconte à [playerX] une intrigue mystérieuse autour d’un vol fictif." , type: 8},
{ desc : "deviens un mime de légende qui interagit uniquement par des gestes avec [playerX]." , type: 8},
{ desc : "prends le rôle d’un animateur de talk-show et interviewe [playerX] sur sa vie exagérée." , type: 8},
{ desc : "fais le narrateur d’un conte pour enfants en inventant une histoire rocambolesque avec [playerX]." , type: 8},
{ desc : "incarne un coach en séduction des années 70 qui donne des conseils kitsch à [playerX]." , type: 8},
{ desc : "joue le présentateur d’un concours de talents en organisant une compétition fictive avec [playerX]." , type: 8},
{ desc : "deviens un médium qui tente de contacter l’esprit de [playerX] pour révéler un secret hilarant." , type: 8},
{ desc : "fais l’imitateur de célébrités et fais deviner à [playerX] laquelle tu incarnes." , type: 8},
{ desc : "incarne un réalisateur de film qui organise une scène dramatique improvisée avec [playerX] comme vedette." , type: 8},
{ desc : "fais le sommelier excentrique qui donne une dégustation absurde à [playerX] pour un vin imaginaire." , type: 8},
{ desc : "prends le rôle d’un conseiller conjugal extravagant qui propose à [playerX] des solutions loufoques." , type: 8},
{ desc : "deviens l’animateur d’un jeu télévisé délirant et organise un « quiz de la séduction » avec [playerX] en star." , type: 8},
{ desc : "incarne un strip-teaseur extravagant qui doit charmer [playerX] avec une danse sensuelle… et décalée." , type: 8},
{ desc : "joue un sex-therapeute déjanté et propose à [playerX] une consultation « hors normes »." , type: 8},
{ desc : "adopte le rôle d’un séducteur de télé-achat, vendant à [playerX] « le kit ultime de l’amour » avec des démonstrations absurdes." , type: 8},
{ desc : "fais semblant d’être un coach en séduction vintage qui donne à [playerX] des conseils farfelus sur l’art de charmer." , type: 8},
{ desc : "incarne un espion sexy qui doit transmettre à [playerX] un message codé aux sous-entendus coquins." , type: 8},
{ desc : "joue le rôle d’un célèbre playboy des années 70 et séduit [playerX] avec des répliques pleines d’humour." , type: 8},
{ desc : "adopte l’attitude d’un expert en aphrodisiaques imaginaires et persuade [playerX] de goûter sa « potion d’amour »." , type: 8},
{ desc : "incarne un animateur de talk-show où [playerX] est l’invité spécial pour parler de ses expériences « torrides »... fictives." , type: 8},
{ desc : "fais le rôle d’un DJ sensuel qui doit faire vibrer [playerX] avec ses « beats amoureux »." , type: 8},
{ desc : "joue un personnage de roman érotique en improvisant une scène de séduction humoristique avec [playerX]." , type: 8},
{ desc : "deviens un mime charnel qui tente de faire deviner à [playerX] un geste sexy sans prononcer un mot." , type: 8},
{ desc : "incarne un professeur de « séduction avancée » qui donne un cours accéléré à [playerX]." , type: 8},
{ desc : "fais semblant d’être un consultant en image amoureuse et critique la « tenue de séduction » de [playerX] de manière décalée." , type: 8},
{ desc : "joue un personnage de film romantique décalé qui confie à [playerX] ses secrets de conquête… absurdes." , type: 8},
{ desc : "adopte le rôle d’un coach de « strip-danse » et doit enseigner à [playerX] des mouvements improbables." , type: 8},
{ desc : "incarne un romanleur de séduction qui raconte à [playerX] son ultime aventure passionnée… fictive." , type: 8},
{ desc : "fais semblant d’être un vendeur de lingerie « révolutionnaire » et propose à [playerX] un essayage insolite." , type: 8},
{ desc : "joue le rôle d’un expert en techniques de flirt improbables, donnant à [playerX] des astuces farfelues." , type: 8},
{ desc : "incarne un séducteur maladroit qui tente d’enflammer [playerX] avec des compliments exagérés." , type: 8},
{ desc : "adopte le rôle d’un acteur de films pour adultes parodiques et invite [playerX] à jouer une scène déjantée." , type: 8},
{ desc : "fais semblant d’être un influenceur du « love hacking » et donne à [playerX] des conseils improbables pour draguer." , type: 8},
{ desc : "joue un expert en positions improbables et doit expliquer à [playerX] un « move » révolutionnaire." , type: 8},
{ desc : "incarne un organisateur de soirées érotiques fictives et propose à [playerX] une « initiation » surprenante." , type: 8},
{ desc : "adopte le rôle d’un romancier érotique et récite à [playerX] une déclaration d’amour théâtrale et burlesque." , type: 8},
{ desc : "fais semblant d’être un barman spécialisé dans les cocktails aphrodisiaques et prépare à [playerX] un « breuvage de l’amour »." , type: 8},
{ desc : "joue un animateur de quiz coquin qui pose à [playerX] des questions risquées sur la séduction." , type: 8},
{ desc : "incarne un expert en massage sensuel et fait une démonstration comique sur [playerX] (mimes et tout)." , type: 8},
{ desc : "adopte le rôle d’un conseiller conjugal décalé et propose à [playerX] des « solutions d’amour » insolites." , type: 8},
{ desc : "fais semblant d’être un critique de films érotiques et demande à [playerX] de rejouer une scène culte… avec humour." , type: 8},
{ desc : "joue le rôle d’un vendeur de parfums « aphrodisiaques » et tente de convaincre [playerX] des vertus de sa fragrance imaginaire." , type: 8},
{ desc : "incarne un coach de « drague express » qui organise un atelier éclair avec [playerX]." , type: 8},
{ desc : "adopte le rôle d’un publicitaire pour des préservatifs ultra originaux et lance son spot en duo avec [playerX]." , type: 8},
{ desc : "fais semblant d’être un narrateur de conte érotique en racontant une histoire hilarante à [playerX]." , type: 8},
{ desc : "joue un personnage de bande dessinée sexy et comique qui doit conquérir [playerX] par ses répliques." , type: 8},
{ desc : "incarne un dompteur de passions exagérées et entraîne [playerX] dans un « cirque de l’amour »." , type: 8},
{ desc : "adopte le rôle d’un conseiller en séduction post-moderne et fait une analyse humoristique de la « technique du clin d’œil » pour [playerX]." , type: 8},
{ desc : "fais semblant d’être un professeur de « langues de baisers » et enseigne à [playerX] des « expressions coquines » inventées." , type: 8},
{ desc : "joue un séducteur en pleine crise existentielle qui questionne [playerX] sur le sens de la passion." , type: 8},
{ desc : "incarne un champion de la « drague olympique » et propose à [playerX] une compétition de compliments." , type: 8},
{ desc : "adopte le rôle d’un imitateur de scènes cultes de films érotiques et invite [playerX] à en jouer une parodie." , type: 8},
{ desc : "fais semblant d’être un expert en « positions improbables » et explique à [playerX] comment « renverser la gravité »." , type: 8},
{ desc : "joue le rôle d’un romancier décalé en improvisant une scène de séduction rocambolesque avec [playerX]." , type: 8},
{ desc : "incarne un gourou de l’amour libre et organise une séance de méditation « érotique » avec [playerX]." , type: 8},
{ desc : "adopte le rôle d’un vendeur de jouets coquins imaginaires et fait une démonstration humoristique à [playerX]." , type: 8},
{ desc : "fais semblant d’être un coach de « love hacking » et dévoile à [playerX] ses astuces pour un flirt instantané." , type: 8},
{ desc : "joue un séducteur maladroit qui renverse accidentellement son propre charme sur [playerX]." , type: 8},
{ desc : "incarne un animateur de karaoké coquin qui réinvente une chanson d’amour avec [playerX]." , type: 8},
{ desc : "adopte le rôle d’un narrateur de téléréalité érotique et décrit en détail (et avec humour) la rencontre fictive avec [playerX]." , type: 8},
{ desc : "fais semblant d’être un expert en « aphrodisiaques naturels » et tente d’expliquer à [playerX] comment la nature booste le désir." , type: 8},
{ desc : "joue le rôle d’un play-boy invétéré qui confie à [playerX] son « CV amoureux » plein d’anecdotes exagérées." , type: 8},


];