const carddata19 = [
{ "desc" : "Je fais semblant de ne pas être à la maison quand quelqu'un sonne à ma porte", "type":19},
{ "desc" : "J'ai déjà mangé un plat entier sans le partager alors que j'aurais dû", "type":19},
{ "desc" : "Je réponds à mes messages WhatsApp et je ne réponds pas sur Messenger volontairement", "type":19},
{ "desc" : "J'ai au moins trois applications de livraison de nourriture sur mon téléphone", "type":19},
{ "desc" : "Je regarde le fond de ma tasse après avoir bu du café", "type":19},
{ "desc" : "J'ai déjà porté les mêmes vêtements trois jours de suite", "type":19},
{ "desc" : "Je préfère les toilettes de ma maison à toutes les autres", "type":19},
{ "desc" : "J'utilise encore des CD ou des DVD de temps en temps", "type":19},
{ "desc" : "Je sens mes vêtements pour savoir s'ils sont propres", "type":19},
{ "desc" : "Je parle à mes plantes", "type":19},
{ "desc" : "J'ai déjà essayé de réparer quelque chose puis j'ai fait semblant que ce n'était pas moi quand ça a empiré", "type":19},
{ "desc" : "Je recycle seulement quand quelqu'un peut me voir", "type":19},
{ "desc" : "Je garde des sacs plastiques dans un autre sac plastique", "type":19},
{ "desc" : "Je vérifie si le frigo est vide même quand je viens juste de regarder dedans", "type":19},
{ "desc" : "J'ai déjà utilisé Google pour vérifier l'orthographe d'un mot simple", "type":19},
{ "desc" : "Je mange le morceau de gâteau le plus gros quand c'est moi qui sers", "type":19},
{ "desc" : "Je jette des déchets par la fenêtre de ma voiture", "type":19},
{ "desc" : "J'invente des excuses pour ne pas sortir quand j'ai la flemme", "type":19},
{ "desc" : "J'ai une pile de livres que je compte lire \"un jour\"", "type":19},
{ "desc" : "Je fais des listes de tâches et j'ajoute des choses déjà accomplies pour les barrer", "type":19},
{ "desc" : "J'ai déjà fait semblant de recevoir un appel pour éviter une conversation", "type":19},
{ "desc" : "Je filme les concerts au lieu de les regarder", "type":19},
{ "desc" : "J'ai un compte Instagram juste pour espionner les autres", "type":19},
{ "desc" : "Je scrolle TikTok pendant plus d'une heure d'affilée", "type":19},
{ "desc" : "J'ai déjà envoyé un message et fait semblant que c'était destiné à quelqu'un d'autre", "type":19},
{ "desc" : "Je prends en photo ma nourriture avant de manger", "type":19},
{ "desc" : "Je regarde le téléphone des autres quand ils me montrent une photo", "type":19},
{ "desc" : "J'ai déjà supprimé un commentaire après avoir reçu des réponses négatives", "type":19},
{ "desc" : "Je me suis déjà endormi avec mon téléphone dans la main", "type":19},
{ "desc" : "J'ai déjà fait un post sur les réseaux pour rendre quelqu'un jaloux", "type":19},
{ "desc" : "Je suis inscrit à Netflix mais j'utilise le compte de quelqu'un d'autre", "type":19},
{ "desc" : "J'ai déjà googlelé mon propre nom pour voir ce qu'on trouve", "type":19},
{ "desc" : "Je mets des filtres sur toutes mes photos", "type":19},
{ "desc" : "J'ai un profil LinkedIn mais je ne l'ai pas mis à jour depuis des années", "type":19},
{ "desc" : "Je réponds \"je vais réfléchir\" quand je ne comprends rien à une explication tech", "type":19},
{ "desc" : "J'ai déjà passé plus de 10 minutes à chercher le titre parfait pour une publication", "type":19},
{ "desc" : "Je fais semblant d'être occupé sur mon téléphone pour éviter les gens", "type":19},
{ "desc" : "J'ai déjà posté sur les réseaux sociaux dans les toilettes", "type":19},
{ "desc" : "Je raconte des anecdotes du web comme si elles m'étaient arrivées", "type":19},
{ "desc" : "J'ai un compte TikTok secret que mes amis ne connaissent pas", "type":19},
{ "desc" : "Je mange des chips sans faire de bruit quand quelqu'un dort à côté", "type":19},
{ "desc" : "J'ai déjà fini un pot de Nutella en moins de trois jours", "type":19},
{ "desc" : "Je prétends aimer le vin alors que je n'y connais rien", "type":19},
{ "desc" : "Je juge les gens qui mettent de l'ananas sur leur pizza", "type":19},
{ "desc" : "J'ai déjà léché l'assiette quand personne ne me regardait", "type":19},
{ "desc" : "Je mange les restes directement du tupperware", "type":19},
{ "desc" : "Je goûte la pâte à gâteau crue malgré les œufs crus", "type":19},
{ "desc" : "J'ai déjà fait semblant d'aimer un plat pour ne pas vexer la personne qui l'a cuisiné", "type":19},
{ "desc" : "Je mange les biscuits qui sont tombés par terre", "type":19},
{ "desc" : "Je mange différemment quand je suis seul", "type":19},
{ "desc" : "J'ai déjà mangé le dernier morceau et remis la boîte vide au frigo", "type":19},
{ "desc" : "Je mens sur mes allergies alimentaires pour éviter de manger certains aliments", "type":19},
{ "desc" : "J'ai déjà bu du lait directement à la bouteille", "type":19},
{ "desc" : "Je jette de la nourriture périmée sans l'ouvrir pour vérifier si elle est encore bonne", "type":19},
{ "desc" : "Je mange le dessert avant le plat principal quand je suis seul", "type":19},
{ "desc" : "J'ai un aliment \"guilty pleasure\" que je cache aux autres", "type":19},
{ "desc" : "Je mange plus vite quand j'ai cuisiné quelque chose de vraiment bon", "type":19},
{ "desc" : "J'ai déjà fait semblant d'être un connaisseur de fromage/vin/café", "type":19},
{ "desc" : "Je mange les frites du plateau des autres au fast-food", "type":19},
{ "desc" : "J'ai déjà mangé dans mon lit malgré les miettes", "type":19},
{ "desc" : "J'ai déjà tapé le nom de mon ex sur les réseaux sociaux cette semaine", "type":19},
{ "desc" : "J'ai ghosté quelqu'un au lieu de lui dire que je n'étais plus intéressé", "type":19},
{ "desc" : "J'ai fait semblant d'avoir un rendez-vous pour éviter une sortie", "type":19},
{ "desc" : "Je raconte des histoires différentes selon les groupes d'amis", "type":19},
{ "desc" : "J'ai déjà menti sur mon âge à un partenaire potentiel", "type":19},
{ "desc" : "Je parle à mes amis de mes rencards en détail", "type":19},
{ "desc" : "J'ai déjà répondu à un ex après avoir bu", "type":19},
{ "desc" : "Je prétends connaître des chansons/films/séries pour impressionner quelqu'un", "type":19},
{ "desc" : "J'ai déjà cherché le profil LinkedIn de quelqu'un avant un premier rendez-vous", "type":19},
{ "desc" : "Je juge les couples qui se disputent en public", "type":19},
{ "desc" : "J'ai déjà envoyé un message puis je l'ai regretté immédiatement", "type":19},
{ "desc" : "Je suis resté dans une relation par habitude", "type":19},
{ "desc" : "J'ai déjà prétexté une migraine pour éviter un câlin", "type":19},
{ "desc" : "Je regarde parfois le téléphone de mon/ma partenaire quand il/elle dort", "type":19},
{ "desc" : "J'ai déjà fait une liste des pour et des contre avant de quitter quelqu'un", "type":19},
{ "desc" : "Je mens sur le nombre de mes ex", "type":19},
{ "desc" : "J'ai déjà rompu par message", "type":19},
{ "desc" : "Je reste ami avec mes ex sur les réseaux sociaux pour les surveiller", "type":19},
{ "desc" : "J'ai un/une ex dont je n'arrive pas à me remettre", "type":19},
{ "desc" : "J'invente des détails quand je raconte comment j'ai rencontré mon/ma partenaire", "type":19},
{ "desc" : "J'ai déjà fait semblant d'avoir un orgasme", "type":19},
{ "desc" : "Je suis déjà resté avec quelqu'un juste pour le sexe", "type":19},
{ "desc" : "J'ai des fantasmes que je n'avoue pas à mon/ma partenaire", "type":19},
{ "desc" : "J'ai déjà fait l'amour sans me laver avant", "type":19},
{ "desc" : "Je me suis déjà masturbé en pensant à un(e) ami(e)", "type":19},
{ "desc" : "J'ai déjà regardé du porno avec mon/ma partenaire", "type":19},
{ "desc" : "Je préfère la lumière éteinte pendant les rapports", "type":19},
{ "desc" : "J'ai déjà fait une recherche sur \"comment être meilleur au lit\"", "type":19},
{ "desc" : "J'ai eu un rapport sexuel dans une salle de bain publique", "type":19},
{ "desc" : "J'ai déjà appelé quelqu'un par le mauvais prénom pendant l'acte", "type":19},
{ "desc" : "J'ai un sex toy caché", "type":19},
{ "desc" : "Je me masturbe au moins trois fois par semaine", "type":19},
{ "desc" : "J'ai déjà eu un rapport sexuel dans une voiture", "type":19},
{ "desc" : "J'ai déjà utilisé de la nourriture pendant un rapport sexuel", "type":19},
{ "desc" : "J'ai des sous-vêtements spéciaux pour les rendez-vous galants", "type":19},
{ "desc" : "J'ai déjà eu un rapport sexuel dans la maison de mes parents/beaux-parents", "type":19},
{ "desc" : "J'ai déjà envoyé des photos intimes à quelqu'un", "type":19},
{ "desc" : "J'ai déjà fait l'amour pendant mes règles/les règles de ma partenaire", "type":19},
{ "desc" : "J'ai déjà simulé l'intérêt pour un fétiche pour faire plaisir à quelqu'un", "type":19},
{ "desc" : "J'ai déjà été surpris en plein acte", "type":19},
{ "desc" : "Je fais semblant d'être au téléphone dans l'ascenseur pour éviter de parler", "type":19},
{ "desc" : "J'ai un compte secret sur un site de rencontres", "type":19},
{ "desc" : "Je cache des friandises dans des endroits improbables", "type":19},
{ "desc" : "J'ai déjà mis un réveil plus tôt pour pouvoir faire semblant de dormir encore", "type":19},
{ "desc" : "Je recule la date d'expiration de médicaments qui me semblent encore bons", "type":19},
{ "desc" : "J'ai déjà gardé un cadeau que je n'aimais pas pour le recycler plus tard", "type":19},
{ "desc" : "Je mens sur le prix des choses que j'achète", "type":19},
{ "desc" : "J'ai un pseudonyme que j'utilise pour commander au café", "type":19},
{ "desc" : "Je prends des selfies quand je me sens beau/belle mais ne les poste jamais", "type":19},
{ "desc" : "J'ai déjà fait un trajet plus long pour éviter de croiser quelqu'un", "type":19},
{ "desc" : "Je suis déjà allé faire des courses uniquement pour voir une personne qui m'intéressait", "type":19},
{ "desc" : "J'ai un compte de streaming pour regarder des séries que je ne veux pas que les autres sachent que je regarde", "type":19},
{ "desc" : "Je regarde dans les fenêtres des voisins quand je passe devant", "type":19},
{ "desc" : "J'ai déjà fouillé dans les affaires de quelqu'un quand j'étais seul chez lui/elle", "type":19},
{ "desc" : "Je bois parfois l'eau de la douche", "type":19},
{ "desc" : "J'ai déjà fait semblant de travailler alors que je ne faisais rien", "type":19},
{ "desc" : "Je me rince les dents avec de l'eau quand je n'ai pas envie de me brosser les dents", "type":19},
{ "desc" : "J'ai déjà volé des échantillons gratuits en trop grande quantité", "type":19},
{ "desc" : "Je fais des recherches sur les gens avant de les rencontrer", "type":19},
{ "desc" : "Je me parle à voix haute quand je suis seul", "type":19},
{ "desc" : "J'ai déjà changé d'opinion politique pour plaire à quelqu'un", "type":19},
{ "desc" : "Je ne lis que les titres des articles avant de les partager", "type":19},
{ "desc" : "Je me considère plus intelligent que la moyenne", "type":19},
{ "desc" : "J'ai des opinions controversées que je garde pour moi", "type":19},
{ "desc" : "Je juge les gens qui ne votent pas", "type":19},
{ "desc" : "J'ai déjà prétendu avoir lu un livre de philosophie dont je ne connais que le titre", "type":19},
{ "desc" : "Je méprise secrètement certaines professions", "type":19},
{ "desc" : "J'ai déjà fait semblant de comprendre une blague que je ne comprenais pas", "type":19},
{ "desc" : "Je fais semblant de m'intéresser à l'écologie devant certaines personnes", "type":19},
{ "desc" : "J'ai des préjugés que j'essaie de combattre", "type":19},
{ "desc" : "J'ai déjà signé une pétition sans la lire entièrement", "type":19},
{ "desc" : "Je pense que certains accents sont moins séduisants que d'autres", "type":19},
{ "desc" : "J'ai une opinion sur l'immigration que je n'assume pas publiquement", "type":19},
{ "desc" : "Je juge les parents sur l'éducation qu'ils donnent à leurs enfants", "type":19},
{ "desc" : "J'ai déjà fait un don juste pour me donner bonne conscience", "type":19},
{ "desc" : "Je pense secrètement que certaines personnes méritent ce qui leur arrive", "type":19},
{ "desc" : "J'ai déjà utilisé des arguments que je savais faux dans un débat", "type":19},
{ "desc" : "Je prétends parfois être engagé pour des causes qui ne m'intéressent pas vraiment", "type":19},
{ "desc" : "J'ai déjà participé à une manifestation plus pour l'ambiance que pour la cause", "type":19},
{ "desc" : "Je juge les gens sur leur façon de s'habiller", "type":19},
{ "desc" : "J'ai déjà fait semblant de travailler alors que je regardais des vidéos", "type":19},
{ "desc" : "Je mens sur mon salaire", "type":19},
{ "desc" : "J'ai déjà appelé malade alors que j'allais parfaitement bien", "type":19},
{ "desc" : "Je garde les pièces jaunes qu'on me rend dans ma poche au lieu de les mettre dans la tirelire caritative", "type":19},
{ "desc" : "J'ai déjà \"emprunté\" des fournitures de bureau au travail", "type":19},
{ "desc" : "Je laisse parfois les autres payer plus que leur part", "type":19},
{ "desc" : "J'ai déjà regardé ce que gagnent mes collègues", "type":19},
{ "desc" : "Je prétends avoir lu tous les emails que je n'ai pas ouverts", "type":19},
{ "desc" : "J'ai un CV avec des compétences exagérées", "type":19},
{ "desc" : "Je fais des pauses toilettes plus longues que nécessaire au travail", "type":19},
{ "desc" : "J'ai déjà pris crédit pour le travail de quelqu'un d'autre", "type":19},
{ "desc" : "Je garde la monnaie quand on me donne trop de retour", "type":19},
{ "desc" : "Je me suis déjà endormi pendant une réunion en ligne", "type":19},
{ "desc" : "J'ai un compte d'épargne secret", "type":19},
{ "desc" : "Je déteste secrètement mon travail mais je fais semblant d'aimer", "type":19},
{ "desc" : "J'ai déjà menti sur les raisons de mon retard", "type":19},
{ "desc" : "Je suis content quand une réunion est annulée", "type":19},
{ "desc" : "J'ai déjà dépensé de l'argent que je ne pouvais pas me permettre de dépenser", "type":19},
{ "desc" : "Je juge les gens qui dépensent beaucoup en produits de luxe", "type":19},
{ "desc" : "J'ai déjà fait un achat impulsif que j'ai regretté immédiatement", "type":19},
{ "desc" : "Je me pèse tous les jours", "type":19},
{ "desc" : "J'ai déjà fait semblant d'avoir une allergie pour éviter un aliment", "type":19},
{ "desc" : "Je regarde dans le miroir plus de dix fois par jour", "type":19},
{ "desc" : "J'ai déjà fait un régime sans le dire à personne", "type":19},
{ "desc" : "Je ne vais chez le médecin qu'en dernier recours", "type":19},
{ "desc" : "J'ai googlé des symptômes puis j'ai paniqué en lisant les résultats", "type":19},
{ "desc" : "Je porte des vêtements qui ne me vont pas parce qu'ils sont à la mode", "type":19},
{ "desc" : "J'ai déjà annulé un rendez-vous chez le dentiste par peur", "type":19},
{ "desc" : "Je mens sur ma taille", "type":19},
{ "desc" : "J'ai déjà fait un selfie plus de dix fois avant d'en trouver un bon", "type":19},
{ "desc" : "Je prends des médicaments sans lire la notice", "type":19},
{ "desc" : "J'ai déjà fait semblant d'avoir mal quelque part pour attirer l'attention", "type":19},
{ "desc" : "Je me regarde dans les vitres des magasins pour vérifier mon apparence", "type":19},
{ "desc" : "J'ai déjà frotté une tache sur un vêtement plutôt que de le laver", "type":19},
{ "desc" : "Je me brosse les dents différemment quand je suis chez le dentiste", "type":19},
{ "desc" : "J'ai déjà porté des sous-vêtements à l'envers par paresse", "type":19},
{ "desc" : "Je mens sur mon âge même à des gens qui ne me jugeront pas", "type":19},
{ "desc" : "J'ai déjà utilisé le déodorant de quelqu'un d'autre sans demander", "type":19},
{ "desc" : "Je regarde les autres personnes au gym pour comparer notre forme physique", "type":19},
{ "desc" : "J'ai déjà retouché mes photos pour paraître plus mince", "type":19},
{ "desc" : "J'ai déjà triché à un examen", "type":19},
{ "desc" : "Je prétends avoir lu des classiques de la littérature", "type":19},
{ "desc" : "J'ai déjà utilisé Wikipedia comme source principale pour un travail scolaire", "type":19},
{ "desc" : "Je fais semblant de connaître des références culturelles", "type":19},
{ "desc" : "J'ai déjà copié les devoirs de quelqu'un d'autre", "type":19},
{ "desc" : "Je juge les goûts musicaux des autres", "type":19},
{ "desc" : "J'ai un diplôme dont je ne me sers pas du tout", "type":19},
{ "desc" : "Je prétends parler une langue étrangère mieux que je ne le fais réellement", "type":19},
{ "desc" : "J'ai déjà fait semblant d'apprécier un film d'art et essai", "type":19},
{ "desc" : "Je regarde des documentaires juste pour pouvoir en parler", "type":19},
{ "desc" : "J'ai déjà menti sur mes notes", "type":19},
{ "desc" : "Je prétends avoir lu un livre alors que j'ai seulement vu l'adaptation en film", "type":19},
{ "desc" : "J'ai déjà fait un exposé sur un sujet que je ne maîtrisais pas du tout", "type":19},
{ "desc" : "Je juge les gens qui ne connaissent pas certaines références culturelles basiques", "type":19},
{ "desc" : "J'ai déjà dormi pendant un cours/une conférence", "type":19},
{ "desc" : "Je fais semblant de comprendre des concepts scientifiques complexes", "type":19},
{ "desc" : "Je mens sur le nombre de livres que je lis par an", "type":19},
{ "desc" : "J'ai déjà fait semblant d'aimer un genre musical pour impressionner quelqu'un", "type":19},
{ "desc" : "Je juge les fautes d'orthographe des autres alors que je fais aussi des erreurs", "type":19},
{ "desc" : "J'ai déjà fait semblant de ne pas connaître la réponse pour ne pas avoir l'air prétentieux", "type":19},
{ "desc" : "Je parle à ma voiture quand elle ne démarre pas", "type":19},
{ "desc" : "J'ai déjà mangé un aliment tombé par terre après bien plus que 5 secondes", "type":19},
{ "desc" : "Je sens mes doigts après m'être gratté certaines parties du corps", "type":19},
{ "desc" : "J'ai déjà pris une douche habillé(e) quand j'étais vraiment fatigué(e)", "type":19},
{ "desc" : "Je goûte la nourriture pour animaux par curiosité", "type":19},
{ "desc" : "J'ai déjà fait semblant de ne pas voir quelqu'un qui me saluait", "type":19},
{ "desc" : "Je sens mes vêtements sales avant de les mettre dans le panier", "type":19},
{ "desc" : "J'ai déjà enlevé un poil pubien de mon savon et continué à l'utiliser", "type":19},
{ "desc" : "Je fais des grimaces dans le miroir quand je suis seul", "type":19},
{ "desc" : "J'ai déjà fait caca dans la douche", "type":19},
{ "desc" : "Je renifle mes aisselles pour voir si j'ai besoin de déodorant", "type":19},
{ "desc" : "J'ai déjà utilisé la brosse à dents de quelqu'un d'autre sans le dire", "type":19},
{ "desc" : "Je fais semblant de m'y connaître en vin en reniflant le bouchon", "type":19},
{ "desc" : "J'ai déjà écouté aux portes pour entendre des conversations privées", "type":19},
{ "desc" : "Je me suis déjà assis sur des toilettes publiques sans mettre de papier", "type":19},
{ "desc" : "J'ai déjà fait semblant de ne pas reconnaître quelqu'un que je connaissais", "type":19},
{ "desc" : "Je me gratte les parties intimes en public en essayant d'être discret", "type":19},
{ "desc" : "J'ai déjà senti mes chaussures pour voir si elles puent", "type":19},
{ "desc" : "Je fais semblant de comprendre les paroles des chansons en langues étrangères", "type":19},
{ "desc" : "J'ai déjà mangé de la pâte à dentifrice", "type":19},
{ "desc" : "Je parle à voix haute dans ma voiture comme si j'étais dans un podcast", "type":19},
{ "desc" : "J'ai déjà pris un billet de transport sans le valider", "type":19},
{ "desc" : "Je juge les conducteurs qui ne mettent pas leur clignotant", "type":19},
{ "desc" : "J'ai déjà voyagé sans billet dans les transports en commun", "type":19},
{ "desc" : "Je change de personnalité quand je conduis", "type":19},
{ "desc" : "J'ai déjà pris un Uber pour un trajet que j'aurais pu faire à pied", "type":19},
{ "desc" : "Je mens sur l'endroit où j'ai passé mes vacances pour paraître plus intéressant", "type":19},
{ "desc" : "J'ai déjà fait semblant de dormir dans les transports pour ne pas céder ma place", "type":19},
{ "desc" : "Je prends des photos de monuments célèbres sans vraiment les regarder", "type":19},
{ "desc" : "J'ai déjà prétexté le mal des transports pour avoir la meilleure place", "type":19},
{ "desc" : "Je juge les gens qui se lèvent dès que l'avion atterrit", "type":19},
{ "desc" : "J'ai déjà menti pour obtenir un surclassement", "type":19},
{ "desc" : "Je fais semblant d'être étranger quand je suis touriste dans mon propre pays", "type":19},
{ "desc" : "J'ai déjà conduit sans permis", "type":19},
{ "desc" : "Je photographie ma nourriture en voyage plus que les paysages", "type":19},
{ "desc" : "J'ai déjà dormi à l'aéroport pour économiser une nuit d'hôtel", "type":19},
{ "desc" : "Je fais semblant de connaître le chemin quand je suis perdu", "type":19},
{ "desc" : "J'ai déjà accidentellement gardé un objet de l'hôtel qui n'était pas censé être un souvenir", "type":19},
{ "desc" : "Je déteste qu'on me parle quand j'ai mes écouteurs", "type":19},
{ "desc" : "J'ai déjà menti sur mon poids pour les bagages en avion", "type":19},
{ "desc" : "J'ai un membre de ma famille que je préfère aux autres", "type":19},
{ "desc" : "J'ai déjà fait semblant de ne pas entendre quand mes parents m'appellent", "type":19},
{ "desc" : "Je mens sur ce que je fais quand je suis seul à la maison", "type":19},
{ "desc" : "J'ai déjà fouillé dans les affaires de mes parents", "type":19},
{ "desc" : "Je garde des secrets importants que ma famille ne connaît pas", "type":19},
{ "desc" : "J'ai déjà oublié l'anniversaire d'un membre proche de ma famille", "type":19},
{ "desc" : "Je fais semblant d'apprécier les repas de famille alors que je les redoute", "type":19},
{ "desc" : "J'ai déjà menti à mes parents sur l'endroit où j'allais", "type":19},
{ "desc" : "Je dis à ma famille que je suis trop occupé alors que je veux juste être tranquille", "type":19},
{ "desc" : "J'ai déjà évité de présenter certains amis à ma famille", "type":19},
{ "desc" : "Je compare mon succès à celui de mes frères et sœurs", "type":19},
{ "desc" : "J'ai déjà lu le journal intime d'un membre de ma famille", "type":19},
{ "desc" : "Je préfère passer Noël avec mes amis plutôt qu'avec ma famille", "type":19},
{ "desc" : "J'ai déjà utilisé une excuse bidon pour éviter une réunion familiale", "type":19},
{ "desc" : "Je m'invente des rendez-vous médicaux pour quitter les réunions de famille plus tôt", "type":19},
{ "desc" : "J'ai déjà été jaloux d'un frère ou d'une sœur", "type":19},
{ "desc" : "Je juge les méthodes d'éducation de mes parents", "type":19},
{ "desc" : "J'ai déjà fait semblant de ne pas connaître la réponse à une question pour éviter d'aider", "type":19},
{ "desc" : "Je mens à ma famille sur mes habitudes quotidiennes", "type":19},
{ "desc" : "J'ai déjà caché une relation amoureuse à ma famille", "type":19},
{ "desc" : "J'ai déjà abandonné un cours parce que je n'aimais pas le prof", "type":19},
{ "desc" : "J'ai eu un crush sur un professeur", "type":19},
{ "desc" : "Je juge les gens qui posent trop de questions en cours", "type":19},
{ "desc" : "J'ai déjà été sur mon téléphone pendant tout un cours", "type":19},
{ "desc" : "Je prétends avoir fait mes devoirs quand je ne les ai pas faits", "type":19},
{ "desc" : "J'ai déjà utilisé des méthodes douteuses pour obtenir de meilleures notes", "type":19},
{ "desc" : "Je mens sur mes ambitions professionnelles", "type":19},
{ "desc" : "J'ai déjà séché les cours pour faire quelque chose de plus intéressant", "type":19},
{ "desc" : "Je juge les gens qui choisissent certaines filières", "type":19},
{ "desc" : "J'ai déjà rendu un devoir sans l'avoir relu", "type":19},
{ "desc" : "Je regarde les notes des autres pour me comparer", "type":19},
{ "desc" : "J'ai déjà inventé une excuse élaborée pour un retard", "type":19},
{ "desc" : "Je fais semblant d'être occupé pour éviter les travaux de groupe", "type":19},
{ "desc" : "J'ai déjà fait un exposé sans me préparer", "type":19},
{ "desc" : "Je fais semblant de prendre des notes alors que je dessine", "type":19},
{ "desc" : "J'ai déjà utilisé les mêmes travaux pour plusieurs cours différents", "type":19},
{ "desc" : "Je me place stratégiquement dans la salle pour être plus ou moins visible", "type":19},
{ "desc" : "J'ai déjà laissé un membre du groupe faire tout le travail", "type":19},
{ "desc" : "Je mens sur le temps que je passe à étudier", "type":19},
{ "desc" : "J'ai déjà fait semblant de ne pas comprendre pour obtenir de l'aide", "type":19},
{ "desc" : "Je fais du tri sélectif seulement quand c'est facile", "type":19},
{ "desc" : "J'ai déjà jeté une pile à la poubelle normale", "type":19},
{ "desc" : "Je laisse couler l'eau pendant que je me brosse les dents", "type":19},
{ "desc" : "J'ai déjà jeté des déchets dans la nature", "type":19},
{ "desc" : "Je prétends être écolo mais je prends ma voiture pour faire 500 mètres", "type":19},
{ "desc" : "J'ai déjà acheté une bouteille d'eau en plastique alors que j'avais ma gourde", "type":19},
{ "desc" : "Je laisse la lumière allumée quand je quitte une pièce", "type":19},
{ "desc" : "J'ai déjà fait semblant de ne pas voir un déchet que j'avais fait tomber", "type":19},
{ "desc" : "Je jette la nourriture périmée sans vérifier si elle est encore bonne", "type":19},
{ "desc" : "J'ai déjà pris l'avion pour un trajet qui aurait pu se faire en train", "type":19},
{ "desc" : "Je me douche trop longtemps", "type":19},
{ "desc" : "J'ai déjà acheté des vêtements fast-fashion tout en critiquant la surconsommation", "type":19},
{ "desc" : "Je ne vérifie pas si les produits que j'achète sont éthiques", "type":19},
{ "desc" : "J'ai déjà utilisé une paille en plastique après avoir dit que je les évitais", "type":19},
{ "desc" : "Je monte le chauffage au lieu de mettre un pull", "type":19},
{ "desc" : "J'ai déjà jeté un appareil électronique à la poubelle normale", "type":19},
{ "desc" : "Je prétends m'intéresser au réchauffement climatique mais je ne change pas mes habitudes", "type":19},
{ "desc" : "J'ai déjà acheté des fruits hors saison tout en me disant écolo", "type":19},
{ "desc" : "Je fais tourner des machines à laver à moitié vides", "type":19},
{ "desc" : "J'ai déjà imprimé des documents inutilement", "type":19},
{ "desc" : "Je mens sur la fréquence à laquelle je vais à la salle de sport", "type":19},
{ "desc" : "J'ai déjà fait semblant d'être sportif pour impressionner quelqu'un", "type":19},
{ "desc" : "Je prétends avoir fait plus de répétitions que je n'en ai fait réellement", "type":19},
{ "desc" : "J'ai déjà pris une photo à la salle sans m'entraîner sérieusement", "type":19},
{ "desc" : "Je vais à la piscine mais je ne nage presque pas", "type":19},
{ "desc" : "J'ai déjà inventé une blessure pour éviter une activité physique", "type":19},
{ "desc" : "Je porte des vêtements de sport sans faire de sport", "type":19},
{ "desc" : "J'ai déjà fait semblant de ne pas être fatigué pendant un entraînement", "type":19},
{ "desc" : "Je prétends connaître les règles d'un sport que je ne comprends pas", "type":19},
{ "desc" : "J'ai déjà exagéré mes performances sportives", "type":19},
{ "desc" : "Je choisis des activités physiques en fonction de comment je vais paraître", "type":19},
{ "desc" : "J'ai déjà fait semblant d'être fan d'une équipe pour m'intégrer", "type":19},
{ "desc" : "Je juge les gens qui font du CrossFit", "type":19},
{ "desc" : "J'ai déjà abandonné un sport après avoir acheté tout l'équipement", "type":19},
{ "desc" : "Je prends l'ascenseur pour monter un seul étage", "type":19},
{ "desc" : "J'ai déjà regardé les fesses de quelqu'un à la salle de sport", "type":19},
{ "desc" : "Je fais semblant d'être plus compétitif que je ne le suis", "type":19},
{ "desc" : "J'ai déjà triché pendant une course", "type":19},
{ "desc" : "Je prétends aimer courir alors que je déteste ça", "type":19},
{ "desc" : "J'ai déjà pris des selfies au milieu d'une randonnée difficile pour faire croire que c'était facile", "type":19},
{ "desc" : "Je mange directement dans le pot de glace", "type":19},
{ "desc" : "J'ai déjà fini les restes de quelqu'un sans demander", "type":19},
{ "desc" : "Je dis être allergique à certains aliments juste parce que je ne les aime pas", "type":19},
{ "desc" : "J'ai déjà mangé au restaurant alors que j'avais de la nourriture à la maison", "type":19},
{ "desc" : "Je goûte la nourriture au supermarché sans l'acheter", "type":19},
{ "desc" : "J'ai déjà mangé un gâteau entier en une seule fois", "type":19},
{ "desc" : "Je mange différemment selon les personnes avec qui je suis", "type":19},
{ "desc" : "J'ai déjà caché des bonbons pour ne pas les partager", "type":19},
{ "desc" : "Je juge les végétariens/végétaliens en secret", "type":19},
{ "desc" : "J'ai déjà mangé le dessert préparé pour quelqu'un d'autre", "type":19},
{ "desc" : "Je me ressers avant que tout le monde ait eu sa part", "type":19},
{ "desc" : "J'ai déjà commandé deux plats en faisant croire que l'un était pour quelqu'un d'autre", "type":19},
{ "desc" : "Je mange les pizzas avec les mains même dans un restaurant chic", "type":19},
{ "desc" : "J'ai déjà léché mes doigts en public après avoir mangé", "type":19},
{ "desc" : "Je jette la nourriture que je n'aime pas dans la poubelle des autres", "type":19},
{ "desc" : "J'ai déjà mangé un truc qui était tombé dans l'évier", "type":19},
{ "desc" : "Je prétends aimer la cuisine gastronomique alors que je préfère la junk food", "type":19},
{ "desc" : "J'ai déjà fait semblant d'aimer un plat pour ne pas vexer celui qui l'a préparé", "type":19},
{ "desc" : "Je mange les croûtes de pizza des autres quand ils les laissent", "type":19},
{ "desc" : "J'ai déjà fait un régime sans le dire à personne", "type":19},
{ "desc" : "Je regarde des émissions de télé-réalité mais je n'ose pas l'avouer", "type":19},
{ "desc" : "J'ai déjà prétendu avoir vu un film culte que je n'ai jamais vu", "type":19},
{ "desc" : "Je lis les spoilers volontairement", "type":19},
{ "desc" : "J'ai déjà passé plus de 8 heures à binge-watcher une série", "type":19},
{ "desc" : "Je mens sur les livres que j'ai lus", "type":19},
{ "desc" : "J'ai déjà fait semblant de ne pas connaître une chanson populaire pour paraître cool", "type":19},
{ "desc" : "Je regarde les mêmes séries en boucle plutôt que d'en découvrir de nouvelles", "type":19},
{ "desc" : "J'ai déjà prétendu aimer un genre de musique pour impressionner quelqu'un", "type":19},
{ "desc" : "Je zappe les génériques dès que possible", "type":19},
{ "desc" : "J'ai déjà regardé la fin d'un film avant de le commencer", "type":19},
{ "desc" : "Je juge les goûts musicaux des autres", "type":19},
{ "desc" : "J'ai déjà fait semblant de comprendre un film d'art et essai", "type":19},
{ "desc" : "Je prétends lire des livres que je n'ai jamais ouverts", "type":19},
{ "desc" : "J'ai déjà regardé un film en entier sans comprendre l'intrigue", "type":19},
{ "desc" : "Je choisis des films en fonction de leur durée plutôt que de leur qualité", "type":19},
{ "desc" : "J'ai déjà fait semblant d'avoir lu un livre dont j'ai seulement lu le résumé", "type":19},
{ "desc" : "Je regarde des vidéos YouTube en cachette pendant les réunions", "type":19},
{ "desc" : "J'ai déjà inventé une opinion sur un film que je n'ai jamais vu", "type":19},
{ "desc" : "Je prétends connaître les paroles des chansons alors que je marmonne", "type":19},
{ "desc" : "J'ai déjà ri à une blague que je n'ai pas comprise", "type":19},
{ "desc" : "Je pratique des conversations importantes dans ma tête avant de les avoir", "type":19},
{ "desc" : "J'ai déjà fait semblant de reconnaître quelqu'un qui me parlait comme si on se connaissait", "type":19},
{ "desc" : "Je prétends être occupé sur mon téléphone pour éviter les interactions sociales", "type":19},
{ "desc" : "J'ai déjà fait un compliment que je ne pensais pas juste pour être poli", "type":19},
{ "desc" : "Je regrette immédiatement la plupart de mes invitations après les avoir lancées", "type":19},
{ "desc" : "J'ai déjà prétendu avoir un empêchement pour annuler un rendez-vous", "type":19},
{ "desc" : "Je souris et hoche la tête quand je n'entends pas ce que quelqu'un me dit", "type":19},
{ "desc" : "J'ai déjà fait semblant d'être malade pour éviter une soirée", "type":19},
{ "desc" : "Je mens sur mes centres d'intérêt pour paraître plus intéressant", "type":19},
{ "desc" : "J'ai déjà inventé une histoire pour impressionner des inconnus", "type":19},
{ "desc" : "Je dis \"on doit se voir bientôt\" sans avoir l'intention de le faire", "type":19},
{ "desc" : "J'ai déjà fait semblant de ne pas voir quelqu'un pour éviter de lui parler", "type":19},
{ "desc" : "Je prétends connaître une célébrité de loin", "type":19},
{ "desc" : "J'ai déjà ri à une blague raciste/sexiste par malaise", "type":19},
{ "desc" : "Je raconte les mêmes anecdotes à différents groupes d'amis", "type":19},
{ "desc" : "J'ai déjà fait semblant d'être au téléphone pour éviter quelqu'un", "type":19},
{ "desc" : "Je change légèrement de personnalité selon les personnes avec qui je suis", "type":19},
{ "desc" : "J'ai déjà fait semblant d'être intéressé par la vie de quelqu'un", "type":19},
{ "desc" : "Je m'invente des excuses pour partir tôt d'une soirée ennuyeuse", "type":19},
{ "desc" : "J'ai déjà prétendu ne pas voir un message pour ne pas avoir à répondre", "type":19},
{ "desc" : "Je sens mes pets quand je suis seul", "type":19},
{ "desc" : "J'ai déjà reniflé mes sous-vêtements pour voir s'ils étaient portables", "type":19},
{ "desc" : "Je parle à voix haute quand je suis seul", "type":19},
{ "desc" : "J'ai déjà fait caca chez quelqu'un et tiré plusieurs fois la chasse pour cacher le bruit", "type":19},
{ "desc" : "Je regarde mes crottes de nez après les avoir enlevées", "type":19},
{ "desc" : "J'ai déjà fait semblant de ne pas être responsable d'une mauvaise odeur", "type":19},
{ "desc" : "Je fais craquer différentes parties de mon corps en public", "type":19},
{ "desc" : "J'ai déjà goûté ma propre sueur par curiosité", "type":19},
{ "desc" : "Je sens mon nombril de temps en temps", "type":19},
{ "desc" : "J'ai déjà jeté des vêtements sales plutôt que de les laver", "type":19},
{ "desc" : "Je me gratte et je renifle mes doigts après", "type":19},
{ "desc" : "J'ai déjà utilisé le même mouchoir plusieurs fois", "type":19},
{ "desc" : "Je mange mes peaux mortes/cuticules", "type":19},
{ "desc" : "J'ai déjà feuilleté un magazine après être allé aux toilettes sans me laver les mains", "type":19},
{ "desc" : "Je chante sous la douche à tue-tête", "type":19},
{ "desc" : "J'ai déjà mangé quelque chose qui était tombé dans les toilettes (avant la chasse)", "type":19},
{ "desc" : "Je passe trop de temps à regarder mes boutons dans le miroir", "type":19},
{ "desc" : "J'ai déjà porté les mêmes chaussettes plusieurs jours de suite", "type":19},
{ "desc" : "Je mange parfois avec les doigts même quand ce n'est pas approprié", "type":19},
{ "desc" : "J'ai déjà gardé un chewing-gum toute une journée", "type":19},
{ "desc" : "Je juge les gens sur leur grammaire dans les messages", "type":19},
{ "desc" : "J'ai déjà fait une blague sur un sujet sensible au mauvais moment", "type":19},
{ "desc" : "Je fais semblant d'être politiquement correct devant certaines personnes", "type":19},
{ "desc" : "J'ai déjà regardé quelqu'un à cause de son apparence physique", "type":19},
{ "desc" : "Je me moque parfois des accents étrangers", "type":19},
{ "desc" : "J'ai déjà fait semblant d'être indigné par quelque chose qui ne me dérange pas", "type":19},
{ "desc" : "Je juge les parents dont les enfants font une crise en public", "type":19},
{ "desc" : "J'ai déjà fait semblant d'être plus tolérant que je ne le suis", "type":19},
{ "desc" : "Je fais parfois des suppositions sur les gens basées sur des stéréotypes", "type":19},
{ "desc" : "J'ai déjà ri d'une blague que je savais offensante", "type":19},
{ "desc" : "Je change de trottoir quand je vois certains types de personnes", "type":19},
{ "desc" : "J'ai déjà fait semblant d'avoir une opinion plus progressiste en public", "type":19},
{ "desc" : "Je juge les étrangers qui ne parlent pas bien ma langue", "type":19},
{ "desc" : "J'ai déjà présumé de la sexualité de quelqu'un à son apparence", "type":19},
{ "desc" : "Je prétends être à l'aise avec tous les sujets mais certains me mettent mal à l'aise", "type":19},
{ "desc" : "J'ai déjà fait semblant de comprendre un accent que je ne comprenais pas", "type":19},
{ "desc" : "Je juge les couples avec une grande différence d'âge", "type":19},
{ "desc" : "J'ai déjà fait semblant d'être pauvre/riche selon la situation", "type":19},
{ "desc" : "Je regarde avec insistance les personnes très grandes/petites", "type":19},
{ "desc" : "J'ai déjà fait une blague sur un handicap", "type":19},
{ "desc" : "Je me demande parfois si je vis dans une simulation", "type":19},
{ "desc" : "J'ai déjà parlé à Dieu/l'univers dans un moment difficile", "type":19},
{ "desc" : "Je crois secrètement aux horoscopes", "type":19},
{ "desc" : "J'ai déjà fait un rituel superstitieux \"juste au cas où\"", "type":19},
{ "desc" : "Je me demande ce que les autres pensent de moi plusieurs fois par jour", "type":19},
{ "desc" : "J'ai déjà blâmé le destin pour mes propres erreurs", "type":19},
{ "desc" : "Je crois à certaines théories du complot", "type":19},
{ "desc" : "J'ai déjà consulté un médium/voyant", "type":19},
{ "desc" : "Je parle à des proches décédés", "type":19},
{ "desc" : "J'ai déjà fait un pacte avec moi-même du type \"si ceci arrive, alors...\"", "type":19},
{ "desc" : "Je me demande si mes amis m'apprécient vraiment", "type":19},
{ "desc" : "J'ai déjà fait une liste de ce que je ferais si j'avais un an à vivre", "type":19},
{ "desc" : "Je crois aux fantômes mais je ne l'avoue pas", "type":19},
{ "desc" : "J'ai déjà imaginé ma propre cérémonie funéraire", "type":19},
{ "desc" : "Je me demande si je suis le seul à avoir certaines pensées bizarres", "type":19},
{ "desc" : "J'ai déjà eu peur que mes appareils électroniques m'écoutent", "type":19},
{ "desc" : "Je crois en une forme de karma", "type":19},
{ "desc" : "J'ai déjà pris une décision importante basée sur un signe du destin", "type":19},
{ "desc" : "Je me demande ce que je ferais en cas d'apocalypse zombie", "type":19},
{ "desc" : "J'ai déjà inventé une vie alternative où j'aurais fait des choix différents", "type":19},
{ "desc" : "Je ne me lave pas les mains après avoir fait pipi chez moi", "type":19},
{ "desc" : "J'ai déjà utilisé la serviette de quelqu'un d'autre", "type":19},
{ "desc" : "Je vérifie l'aspect de mes selles dans les toilettes", "type":19},
{ "desc" : "J'ai déjà fait pipi sous la douche", "type":19},
{ "desc" : "Je me nettoie les oreilles avec autre chose que des cotons-tiges", "type":19},
{ "desc" : "J'ai déjà utilisé du shampoing comme gel douche (ou l'inverse)", "type":19},
{ "desc" : "Je me regarde dans le miroir en faisant des poses", "type":19},
{ "desc" : "J'ai déjà utilisé une brosse à dents qui est tombée par terre", "type":19},
{ "desc" : "Je fais pipi dans la douche pour économiser de l'eau", "type":19},
{ "desc" : "J'ai déjà utilisé du papier toilette public pour me moucher", "type":19},
{ "desc" : "Je ne change pas mes draps aussi souvent que je le devrais", "type":19},
{ "desc" : "J'ai déjà utilisé du dentifrice qui n'était pas le mien", "type":19},
{ "desc" : "Je me pèse avant et après être allé aux toilettes", "type":19},
{ "desc" : "J'ai déjà fait caca et réalisé qu'il n'y avait plus de papier toilette", "type":19},
{ "desc" : "Je sens l'odeur de mon propre pet", "type":19},
{ "desc" : "J'ai déjà pris un bain sans me laver ensuite sous la douche", "type":19},
{ "desc" : "Je ne lave pas mon pyjama assez souvent", "type":19},
{ "desc" : "J'ai déjà utilisé les toilettes pendant que quelqu'un se douchait", "type":19},
{ "desc" : "Je ne me lave pas les mains avant de cuisiner", "type":19},
{ "desc" : "J'ai déjà utilisé du parfum pour masquer le fait que je ne m'étais pas lavé", "type":19},
{ "desc" : "Je parle à mon animal de compagnie comme s'il comprenait tout", "type":19},
{ "desc" : "J'ai déjà fait semblant d'aimer l'animal de quelqu'un alors que je le trouvais insupportable", "type":19},
{ "desc" : "Je permets à mon animal de faire des choses que je critique chez les animaux des autres", "type":19},
{ "desc" : "J'ai déjà donné de la nourriture humaine à un animal qui ne devrait pas en manger", "type":19},
{ "desc" : "Je prétends aimer les randonnées mais je déteste ça", "type":19},
{ "desc" : "J'ai déjà fait semblant d'avoir peur d'un insecte pour paraître mignon/vulnérable", "type":19},
{ "desc" : "Je préfère mon animal de compagnie à certains membres de ma famille", "type":19},
{ "desc" : "J'ai déjà fait semblant d'avoir un intérêt pour la nature pour impressionner quelqu'un", "type":19},
{ "desc" : "Je parle avec une voix bizarre à mon animal", "type":19},
{ "desc" : "J'ai déjà pris une photo d'un animal sauvage en l'approchant trop près", "type":19},
{ "desc" : "Je fais semblant d'être un amoureux de la nature mais je déteste le camping", "type":19},
{ "desc" : "J'ai déjà nourri des animaux sauvages alors que c'est interdit", "type":19},
{ "desc" : "Je laisse mon animal dormir dans mon lit même si je sais que c'est mauvais", "type":19},
{ "desc" : "J'ai déjà fait semblant de ne pas voir mon chien faire ses besoins pour ne pas ramasser", "type":19},
{ "desc" : "Je prétends être écolo mais je ne connais pas la différence entre recyclable et compostable", "type":19},
{ "desc" : "J'ai déjà exagéré l'intelligence de mon animal", "type":19},
{ "desc" : "Je donne des noms aux animaux sauvages que je vois régulièrement", "type":19},
{ "desc" : "J'ai déjà fait semblant de ne pas avoir peur d'un animal dont j'avais peur", "type":19},
{ "desc" : "Je préfère les animaux aux humains", "type":19},
{ "desc" : "J'ai déjà ramené chez moi un animal ou une plante d'un lieu protégé", "type":19},
{ "desc" : "Je fais semblant de comprendre comment fonctionne le cloud", "type":19},
{ "desc" : "J'ai déjà fait croire que j'étais expert en informatique alors que j'ai juste fait redémarrer l'appareil", "type":19},
{ "desc" : "Je prétends ne pas être accro à mon téléphone", "type":19},
{ "desc" : "J'ai déjà fait semblant de recevoir un appel pour éviter une situation", "type":19},
{ "desc" : "Je mens sur le temps que je passe sur les réseaux sociaux", "type":19},
{ "desc" : "J'ai déjà fait croire que je savais coder alors que je copie-colle du Stack Overflow", "type":19},
{ "desc" : "Je juge les gens qui ont un téléphone/ordinateur plus ancien que le mien", "type":19},
{ "desc" : "J'ai déjà prétendu comprendre le Bitcoin alors que je n'y connais rien", "type":19},
{ "desc" : "Je fais semblant de lire les conditions d'utilisation", "type":19},
{ "desc" : "J'ai déjà pris une photo d'un écran au lieu de faire une capture d'écran", "type":19},
{ "desc" : "Je tape plus fort sur mon clavier quand je suis énervé", "type":19},
{ "desc" : "J'ai déjà fait semblant de savoir utiliser un logiciel au travail", "type":19},
{ "desc" : "Je prétends être déconnecté quand je suis en vacances mais je vérifie mes mails", "type":19},
{ "desc" : "J'ai déjà utilisé \"problème technique\" comme excuse pour un retard", "type":19},
{ "desc" : "Je nettoie mon téléphone juste avant de le montrer à quelqu'un", "type":19},
{ "desc" : "J'ai déjà supprimé l'historique de mon navigateur par précaution", "type":19},
{ "desc" : "Je dis \"on s'appelle\" alors que je préfère envoyer des messages", "type":19},
{ "desc" : "J'ai déjà fait semblant de savoir réparer un appareil électronique", "type":19},
{ "desc" : "Je prétends ne pas être accro aux réseaux sociaux", "type":19},
{ "desc" : "J'ai déjà menti sur mes compétences technologiques pour impressionner quelqu'un", "type":19},
{ "desc" : "J'ai déjà fait semblant d'être somnambule pour manger des gâteaux la nuit", "type":19},
{ "desc" : "J'ai donné un nom à une partie de mon corps", "type":19},
{ "desc" : "Je me suis déjà caché dans un placard pour faire peur à quelqu'un", "type":19},
{ "desc" : "J'ai essayé de lécher mon coude plus de 10 fois dans ma vie", "type":19},
{ "desc" : "Je me suis déjà endormi sur les toilettes", "type":19},
{ "desc" : "J'ai déjà porté des vêtements à l'envers toute une journée sans m'en rendre compte", "type":19},
{ "desc" : "Je me suis déjà brossé les dents avec mon doigt faute de brosse à dents", "type":19},
{ "desc" : "J'ai déjà parlé à un objet inanimé en lui donnant un nom", "type":19},
{ "desc" : "Je me suis déjà pris en photo avec une statue en position compromettante", "type":19},
{ "desc" : "J'ai tenté d'attraper quelque chose qui tombait et j'ai tout fait tomber encore plus", "type":19},
{ "desc" : "Je me suis déjà coiffé avec un aspirateur par curiosité", "type":19},
{ "desc" : "J'ai léché un aliment dans un magasin puis l'ai remis en rayon", "type":19},
{ "desc" : "Je me suis déjà enfermé dehors en sous-vêtements", "type":19},
{ "desc" : "J'ai eu une conversation sérieuse avec mon reflet dans le miroir", "type":19},
{ "desc" : "Je me suis déjà endormi au cinéma et j'ai ronflé bruyamment", "type":19},
{ "desc" : "J'ai mangé de la pâte à modeler ou de la colle étant adulte", "type":19},
{ "desc" : "Je me suis déjà assis sur la cuvette des toilettes sans vérifier s'il y avait du papier", "type":19},
{ "desc" : "J'ai goûté la nourriture pour chat/chien par curiosité", "type":19},
{ "desc" : "Je me suis déjà pris pour un superhéros sous la douche", "type":19},
{ "desc" : "J'ai fait semblant d'être une statue dans un lieu public", "type":19},
{ "desc" : "J'ai déjà fait l'amour dans une piscine/jacuzzi", "type":19},
{ "desc" : "J'ai eu un rapport sexuel dans une voiture garée dans un lieu public", "type":19},
{ "desc" : "Je me suis déjà masturbé dans les toilettes au travail/à l'école", "type":19},
{ "desc" : "J'ai déjà utilisé un objet non prévu à cet effet comme sex toy", "type":19},
{ "desc" : "Je me suis déjà filmé pendant un acte sexuel", "type":19},
{ "desc" : "J'ai eu un rapport sexuel pendant que d'autres personnes dormaient dans la même pièce", "type":19},
{ "desc" : "Je me masturbe en pensant aux amis de mon/ma partenaire", "type":19},
{ "desc" : "J'ai déjà fait l'amour dans la maison de mes parents pendant qu'ils étaient là", "type":19},
{ "desc" : "Je me suis déjà endormi pendant un acte sexuel", "type":19},
{ "desc" : "J'ai fait semblant d'avoir un orgasme pour en finir plus vite", "type":19},
{ "desc" : "Je me suis déjà masturbé en regardant par la fenêtre", "type":19},
{ "desc" : "J'ai eu un rapport sexuel sur un balcon/terrasse", "type":19},
{ "desc" : "Je me suis déjà fait surprendre en plein acte par quelqu'un", "type":19},
{ "desc" : "J'ai regardé du porno avec le son trop fort par accident", "type":19},
{ "desc" : "Je me suis déjà masturbé avec un fruit/légume", "type":19},
{ "desc" : "J'ai eu une érection/excitation dans un lieu très inapproprié", "type":19},
{ "desc" : "Je me suis déjà masturbé plusieurs fois dans la même journée", "type":19},
{ "desc" : "J'ai déjà appelé mon/ma partenaire par le mauvais prénom pendant l'acte", "type":19},
{ "desc" : "Je possède un jouet sexuel que personne ne connaît", "type":19},
{ "desc" : "J'ai déjà fait l'amour dans une tente avec d'autres personnes à proximité", "type":19},
{ "desc" : "J'ai marché avec du papier toilette collé à ma chaussure", "type":19},
{ "desc" : "J'ai raconté une blague et personne n'a ri", "type":19},
{ "desc" : "J'ai déjà confondu un inconnu avec un ami et lui ai tapé sur l'épaule", "type":19},
{ "desc" : "J'ai envoyé un message coquin à la mauvaise personne", "type":19},
{ "desc" : "J'ai déjà appelé mon prof \"maman\" ou \"papa\"", "type":19},
{ "desc" : "J'ai fait un bruit embarrassant lors d'un moment de silence", "type":19},
{ "desc" : "J'ai déjà perdu mon maillot de bain en plongeant", "type":19},
{ "desc" : "J'ai confondu un homme enceinte avec une femme enceinte", "type":19},
{ "desc" : "J'ai déjà renversé une boisson sur quelqu'un d'important", "type":19},
{ "desc" : "J'ai eu une tache visible sur mes vêtements toute une journée sans m'en rendre compte", "type":19},
{ "desc" : "J'ai parlé à quelqu'un qui portait des écouteurs et ne m'entendait pas", "type":19},
{ "desc" : "J'ai déjà oublié le nom de quelqu'un que je fréquentais", "type":19},
{ "desc" : "J'ai été surpris en train de me curer le nez en public", "type":19},
{ "desc" : "J'ai déjà fait un câlin à quelqu'un qui tendait juste la main pour me saluer", "type":19},
{ "desc" : "J'ai parlé en mal de quelqu'un qui se trouvait juste derrière moi", "type":19},
{ "desc" : "J'ai eu une érection visible pendant une présentation", "type":19},
{ "desc" : "J'ai déjà confondu la porte des toilettes hommes/femmes", "type":19},
{ "desc" : "J'ai marché avec la braguette ouverte pendant des heures", "type":19},
{ "desc" : "J'ai été pris en photo dans une position embarrassante", "type":19},
{ "desc" : "J'ai appelé mon partenaire actuel par le nom d'un ex", "type":19},
{ "desc" : "J'ai déjà fantasmé sur un personnage de dessin animé/jeu vidéo", "type":19},
{ "desc" : "J'aimerais faire l'amour dans un avion", "type":19},
{ "desc" : "J'ai déjà été excité par un scénario BDSM", "type":19},
{ "desc" : "J'aimerais participer à un plan à trois", "type":19},
{ "desc" : "J'ai déjà fantasmé sur un professeur/patron", "type":19},
{ "desc" : "J'aimerais essayer les jeux de rôle sexuels", "type":19},
{ "desc" : "J'ai déjà été excité par quelqu'un qui portait un uniforme", "type":19},
{ "desc" : "J'aimerais faire l'amour sur une plage déserte", "type":19},
{ "desc" : "J'ai déjà fantasmé sur une personne du même sexe (si hétéro) ou du sexe opposé (si homo)", "type":19},
{ "desc" : "J'aimerais essayer le sexe tantrique", "type":19},
{ "desc" : "J'ai déjà été excité par un film non pornographique", "type":19},
{ "desc" : "J'aimerais faire l'amour dans un lieu sacré/religieux", "type":19},
{ "desc" : "J'ai déjà fantasmé sur une personne que je déteste", "type":19},
{ "desc" : "J'aimerais essayer le sexe avec des menottes/contraintes", "type":19},
{ "desc" : "J'ai déjà été excité par un accent particulier", "type":19},
{ "desc" : "J'aimerais faire l'amour dans un lieu interdit ou risqué", "type":19},
{ "desc" : "J'ai déjà fantasmé sur quelqu'un beaucoup plus âgé/jeune que moi", "type":19},
{ "desc" : "J'aimerais essayer les jouets sexuels télécommandés en public", "type":19},
{ "desc" : "J'ai déjà été excité par quelqu'un qui lisait un livre", "type":19},
{ "desc" : "J'aimerais essayer le sexe en apesanteur", "type":19},
{ "desc" : "J'ai déjà mangé un pot de glace entier en une seule fois", "type":19},
{ "desc" : "J'ai léché le plateau quand personne ne regardait", "type":19},
{ "desc" : "Je me suis déjà réveillé à 3h du matin pour manger en cachette", "type":19},
{ "desc" : "J'ai mangé les derniers biscuits et remis la boîte vide dans le placard", "type":19},
{ "desc" : "Je cache de la nourriture dans ma chambre", "type":19},
{ "desc" : "J'ai déjà mangé les restes froids directement du frigo à 2h du matin", "type":19},
{ "desc" : "Je commande deux desserts au restaurant en prétendant qu'un est pour quelqu'un d'autre", "type":19},
{ "desc" : "J'ai déjà fini le plat de quelqu'un qui était aux toilettes", "type":19},
{ "desc" : "Je mange parfois le glaçage du gâteau en laissant le reste", "type":19},
{ "desc" : "J'ai déjà mangé une pizza entière seul en une seule fois", "type":19},
{ "desc" : "Je mange les frites tombées dans l'emballage de mon burger", "type":19},
{ "desc" : "J'ai déjà mangé quelque chose qui était clairement étiqueté au nom de quelqu'un d'autre", "type":19},
{ "desc" : "Je me suis déjà resservi trois fois à un buffet à volonté", "type":19},
{ "desc" : "J'ai mangé du chocolat caché dans la salle de bain", "type":19},
{ "desc" : "Je prends plus que ma part quand je sers les portions", "type":19},
{ "desc" : "J'ai déjà mangé le gâteau d'anniversaire avant la fête", "type":19},
{ "desc" : "Je me suis réveillé avec des miettes dans mon lit sans me souvenir d'avoir mangé", "type":19},
{ "desc" : "J'ai déjà léché l'assiette d'une tarte après l'avoir mangée", "type":19},
{ "desc" : "Je mange des aliments périmés quand j'ai vraiment faim", "type":19},
{ "desc" : "J'ai déjà mangé directement du pot avec la grande cuillère", "type":19},
{ "desc" : "J'ai déjà regardé du porno de niche dont j'ai honte", "type":19},
{ "desc" : "J'ai cherché des positions sexuelles impossibles à réaliser", "type":19},
{ "desc" : "Je me suis déjà masturbé avec un objet étrange juste pour voir", "type":19},
{ "desc" : "J'ai déjà fait des recherches sur des pratiques sexuelles extrêmes par curiosité", "type":19},
{ "desc" : "Je me suis déjà filmé pour voir à quoi je ressemble pendant l'acte", "type":19},
{ "desc" : "J'ai déjà comparé mes parties intimes à celles des acteurs pornos", "type":19},
{ "desc" : "Je me suis déjà masturbé avec des fruits/légumes pour tester les sensations", "type":19},
{ "desc" : "J'ai regardé du porno gay/lesbien même si ce n'est pas mon orientation", "type":19},
{ "desc" : "Je me suis déjà touché en cachette sous une couverture en présence d'autres personnes", "type":19},
{ "desc" : "J'ai déjà essayé de me lécher moi-même", "type":19},
{ "desc" : "Je me suis déjà masturbé en écoutant mes voisins faire l'amour", "type":19},
{ "desc" : "J'ai cherché à quoi ressemblaient les parties intimes de célébrités", "type":19},
{ "desc" : "Je me suis déjà enduit le corps d'une substance bizarre pour des raisons sexuelles", "type":19},
{ "desc" : "J'ai déjà essayé de me donner du plaisir avec un jet d'eau", "type":19},
{ "desc" : "Je suis déjà resté éveillé toute la nuit à regarder du porno", "type":19},
{ "desc" : "J'ai déjà essayé d'imiter les bruits des films pornos", "type":19},
{ "desc" : "Je me suis déjà masturbé plusieurs fois de suite pour voir combien de fois je pouvais le faire", "type":19},
{ "desc" : "J'ai regardé des vidéos porno étrangères sans comprendre ce qu'ils disaient", "type":19},
{ "desc" : "Je me suis déjà masturbé en public sous mes vêtements", "type":19},
{ "desc" : "J'ai déjà été excité par un dessin animé/anime", "type":19},
{ "desc" : "Je donne des noms à mes plantes", "type":19},
{ "desc" : "J'ai une conversation entière avec moi-même quand je suis seul", "type":19},
{ "desc" : "Je fais semblant d'être dans un clip vidéo quand j'écoute de la musique", "type":19},
{ "desc" : "J'ai un rituel étrange avant de me coucher", "type":19},
{ "desc" : "Je parle à ma voiture/mon ordinateur quand ils ne fonctionnent pas", "type":19},
{ "desc" : "J'ai une chanson que je chante sur les toilettes", "type":19},
{ "desc" : "Je danse comme un fou quand personne ne me regarde", "type":19},
{ "desc" : "J'ai déjà léché un objet pour marquer ma propriété", "type":19},
{ "desc" : "Je fais des grimaces dans les surfaces réfléchissantes en public", "type":19},
{ "desc" : "J'ai un doudou/peluche caché même à l'âge adulte", "type":19},
{ "desc" : "Je pratique des scénarios de zombie apocalypse dans ma tête", "type":19},
{ "desc" : "J'ai une voix spéciale pour parler à certains objets", "type":19},
{ "desc" : "Je sens mes vêtements avant de les porter même s'ils sont propres", "type":19},
{ "desc" : "J'ai des conversations imaginaires sous la douche", "type":19},
{ "desc" : "Je goûte des combinaisons d'aliments bizarres quand personne ne regarde", "type":19},
{ "desc" : "J'ai déjà crié dans un oreiller pour me défouler", "type":19},
{ "desc" : "Je fais des bruits d'animaux quand je suis seul", "type":19},
{ "desc" : "J'ai une collection de choses inutiles que je n'ose pas jeter", "type":19},
{ "desc" : "Je me déguise parfois juste pour me regarder dans le miroir", "type":19},
{ "desc" : "J'ai déjà léché une pile 9V pour sentir le petit choc", "type":19},
{ "desc" : "Nous avons déjà fait l'amour avec un film en arrière-plan que nous regardions quand même", "type":19},
{ "desc" : "J'ai déjà prétexté un mal de tête pour éviter un rapport sexuel", "type":19},
{ "desc" : "Nous avons fait l'amour en gardant certains vêtements par paresse", "type":19},
{ "desc" : "J'ai déjà envoyé une photo sexy à mon/ma partenaire alors que nous étions dans la même pièce", "type":19},
{ "desc" : "Nous avons fait l'amour sans préliminaires parce qu'on voulait juste dormir après", "type":19},
{ "desc" : "J'ai déjà fait semblant de m'intéresser aux hobbies de mon/ma partenaire pour du sexe", "type":19},
{ "desc" : "Nous avons fait l'amour sans nous embrasser une seule fois", "type":19},
{ "desc" : "J'ai déjà planifié le sexe dans mon agenda comme une tâche", "type":19},
{ "desc" : "Nous avons fait l'amour en chuchotant pour ne pas réveiller le chat/chien", "type":19},
{ "desc" : "J'ai déjà fantasmé sur quelqu'un d'autre pendant l'acte", "type":19},
{ "desc" : "Nous avons fait l'amour avec nos chaussettes parce qu'il faisait froid", "type":19},
{ "desc" : "J'ai déjà regardé mon téléphone pendant que mon/ma partenaire ne me voyait pas", "type":19},
{ "desc" : "Nous avons fait l'amour en évitant certaines positions à cause de nos courbatures", "type":19},
{ "desc" : "J'ai déjà fait semblant de ne pas être fatigué pour satisfaire mon/ma partenaire", "type":19},
{ "desc" : "Nous avons déjà ri pendant l'acte à cause d'un bruit corporel embarrassant", "type":19},
{ "desc" : "J'ai déjà pensé à mes tâches ménagères pendant l'acte", "type":19},
{ "desc" : "Nous avons fait l'amour sur le canapé pour ne pas avoir à changer les draps", "type":19},
{ "desc" : "J'ai déjà calculé combien de temps jusqu'à la fin pendant l'acte", "type":19},
{ "desc" : "Nous avons fait l'amour en silence complet pour ne pas alerter les voisins", "type":19},
{ "desc" : "J'ai déjà fait semblant d'aimer une pratique sexuelle juste pour faire plaisir", "type":19},
{ "desc" : "J'ai déjà fait semblant de prendre un selfie pour me regarder dans l'appareil photo", "type":19},
{ "desc" : "Je prends en photo ma nourriture mais ne la poste jamais", "type":19},
{ "desc" : "J'ai des conversations entières avec des assistants vocaux quand je m'ennuie", "type":19},
{ "desc" : "Je fais des recherches sur des sujets bizarres juste pour perturber mon algorithme publicitaire", "type":19},
{ "desc" : "J'ai déjà pris une photo de mes parties intimes (pas mon visage) pour voir à quoi elles ressemblent", "type":19},
{ "desc" : "Je regarde des vidéos de satisfying content pendant des heures", "type":19},
{ "desc" : "J'ai déjà stalké le profil d'un ex jusqu'à ses toutes premières publications", "type":19},
{ "desc" : "Je parle différemment quand j'enregistre un message vocal", "type":19},
{ "desc" : "J'ai déjà googlé des questions vraiment stupides en mode navigation privée", "type":19},
{ "desc" : "Je prends des selfies en faisant des grimaces que je ne montre à personne", "type":19},
{ "desc" : "J'ai déjà parlé à Siri/Alexa de mes problèmes personnels", "type":19},
{ "desc" : "Je fais semblant de travailler sur mon ordinateur alors que je regarde des mèmes", "type":19},
{ "desc" : "J'ai déjà ri tout seul en regardant mon téléphone dans un lieu public", "type":19},
{ "desc" : "Je scrolle les réseaux sociaux aux toilettes jusqu'à ne plus sentir mes jambes", "type":19},
{ "desc" : "J'ai déjà utilisé des filtres beauté même pour des photos banales", "type":19},
{ "desc" : "Je mémorise des réponses intelligentes pour les utiliser dans des conversations futures", "type":19},
{ "desc" : "J'ai déjà fait un screenshot d'une conversation privée pour la montrer à quelqu'un d'autre", "type":19},
{ "desc" : "Je regarde parfois mon téléphone même s'il n'a pas vibré", "type":19},
{ "desc" : "J'ai déjà envoyé un message et regardé frénétiquement si la personne était en ligne", "type":19},
{ "desc" : "Je mets des alarmes à des heures précises (comme 7h47) par superstition", "type":19},
{ "desc" : "Je mange les M&M's par couleur", "type":19},
{ "desc" : "J'ai déjà léché tout le sel des chips avant de les manger", "type":19},
{ "desc" : "Je trempe des aliments dans des boissons improbables", "type":19},
{ "desc" : "J'ai déjà mangé un aliment directement sorti du congélateur par paresse", "type":19},
{ "desc" : "Je mange les croûtes de pizza en dernier comme un dessert", "type":19},
{ "desc" : "J'ai déjà mangé des pâtes crues comme un snack", "type":19},
{ "desc" : "Je mets du ketchup sur des aliments inappropriés", "type":19},
{ "desc" : "J'ai déjà mangé de la pâte à gâteau crue en cachette", "type":19},
{ "desc" : "Je mange les céréales sans lait comme des chips", "type":19},
{ "desc" : "J'ai déjà mangé un fruit avec la peau alors qu'il fallait l'éplucher", "type":19},
{ "desc" : "Je mange les Kinder Surprise en gardant le jouet dans l'œuf pendant que je mange", "type":19},
{ "desc" : "J'ai déjà léché l'intérieur d'un emballage alimentaire", "type":19},
{ "desc" : "Je mange les feuilles extérieures des légumes que la plupart des gens jettent", "type":19},
{ "desc" : "J'ai déjà mangé des aliments pour bébé alors que je n'en ai pas", "type":19},
{ "desc" : "Je mange la peau du kiwi", "type":19},
{ "desc" : "J'ai déjà mangé des croquettes pour chats/chiens par curiosité", "type":19},
{ "desc" : "Je mange le chocolat en mordant directement dans la tablette au lieu de casser des carrés", "type":19},
{ "desc" : "J'ai déjà mangé un repas entier debout devant le frigo ouvert", "type":19},
{ "desc" : "Je mange parfois la banane avec la peau", "type":19},
{ "desc" : "J'ai déjà mangé de la neige aromatisée avec du sirop", "type":19},
{ "desc" : "Je pisse dans la douche", "type":19},
{ "desc" : "J'ai déjà utilisé du papier cuisine comme papier toilette en cas d'urgence", "type":19},
{ "desc" : "Je me nettoie les oreilles avec d'autres objets que des cotons-tiges", "type":19},
{ "desc" : "J'ai déjà fait caca dans la douche et l'ai poussé vers la bonde avec mon pied", "type":19},
{ "desc" : "Je sens mon propre pet sous la couette", "type":19},
{ "desc" : "J'ai déjà utilisé du dentifrice pour autre chose que mes dents", "type":19},
{ "desc" : "Je regarde ce qui sort de mon nez après m'être mouché", "type":19},
{ "desc" : "J'ai déjà réutilisé un mouchoir usagé mais pas trop sale", "type":19},
{ "desc" : "Je sens l'odeur de mon nombril après l'avoir nettoyé", "type":19},
{ "desc" : "J'ai déjà utilisé les toilettes sans tirer la chasse pour économiser de l'eau (si c'est jaune, c'est serein)", "type":19},
{ "desc" : "Je sens mes doigts après m'être gratté certaines parties du corps", "type":19},
{ "desc" : "J'ai déjà utilisé les vêtements sales du panier comme serviette", "type":19},
{ "desc" : "Je me regarde dans le miroir en faisant caca", "type":19},
{ "desc" : "J'ai déjà utilisé la brosse à dents de quelqu'un d'autre sans le dire", "type":19},
{ "desc" : "Je sniffe mes sous-vêtements pour voir s'ils sont portables un jour de plus", "type":19},
{ "desc" : "J'ai déjà utilisé mes cheveux pour nettoyer mes oreilles", "type":19},
{ "desc" : "Je fais des expériences avec ma morve", "type":19},
{ "desc" : "J'ai déjà uriné dans l'évier quand les toilettes étaient occupées", "type":19},
{ "desc" : "Je gratte et sniffe mes parties intimes pour vérifier leur odeur", "type":19},
{ "desc" : "J'ai déjà utilisé du shampoing comme lubrifiant", "type":19},
{ "desc" : "J'ai déjà fait l'amour avec un bruit de fond embarrassant (dessins animés, météo, etc.)", "type":19},
{ "desc" : "J'ai eu un rapport sexuel interrompu par un appel de mes parents que j'ai pris", "type":19},
{ "desc" : "Je me suis déjà coincé dans une position sexuelle bizarre", "type":19},
{ "desc" : "J'ai déjà crié le mauvais prénom pendant l'orgasme", "type":19},
{ "desc" : "Je me suis endormi pendant les préliminaires", "type":19},
{ "desc" : "J'ai déjà fait l'amour avec des bruits corporels embarrassants continuels", "type":19},
{ "desc" : "Je me suis blessé pendant l'acte mais j'ai continué pour ne pas casser l'ambiance", "type":19},
{ "desc" : "J'ai déjà été surpris par les parents/colocataires de mon/ma partenaire", "type":19},
{ "desc" : "Je me suis déjà masturbé avec un objet qui s'est cassé pendant l'utilisation", "type":19},
{ "desc" : "J'ai continué un rapport sexuel alors que je n'avais plus du tout envie", "type":19},
{ "desc" : "Je me suis déjà retrouvé avec un préservatif perdu quelque part", "type":19},
{ "desc" : "J'ai fait l'amour sur un meuble qui s'est cassé sous notre poids", "type":19},
{ "desc" : "Je me suis déjà retrouvé avec des substances corporelles à des endroits improbables", "type":19},
{ "desc" : "J'ai déjà fait semblant de savoir ce que je faisais alors que j'improvisais complètement", "type":19},
{ "desc" : "Je me suis déjà cogné la tête violemment pendant l'acte", "type":19},
{ "desc" : "J'ai dû interrompre un rapport pour aller aux toilettes de toute urgence", "type":19},
{ "desc" : "Je me suis déjà retrouvé avec une crampe au pire moment possible", "type":19},
{ "desc" : "J'ai fait l'amour avec quelqu'un qui ronflait dès que c'était fini", "type":19},
{ "desc" : "Je me suis déjà retrouvé bloqué dans une pièce après un rapport car je ne pouvais pas sortir nu", "type":19},
{ "desc" : "J'ai déjà fait tomber mon/ma partenaire du lit pendant l'acte", "type":19},
{ "desc" : "J'ai peur des autocollants sur les fruits", "type":19},
{ "desc" : "Je vérifie sous mon lit pour les monstres même adulte", "type":19},
{ "desc" : "J'ai peur que mes appareils électroniques m'écoutent", "type":19},
{ "desc" : "Je monte les escaliers en courant après avoir éteint la lumière", "type":19},
{ "desc" : "J'ai peur de l'aspirateur quand quelqu'un d'autre l'utilise", "type":19},
{ "desc" : "Je ne peux pas dormir si un placard est entrouvert", "type":19},
{ "desc" : "J'ai peur des poupées/mannequins dans le noir", "type":19},
{ "desc" : "Je mets mes pieds sous la couverture même quand il fait chaud", "type":19},
{ "desc" : "J'ai peur des bruits de canalisations la nuit", "type":19},
{ "desc" : "Je sursaute quand le grille-pain éjecte les toasts", "type":19},
{ "desc" : "J'ai peur que quelqu'un me regarde par la fenêtre quand je me déshabille", "type":19},
{ "desc" : "Je vérifie plusieurs fois que la porte est fermée avant de me coucher", "type":19},
{ "desc" : "J'ai peur des poissons qui me regardent dans l'aquarium", "type":19},
{ "desc" : "Je m'éloigne de la bouche d'aération dans les piscines", "type":19},
{ "desc" : "J'ai peur d'être observé à travers les trous de la pomme de douche", "type":19},
{ "desc" : "Je ferme les toilettes avant de tirer la chasse pour éviter les éclaboussures", "type":19},
{ "desc" : "J'ai peur que ma recherche internet me mette sur une liste de surveillance", "type":19},
{ "desc" : "J'évite de marcher sur les grilles d'égout", "type":19},
{ "desc" : "J'ai peur que mon reflet dans le miroir bouge différemment de moi", "type":19},
{ "desc" : "Je vérifie derrière le rideau de douche en entrant dans la salle de bain", "type":19},
{ "desc" : "Je fais des batailles d'eau pendant que je me douche", "type":19},
{ "desc" : "J'ai une peluche préférée que je cache quand j'ai de la visite", "type":19},
{ "desc" : "Je mange des céréales sucrées pour enfants au petit-déjeuner", "type":19},
{ "desc" : "J'ai déjà construit un fort avec des couvertures étant adulte", "type":19},
{ "desc" : "Je regarde encore des dessins animés quand je suis malade", "type":19},
{ "desc" : "J'ai un pyjama avec des personnages enfantins", "type":19},
{ "desc" : "Je saute dans les flaques d'eau quand personne ne regarde", "type":19},
{ "desc" : "J'ai déjà mangé du Nutella directement avec les doigts", "type":19},
{ "desc" : "Je joue encore à cache-cache mais je dis que c'est pour les enfants", "type":19},
{ "desc" : "J'ai une collection de jouets que je prétends conserver pour mes futurs enfants", "type":19},
{ "desc" : "Je fais des batailles d'oreillers avec mon/ma partenaire", "type":19},
{ "desc" : "J'ai déjà joué avec des bulles de savon dans mon bain", "type":19},
{ "desc" : "Je danse et chante devant le miroir avec une brosse comme micro", "type":19},
{ "desc" : "J'ai déjà regardé un dessin animé entier destiné aux tout-petits", "type":19},
{ "desc" : "Je construis encore des châteaux de sable à la plage", "type":19},
{ "desc" : "J'ai déjà fait une bataille de nourriture chez moi", "type":19},
{ "desc" : "Je fais des bruits d'explosion quand je lance quelque chose", "type":19},
{ "desc" : "J'ai un rituel enfantin avant de m'endormir", "type":19},
{ "desc" : "Je compte encore les marches des escaliers", "type":19},
{ "desc" : "J'ai déjà glissé sur le sol avec des chaussettes propres", "type":19},
{ "desc" : "Je touche du bois même quand il n'y en a pas (je dis \"touche du bois\" en touchant ma tête)", "type":19},
{ "desc" : "J'ai un vêtement porte-bonheur pour les occasions importantes", "type":19},
{ "desc" : "Je fais un vœu à chaque fois que l'heure affiche des chiffres identiques", "type":19},
{ "desc" : "J'évite les fissures sur le trottoir", "type":19},
{ "desc" : "J'ai un rituel spécifique avant de prendre l'avion", "type":19},
{ "desc" : "Je ne passe jamais sous une échelle", "type":19},
{ "desc" : "J'ai parlé à un objet inanimé pour qu'il fonctionne correctement", "type":19},
{ "desc" : "Je ne lave pas mes vêtements avant un examen/entretien important", "type":19},
{ "desc" : "J'ai un ordre précis pour enfiler mes vêtements", "type":19},
{ "desc" : "Je fais un signe particulier quand je vois un chat noir", "type":19},
{ "desc" : "J'ai un côté du lit que je considère comme portant malheur", "type":19},
{ "desc" : "Je suis superstitieux concernant certains nombres", "type":19},
{ "desc" : "J'ai jeté du sel par-dessus mon épaule après en avoir renversé", "type":19},
{ "desc" : "Je ne dis jamais certains mots par superstition", "type":19},
{ "desc" : "J'ai gardé un objet trouvé car je pensais que c'était un signe", "type":19},
{ "desc" : "Je croise les doigts dans ma poche pour porter chance", "type":19},
{ "desc" : "J'ai un rituel particulier avant de jouer à la loterie/aux jeux de hasard", "type":19},
{ "desc" : "Je ne prête jamais certains objets par superstition", "type":19},
{ "desc" : "J'ai attribué mes réussites à un objet porte-bonheur", "type":19},
{ "desc" : "Je souffle sur les dés avant de les lancer", "type":19},


];