const carddata1 = [{ desc : "Tu dois répondre à la prochaine question en moins de 5 secondes" , type: 1},
	{ desc : "Ta prochaine réponse doit être en rapport avec le sexe" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en chantant" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois tenir la main du joueur à ta droite" , type: 1},
	{ desc : "Tu ne peux plus dire \"oui\" ou \"non\" pendant [1-3] tours" , type: 1},
	{ desc : "Ta prochaine réponse doit faire exactement 7 mots" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un bébé" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois parler avec un accent étranger" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure une insulte envers toi-même" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en faisant l'éloge de Vladimir Poutine" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois te tenir sur une jambe" , type: 1},
	{ desc : "Ta prochaine réponse doit contenir au moins [1-3] gros mots" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en faisant semblant d'être bourré" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois t'adresser à tout le monde en les appelant \"maître\"" , type: 1},
	{ desc : "Ta prochaine réponse doit commencer par la dernière lettre de la question" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en faisant semblant d'avoir un orgasme" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois garder un glaçon dans ta bouche" , type: 1},
	{ desc : "Ta prochaine réponse doit être une rime" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un robot" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois parler en chuchotant" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure une référence à la politique" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en faisant semblant d'être un animal" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu ne peux utiliser que des mots commençant par la lettre P" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure un compliment pour chaque joueur" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en te tenant la tête en bas" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire semblant d'être amoureux du joueur à ta gauche" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure une théorie du complot" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en faisant semblant d'être un personnage historique" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois boire une gorgée à chaque fois que quelqu'un dit \"je\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être en langage SMS" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en faisant semblant d'être un commentateur sportif" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire semblant d'être invisible" , type: 1},
	{ desc : "Ta prochaine réponse doit être une publicité pour un produit imaginaire" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant à la troisième personne" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois te pincer le nez en parlant" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] mensonges évidents" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en faisant semblant d'être un politicien" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois commencer chaque phrase par \"Selon une étude...\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être en vers" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en faisant semblant d'être un extraterrestre" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois applaudir après chaque phrase que tu dis" , type: 1},
	{ desc : "Ta prochaine réponse doit être une confession embarrassante (réelle ou inventée)" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en faisant semblant d'être une célébrité" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois parler en te bouchant les oreilles" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure une prédiction sur l'avenir d'un des joueurs" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme si tu étais en entretien d'embauche" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure une imitation d'un personnage de dessin animé" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en faisant semblant d'être au confessionnal" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois parler comme si tu racontais un secret" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme des paroles de rap" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en faisant semblant d'être un médecin incompétent" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois finir chaque phrase par \"mais c'est juste mon avis\"" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] double-sens sexuels" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais psy" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois appeler tout le monde par le mauvais prénom" , type: 1},
	{ desc : "Ta prochaine réponse doit être une critique cinglante d'un des joueurs" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en faisant semblant d'être constipé" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois te toucher le nez chaque fois que quelqu'un rit" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure une insulte envers chaque joueur" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en faisant semblant d'être un présentateur télé" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois parler en mettant ton t-shirt sur ta tête" , type: 1},
	{ desc : "Ta prochaine réponse doit être faite comme si tu étais en train de rompre avec quelqu'un" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en faisant semblant d'être une star de cinéma prétentieuse" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois boire une gorgée chaque fois que tu dis \"je\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme un discours politique" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un pirate" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire un bruit d'animal entre chaque phrase" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure un compliment bizarre pour chaque joueur" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en faisant semblant d'être un mauvais vendeur" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois porter un vêtement d'un autre joueur" , type: 1},
	{ desc : "Ta prochaine réponse doit être faite comme si tu étais en train d'accoucher" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un personnage de film porno" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois lécher tes lèvres après chaque phrase" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] références à des films connus" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme ta mère" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire semblant d'avoir un tic nerveux" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme une critique gastronomique" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en faisant semblant d'être ivre" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois tenir ton verre avec tes coudes" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] mentions de fluides corporels" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un enfant de 5 ans" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire semblant d'avoir un accent allemand" , type: 1},
	{ desc : "Ta prochaine réponse doit être un poème sur le joueur à ta droite" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en faisant semblant d'être un mauvais coach de vie" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois parler en te pinçant le nez" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure une excuse bidon pour quitter une soirée" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en faisant semblant d'être allergique à tout" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois commencer chaque phrase par \"Ma grand-mère disait toujours...\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme une lettre de rupture" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un rappeur" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire semblant de ne pas comprendre ce que disent les autres" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] mensonges sur ta vie sexuelle" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un commentateur de foot excité" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois finir chaque phrase par \"comme dirait ma psychologue\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être un SMS que tu pourrais envoyer à ton/ta ex" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en faisant semblant d'être un mauvais politicien" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois parler en tenant tes joues" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure [1-3] conseils douteux pour séduire quelqu'un" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme si tu étais aux toilettes" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois boire une gorgée chaque fois que quelqu'un dit \"non\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme une publicité pour un sex-toy" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en faisant semblant d'être un mauvais médecin" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire semblant d'avoir un hoquet" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure une insulte déguisée envers chaque joueur" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais prof" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois te tenir la gorge en parlant" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme un message vocal gênant" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question comme si c'était la chose la plus excitante du monde" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire semblant de ne pas connaître les autres joueurs" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] excuses bidons pour ne pas aller travailler" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais thérapeute" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois toucher ton coude avec ton nez après chaque phrase" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme une critique de film porno" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un influenceur agaçant" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois parler avec la bouche pleine (ou faire semblant)" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] raisons bizarres de rompre avec quelqu'un" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais gourou" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois finir chaque phrase par \"enfin, c'est ce que mon ex disait\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme un message d'au revoir avant suicide" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un arnaqueur téléphonique" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois avoir un fou rire entre chaque phrase" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] compliments louches" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un pervers" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois commencer chaque phrase par \"Au risque de vous choquer...\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme un testament" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme quelqu'un de très vieux" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire un geste obscène après chaque phrase" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] théories du complot ridicules" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un porno amateur" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois finir chaque phrase par \"comme dirait mon psy\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme une lettre à Jésus" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un dictateur" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire semblant d'avoir un objet coincé dans ton cul" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] excuses pour quitter un date" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais acteur de doublage" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois boire une gorgée chaque fois que quelqu'un rit" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme un discours funèbre" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un présentateur météo" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois parler en te tenant la gorge" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] anecdotes embarrassantes (vraies ou fausses)" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme quelqu'un qui cache un cadavre" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois commencer chaque phrase par \"Dans mon journal intime...\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme un plan pour un crime parfait" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un pervers narcissique" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois te toucher les parties intimes (simuler) après chaque phrase" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] conseils pour stalker quelqu'un efficacement" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un psychopathe" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois finir chaque phrase par \"comme me l'a appris mon oncle\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme un message d'adieu avant de disparaître" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un néo-nazi" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire semblant d'avoir une érection/excitation" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de cacher un corps" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un pédophile" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois commencer chaque phrase par \"Si ma mère savait...\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme une confession à la police" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais prêtre" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire semblant d'être possédé par un démon" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] excuses pour avoir triché" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais gynécologue" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois finir chaque phrase par \"mais c'est notre petit secret\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme une annonce de grossesse non désirée" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un pédant insupportable" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois parler en tenant ta langue" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de se faire virer" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme si tu avais un objet dans le rectum" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois commencer chaque phrase par \"J'ai lu sur Facebook que...\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme un message de drague sur Tinder" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un complotiste" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois prendre un accent russe" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] signes que ton/ta partenaire te trompe" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais nutritionniste" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois finir chaque phrase par \"comme me l'a montré mon ex\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme un message passif-agressif" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais coach sportif" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois parler en serrant les fesses" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons d'éviter de payer ses impôts" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais chirurgien esthétique" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois commencer chaque phrase par \"Sans vouloir être raciste...\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme une demande de rançon" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais agent immobilier" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire semblant d'avoir une araignée sur toi" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de se venger de son ex" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais sexologue" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois finir chaque phrase par \"comme me l'a appris internet\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme une lettre de démission" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais astrologue" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois parler en faisant semblant d'être bourré" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] excuses pour ne pas avoir utilisé de préservatif" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais dentiste" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois commencer chaque phrase par \"Ma thérapie m'a appris que...\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme un message d'excuses après avoir trompé" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais voyant" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire semblant d'avoir une crise d'asthme" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de saboter un mariage" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais psychiatre" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois finir chaque phrase par \"mais c'est entre nous\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme une notice nécrologique" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais politicien en campagne" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois parler avec un doigt dans la bouche" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de faire croire à quelqu'un qu'il devient fou" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais coach de vie" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois commencer chaque phrase par \"Selon ma dernière recherche Google...\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme une note de suicide" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais prof de yoga" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire semblant d'avoir mal au ventre" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de faire fuir ses beaux-parents" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais guide touristique" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois finir chaque phrase par \"c'est ce que m'a dit mon dealer\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme une lettre anonyme de menace" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais représentant pharmaceutique" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois parler en te tenant le ventre comme si tu avais la diarrhée" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de se faire plaquer volontairement" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un témoin de Jéhovah" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois commencer chaque phrase par \"Je ne devrais pas vous le dire, mais...\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme un testament ridicule" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais coach en séduction" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire semblant d'avoir un AVC" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de rater un entretien d'embauche" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois finir chaque phrase par \"comme je l'ai vu sur Pornhub\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme une lettre d'amour à ton pire ennemi" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais infirmier" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois parler en te touchant les tétons" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de ruiner un enterrement" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois commencer chaque phrase par \"Si ma mère m'entendait dire ça...\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme un rapport de police bidon" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais influenceur bien-être" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire semblant d'avoir un orgasme discret" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de gâcher un premier rendez-vous" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais chirurgien" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois finir chaque phrase par \"mais chut, c'est un secret\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme une analyse de tes selles" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais conseiller matrimonial" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois parler en ayant un doigt dans le nez" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de savoir si quelqu'un ment" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais urologue" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois commencer chaque phrase par \"En prison, j'ai appris que...\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme une lettre au Père Noël d'un adulte" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais conseiller fiscal" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire semblant d'avoir une crampe" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de se faire virer volontairement" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois finir chaque phrase par \"comme me l'a montré mon thérapeute\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme un discours de mariage inapproprié" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois parler en léchant tes lèvres de façon suggestive" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de gâcher Noël" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais podologue" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois commencer chaque phrase par \"Dans un porno, j'ai vu que...\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme une explication à la police" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais prof d'éducation sexuelle" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire semblant d'être constipé" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de faire croire qu'on est malade" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois finir chaque phrase par \"c'est ce que font tous les psychopathes\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme un message à la CAF pour expliquer que tu as triché" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais proctologue" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois parler en faisant de grands gestes théâtraux" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de se faire larguer en public" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais pédiatre" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois commencer chaque phrase par \"Selon ma thérapie de groupe...\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme un message d'erreur informatique" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais anesthésiste" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire semblant d'être en manque" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de faire croire qu'on est riche" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais dermatologiste" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois finir chaque phrase par \"comme le faisait mon ex\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme un message de rupture brutal" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais psychanalyste" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois parler en faisant semblant de pleurer" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de faire fuir un date" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois commencer chaque phrase par \"Dans mon journal intime, j'ai écrit que...\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme un message d'excuse après avoir mis un like sur une photo d'il y a 5 ans" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire semblant d'avoir une double personnalité" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de savoir si quelqu'un te stalk" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais vétérinaire" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois finir chaque phrase par \"c'est ce que m'a appris mon ex\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme un message d'au revoir avant d'aller en prison" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais avocat" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois parler en faisant semblant d'être stone" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de savoir si quelqu'un est gay mais ne l'assume pas" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois commencer chaque phrase par \"En thérapie, j'ai découvert que...\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme une page de journal intime" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais curé" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire semblant d'avoir une crise existentielle" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de gâcher une demande en mariage" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais kiné" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois finir chaque phrase par \"mais ça reste entre nous\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme un message d'excuses après avoir pété en public" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois parler en te touchant les parties intimes (simuler)" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de se faire remarquer dans une soirée" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois commencer chaque phrase par \"Mon psy m'a dit que...\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme un discours de fin du monde" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais acteur porno" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire semblant d'avoir le hoquet" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de se faire haïr rapidement" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais chirurgien plastique" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois finir chaque phrase par \"mais ne le répète à personne\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme un message vocal envoyé par erreur" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais entraîneur de foot" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois parler en te frottant contre ton siège" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons d'éviter ses responsabilités" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais conseiller conjugal" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois commencer chaque phrase par \"Contrairement à ce que dit mon thérapeute...\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme un testament incompréhensible" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire semblant d'avoir un problème de vessie" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de faire croire qu'on est intelligent" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais politicien" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois finir chaque phrase par \"comme le faisait mon père\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme une excuse pour avoir vomi sur quelqu'un" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais coach en développement personnel" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois parler en faisant semblant d'avoir le vertige" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de se faire remarquer aux urgences" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois commencer chaque phrase par \"Ma mère ne le sait pas, mais...\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme une lettre à ton futur toi" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais gourou de secte" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire semblant d'avoir un tic facial" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de se faire virer d'un restaurant" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois finir chaque phrase par \"c'est ce qui m'a sauvé en prison\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme des excuses après avoir cassé quelque chose de valeur" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais vendeur de voitures" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois parler en ayant une main dans ton pantalon (simuler)" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de ruiner un mariage" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais prof de sport" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois commencer chaque phrase par \"Mon ex m'a appris que...\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme un message d'excuse après avoir pété pendant un rapport sexuel" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois faire semblant d'être un robot qui bugue" , type: 1},
	{ desc : "Ta prochaine réponse doit inclure au moins [1-3] façons de tricher à un examen" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en parlant comme un mauvais étudiant en médecine" , type: 1},
	{ desc : "Pour les [1-3] prochains tours, tu dois finir chaque phrase par \"mais mes parents ne savent pas\"" , type: 1},
	{ desc : "Ta prochaine réponse doit être formulée comme un statut Facebook trop personnel" , type: 1},
	{ desc : "Choisis un joueur qui doit répondre à la prochaine question avec toi" , type: 1},
	{ desc : "Ton voisin de droite doit te donner un gage ou répondre à une question indiscrète" , type: 1},
	{ desc : "Propose un dilemme impossible au joueur de ton choix" , type: 1},
	{ desc : "Tout le monde vote pour qui serait le plus susceptible d'aller en prison" , type: 1},
	{ desc : "Le joueur à ta gauche décide si tu dois révéler un secret ou faire un gage" , type: 1},
	{ desc : "Tout le monde doit dire un truc qu'il déteste chez toi" , type: 1},
	{ desc : "Choisis un joueur qui ne pourra plus parler pendant [1-3] tours" , type: 1},
	{ desc : "Tout le monde vote pour qui serait le pire en couple" , type: 1},
	{ desc : "Le joueur avec le moins de points te pose une question indiscrète" , type: 1},
	{ desc : "Tous les joueurs échangent leur place" , type: 1},
	{ desc : "Les deux joueurs à ta droite et à ta gauche doivent s'embrasser ou boire" , type: 1},
	{ desc : "Tout le monde vote pour qui serait le plus susceptible de devenir SDF" , type: 1},
	{ desc : "Choisis un joueur qui doit se mettre à poil ou finir son verre" , type: 1},
	{ desc : "Tout le monde vote pour qui serait le pire parent" , type: 1},
	{ desc : "Révèle ton plus gros défaut ou bois un verre" , type: 1},
	{ desc : "Tout le monde vote pour qui serait le plus susceptible de tromper son/sa partenaire" , type: 1},
	{ desc : "Le joueur le plus âgé doit faire un lap dance au plus jeune ou finir son verre" , type: 1},
	{ desc : "Tout le monde vote pour qui vieillirait le plus mal" , type: 1},
	{ desc : "Choisis un joueur qui doit te faire un massage de [1-3]0 secondes" , type: 1},
	{ desc : "Tout le monde vote pour qui serait le pire patron" , type: 1},
	{ desc : "Les deux joueurs qui se connaissent le moins doivent se faire un câlin de 10 secondes" , type: 1},
	{ desc : "Tout le monde vote pour qui serait le plus susceptible de se faire arrêter" , type: 1},
	{ desc : "Le joueur à ta droite doit te dessiner les yeux fermés" , type: 1},
	{ desc : "Tout le monde vote pour qui serait le plus susceptible de finir en prison" , type: 1},
	{ desc : "Le joueur avec le plus de points doit enlever un vêtement ou boire un verre" , type: 1},
	{ desc : "Tout le monde vote pour qui serait le plus susceptible de devenir millionnaire" , type: 1},
	{ desc : "Les deux joueurs les plus sobres doivent échanger leurs verres" , type: 1},
	{ desc : "Tout le monde vote pour qui serait le plus susceptible de divorcer" , type: 1},
	{ desc : "Le joueur qui a le moins bu doit finir son verre" , type: 1},
	{ desc : "Tout le monde vote pour qui a le plus de chance d'être largué dans l'année" , type: 1},
	{ desc : "Choisis un joueur qui doit te faire un compliment sincère" , type: 1},
	{ desc : "Tout le monde vote pour qui serait le plus susceptible de mourir en premier" , type: 1},
	{ desc : "Le joueur le plus grand doit s'asseoir sur les genoux du plus petit jusqu'au prochain tour" , type: 1},
	{ desc : "Tout le monde vote pour qui serait le plus susceptible de gagner au loto" , type: 1},
	{ desc : "Choisis un joueur qui doit te donner son téléphone pendant 1 minute" , type: 1},
	{ desc : "Tout le monde vote pour qui serait le plus susceptible de devenir célèbre" , type: 1},
	{ desc : "Le joueur qui a le plus de followers sur les réseaux sociaux doit montrer sa photo la plus likée" , type: 1},
	{ desc : "Tout le monde vote pour qui serait le plus susceptible de finir en maison de retraite" , type: 1},
	{ desc : "Les trois joueurs à ta gauche doivent chacun te poser une question indiscrète" , type: 1},
	{ desc : "Tout le monde vote pour qui serait le plus susceptible de se faire larguer par SMS" , type: 1},
	{ desc : "Le joueur qui a perdu le plus de points doit faire un selfie embarrassant" , type: 1},
	{ desc : "Tout le monde vote pour qui serait le plus susceptible de faire un OnlyFans" , type: 1},
	{ desc : "Choisis un joueur qui ne pourra plus dire de gros mots jusqu'à la fin de la partie" , type: 1},
	{ desc : "Tout le monde vote pour qui serait le plus susceptible de devenir dictateur" , type: 1},
	{ desc : "Le joueur le plus jeune doit faire un compliment à chaque joueur" , type: 1},
	{ desc : "Tout le monde vote pour qui serait le plus susceptible de finir dans une secte" , type: 1},
	{ desc : "Les deux joueurs les plus vieux doivent échanger un vêtement" , type: 1},
	{ desc : "Tout le monde vote pour qui serait le plus susceptible de se faire tatouer le nom de son/sa partenaire" , type: 1},
	{ desc : "Le joueur à ton choix doit faire 10 pompes ou finir son verre" , type: 1},
	{ desc : "Tout le monde vote pour qui serait le plus susceptible de finir sans-abri" , type: 1},
	{ desc : "Garde un accent étranger au choix pendant les [1-3] prochains tours" , type: 1},
	{ desc : "Fais ton prochain tour les yeux fermés" , type: 1},
	{ desc : "Raconte ta prochaine réponse comme si c'était un conte pour enfants" , type: 1},
	{ desc : "Réponds à la prochaine question en rimant" , type: 1},
	{ desc : "Fais ta prochaine réponse en chuchotant comme si tu révélais un secret d'État" , type: 1},
	{ desc : "Tu dois tenir un objet en équilibre sur ta tête pendant un tour complet" , type: 1},
	{ desc : "Pour ton prochain tour, tu dois parler comme un commentateur sportif excité" , type: 1},
	{ desc : "Réponds à la prochaine question en utilisant uniquement des mots commençant par la même lettre" , type: 1},
	{ desc : "Fais ta prochaine réponse en imitant une célébrité au choix des autres joueurs" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en moins de 5 secondes" , type: 1},
	{ desc : "Réponds à la prochaine question en étant scandalisé par tout ce que tu dis" , type: 1},
	{ desc : "Fais ta prochaine réponse en position de la chaise invisible contre un mur" , type: 1},
	{ desc : "Tu dois faire ta prochaine réponse en parlant comme un robot" , type: 1},
	{ desc : "Pour ton prochain tour, tu dois faire semblant d'être au téléphone avec ta mère" , type: 1},
	{ desc : "Réponds à la prochaine carte en parlant à la troisième personne" , type: 1},
	{ desc : "Fais ta prochaine réponse en étant extrêmement enthousiaste" , type: 1},
	{ desc : "Tu dois faire ta prochaine réponse en prenant l'accent de quelqu'un dans la pièce" , type: 1},
	{ desc : "Réponds à la prochaine question uniquement en utilisant des titres de films" , type: 1},
	{ desc : "Pour ton prochain tour, tu dois faire semblant d'être un présentateur de journal télévisé" , type: 1},
	{ desc : "Tu dois faire ta prochaine réponse en tenant tes chevilles" , type: 1},
	{ desc : "Raconte ta prochaine réponse comme si c'était un secret que tu ne voulais pas partager" , type: 1},
	{ desc : "Réponds à la prochaine question en étant super prétentieux" , type: 1},
	{ desc : "Pour ton prochain tour, tu dois parler comme si tu étais dans un film d'action" , type: 1},
	{ desc : "Tu dois faire ta prochaine réponse en faisant semblant d'être ivre" , type: 1},
	{ desc : "Explique ta prochaine réponse comme si tu parlais à un enfant de 5 ans" , type: 1},
	{ desc : "Fais ton prochain tour en parlant uniquement avec des questions" , type: 1},
	{ desc : "Réponds à la prochaine carte en étant la personne la plus dramatique du monde" , type: 1},
	{ desc : "Tu dois faire semblant d'avoir le hoquet pendant ta prochaine réponse" , type: 1},
	{ desc : "Pour ton prochain tour, réponds en parlant comme ton grand-père ou ta grand-mère" , type: 1},
	{ desc : "Réponds à la prochaine question en faisant semblant de pleurer" , type: 1},
	{ desc : "Fais ta prochaine réponse en parlant comme un pirate" , type: 1},
	{ desc : "Tu dois faire ton prochain tour en étant debout sur une jambe" , type: 1},
	{ desc : "Réponds à la prochaine carte en parlant le plus lentement possible" , type: 1},
	{ desc : "Fais semblant d'être un vendeur télémarketing pour ta prochaine réponse" , type: 1},
	{ desc : "Tu dois faire ta prochaine réponse en chantant" , type: 1},
	{ desc : "Réponds à la prochaine question en parlant comme un snob" , type: 1},
	{ desc : "Pour ton prochain tour, tu dois faire semblant d'être allergique à quelque chose dans la pièce" , type: 1},
	{ desc : "Fais ta prochaine réponse en parlant comme si tu étais dans un western" , type: 1},
	{ desc : "Tu dois répondre à la prochaine carte en parlant le plus rapidement possible" , type: 1},
	{ desc : "Réponds à la prochaine question en étant extrêmement pessimiste" , type: 1},
	{ desc : "Pour ton prochain tour, tu dois parler comme un personnage de dessin animé" , type: 1},
	{ desc : "Fais ta prochaine réponse en faisant semblant de ne pas comprendre la question" , type: 1},
	{ desc : "Tu dois faire ton prochain tour en parlant avec un accent du sud" , type: 1},
	{ desc : "Réponds à la prochaine carte en étant extrêmement susceptible" , type: 1},
	{ desc : "Fais ta prochaine réponse comme si c'était un rap improvisé" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en bégayant" , type: 1},
	{ desc : "Pour ton prochain tour, tu dois parler comme si tout était une théorie du complot" , type: 1},
	{ desc : "Fais ta prochaine réponse en étant extrêmement paranoïaque" , type: 1},
	{ desc : "Tu dois répondre à la prochaine carte en murmurant" , type: 1},
	{ desc : "Fais ton prochain tour en parlant comme un personnage de film d'horreur" , type: 1},
	{ desc : "Réponds à la prochaine question comme si tu étais un guide touristique ennuyeux" , type: 1},
	{ desc : "Pour ton prochain tour, tu dois parler avec un accent britannique exagéré" , type: 1},
	{ desc : "Fais ta prochaine réponse en imitant un animal entre chaque phrase" , type: 1},
	{ desc : "Tu dois répondre à la prochaine carte en parlant comme un politicien qui évite les questions" , type: 1},
	{ desc : "Réponds à la prochaine question en faisant semblant d'être un expert en quelque chose que tu ne connais pas" , type: 1},
	{ desc : "Pour ton prochain tour, tu dois parler comme si tu racontais un secret scandaleux" , type: 1},
	{ desc : "Fais ta prochaine réponse en parlant avec le nez pincé" , type: 1},
	{ desc : "Tu dois faire ton prochain tour en parlant comme un personnage de télé-réalité" , type: 1},
	{ desc : "Réponds à la prochaine carte en étant extrêmement nostalgique" , type: 1},
	{ desc : "Fais ta prochaine réponse en étant super passif-agressif" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en faisant semblant d'avoir la bouche pleine" , type: 1},
	{ desc : "Pour ton prochain tour, tu dois parler comme si tu étais en train de faire du sport intense" , type: 1},
	{ desc : "Fais ta prochaine réponse en imitant une personne célèbre au choix du joueur à ta droite" , type: 1},
	{ desc : "Tu dois faire ton prochain tour en parlant comme un mauvais poète" , type: 1},
	{ desc : "Réponds à la prochaine carte en étant complètement blasé" , type: 1},
	{ desc : "Pour ton prochain tour, tu dois parler en faisant semblant d'avoir très froid" , type: 1},
	{ desc : "Fais ta prochaine réponse en parlant comme si tu avais un secret à cacher" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en faisant semblant d'être un super-héros" , type: 1},
	{ desc : "Réponds à la prochaine carte en parlant comme quelqu'un qui vient de se réveiller" , type: 1},
	{ desc : "Fais ton prochain tour en parlant comme un mauvais doublage de film" , type: 1},
	{ desc : "Tu dois faire ta prochaine réponse en faisant semblant d'avoir un fou rire" , type: 1},
	{ desc : "Pour ton prochain tour, tu dois parler comme si tu étais au milieu d'une tempête" , type: 1},
	{ desc : "Réponds à la prochaine question en parlant comme ton animal de compagnie s'il pouvait parler" , type: 1},
	{ desc : "Fais ta prochaine réponse en faisant semblant d'avoir un accent français exagéré" , type: 1},
	{ desc : "Tu dois faire ton prochain tour en parlant comme un personnage de soap opera" , type: 1},
	{ desc : "Réponds à la prochaine carte en étant extrêmement confus" , type: 1},
	{ desc : "Pour ton prochain tour, tu dois parler comme si tu étais en chute libre" , type: 1},
	{ desc : "Fais ta prochaine réponse en imitant le joueur à ta gauche" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question comme si c'était la chose la plus excitante que tu aies jamais entendue" , type: 1},
	{ desc : "Réponds à la prochaine carte en parlant comme un mauvais acteur" , type: 1},
	{ desc : "Fais ton prochain tour en faisant semblant d'avoir perdu la voix" , type: 1},
	{ desc : "Tu dois faire ta prochaine réponse en parlant comme un prof ennuyeux" , type: 1},
	{ desc : "Pour ton prochain tour, tu dois parler en faisant semblant d'avoir très chaud" , type: 1},
	{ desc : "Réponds à la prochaine question en étant extrêmement condescendant" , type: 1},
	{ desc : "Fais ta prochaine réponse en parlant comme si tu étais dans un documentaire animalier" , type: 1},
	{ desc : "Tu dois faire ton prochain tour en parlant comme un robot qui dysfonctionne" , type: 1},
	{ desc : "Réponds à la prochaine carte en faisant semblant d'être jaloux de tout le monde" , type: 1},
	{ desc : "Pour ton prochain tour, tu dois parler en faisant semblant de pleurer" , type: 1},
	{ desc : "Fais ta prochaine réponse en parlant comme un personnage de conte de fées" , type: 1},
	{ desc : "Tu dois répondre à la prochaine question en faisant semblant d'avoir le hoquet" , type: 1},
	{ desc : "Réponds à la prochaine carte en parlant comme un vampire" , type: 1},
	{ desc : "Fais ton prochain tour en faisant semblant d'être un commentateur sportif" , type: 1},
	{ desc : "Tu dois faire ta prochaine réponse en parlant comme un extraterrestre qui découvre la Terre" , type: 1},
	{ desc : "Pour ton prochain tour, tu dois parler comme si tu étais sous l'eau" , type: 1},
	{ desc : "Réponds à la prochaine question en faisant semblant d'être un mauvais magicien" , type: 1},
	{ desc : "Fais ta prochaine réponse en parlant comme si tu racontais un film d'horreur" , type: 1},
	{ desc : "Tu dois faire ton prochain tour en parlant comme un journaliste sensationnaliste" , type: 1},
	{ desc : "Réponds à la prochaine carte en faisant semblant d'être un mauvais rappeur" , type: 1},
	{ desc : "Pour ton prochain tour, tu dois parler comme si tu étais à un entretien d'embauche" , type: 1},
	{ desc : "Fais ta prochaine réponse en parlant comme si tu avais un secret incroyable à révéler" , type: 1}
];